@ Chapter 0x02: Ch. 2: Sword of Spirits
@ Generated by tools/evdis.py

#include "event_macros.inc"

	.section .rodata.ev_08CA09B4, "a"

	.global EvList_Ch02_Turn
EvList_Ch02_Turn:
	TURN 0, EventScr_Ch02_Beginning, 1, 0, FACTION_BLUE, 0
	TURN 0, EventScr_08CA929C, 1, 0, FACTION_BLUE, 0
	EVLIST_END

	.global EvList_Ch02_TutorialD
EvList_Ch02_TutorialD:
	TURN 0, EventScr_08CA9300, 2, 0, FACTION_BLUE, 0
	TURN 0, EventScr_08CA933C, 3, 0, FACTION_BLUE, 0
	EVLIST_END

	.global EvList_Ch02_Character
EvList_Ch02_Character:
	EVLIST_END

	.global EvList_Ch02_Location
EvList_Ch02_Location:
	LOCA 3, EVENT_NOSCRIPT, 0xB, 1, 0xF
	LOCA 0, EventScr_08CA9370, 1, 7, 0xE
	LOCA 0, EventScr_08CA93A8, 0, 9, 0xE
	LOCA 0, EventScr_08CA93E0, 0, 7, 0xE
	EVLIST_END

	.global EvList_Ch02_TutorialA
EvList_Ch02_TutorialA:
	AFEV 7, EventScr_08CA9418, 6
	AFEV 9, EventScr_08CA94BC, 8
	AFEV 0xB, EventScr_08CA9578, 0xA
	EVLIST_END

	.global AreaList_08CA0A5C
AreaList_08CA0A5C:
	.byte 0, 7, 0, 0
	.byte 255, 0, 0, 0

	.global AreaList_08CA0A64
AreaList_08CA0A64:
	.byte 1, 7, 0, 0
	.byte 255, 0, 0, 0

	.global AreaList_08CA0A6C
AreaList_08CA0A6C:
	.byte 0, 9, 0, 0
	.byte 255, 0, 0, 0

	.global EvList_Ch02_TutorialB
EvList_Ch02_TutorialB:
	TUTORIAL_POS 0xE, AreaList_08CA0A5C, EventScr_08CA96A8, 7
	TUTORIAL_POS 0xF, AreaList_08CA0A64, EventScr_08CA96E4, 9
	TUTORIAL_POS 0x10, AreaList_08CA0A64, EventScr_08CA9724, 0xC
	TUTORIAL_POS 0x10, AreaList_08CA0A6C, EventScr_08CA9724, 0xD
	EVLIST_END

	.global EvList_Ch02_TutorialC
EvList_Ch02_TutorialC:
	EVLIST_END

	.global EvList_Ch02_Misc
EvList_Ch02_Misc:
	AFEV 0x11, EventScr_08CA97A4, 7
	AFEV 0x12, EventScr_08CA987C, 9
	AFEV 0x13, EventScr_08CA98B8, 9
	AFEV 0x14, EventScr_08CA991C, 0xB
	AFEV 0, gEvent_GameOver, 0x65
	AFEV 0x15, EventScr_08CA9960, 2
	EVLIST_END

	.global ChapterEvents_Ch02
ChapterEvents_Ch02:
	.4byte EvList_Ch02_Turn                  @ turn
	.4byte EvList_Ch02_Character             @ character
	.4byte EvList_Ch02_Location              @ location
	.4byte EvList_Ch02_Misc                  @ misc
	.4byte Traps_Ch02                        @ traps
	.4byte Traps_Ch02_Hector                 @ traps (Hector mode)
	.4byte Units_Ch02_Initial                @ units loaded at start
	.4byte Units_Ch02_Initial                @ (hard)
	.4byte Units_Ch02_Initial                @ (Hector mode)
	.4byte Units_Ch02_Initial                @ (Hector mode, hard)
	.4byte Units_Ch02_Player                 @ player units
	.4byte Units_Ch02_Player                 @ (hard)
	.4byte Units_Ch02_Player                 @ (Hector mode)
	.4byte Units_Ch02_Player                 @ (Hector mode, hard)
	.4byte EventScr_Ch02_Beginning           @ beginning scene
	.4byte EventScr_Ch02_Ending              @ ending scene

	.section .rodata.ev_08CA9040, "a"

	.global MoveScr_08CA9040
MoveScr_08CA9040:
	.byte MV_SPEED, 0x18, MV_LEFT, MV_UP, MV_HALT

	.global MoveScr_08CA9045
MoveScr_08CA9045:
	.byte MV_SPEED, 0x8, MV_UP, MV_LEFT, MV_SPEED, 0x30, MV_LEFT, MV_LEFT, MV_LEFT, MV_LEFT, MV_HALT

	.global MoveScr_08CA9050
MoveScr_08CA9050:
	.byte MV_SPEED, 0x20, MV_LEFT, MV_HALT

	.global MoveScr_08CA9054
MoveScr_08CA9054:
	.byte MV_SPEED, 0x10, MV_UP, MV_HALT

	.global MoveScr_08CA9058
MoveScr_08CA9058:
	.byte MV_SPEED, 0x10, MV_LEFT, MV_UP, MV_HALT

	.fill 3, 1, 0

	.global EventScr_Ch02_Beginning
EventScr_Ch02_Beginning:
	UNIT_CAM_OFF
	ASMC UpdatePrevDeployStates
	LOU1 Units_08CC5DC8
	LOU1 Units_08CC5DE8
	ENUN
	FADE_FROM_OPENING
	STAL 0x40
	LOU1 Units_Ch02_Player
	ENUN
	MOVE CHARACTER_LYN_TUTORIAL, 2, 3
	MOVE CHARACTER_SAIN_TUTORIAL, 1, 4
	MOVE CHARACTER_KENT_TUTORIAL, 0, 4
	LOU1 Units_08CC5D28
	ENUN
	FADI 0x10
	EXIT_MAP
	BACG 0x22
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_881                             @ , hold a moment, and allow me a short detour. Th
	CLEAN
	LOU1 Units_08CC5D58
	ENUN
	MOVE_SCR CHARACTER_GLASS, MoveScr_08CA9040
	ENUN
	MUSC SONG_32
	FADI 0x10
	EXIT_MAP
	BACG 0x4F
	STAL 0x20
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_882                             @ Old man! Stay where you are, and hold your tongu
	CLEAN
	MOVE_SPEED CHARACTER_CITIZEN_DA, 13, 1, 0x30
	ENUN
	STAL 0x20
	MOVE CHARACTER_GLASS, 11, 1
	ENUN
	STAL 0x40
	FADI 0x10
	EXIT_MAP
	BACG 0x4F
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_883                             @ This is it! It's more magnificent than I'd imagi
	CLEAN
	SOUN SONG_B1
	MNCH_MAP 1
	MOVE CHARACTER_GLASS, 12, 1
	ENUN
	MOVE_SPEED CHARACTER_CITIZEN_DA, 13, -1, 0x30
	ENUN
	DISA CHARACTER_CITIZEN_DA
	MOVE CHARACTER_GLASS, 13, 1
	ENUN
	SOUN SONG_B1
	MNCH_MAP 0x8000
	STAL 0x3C
	MOVE CHARACTER_GLASS, 11, 1
	ENUN
	FADI 0x10
	EXIT_MAP
	BACG 0x4F
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_884                             @ Curses! Miserable spirits! I care nothing for yo
	CLEAN
	STAL 0x40
	MOVE_SCR CHARACTER_CITIZEN_DB, MoveScr_08CA9045
	ENUN
	FADI 0x10
	EXIT_MAP
	BACG 0x22
	DISA CHARACTER_CITIZEN_DB
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_885                             @ I beg your pardon, milady. Are you headed east?
	CLEAN
	ASMC sub_08018888
	MOVE CHARACTER_LYN_TUTORIAL, 0, 4
	ENUN
	MOVE_SCR CHARACTER_TACTICIAN, MoveScr_08CA9050
	ENUN
	DISA CHARACTER_TACTICIAN
	MOVE_BLUE_OR_SCR CHARACTER_KENT_TUTORIAL, 0x10, 1, 5, MoveScr_08CA9054
	MOVE_BLUE_OR_SCR CHARACTER_SAIN_TUTORIAL, 0x10, 1, 3, MoveScr_08CA9058
	ENUN
	ASMC HideAllAlliesExceptLeader
	ASMC sub_0807CF68
	REMA
	ENDA

	.global EventScr_08CA929C
EventScr_08CA929C:
	IFDIFF 1, 0x63
	MUSC 0x30
	IFTU 0x32
	EVBIT_SILENTSKIP
	STAL 8
	TUTORIAL_TEXT 0, 0, MSG_886, 5           @ The three buildings to the south are homes . You
	ASMC_WAIT2 BoxTalkActive
	LABEL 0x32
	TEX1 MSG_887                             @ Shall I take the lead? All right. Tell me what y
	CLEAN
	ENUT 6
	MENU_OVERRIDE_CLEAR
	MENU_OVERRIDE_HIDE 0x71
	LABEL 0x63
	REMA
	ENDA

	.global EventScr_08CA9300
EventScr_08CA9300:
	IFTU 0x32
	CURF_POS 2, 2
	EVBIT_SILENTSKIP
	STAL 8
	TUTORIAL_TEXT 0, 0, MSG_89F, 5           @ You should know something about fortresses . For
	ASMC_WAIT2 BoxTalkActive
	LABEL 0x32
	REMA
	ENDA

	.global EventScr_08CA933C
EventScr_08CA933C:
	IFTU 0x32
	EVBIT_SILENTSKIP
	STAL 8
	TUTORIAL_TEXT 0, 0, MSG_8A0, 5           @ This chapter's goal is to seize the throne . The
	ASMC_WAIT2 BoxTalkActive
	LABEL 0x32
	REMA
	ENDA

	.global EventScr_08CA9370
EventScr_08CA9370:
	IGNORE_KEYS 0x0
	MUSI
	FADI 0x10
	EXIT_MAP
	BACG 1
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_89C                             @ Mountains make it more difficult to be hit , but
	CLEAN
	MUNO
	REMA
	ENDA

	.global EventScr_08CA93A8
EventScr_08CA93A8:
	IGNORE_KEYS 0x0
	MUSI
	FADI 0x10
	EXIT_MAP
	BACG 1
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_89D                             @ Do you know much about the sword held at the alt
	CLEAN
	MUNO
	REMA
	ENDA

	.global EventScr_08CA93E0
EventScr_08CA93E0:
	IGNORE_KEYS 0x0
	MUSI
	FADI 0x10
	EXIT_MAP
	BACG 1
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_89E                             @ Say, aren't you the... Oh! You're going to help
	CLEAN
	MUNO
	REMA
	ENDA

	.global EventScr_08CA9418
EventScr_08CA9418:
	EVBIT_SILENTSKIP
	IFUA 1, 1, CHARACTER_LYN_TUTORIAL
	ASMC HideMoveRangeGraphics
	CURF CHARACTER_LYN_TUTORIAL
	TEX1 MSG_888                             @ I'm going to visit that home, right? Just point
	CLEAN
	IGNORE_KEYS 0x3F3
	ASMC sub_0807A4C8
	ENUF 7
	GOTO 9
	LABEL 1
	TUTORIAL_CURSORS AreaList_08CA0A5C
	STAL 8
	TUTORIAL_TEXT 56, 56, MSG_889            @ You want me to visit that home, right? I underst
	ASMC_WAIT2 BoxTalkActive
	ASMC_WAIT2 sub_0807A7B4
	IGNORE_KEYS 0x102
	MENU_OVERRIDE_HIDE 0x63
	MENU_OVERRIDE_HIDE 0x67
	LABEL 9
	EVBIT_YESSKIP
	REMA
	ENDA

	.global EventScr_08CA94BC
EventScr_08CA94BC:
	EVBIT_SILENTSKIP
	IFUA 1, 1, CHARACTER_SAIN_TUTORIAL
	ASMC HideMoveRangeGraphics
	CURF CHARACTER_SAIN_TUTORIAL
	TEX1_BY_GENDER MSG_88D, MSG_88E          @ It's my turn to speak with the locals, is it? Th / Please, I would like to help out however I can.
	CLEAN
	IGNORE_KEYS 0x3F3
	ASMC sub_0807A4C8
	ENUF 9
	GOTO 9
	LABEL 1
	TUTORIAL_CURSORS AreaList_08CA0A64
	STAL 8
	TUTORIAL_TEXT_BY_GENDER 52, 56, MSG_890, MSG_891 @ I'm next, am I? Well, I'm ready to go! / It's my turn next? I'm ready to go!
	ASMC_WAIT2 BoxTalkActive
	ASMC_WAIT2 sub_0807A7B4
	IGNORE_KEYS 0x102
	MENU_OVERRIDE_HIDE 0x63
	MENU_OVERRIDE_HIDE 0x5F
	MENU_OVERRIDE_HIDE 0x64
	MENU_OVERRIDE_HIDE 0x67
	LABEL 9
	EVBIT_YESSKIP
	REMA
	ENDA

	.global EventScr_08CA9578
EventScr_08CA9578:
	EVBIT_SILENTSKIP
	IFUA 1, 0xA, CHARACTER_KENT_TUTORIAL
	ASMC HideMoveRangeGraphics
	CURF CHARACTER_SAIN_TUTORIAL
	IFET 5, 0x77
	TEX1 MSG_899                             @ Ah, would you like me to visit that home? Then o
	CLEAN
	GOTO 6
	LABEL 5
	TEX1 MSG_88F                             @ Yes, I await your orders. I understand I am to v
	CLEAN
	LABEL 6
	IGNORE_KEYS 0x3F3
	ASMC sub_0807A4C8
	ENUF 0xB
	GOTO 9
	LABEL 0xA
	IFET 0xF, 0x77
	TUTORIAL_CURSORS AreaList_08CA0A6C
	STAL 8
	TUTORIAL_TEXT 52, 56, MSG_89A            @ I'm next to move, am I not? I await your command
	ASMC_WAIT2 BoxTalkActive
	ENUT 0xD
	GOTO 0x10
	LABEL 0xF
	TUTORIAL_CURSORS AreaList_08CA0A64
	STAL 8
	TUTORIAL_TEXT 52, 56, MSG_892            @ I believe that I am next. I await your command.
	ASMC_WAIT2 BoxTalkActive
	ENUT 0xC
	LABEL 0x10
	ASMC_WAIT2 sub_0807A7B4
	IGNORE_KEYS 0x102
	MENU_OVERRIDE_HIDE 0x63
	MENU_OVERRIDE_HIDE 0x5F
	MENU_OVERRIDE_HIDE 0x64
	MENU_OVERRIDE_HIDE 0x67
	LABEL 9
	EVBIT_YESSKIP
	REMA
	ENDA

	.global EventScr_08CA96A8
EventScr_08CA96A8:
	EVBIT_SILENTSKIP
	TUTORIAL_CURSORS AreaList_08CA0A5C
	STAL 8
	TUTORIAL_TEXT 52, 56, MSG_88A            @ First, I'm going to visit that home, right? Well
	ASMC_WAIT2 BoxTalkActive
	ASMC_WAIT2 sub_0807A7B4
	ENUF 0xE
	EVBIT_YESSKIP
	REMA
	ENDA

	.global EventScr_08CA96E4
EventScr_08CA96E4:
	EVBIT_SILENTSKIP
	TUTORIAL_CURSORS AreaList_08CA0A64
	STAL 8
	TUTORIAL_TEXT_BY_GENDER 48, 56, MSG_893, MSG_894 @ It's my turn to speak with the locals, isn't it? / Please, I would like to help out however I can.
	ASMC_WAIT2 BoxTalkActive
	ASMC_WAIT2 sub_0807A7B4
	ENUF 0xF
	EVBIT_YESSKIP
	REMA
	ENDA

	.global EventScr_08CA9724
EventScr_08CA9724:
	EVBIT_SILENTSKIP
	IFET 5, 0x77
	TUTORIAL_CURSORS AreaList_08CA0A6C
	STAL 8
	TUTORIAL_TEXT 52, 56, MSG_89B            @ Am I not supposed to visit that home? Please, gi
	ASMC_WAIT2 BoxTalkActive
	GOTO 6
	LABEL 5
	TUTORIAL_CURSORS AreaList_08CA0A64
	STAL 8
	TUTORIAL_TEXT 52, 56, MSG_895            @ Yes, I await your orders. I understand I am to v
	ASMC_WAIT2 BoxTalkActive
	LABEL 6
	ASMC_WAIT2 sub_0807A7B4
	ENUF 0x10
	EVBIT_YESSKIP
	REMA
	ENDA

	.global EventScr_08CA97A4
EventScr_08CA97A4:
	EVBIT_SILENTSKIP
	ASMC sub_0801CD50
	IGNORE_KEYS 0x0
	MENU_OVERRIDE_CLEAR
	IFET 5, 0x77
	IFTU 0x32
	CURF CHARACTER_SAIN_TUTORIAL
	STAL 8
	TUTORIAL_TEXT 0, 0, MSG_88B, 5           @ Next, send Sain to visit another home. Start by
	ASMC_WAIT2 BoxTalkActive
	LABEL 0x32
	IFDIFF 1, 0x63
	ENUT 8
	MENU_OVERRIDE_HIDE 0x71
	GOTO 0x63
	LABEL 5
	IFET 0x63, 0x76
	IFTU 0x33
	CURF CHARACTER_KENT_TUTORIAL
	STAL 8
	TUTORIAL_TEXT 0, 0, MSG_88C, 5           @ Now, send Kent to visit the next home. First, se
	ASMC_WAIT2 BoxTalkActive
	LABEL 0x33
	IFDIFF 1, 0x63
	ENUT 0xA
	MENU_OVERRIDE_HIDE 0x71
	LABEL 0x63
	REMA
	ENDA

	.global EventScr_08CA987C
EventScr_08CA987C:
	EVBIT_SILENTSKIP
	MENU_OVERRIDE_CLEAR
	IFTU 0x32
	STAL 8
	TUTORIAL_TEXT 0, 0, MSG_896, 5           @ Remember, your mounted units possess the ability
	ASMC_WAIT2 BoxTalkActive
	ENUT 0x16
	LABEL 0x32
	REMA
	ENDA

	.global EventScr_08CA98B8
EventScr_08CA98B8:
	EVBIT_SILENTSKIP
	ASMC sub_0801CD50
	IFET 0x63, 0x76
	IFTU 0x32
	CURF CHARACTER_KENT_TUTORIAL
	STAL 8
	TUTORIAL_TEXT 0, 0, MSG_898, 5           @ Finally, let's send Kent to visit the remaining
	ASMC_WAIT2 BoxTalkActive
	LABEL 0x32
	ENUT 0xA
	MENU_OVERRIDE_HIDE 0x71
	LABEL 0x63
	REMA
	ENDA

	.global EventScr_08CA991C
EventScr_08CA991C:
	EVBIT_SILENTSKIP
	MENU_OVERRIDE_CLEAR
	IFET 0x32, 0x16
	IFTU 0x32
	STAL 8
	TUTORIAL_TEXT 0, 0, MSG_897, 5           @ Remember, your mounted units possess the ability
	ASMC_WAIT2 BoxTalkActive
	LABEL 0x32
	REMA
	ENDA

	.global EventScr_08CA9960
EventScr_08CA9960:
	EVBIT_SILENTSKIP
	IFTU 0x32
	STAL 8
	TUTORIAL_TEXT 0, 0, MSG_8A3, 5           @ Sometimes, you'll get items after defeating enem
	ASMC_WAIT2 BoxTalkActive
	LABEL 0x32
	REMA
	ENDA

	.global EventScr_Ch02_Ending
EventScr_Ch02_Ending:
	MENU_OVERRIDE_CLEAR
	MUSC 0x38
	STAL 0x40
	FADI 0x10
	EXIT_MAP
	ASMC sub_0807A8B8
	LOU1 Units_08CC5DC8
	MOVE_INSTANT CHARACTER_LYN_TUTORIAL, 11, 2
	MOVE_INSTANT CHARACTER_KENT_TUTORIAL, 10, 5
	MOVE_INSTANT CHARACTER_SAIN_TUTORIAL, 12, 5
	BACG 0x4F
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_8A4                             @ Ah, your clothing... Are you of the Lorca tribe?
	MUEN 4
	STAL 0x3C
	STAL 0x20
	SOUN 0x26C
	FAWI 0x10
	EXIT_MAP
	TEXTEND
	STAL 3
	FAWU 0x10
	ENTER_MAP
	TEX2 MSG_8A5                             @ Hm? What? Did--
	SOUN 0x2EB
	FAWI 4
	EXIT_MAP
	TEXTEND
	STAL 0xA
	FAWU 4
	ENTER_MAP
	TEX2 MSG_8A6                             @ The sword... It's...glowing. Ah. Hm... It's the
	FAWI 0x10
	EXIT_MAP
	ASMC ClearTalk
	SOUN 0x2DA
	STAL 0x20
	CG_BACG 2
	FAWU 0x10
	ENTER_MAP
	STAL 0x3C
	CG_TEXT MSG_8A7, 1                       @ Lyn It came out...effortlessly.
	MURE 6
	CG_TEXT_MORE MSG_8A8, 1                  @ Priest I never dared to hope that I might meet t
	CG_TEXT_MORE MSG_8A9, 1                  @ Lyn My sword?
	STAL3 0x3C
	FADI 0x10
	EXIT_MAP
	ASMC ImmediateDisplayMap
	BACG 0x4F
	FADU 4
	ENTER_MAP
	MUSC SONG_3F
	TEX1 MSG_8AA                             @ It is time for you to go, Lyn. You face a great
	CLEAN
	EVBIT_NOSKIP
	ENTER_MAP
	ITGC CHARACTER_LYN_TUTORIAL, ITEM_SWORD_MKATTI
	EVBIT_YESSKIP
	STAL 0x20
	FADI 4
	EXIT_MAP
	STAL 0x40
	BACG 0x22
	FADU 4
	ENTER_MAP
	TEX1 MSG_8AB                             @ So this is the Mani Katti... A blade with no equ
	TEX2 MSG_8AC                             @ Think of it this way: Some weapons feel more com
	MUEN 8
	CALL EventScr_08CC0928
	CLEAR_ON_SKIP_ASM
	FADI 4
	EXIT_MAP
	ASMC sub_0807A8B8
	LOMA CHAPTER_0B, 2, 0x10
	STAL 0x80
	MUSC 0x53
	FADU 2
	ENTER_MAP
	BROWN_TEXTBOX MSG_5DF, 16, 12            @ Castle Caelin
	STAL 0x64
	BROWN_TEXTBOX_END
	STAL 0x10
	CURF_POS 2, 16
	STAL 0x20
	FADI 0x10
	EXIT_MAP
	BACG 0x10
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_8AD                             @ What? Madelyn's daughter is still alive? Uh... Y
	FADI 4
	EXIT_MAP
	BACG 0x5B
	LOMA_ID CHAPTER_02
	MNCH CHAPTER_03
	STAL 1
	ENDB
	REMA
	ENDA

	.section .rodata.ev_08CC5CE8, "a"

	.global Units_Ch02_Player
Units_Ch02_Player:
	UNIT CHARACTER_LYN_TUTORIAL, CLASS_LORD_LYN, CHARACTER_NONE, 2, FACTION_ID_BLUE, 0, 2, 0, 2, 0, ITEM_SWORD_IRON, ITEM_VULNERARY
	UNIT CHARACTER_SAIN_TUTORIAL, CLASS_CAVALIER, CHARACTER_LYN_TUTORIAL, 1, FACTION_ID_BLUE, 0, 1, 0, 1, 0, ITEM_SWORD_IRON, ITEM_LANCE_IRON, ITEM_VULNERARY
	UNIT CHARACTER_KENT_TUTORIAL, CLASS_CAVALIER, CHARACTER_LYN_TUTORIAL, 1, FACTION_ID_BLUE, 0, 0, 0, 0, 0, ITEM_SWORD_IRON, ITEM_LANCE_IRON, ITEM_VULNERARY
	UNIT_END

	.global Units_08CC5D28
Units_08CC5D28:
	UNIT CHARACTER_TACTICIAN, CLASS_PRINCE_51, CHARACTER_NONE, 1, FACTION_ID_GREEN, 0, 1, 0, 1, 3
	UNIT_END

	.global Units_Ch02_Initial
Units_Ch02_Initial:
	UNIT_END

	.global Units_08CC5D58
Units_08CC5D58:
	UNIT CHARACTER_GLASS, CLASS_MERCENARY, CHARACTER_NONE, 3, FACTION_ID_RED, 0, 11, 9, 11, 2, ITEM_SWORD_IRON, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0x3, 0x3, 0x2, 0x20
	UNIT CHARACTER_BANDIT_8A, CLASS_BRIGAND, CHARACTER_GLASS, 1, FACTION_ID_RED, 1, 7, 0, 7, 0, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x8, 0x0, 0x1
	UNIT CHARACTER_BANDIT_8B, CLASS_BRIGAND, CHARACTER_GLASS, 2, FACTION_ID_RED, 1, 11, 9, 11, 3, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x8, 0x3, 0x1
	UNIT CHARACTER_BANDIT_8A, CLASS_BRIGAND, CHARACTER_GLASS, 1, FACTION_ID_RED, 1, 10, 9, 7, 9, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x8, 0x0, 0x1
	UNIT CHARACTER_BANDIT_8A, CLASS_BRIGAND, CHARACTER_GLASS, 1, FACTION_ID_RED, 1, 11, 9, 11, 9, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x8, 0x0, 0x1
	UNIT CHARACTER_BANDIT_8B, CLASS_BRIGAND, CHARACTER_GLASS, 2, FACTION_ID_RED, 1, 12, 9, 13, 8, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x8, 0x3, 0x1
	UNIT_END

	.global Units_08CC5DC8
Units_08CC5DC8:
	UNIT CHARACTER_CITIZEN_DA, CLASS_BISHOP, CHARACTER_NONE, 1, FACTION_ID_GREEN, 0, 11, 1, 11, 1, ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x6, 0x3, 0x1
	UNIT_END

	.global Units_08CC5DE8
Units_08CC5DE8:
	UNIT CHARACTER_CITIZEN_DB, CLASS_CIVILIAN_48, CHARACTER_NONE, 1, FACTION_ID_GREEN, 0, 7, 5, 7, 5
	UNIT_END

	.global EventScr_08CC5E08
EventScr_08CC5E08:	@ unreferenced
	LOU1 Units_Ch02_Player
	ENUN
	REMA
	ENDA

	.global EventScr_08CC5E1C
EventScr_08CC5E1C:	@ unreferenced
	LOU1 Units_08CC5D28
	ENUN
	REMA
	ENDA

	.global EventScr_08CC5E30
EventScr_08CC5E30:	@ unreferenced
	UNIT_CAM_OFF
	EVBIT_NOSKIP
	LOU1 Units_Ch02_Initial
	ENUN
	REMA
	ENDA

	.global EventScr_08CC5E4C
EventScr_08CC5E4C:	@ unreferenced
	LOU1 Units_08CC5D58
	ENUN
	REMA
	ENDA

	.global EventScr_08CC5E60
EventScr_08CC5E60:	@ unreferenced
	LOU1 Units_08CC5DC8
	ENUN
	REMA
	ENDA

	.global EventScr_08CC5E74
EventScr_08CC5E74:	@ unreferenced
	LOU1 Units_08CC5DE8
	ENUN
	REMA
	ENDA
