@ Chapter 0x0C: Ch. 11: Taking Leave (E)
@ Generated by tools/evdis.py

#include "event_macros.inc"

	.section .rodata.ev_08CA18F0, "a"

	.align 2, 0
	.global EvList_Ch0C_Turn
EvList_Ch0C_Turn:
	TURN 0, EventScr_Ch0C_Beginning, 1, 0, FACTION_BLUE, 0
	TURN 0, EventScr_08CAE350, 2, 0, FACTION_BLUE, 0
	EVLIST_END

	.align 2, 0
	.global EvList_Ch0C_Character
EvList_Ch0C_Character:
	EVLIST_END

	.align 2, 0
	.global EvList_Ch0C_Location
EvList_Ch0C_Location:
	LOCA 0, EventScr_08CAE378, 9, 2, 0xE
	LOCA 0, EventScr_08CAE3B0, 0xA, 2, 0xE
	VILL 8, EventScr_08CAE3E0, 0x10, 2, 0xE
	LOCA 8, EVENT_NOSCRIPT, 0x10, 1, 0x1D
	LOCA 3, EVENT_NOSCRIPT, 3, 7, 0xF
	SHOP 0, ShopList_08CA6F72, 6, 4, 0x14
	EVLIST_END

	.align 2, 0
	.global EvList_Ch0C_Misc
EvList_Ch0C_Misc:
	AFEV 0, gEvent_GameOver, 0x65
	EVLIST_END

	.align 2, 0
	.global ChapterEvents_Ch0C
ChapterEvents_Ch0C:
	.4byte EvList_Ch0C_Turn                  @ turn
	.4byte EvList_Ch0C_Character             @ character
	.4byte EvList_Ch0C_Location              @ location
	.4byte EvList_Ch0C_Misc                  @ misc
	.4byte Traps_Ch0C                        @ traps
	.4byte Traps_Ch0C_Hector                 @ traps (Hector mode)
	.4byte Units_Ch0C_Initial                @ units loaded at start
	.4byte Units_Ch0C_Initial                @ (hard)
	.4byte Units_Ch0C_Initial                @ (Hector mode)
	.4byte Units_Ch0C_Initial                @ (Hector mode, hard)
	.4byte Units_Ch0C_Player                 @ player units
	.4byte Units_Ch0C_Player                 @ (hard)
	.4byte Units_Ch0C_Player                 @ (Hector mode)
	.4byte Units_Ch0C_Player                 @ (Hector mode, hard)
	.4byte EventScr_Ch0C_Beginning           @ beginning scene
	.4byte EventScr_Ch0C_Ending              @ ending scene

	.section .rodata.ev_08CAE020, "a"

	.align 2, 0
	.global MoveScr_08CAE020
MoveScr_08CAE020:
	.byte MV_DOWN, MV_DOWN, MV_RIGHT, MV_HALT

	.align 2, 0
	.global MoveScr_08CAE024
MoveScr_08CAE024:
	.byte MV_RIGHT, MV_RIGHT, MV_UP, MV_HALT

	.align 2, 0
	.global MoveScr_08CAE028
MoveScr_08CAE028:
	.byte MV_DOWN, MV_HALT

	.global MoveScr_08CAE02A
MoveScr_08CAE02A:
	.byte MV_LEFT, MV_HALT

	.align 2, 0
	.global MoveScr_08CAE02C
MoveScr_08CAE02C:
	.byte MV_SPEED, 0x8, MV_LEFT, MV_UP, MV_HALT

	.align 2, 0
	.global EventScr_Ch0C_Beginning
EventScr_Ch0C_Beginning:
	UNIT_CAM_OFF
	ASMC sub_0807CFE4
	LOU1 Units_08CC7DDC
	ENUN
	LOU1 Units_Ch0C_Player
	ENUN
	LOU1 Units_08CC7BFC
	ENUN
	LOU1 Units_Ch0C_Initial
	ENUN
	TEX1 MSG_9F6                             @ Lord Eliwood, we leave on your word. I see. Than
	CLEAN
	CAM1 CHARACTER_ELIWOOD
	UNIT_CAM_ON
	MOVE CHARACTER_ELIWOOD, 15, 10
	MOVE CHARACTER_MARCUS, 14, 11
	ENUN
	STAL 0xF
	MOVE_SPEED CHARACTER_ELEANORA, 16, 10, 8
	ENUN
	STAL 0x1E
	FADI 0x10
	EXIT_MAP
	BACG 0x1C
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_9F7                             @ Mother, it's time for us to go. Eliwood... Promi
	CLEAN
	STAL 0x1E
	MOVE_SPEED CHARACTER_ELEANORA, 18, 10, 8
	ENUN
	DISA CHARACTER_ELEANORA
	MUEN 4
	MOVE CHARACTER_BANDIT_67, 18, 9
	MOVE CHARACTER_ISADORA, 18, 11
	ENUN
	DISA CHARACTER_BANDIT_67
	DISA CHARACTER_ISADORA
	STAL 0x1E
	MOVE CHARACTER_MARCUS, 15, 11
	ENUN
	MUSC SONG_33
	TEX1 MSG_9F8                             @ Well, Marcus, it looks like it's just the two of
	CLEAN
	MUEN 4
	CAM1_POS 3, 7
	CURF_POS 3, 7
	MUSC 0x20
	FADI 0x10
	EXIT_MAP
	BACG 2
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_9F9                             @ We've all heard that the knights of Pherae have
	CLEAN
	LOU1 Units_08CC7C1C
	ENUN
	STAL 0x1E
	LOU1 Units_08CC7C8C
	ENUN
	MOVE_SCR CHARACTER_REBECCA, MoveScr_08CAE020
	ENUN
	DISA CHARACTER_REBECCA
	MOVE CHARACTER_LOWEN, 15, 9
	ENUN
	MUSC SONG_32
	FADI 0x10
	EXIT_MAP
	BACG 0x1C
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_9FA                             @ Lord Eliwood! Co-Commander Marcus! I... Lowen! C
	CLEAN
	STAL 0x1E
	LOU1 Units_08CC7C3C
	ENUN
	MOVE_SPEED CHARACTER_REBECCA, 14, 10, 0x10
	STAL 0x1E
	FADI 0x10
	EXIT_MAP
	BACG 0x1C
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_9FB                             @ My lord Eliwood? I'm the daughter of the village
	IFAF 0xB, sub_0807A3B8
	STAL 0x1E
	FADI 0x10
	EXIT_MAP
	BACG 0x1C
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_9FC                             @ Lord Eliwood, one more thing. There is another i
	CLEAN
	STAL 0x10
	LOU1 Units_08CC7E1C
	ENUN
	MOVE_SPEED CHARACTER_TACTICIAN, 16, 10, 0x10
	ENUN
	FADI 0x10
	EXIT_MAP
	BACG 0x1C
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_9FD                             @ ! Do you know this person, milord? Yes. I met du
	TEXTEND
	STAL 0x3C
	TEX2 MSG_9FE                             @ Ha! Still traveling about, honing your skills? O
	LABEL 0xB
	CLEAN
	LOU1 Units_08CC7CBC
	ENUN
	LOU1 Units_08CC7D0C
	ENUN
	LOU1 Units_08CC7D4C
	ENUN
	LOU1 Units_08CC7D6C
	ENUN
	IFAF 0xE, sub_0807A3B8
	MOVE_SCR CHARACTER_TACTICIAN, MoveScr_08CAE02A
	ENUN
	DISA CHARACTER_TACTICIAN
	LABEL 0xE
	MOVE_SCR CHARACTER_REBECCA, MoveScr_08CAE024
	MOVE CHARACTER_MARCUS, 14, 11
	MOVE_SCR CHARACTER_ELIWOOD, MoveScr_08CAE028
	ENUN
	LOU1_IF_MODE 2, 1, Units_08CC7D9C
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CAE350
EventScr_08CAE350:
	LOU1 Units_08CC7C5C
	ENUN
	MUSS 0x42
	TEX1 MSG_9FF                             @ Look, Dorcas! Can you believe it? It's just like
	CLEAN
	MURE 6
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CAE378
EventScr_08CAE378:
	MUSI
	FADI 0x10
	EXIT_MAP
	BACG 1
	FADU 0x10
	ENTER_MAP
	TEX1_IF_ASM sub_0807A3B8, MSG_A03, MSG_A02 @ There's a young traveler been stayin' with the m / This is terrible! Bandits! B-B-Bandits from the
	CLEAN
	MUNO
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CAE3B0
EventScr_08CAE3B0:
	MUSI
	FADI 0x10
	EXIT_MAP
	BACG 1
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_A04                             @ You've got some skill with weapons, but do you u
	CLEAN
	MUNO
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CAE3E0
EventScr_08CAE3E0:
	MUSI
	FADI 0x10
	EXIT_MAP
	BACG 2
	FADU 0x10
	ENTER_MAP
	IFUA 0, 5, CHARACTER_ELIWOOD
	TEX1 MSG_A01                             @ Lord Eliwood, it is you! I can't thank you enoug
	GOTO 7
	LABEL 5
	TEX1 MSG_A00                             @ Is Lord Elbert well? We've heard nothing but fou
	LABEL 7
	CLEAN
	MUNO
	EVBIT_NOSKIP
	ENTER_MAP
	ITGV ITEM_BOOSTER_DEF
	REMA
	ENDA

	.align 2, 0
	.global EventScr_Ch0C_Ending
EventScr_Ch0C_Ending:
	MUSC 0x38
	STAL 0x3C
	FADI 4
	EXIT_MAP
	ASMC sub_0807A8B8
	BACG 2
	FADU 4
	ENTER_MAP
	TEX1 MSG_A07                             @ Ah, you would be Lord Eliwood, yes? Our deepest
	TEX2 MSG_A08                             @ Lord Eliwood, if this is true, the situation is
	CLEAN
	LOU1 Units_08CC7E3C
	STAL 5
	SKIP_IFN_ASM 1, sub_0807A3B8
	LOU1 Units_08CC7EAC
	ENUN
	IFAF 5, sub_0807A3B8
	TEX1 MSG_A09                             @ Thank you for your guidance, . Where are you bou
	STAL 0x3C
	TEX2 MSG_A0A                             @ You will travel with us? Splendid! Thank you! I
	CLEAN
	MOVE_SPEED CHARACTER_ELIWOOD, 2, 8, 0x10
	ENUN
	MOVE_SCR CHARACTER_TACTICIAN, MoveScr_08CAE02C
	ENUN
	DISA CHARACTER_TACTICIAN
	LABEL 5
	MOVE_SPEED CHARACTER_ELIWOOD, -1, 5, 0xF
	STAL 0x3C
	MOVE_SPEED CHARACTER_MARCUS, -1, 5, 0xF
	ENUN
	IFAT 7, sub_0807A3B8
	LOU1 Units_08CC7E6C
	ENUN
	TEX1 MSG_A0B                             @ Good luck! Travel safely!
	CLEAN
	LABEL 7
	IFAF 8, sub_08079D8C
	LOU1 Units_08CC7E8C
	STAL 0x10
	SKIP_IFN_ASM 1, sub_0807A3B8
	LOU1 Units_08CC7E6C
	ENUN
	STAL 0x20
	FADI 0x10
	EXIT_MAP
	BACG 2
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_A0C                             @ Rebecca! Where do you think you're going, young
	CLEAN
	MOVE_SPEED CHARACTER_REBECCA, -1, 5, 0x14
	ENUN
	LABEL 8
	CALL EventScr_08CC0C14
	CLEAR_ON_SKIP_ASM
	FADI 4
	EXIT_MAP
	BACG 0x5B
	MNCH CHAPTER_0E
	STAL 1
	ENDB
	REMA
	ENDA

	.section .rodata.ev_08CC7BDC, "a"

	.align 2, 0
	.global Units_Ch0C_Player
Units_Ch0C_Player:
	UNIT CHARACTER_ELIWOOD, CLASS_LORD_ELIWOOD, CHARACTER_NONE, 1, FACTION_ID_BLUE, 0, 12, 11, 12, 10, ITEM_SWORD_RAPIER, ITEM_VULNERARY
	UNIT_END

	.align 2, 0
	.global Units_08CC7BFC
Units_08CC7BFC:
	UNIT CHARACTER_MARCUS, CLASS_PALADIN, CHARACTER_ELIWOOD, 1, FACTION_ID_BLUE, 0, 15, 8, 12, 9, ITEM_SWORD_STEEL, ITEM_LANCE_STEEL
	UNIT_END

	.align 2, 0
	.global Units_08CC7C1C
Units_08CC7C1C:
	UNIT CHARACTER_LOWEN, CLASS_CAVALIER, CHARACTER_ELIWOOD, 2, FACTION_ID_BLUE, 0, 3, 7, 4, 9, ITEM_SWORD_IRON, ITEM_LANCE_JAVELIN
	UNIT_END

	.align 2, 0
	.global Units_08CC7C3C
Units_08CC7C3C:
	UNIT CHARACTER_REBECCA, CLASS_ARCHER_F, CHARACTER_ELIWOOD, 1, FACTION_ID_BLUE, 0, 15, 9, 14, 9, ITEM_BOW_IRON, ITEM_VULNERARY
	UNIT_END

	.align 2, 0
	.global Units_08CC7C5C
Units_08CC7C5C:
	UNIT CHARACTER_DORCAS, CLASS_FIGHTER, CHARACTER_ELIWOOD, 3, FACTION_ID_BLUE, 0, 16, 2, 16, 3, ITEM_AXE_STEEL, ITEM_BOOSTER_POW
	UNIT CHARACTER_BARTRE, CLASS_FIGHTER, CHARACTER_ELIWOOD, 2, FACTION_ID_BLUE, 0, 16, 2, 17, 3, ITEM_AXE_IRON, ITEM_AXE_HANDAXE
	UNIT_END

	.align 2, 0
	.global Units_08CC7C8C
Units_08CC7C8C:
	UNIT CHARACTER_REBECCA, CLASS_ARCHER_F, CHARACTER_ELIWOOD, 1, FACTION_ID_BLUE, 0, 3, 7, 3, 7, ITEM_BOW_IRON, ITEM_VULNERARY
	UNIT_END

	.align 2, 0
	.global Units_Ch0C_Initial
Units_Ch0C_Initial:
	UNIT_END

	.align 2, 0
	.global Units_08CC7CBC
Units_08CC7CBC:
	UNIT CHARACTER_GROZNYI, CLASS_BRIGAND, CHARACTER_NONE, 5, FACTION_ID_RED, 0, 2, 10, 3, 7, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x3, 0x3, 0x9, 0x20
	UNIT CHARACTER_BANDIT_3E, CLASS_ARCHER, CHARACTER_GROZNYI, 1, FACTION_ID_RED, 0, 2, 10, 3, 9, ITEM_BOW_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x3, 0x29
	UNIT CHARACTER_BANDIT_3E, CLASS_BRIGAND, CHARACTER_GROZNYI, 2, FACTION_ID_RED, 1, 2, 10, 2, 8, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x3, 0x9
	UNIT CHARACTER_BANDIT_3E, CLASS_BRIGAND, CHARACTER_GROZNYI, 2, FACTION_ID_RED, 1, 2, 10, 4, 8, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x3, 0x9
	UNIT_END

	.align 2, 0
	.global Units_08CC7D0C
Units_08CC7D0C:
	UNIT CHARACTER_BANDIT_3E, CLASS_BRIGAND, CHARACTER_GROZNYI, 1, FACTION_ID_RED, 1, 2, 10, 7, 7, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x3, 0x9
	UNIT CHARACTER_BANDIT_3E, CLASS_BRIGAND, CHARACTER_GROZNYI, 3, FACTION_ID_RED, 1, 14, 4, 12, 3, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0x9
	UNIT CHARACTER_BANDIT_3E, CLASS_BRIGAND, CHARACTER_GROZNYI, 1, FACTION_ID_RED, 1, 14, 4, 15, 5, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x3, 0x9
	UNIT_END

	.align 2, 0
	.global Units_08CC7D4C
Units_08CC7D4C:
	UNIT CHARACTER_BANDIT_3E, CLASS_BRIGAND, CHARACTER_GROZNYI, 1, FACTION_ID_RED, 1, 2, 10, 0, 10, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0x9
	UNIT_END

	.align 2, 0
	.global Units_08CC7D6C
Units_08CC7D6C:
	UNIT CHARACTER_BANDIT_3E, CLASS_ARCHER, CHARACTER_GROZNYI, 2, FACTION_ID_RED, 1, 14, 4, 8, 3, ITEM_BOW_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0x29
	UNIT CHARACTER_BANDIT_3E, CLASS_BRIGAND, CHARACTER_GROZNYI, 1, FACTION_ID_RED, 1, 2, 10, 1, 4, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0x9
	UNIT_END

	.align 2, 0
	.global Units_08CC7D9C
Units_08CC7D9C:
	UNIT CHARACTER_BANDIT_3E, CLASS_BRIGAND, CHARACTER_GROZNYI, 1, FACTION_ID_RED, 1, 1, 1, 1, 1, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0x9
	UNIT CHARACTER_BANDIT_3E, CLASS_BRIGAND, CHARACTER_GROZNYI, 1, FACTION_ID_RED, 1, 2, 0, 2, 0, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0x9
	UNIT CHARACTER_BANDIT_3E, CLASS_BRIGAND, CHARACTER_GROZNYI, 1, FACTION_ID_RED, 1, 10, 5, 10, 5, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0x9
	UNIT_END

	.align 2, 0
	.global Units_08CC7DDC
Units_08CC7DDC:
	UNIT CHARACTER_ELEANORA, CLASS_BISHOP_F, CHARACTER_NONE, 1, FACTION_ID_GREEN, 0, 17, 11, 17, 10
	UNIT CHARACTER_ISADORA, CLASS_PALADIN_F, CHARACTER_ELIWOOD, 1, FACTION_ID_GREEN, 0, 17, 11, 17, 11, ITEM_SWORD_IRON, ITEM_LANCE_SILVER
	UNIT CHARACTER_BANDIT_67, CLASS_CAVALIER_F, CHARACTER_ELIWOOD, 1, FACTION_ID_GREEN, 0, 17, 9, 17, 9, ITEM_SWORD_IRON, ITEM_LANCE_SILVER
	UNIT_END

	.align 2, 0
	.global Units_08CC7E1C
Units_08CC7E1C:
	UNIT CHARACTER_TACTICIAN, CLASS_PRINCE_51, CHARACTER_NONE, 1, FACTION_ID_GREEN, 0, 15, 9, 16, 9
	UNIT_END

	.align 2, 0
	.global Units_08CC7E3C
Units_08CC7E3C:
	UNIT CHARACTER_ELIWOOD, CLASS_LORD_ELIWOOD, CHARACTER_NONE, 1, FACTION_ID_BLUE, 0, 3, 7, 1, 8, ITEM_SWORD_RAPIER, ITEM_VULNERARY
	UNIT CHARACTER_MARCUS, CLASS_PALADIN, CHARACTER_ELIWOOD, 1, FACTION_ID_BLUE, 0, 3, 7, 1, 9, ITEM_SWORD_IRON, ITEM_LANCE_SILVER
	UNIT_END

	.align 2, 0
	.global Units_08CC7E6C
Units_08CC7E6C:
	UNIT CHARACTER_CITIZEN_DA, CLASS_CIVILIAN_47, CHARACTER_NONE, 7, FACTION_ID_GREEN, 1, 3, 7, 3, 8, ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x6
	UNIT_END

	.align 2, 0
	.global Units_08CC7E8C
Units_08CC7E8C:
	UNIT CHARACTER_REBECCA, CLASS_ARCHER_F, CHARACTER_ELIWOOD, 1, FACTION_ID_BLUE, 0, 3, 7, 1, 8, ITEM_BOW_IRON, ITEM_VULNERARY
	UNIT_END

	.align 2, 0
	.global Units_08CC7EAC
Units_08CC7EAC:
	UNIT CHARACTER_TACTICIAN, CLASS_PRINCE_51, CHARACTER_NONE, 1, FACTION_ID_GREEN, 0, 3, 7, 3, 9
	UNIT_END

	.align 2, 0
	.global EventScr_08CC7ECC
EventScr_08CC7ECC:	@ unreferenced
	LOU1 Units_Ch0C_Player
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC7EE0
EventScr_08CC7EE0:	@ unreferenced
	LOU1 Units_08CC7BFC
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC7EF4
EventScr_08CC7EF4:	@ unreferenced
	LOU1 Units_08CC7C1C
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC7F08
EventScr_08CC7F08:	@ unreferenced
	LOU1 Units_08CC7C3C
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC7F1C
EventScr_08CC7F1C:	@ unreferenced
	LOU1 Units_08CC7C5C
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC7F30
EventScr_08CC7F30:	@ unreferenced
	LOU1 Units_08CC7C8C
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC7F44
EventScr_08CC7F44:	@ unreferenced
	UNIT_CAM_OFF
	EVBIT_NOSKIP
	LOU1 Units_Ch0C_Initial
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC7F60
EventScr_08CC7F60:	@ unreferenced
	LOU1 Units_08CC7CBC
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC7F74
EventScr_08CC7F74:	@ unreferenced
	LOU1 Units_08CC7D0C
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC7F88
EventScr_08CC7F88:	@ unreferenced
	LOU1 Units_08CC7D4C
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC7F9C
EventScr_08CC7F9C:	@ unreferenced
	LOU1 Units_08CC7D6C
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC7FB0
EventScr_08CC7FB0:	@ unreferenced
	LOU1 Units_08CC7D9C
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC7FC4
EventScr_08CC7FC4:	@ unreferenced
	LOU1 Units_08CC7DDC
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC7FD8
EventScr_08CC7FD8:	@ unreferenced
	LOU1 Units_08CC7E1C
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC7FEC
EventScr_08CC7FEC:	@ unreferenced
	LOU1 Units_08CC7E3C
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC8000
EventScr_08CC8000:	@ unreferenced
	LOU1 Units_08CC7E6C
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC8014
EventScr_08CC8014:	@ unreferenced
	LOU1 Units_08CC7E8C
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC8028
EventScr_08CC8028:	@ unreferenced
	LOU1 Units_08CC7EAC
	ENUN
	REMA
	ENDA
