@ Chapter 0x0D: Ch. 11: Another Journey (H)
@ Generated by tools/evdis.py

#include "event_macros.inc"

	.section .rodata.ev_08CA19B4, "a"

	.align 2, 0
	.global EvList_Ch0D_Turn
EvList_Ch0D_Turn:
	TURN 0, EventScr_Ch0D_Beginning, 1, 0, FACTION_BLUE, 0
	EVLIST_END

	.align 2, 0
	.global EvList_Ch0D_Character
EvList_Ch0D_Character:
	EVLIST_END

	.align 2, 0
	.global EvList_Ch0D_Location
EvList_Ch0D_Location:
	CHES 8, ITEM_REDGEM, 0, 0xB, 5, 0x12
	DOOR 0, EVENT_NOSCRIPT, 0xB, 3, 0x10
	DOOR 0, EVENT_NOSCRIPT, 1, 3, 0x10
	DOOR 0, EVENT_NOSCRIPT, 0xB, 7, 0x10
	DOOR 0, EVENT_NOSCRIPT, 6, 3, 0x10
	DOOR 0, EVENT_NOSCRIPT, 0xF, 3, 0x10
	EVLIST_END

	.align 2, 0
	.global EvList_Ch0D_Misc
EvList_Ch0D_Misc:
	AFEV 0, EventScr_Ch0D_Ending, 2
	AFEV 0, gEvent_GameOver, 0x65
	EVLIST_END

	.align 2, 0
	.global ChapterEvents_Ch0D
ChapterEvents_Ch0D:
	.4byte EvList_Ch0D_Turn                  @ turn
	.4byte EvList_Ch0D_Character             @ character
	.4byte EvList_Ch0D_Location              @ location
	.4byte EvList_Ch0D_Misc                  @ misc
	.4byte Traps_Ch0D                        @ traps
	.4byte Traps_Ch0D_Hector                 @ traps (Hector mode)
	.4byte Units_Ch0D_Initial                @ units loaded at start
	.4byte Units_Ch0D_Initial                @ (hard)
	.4byte Units_Ch0D_Initial                @ (Hector mode)
	.4byte Units_Ch0D_Initial                @ (Hector mode, hard)
	.4byte Units_Ch0D_Player                 @ player units
	.4byte Units_Ch0D_Player                 @ (hard)
	.4byte Units_Ch0D_Player                 @ (Hector mode)
	.4byte Units_Ch0D_Player                 @ (Hector mode, hard)
	.4byte EventScr_Ch0D_Beginning           @ beginning scene
	.4byte EventScr_Ch0D_Ending              @ ending scene

	.section .rodata.ev_08CAE5E8, "a"

	.align 2, 0
	.global MoveScr_08CAE5E8
MoveScr_08CAE5E8:
	.byte MV_SPEED, 0x38, MV_DOWN, MV_DOWN, MV_LEFT, MV_LEFT, MV_HALT

	.global MoveScr_08CAE5EF
MoveScr_08CAE5EF:
	.byte MV_SPEED, 0x38, MV_LEFT, MV_HALT

	.global MoveScr_08CAE5F3
MoveScr_08CAE5F3:
	.byte MV_SPEED, 0x38, MV_LEFT, MV_DOWN, MV_HALT

	.align 2, 0
	.global SpriteAnimConf_08CAE5F8
SpriteAnimConf_08CAE5F8:
	.4byte 0, Img_EventSpriteAnim_SpawnThief, ApConf_EventSpriteAnim_SpawnAssassin
	.2byte 0x0, 0x200
	.byte 10, 1, 0, 0

	.align 2, 0
	.global EventScr_Ch0D_Beginning
EventScr_Ch0D_Beginning:
	UNIT_CAM_OFF
	PAL_FADE_TO_BLACK 0
	EXIT_MAP
	CG_BACG 0x33
	PAL_FADE_FROM_BLACK 2
	ENTER_MAP
	BROWN_TEXTBOX MSG_5DA, 136, 12           @ Castle Ostia
	STAL 0x64
	BROWN_TEXTBOX_END
	STAL 0x20
	FADI 4
	EXIT_MAP
	ASMC ImmediateDisplayMap
	BACG 0x10
	FADU 4
	ENTER_MAP
	TEX1 MSG_A0D                             @ Brother! Brother!! Where is he!? He's here, isn'
	FADI 0x10
	EXIT_MAP
	BACG 0x10
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_A0E                             @ That's enough, Hector! What is the meaning of th
	FADI 4
	EXIT_MAP
	LOMA 0x32, 0, 0
	CLEAN
	STAL 0x78
	FADU 4
	ENTER_MAP
	LOU1 Units_08CC812C
	ENUN
	MUSI
	TEX1 MSG_A0F                             @ Matthew! Matthew! Blast it! Where could he be?
	CLEAN
	MUNO
	SPRITE_ANIM SpriteAnimConf_08CAE5F8, 160, 48
	SOUN 0x2F6
	STAL 0x14
	LOU1 Units_08CC814C
	ENUN
	SPRITE_ANIM_END
	TEX1 MSG_A10                             @ I'm right here. You... You're not a wraith. Stop
	CLEAN
	STAL 2
	UNIT_SET_STATE CHARACTER_MATTHEW, 0x1
	STAL 2
	UNIT_CLEAR_STATE CHARACTER_MATTHEW, 0x1
	STAL 2
	UNIT_SET_STATE CHARACTER_MATTHEW, 0x1
	STAL 4
	UNIT_CLEAR_STATE CHARACTER_MATTHEW, 0x1
	STAL 2
	UNIT_SET_STATE CHARACTER_MATTHEW, 0x1
	STAL 6
	UNIT_CLEAR_STATE CHARACTER_MATTHEW, 0x1
	STAL 2
	UNIT_SET_STATE CHARACTER_MATTHEW, 0x1
	STAL 0x3C
	MOVE_SPEED CHARACTER_HECTOR, 10, 3, 0x10
	ENUN
	TEX1 MSG_A11                             @ Huh? He... He gave up too easily. I don't trust
	MUEN 1
	TEX2 MSG_A12                             @ Huh? ...... Come out. I know you're there.
	CLEAN
	LOU1 Units_08CC816C
	ENUN
	STAL 2
	UNIT_SET_STATE CHARACTER_CITIZEN_DA, 0x1
	STAL 4
	UNIT_CLEAR_STATE CHARACTER_CITIZEN_DA, 0x1
	STAL 2
	UNIT_SET_STATE CHARACTER_CITIZEN_DA, 0x1
	STAL 4
	UNIT_CLEAR_STATE CHARACTER_CITIZEN_DA, 0x1
	STAL 2
	UNIT_SET_STATE CHARACTER_CITIZEN_DA, 0x1
	STAL 2
	UNIT_CLEAR_STATE CHARACTER_CITIZEN_DA, 0x1
	MUSC SONG_32
	TEX1 MSG_A13                             @ ...... Who are you? ...... Too dumb to speak? Ma
	CLEAN
	MOVE_SCR CHARACTER_HECTOR, MoveScr_08CAE5E8
	ENUN
	STAL 4
	MOVE_SCR CHARACTER_CITIZEN_DA, MoveScr_08CAE5EF
	ENUN
	STAL 4
	DISA_FADE CHARACTER_CITIZEN_DA
	STAL 0x3C
	MOVE_INSTANT CHARACTER_MATTHEW, 6, 7
	STAL 2
	UNIT_SET_STATE CHARACTER_MATTHEW, 0x1
	STAL 4
	UNIT_CLEAR_STATE CHARACTER_MATTHEW, 0x1
	STAL 2
	UNIT_SET_STATE CHARACTER_MATTHEW, 0x1
	STAL 4
	UNIT_CLEAR_STATE CHARACTER_MATTHEW, 0x1
	STAL 2
	UNIT_SET_STATE CHARACTER_MATTHEW, 0x1
	STAL 2
	UNIT_CLEAR_STATE CHARACTER_MATTHEW, 0x1
	STAL 0x20
	MOVE_SCR CHARACTER_HECTOR, MoveScr_08CAE5F3
	MOVE_SPEED CHARACTER_MATTHEW, 8, 7, 0x38
	ENUN
	TEX1 MSG_A14                             @ Hah! Whoa! M-Milord! Stay your arm! It's me! Who
	CLEAN
	FADI 4
	EXIT_MAP
	LOMA CHAPTER_0D, 0, 0
	HIDE CHARACTER_HECTOR
	HIDE CHARACTER_MATTHEW
	LOU1 Units_Ch0D_Player
	ENUN
	LOU1 Units_Ch0D_Initial
	ENUN
	LOU1_IF_MODE 3, 1, Units_08CC810C
	REMA
	ENDA

	.align 2, 0
	.global EventScr_Ch0D_Ending
EventScr_Ch0D_Ending:
	MUEN 4
	FADI 4
	EXIT_MAP
	ASMC sub_0807A868
	BACG 0x15
	FADU 4
	ENTER_MAP
	IFAF 0xA, sub_08079DBC
	MUSC 0x38
	TEX1 MSG_A18                             @ Whew... That was close. Glad we're both all righ
	GOTO 0xB
	LABEL 0xA
	MUSC SONG_39
	TEX1 MSG_A19                             @ Is it...over? Oh, no... I can't... ... ...... ..
	LABEL 0xB
	FADI 4
	EXIT_MAP
	BACG 0x10
	FADU 4
	ENTER_MAP
	TEX1 MSG_A1A                             @ My lord! Marquess! It's Lord Hector! He's-- He's
	FADI 4
	EXIT_MAP
	BACG 0x5B
	MNCH CHAPTER_0E
	STAL 1
	ENDB
	REMA
	ENDA

	.section .rodata.ev_08CC803C, "a"

	.align 2, 0
	.global Units_Ch0D_Player
Units_Ch0D_Player:
	UNIT CHARACTER_HECTOR, CLASS_LORD_HECTOR, CHARACTER_NONE, 1, FACTION_ID_BLUE, 0, 15, 1, 15, 1, ITEM_AXE_WOLF_BEIL, ITEM_AXE_HANDAXE
	UNIT CHARACTER_MATTHEW, CLASS_THIEF, CHARACTER_NONE, 2, FACTION_ID_BLUE, 0, 16, 2, 16, 2, ITEM_SWORD_IRON, ITEM_LOCKPICK
	UNIT_END

	.align 2, 0
	.global Units_Ch0D_Initial
Units_Ch0D_Initial:
	UNIT CHARACTER_WIRE, CLASS_KNIGHT, CHARACTER_NONE, 7, FACTION_ID_RED, 0, 1, 9, 1, 9, ITEM_LANCE_IRON, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0x3, 0x3, 0x9
	UNIT CHARACTER_BLACK_FANG_DE, CLASS_SOLDIER, CHARACTER_WIRE, 5, FACTION_ID_RED, 1, 15, 7, 15, 7, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0x9
	UNIT CHARACTER_BLACK_FANG_DD, CLASS_KNIGHT, CHARACTER_WIRE, 5, FACTION_ID_RED, 1, 11, 9, 11, 9, ITEM_LANCE_IRON, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0x0, 0x3, 0x9
	UNIT CHARACTER_BLACK_FANG_DE, CLASS_SOLDIER, CHARACTER_WIRE, 5, FACTION_ID_RED, 1, 6, 10, 6, 10, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0x9
	UNIT CHARACTER_BLACK_FANG_DE, CLASS_SOLDIER, CHARACTER_WIRE, 3, FACTION_ID_RED, 1, 7, 1, 7, 1, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0x9
	UNIT CHARACTER_BLACK_FANG_DE, CLASS_ARCHER, CHARACTER_WIRE, 3, FACTION_ID_RED, 1, 1, 1, 1, 1, ITEM_BOW_IRON, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0x0, 0x3, 0x9
	UNIT CHARACTER_BLACK_FANG_DE, CLASS_ARCHER, CHARACTER_WIRE, 3, FACTION_ID_RED, 1, 14, 10, 14, 10, ITEM_BOW_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0x9
	UNIT CHARACTER_BLACK_FANG_DE, CLASS_ARCHER, CHARACTER_WIRE, 3, FACTION_ID_RED, 1, 7, 10, 7, 10, ITEM_BOW_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0x9
	UNIT CHARACTER_BLACK_FANG_DD, CLASS_ARCHER, CHARACTER_WIRE, 3, FACTION_ID_RED, 1, 5, 1, 5, 1, ITEM_BOW_IRON, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0x0, 0x1C, 0x9
	UNIT_END

	.align 2, 0
	.global Units_08CC810C
Units_08CC810C:
	UNIT CHARACTER_BLACK_FANG_DE, CLASS_THIEF, CHARACTER_WIRE, 1, FACTION_ID_RED, 1, 15, 11, 15, 11, ITEM_SWORD_IRON, ITEM_LOCKPICK, ITEM_NONE, ITEM_NONE, 0x6, 0x12, 0x9
	UNIT_END

	.align 2, 0
	.global Units_08CC812C
Units_08CC812C:
	UNIT CHARACTER_HECTOR, CLASS_LORD_HECTOR, CHARACTER_NONE, 1, FACTION_ID_BLUE, 0, 14, 5, 10, 5, ITEM_AXE_WOLF_BEIL, ITEM_AXE_HANDAXE
	UNIT_END

	.align 2, 0
	.global Units_08CC814C
Units_08CC814C:
	UNIT CHARACTER_MATTHEW, CLASS_THIEF, CHARACTER_NONE, 2, FACTION_ID_BLUE, 0, 10, 3, 10, 3, ITEM_SWORD_IRON, ITEM_LOCKPICK
	UNIT_END

	.align 2, 0
	.global Units_08CC816C
Units_08CC816C:
	UNIT CHARACTER_CITIZEN_DA, CLASS_SOLDIER, CHARACTER_NONE, 5, FACTION_ID_RED, 1, 7, 5, 7, 5, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0x9
	UNIT_END

	.align 2, 0
	.global EventScr_08CC818C
EventScr_08CC818C:	@ unreferenced
	LOU1 Units_Ch0D_Player
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC81A0
EventScr_08CC81A0:	@ unreferenced
	UNIT_CAM_OFF
	EVBIT_NOSKIP
	LOU1 Units_Ch0D_Initial
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC81BC
EventScr_08CC81BC:	@ unreferenced
	LOU1 Units_08CC810C
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC81D0
EventScr_08CC81D0:	@ unreferenced
	LOU1 Units_08CC812C
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC81E4
EventScr_08CC81E4:	@ unreferenced
	LOU1 Units_08CC814C
	ENUN
	REMA
	ENDA

	.align 2, 0
	.global EventScr_08CC81F8
EventScr_08CC81F8:	@ unreferenced
	LOU1 Units_08CC816C
	ENUN
	REMA
	ENDA
