@ Chapter 0x1D: Ch. 22/23: Living Legend
@ Generated by tools/evdis.py

#include "event_macros.inc"

	.section .rodata.ev_08CA3B60, "a"

	.global EvList_Ch1D_Turn
EvList_Ch1D_Turn:
	TURN 0, EventScr_08CB5A24, 1, 0, FACTION_BLUE, 0
	TURN 0, EventScr_08CB5AEC, 2, 0, FACTION_BLUE, 1
	TURN 0, EventScr_08CB5AEC, 2, 0, FACTION_BLUE, 2
	TURN 0, EventScr_08CD2694, 3, 0, FACTION_BLUE, 1
	TURN 0, EventScr_08CD26A8, 5, 0, FACTION_BLUE, 1
	TURN 0, EventScr_08CD26BC, 5, 6, FACTION_BLUE, 1
	TURN 0, EventScr_08CD26D0, 7, 8, FACTION_BLUE, 1
	TURN 0, EventScr_08CD2694, 3, 0, FACTION_BLUE, 2
	TURN 0, EventScr_08CD26A8, 5, 0, FACTION_BLUE, 2
	TURN 0, EventScr_08CD26BC, 5, 6, FACTION_BLUE, 2
	TURN 0, EventScr_08CD26D0, 7, 8, FACTION_BLUE, 2
	TURN 0, EventScr_08CB5B90, 1, 0, FACTION_BLUE, 4
	TURN 0, EventScr_08CB5AEC, 2, 0, FACTION_BLUE, 3
	TURN 0, EventScr_08CB5B48, 2, 0, FACTION_BLUE, 4
	TURN 0, EventScr_08CD2694, 2, 3, FACTION_BLUE, 5
	TURN 0, EventScr_08CD26A8, 4, 5, FACTION_BLUE, 5
	TURN 0, EventScr_08CD26BC, 4, 6, FACTION_BLUE, 5
	TURN 0, EventScr_08CD26D0, 6, 8, FACTION_BLUE, 5
	EVLIST_END

	.global EvList_Ch1D_Character
EvList_Ch1D_Character:
	CHAR 7, EventScr_08CB5BA8, CHARACTER_ELIWOOD, CHARACTER_HAWKEYE, 1
	CHAR 7, EventScr_08CB5BA8, CHARACTER_HAWKEYE, CHARACTER_ELIWOOD, 1
	CHAR 7, EventScr_08CB5BD0, CHARACTER_HECTOR, CHARACTER_HAWKEYE, 2
	CHAR 7, EventScr_08CB5BD0, CHARACTER_HAWKEYE, CHARACTER_HECTOR, 2
	CHAR 8, EventScr_08CB5BF8, CHARACTER_ELIWOOD, CHARACTER_PENT, 1
	CHAR 8, EventScr_08CB5BF8, CHARACTER_PENT, CHARACTER_ELIWOOD, 1
	CHAR 8, EventScr_08CB5C14, CHARACTER_HECTOR, CHARACTER_PENT, 2
	CHAR 8, EventScr_08CB5C14, CHARACTER_PENT, CHARACTER_HECTOR, 2
	EVLIST_END

	.global EvList_Ch1D_Location
EvList_Ch1D_Location:
	LOCA 0, EventScr_08CB5C68, 0xC, 0xD, 0xE
	EVLIST_END

	.global EvList_Ch1D_Misc
EvList_Ch1D_Misc:
	ASME 0, EventScr_Ch1D_Ending, sub_08079FE8
	AFEV 0, gEvent_GameOver, 0x65
	AREA 9, EventScr_08CB5CC4, 0, 4, 1, 5
	AREA 0xA, EventScr_08CB5D04, 3, 4, 4, 5
	AREA 0xB, EventScr_08CB5D44, 5, 8, 7, 9
	AREA 0xC, EventScr_08CB5D84, 6, 7, 8, 8
	AREA 0xD, EventScr_08CB5DC4, 0x12, 0xE, 0x13, 0xF
	AREA 0xE, EventScr_08CB5E04, 4, 0xC, 5, 0xD
	EVLIST_END

	.global ChapterEvents_Ch1D
ChapterEvents_Ch1D:
	.4byte EvList_Ch1D_Turn                  @ turn
	.4byte EvList_Ch1D_Character             @ character
	.4byte EvList_Ch1D_Location              @ location
	.4byte EvList_Ch1D_Misc                  @ misc
	.4byte Traps_Ch1D                        @ traps
	.4byte Traps_Ch1D_Hector                 @ traps (Hector mode)
	.4byte Units_Ch1D_Initial                @ units loaded at start
	.4byte Units_Ch1D_InitialHard            @ (hard)
	.4byte Units_Ch1D_InitialHector          @ (Hector mode)
	.4byte Units_Ch1D_InitialHectorHard      @ (Hector mode, hard)
	.4byte Units_Ch1D_Player                 @ player units
	.4byte Units_Ch1D_PlayerHard             @ (hard)
	.4byte Units_Ch1D_PlayerHector           @ (Hector mode)
	.4byte Units_Ch1D_PlayerHectorHard       @ (Hector mode, hard)
	.4byte EventScr_Ch1D_Beginning           @ beginning scene
	.4byte EventScr_Ch1D_Ending              @ ending scene

	.section .rodata.ev_08CB57DC, "a"

	.global EventScr_Ch1D_Beginning
EventScr_Ch1D_Beginning:
	UNIT_CAM_OFF
	LOU1 Units_08CD242C
	SKIP_IFN_ASM 1, sub_0807A3B8
	LOAD_UNIT CHARACTER_TACTICIAN, CLASS_PRINCE_51, 0x11, 3
	LOU1 Units_08CD247C
	ENUN
	CAM1_POS 0x11, 5
	FADE_FROM_OPENING
	STAL 0x20
	MOVE_SPEED CHARACTER_CITIZEN_DA, 19, 7, 0x44
	ENUN
	STAL 0x20
	MOVE_SPEED CHARACTER_CITIZEN_DA, 18, 7, 0x44
	ENUN
	STAL 0x20
	FADI 0x10
	EXIT_MAP
	BACG 0x51
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_C26                             @ ...So hot. I'm... going to die. Hey, do you want
	CLEAN
	MOVE_SPEED CHARACTER_HECTOR, 17, 7, 0x18
	ENUN
	BACG_FADE 0xD, 0x4
	STAL 1
	CG_TEXT MSG_C27, 1                       @ Nils Waaaaaaa!!! I'm going to fall! I'm going to
	MUEN 4
	STAL 0x20
	FADI 4
	EXIT_MAP
	ASMC ImmediateDisplayMap
	MUSC 0x3A
	BACG 0x51
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_C28                             @ ...Marquess Ostia said, "Enter the desert and mo
	MUEN 6
	FADI 4
	EXIT_MAP
	STAL 0x1E
	BACG 0x4A
	FADU 4
	ENTER_MAP
	MUSC 0x3B1
	TEX1 MSG_C29                             @ ...I believe someone approaches. Is it Lord Pent
	MUEN 4
	FADI 4
	EXIT_MAP
	LOU1_BY_MODE Units_Ch1D_Initial, Units_Ch1D_InitialHector, Units_Ch1D_InitialHard, Units_Ch1D_InitialHectorHard
	LOU1_IF_MODE 2, 0, Units_08CD22FC
	LOU1_IF_MODE 3, 0, Units_08CD231C
	ENUN
	IFHM 0xF
	MOVE_INSTANT CHARACTER_PAUL, 8, 9
	MOVE_INSTANT CHARACTER_JASMINE, 10, 9
	LABEL 0xF
	IFEM 0xE
	MOVE_INSTANT CHARACTER_PAUL, 4, 6
	MOVE_INSTANT CHARACTER_JASMINE, 3, 7
	LABEL 0xE
	BACG 0x51
	STAL 0x20
	FADU 4
	ENTER_MAP
	MUSC SONG_32
	TEX1 MSG_C2A                             @ Um, Lord Eliwood? Ninian? Over there... Someone
	IFEM 0xA
	FADI 0x10
	EXIT_MAP
	BACG 0x51
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_C2B                             @ Hector! Hurry!! I'm going to leave you behind!!!
	LABEL 0xA
	CLEAN
	MUEN 6
	IFHM 0x10
	CAM1_POS 5, 0xC
	LABEL 0x10
	IFEM 0x11
	CAM1_POS 0, 0
	LABEL 0x11
	STAL 0x60
	FADI 0x10
	EXIT_MAP
	MUSC SONG_44
	BACG 0x51
	FADU 0x10
	ENTER_MAP
	TEX1 MSG_C2C                             @ Oh, look at this kindly soul, Jasmine! He's wait
	FADI 0x10
	EXIT_MAP
	REMA_PREP
	ENDA

	.global EventScr_08CB5A24
EventScr_08CB5A24:
	LOU2_BY_MODE Units_Ch1D_Player, Units_Ch1D_PlayerHard, Units_Ch1D_PlayerHector, Units_Ch1D_PlayerHectorHard
	LOU1_IF_MODE 2, 0, Units_08CD22FC
	LOU1_IF_MODE 3, 0, Units_08CD231C
	ASMC sub_0807D2EC
	FADE_FROM_OPENING
	IFAF 7, sub_0807A3B8
	IFHM 5
	IFDEPLOYED 0, 7, CHARACTER_CANAS
	MUEN 4
	CAM1 CHARACTER_CANAS
	CURF CHARACTER_CANAS
	MUSC SONG_02
	TEX1 MSG_C2D                             @ Actually, this is quite fascinating. , the Nabat
	GOTO 6
	LABEL 5
	IFDEPLOYED 0, 7, CHARACTER_RATH
	MUEN 4
	CAM1 CHARACTER_RATH
	CURF CHARACTER_RATH
	MUSC SONG_0A
	TEX1 MSG_C2E                             @ ... It's been a long time. No... I have no other
	LABEL 6
	CLEAN
	LABEL 7
	REMA
	ENDA

	.global EventScr_08CB5AEC
EventScr_08CB5AEC:
	MUEN 4
	CAM1_POS 0x15, 0xF
	SOUN 0x3AF
	FAWI 4
	EXIT_MAP
	LOU1_IF_MODE 2, 0, Units_08CD233C
	LOU1_IF_MODE 3, 0, Units_08CD235C
	ENUN
	STAL 0x1E
	ASMC2 sub_0800F324
	FAWU 4
	ENTER_MAP
	TEX1 MSG_C2F                             @ ......
	CLEAN
	WEA2 0
	REMA
	ENDA

	.global EventScr_08CB5B48
EventScr_08CB5B48:
	MUEN 4
	CAM1_POS 0x15, 0xF
	SOUN 0x3AF
	LOU1_IF_MODE 2, 0, Units_08CD233C
	LOU1_IF_MODE 3, 0, Units_08CD235C
	TEX1 MSG_C2F                             @ ......
	CLEAN
	REMA
	ENDA

	.global EventScr_08CB5B80
EventScr_08CB5B80:	@ unreferenced
	SOUN 0x3A2
	WEA1 4
	REMA
	ENDA

	.global EventScr_08CB5B90
EventScr_08CB5B90:
	EVBIT_NOSKIP
	VCBF 3
	WEA1 6
	EVBIT_YESSKIP
	REMA
	ENDA

	.global EventScr_08CB5BA8
EventScr_08CB5BA8:
	MUSS 0x42
	TEX1 MSG_C31                             @ Who are you? I'm Hawkeye, defender of this deser
	CLEAN
	CHANGE_FACTION CHARACTER_HAWKEYE, 0
	MURE 6
	REMA
	ENDA

	.global EventScr_08CB5BD0
EventScr_08CB5BD0:
	MUSS 0x42
	TEX1 MSG_C32                             @ Ahh...shade. Whew...that's nice. ...Huh? Shade..
	CLEAN
	CHANGE_FACTION CHARACTER_HAWKEYE, 0
	MURE 6
	REMA
	ENDA

	.global EventScr_08CB5BF8
EventScr_08CB5BF8:
	MUSI
	TEX1 MSG_C33                             @ Hello there. Beautiful weather, isn't it? Er...
	CLEAN
	MUNO
	REMA
	ENDA

	.global EventScr_08CB5C14
EventScr_08CB5C14:
	MUSI
	TEX1 MSG_C34                             @ Hey, you! Are you OK? Hello there. Beautiful wea
	CLEAN
	MUNO
	REMA
	ENDA

	.global MsgList_08CB5C30
MsgList_08CB5C30:
	.4byte MSG_C35                           @ You know what? I'm watching the house all by mys
	.4byte MSG_C36                           @ You know what? I'm watching the house all by mys
	.4byte MSG_C35                           @ You know what? I'm watching the house all by mys
	.4byte MSG_C35                           @ You know what? I'm watching the house all by mys
	.4byte MSG_C36                           @ You know what? I'm watching the house all by mys
	.4byte MSG_C35                           @ You know what? I'm watching the house all by mys
	.4byte MSG_C35                           @ You know what? I'm watching the house all by mys
	.4byte MSG_C37                           @ You know what? I'm watching the house all by mys
	.4byte MSG_C37                           @ You know what? I'm watching the house all by mys
	.4byte MSG_C38
	.4byte MSG_C37                           @ You know what? I'm watching the house all by mys
	.4byte MSG_C37                           @ You know what? I'm watching the house all by mys
	.4byte MSG_C37                           @ You know what? I'm watching the house all by mys
	.4byte MSG_C38

	.global EventScr_08CB5C68
EventScr_08CB5C68:
	MUSI
	FADI 0x10
	EXIT_MAP
	BACG 1
	FADU 0x10
	ENTER_MAP
	IFUA 0, 5, CHARACTER_HAWKEYE
	TEX1 MSG_C39                             @ Ah! It's you, Hawkeye! What are you doing, Fae?
	GOTO 6
	LABEL 5
	TEX1_VISIT MsgList_08CB5C30
	LABEL 6
	CLEAN
	MUNO
	REMA
	ENDA

	.global EventScr_08CB5CC4
EventScr_08CB5CC4:
	IFAT 1, sub_0807D2B0
	ENUF 9
	GOTO 9
	LABEL 1
	EVBIT_NOSKIP
	ENTER_MAP
	ITGV ITEM_HEROCREST
	LABEL 9
	REMA
	ENDA

	.global EventScr_08CB5D04
EventScr_08CB5D04:
	IFAT 1, sub_0807D2B0
	ENUF 0xA
	GOTO 9
	LABEL 1
	EVBIT_NOSKIP
	ENTER_MAP
	ITGV ITEM_SWORD_LIGHTBRAND
	LABEL 9
	REMA
	ENDA

	.global EventScr_08CB5D44
EventScr_08CB5D44:
	IFAT 1, sub_0807D2B0
	ENUF 0xB
	GOTO 9
	LABEL 1
	EVBIT_NOSKIP
	ENTER_MAP
	ITGV ITEM_FILLAS_MIGHT
	LABEL 9
	REMA
	ENDA

	.global EventScr_08CB5D84
EventScr_08CB5D84:
	IFAT 1, sub_0807D2B0
	ENUF 0xC
	GOTO 9
	LABEL 1
	EVBIT_NOSKIP
	ENTER_MAP
	ITGV ITEM_DARK_ECLIPSE
	LABEL 9
	REMA
	ENDA

	.global EventScr_08CB5DC4
EventScr_08CB5DC4:
	IFAT 1, sub_0807D2B0
	ENUF 0xD
	GOTO 9
	LABEL 1
	EVBIT_NOSKIP
	ENTER_MAP
	ITGV ITEM_OCEANSEAL
	LABEL 9
	REMA
	ENDA

	.global EventScr_08CB5E04
EventScr_08CB5E04:
	IFAT 1, sub_0807D2B0
	ENUF 0xE
	GOTO 9
	LABEL 1
	EVBIT_NOSKIP
	ENTER_MAP
	ITGV ITEM_BOOSTER_CON
	LABEL 9
	REMA
	ENDA

	.global EventScr_Ch1D_Ending
EventScr_Ch1D_Ending:
	MUEN 2
	ASMC sub_08079B5C
	MUSC 0x38
	STAL 0x3C
	FADI 4
	EXIT_MAP
	ASMC sub_0807A868
	BACG 0x51
	FADU 4
	ENTER_MAP
	IFET 1, 7
	TEX1 MSG_C3D                             @ That's about it, eh? ...Say, Eliwood? I wanted t
	FADI 0x10
	EXIT_MAP
	IFET 0x12, 0x81
	CHANGE_FACTION CHARACTER_HAWKEYE, 0
	LABEL 0x12
	BACG 0x51
	FADU 0x10
	ENTER_MAP
	LABEL 1
	TEX1_BY_MODE MSG_C3E, MSG_C3F            @ You really helped me out. Thank you. We couldn't / You really helped me out. Thank you. Don't reall
	IFAF 5, sub_0807D324
	IFAF 5, sub_08079EFC
	FADI 4
	EXIT_MAP
	EVBIT_NOTEXTSKIP
	BACG 0x5B
	FADU 0x80
	ENTER_MAP
	STAL 2
	ASMC ApplySystemObjectsGraphics
	TUTORIAL_TEXT 0, 0, MSG_C40, 7           @ Accept side quest?
	ASMC_WAIT2 BoxTalkActive
	EVBIT_YESSKIP
	IFYN 5
	CALL EventScr_08CC0C14
	CLEAR_ON_SKIP_ASM
	MUEN 1
	FADI 0x10
	EXIT_MAP
	ASMC sub_0807A8B8
	BACG 0x51
	FADU 0x10
	ENTER_MAP
	MUSC 0x3AE
	TEX1 MSG_C41                             @ I don't mind going with you, but how far do we h
	FADI 4
	EXIT_MAP
	BACG 0x5B
	MNCH CHAPTER_1E
	STAL 1
	ENDB
	GOTO 9
	LABEL 5
	STAL 0x20
	CALL EventScr_08CB5FFC
	CLEAR_ON_SKIP_ASM
	CALL EventScr_08CC0C14
	CLEAR_ON_SKIP_ASM
	FADI 4
	EXIT_MAP
	BACG 0x5B
	LOMA_ID CHAPTER_1D
	IFAF 7, sub_0807D368
	MNCH CHAPTER_20
	STAL 1
	ENDB
	GOTO 9
	LABEL 7
	MNCH CHAPTER_1F
	STAL 1
	ENDB
	LABEL 9
	REMA
	ENDA

	.section .rodata.ev_08CD237C, "a"

	.global Units_08CD237C
Units_08CD237C:
	UNIT CHARACTER_BANDIT_E8, CLASS_WYVERN_RIDER, CHARACTER_PAUL, 9, FACTION_ID_RED, 1, 2, 15, 2, 15, ITEM_LANCE_STEEL, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0xA
	UNIT CHARACTER_BANDIT_E8, CLASS_WYVERN_RIDER, CHARACTER_PAUL, 9, FACTION_ID_RED, 1, 0, 4, 0, 4, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0xA
	UNIT_END

	.global Units_08CD23AC
Units_08CD23AC:
	UNIT CHARACTER_BANDIT_E8, CLASS_WYVERN_RIDER, CHARACTER_PAUL, 9, FACTION_ID_RED, 1, 4, 15, 4, 15, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0xA
	UNIT CHARACTER_BANDIT_E8, CLASS_WYVERN_RIDER, CHARACTER_PAUL, 9, FACTION_ID_RED, 1, 0, 2, 0, 2, ITEM_LANCE_STEEL, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0xA
	UNIT_END

	.global Units_08CD23DC
Units_08CD23DC:
	UNIT CHARACTER_BANDIT_E8, CLASS_MAGE, CHARACTER_PAUL, 9, FACTION_ID_RED, 1, 4, 2, 4, 2, ITEM_ANIMA_THUNDER, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0xA
	UNIT_END

	.global Units_08CD23FC
Units_08CD23FC:
	UNIT CHARACTER_BANDIT_E8, CLASS_SHAMAN, CHARACTER_PAUL, 9, FACTION_ID_RED, 1, 0, 11, 0, 11, ITEM_DARK_FLUX, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0xA
	UNIT CHARACTER_BANDIT_E8, CLASS_SHAMAN, CHARACTER_PAUL, 9, FACTION_ID_RED, 1, 0, 3, 0, 3, ITEM_DARK_FLUX, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x0, 0x0, 0xA
	UNIT_END

	.global Units_08CD242C
Units_08CD242C:
	UNIT CHARACTER_ELIWOOD, CLASS_LORD_ELIWOOD, CHARACTER_NONE, 14, FACTION_ID_BLUE, 1, 16, 4, 16, 4, ITEM_SWORD_IRON, ITEM_SWORD_RAPIER
	UNIT CHARACTER_HECTOR, CLASS_LORD_HECTOR, CHARACTER_ELIWOOD, 12, FACTION_ID_BLUE, 1, 16, 7, 16, 7, ITEM_AXE_IRON, ITEM_AXE_HANDAXE, ITEM_AXE_HAMMER
	UNIT CHARACTER_LYN, CLASS_LORD_LYN, CHARACTER_NONE, 9, FACTION_ID_BLUE, 1, 14, 3, 14, 3, ITEM_SWORD_MKATTI, ITEM_SWORD_IRON, ITEM_BLADE_IRON
	UNIT CHARACTER_NINIAN, CLASS_DANCER, CHARACTER_NONE, 5, FACTION_ID_BLUE, 1, 16, 5, 16, 5, ITEM_ELIXIR, ITEM_ELIXIR
	UNIT_END

	.global Units_08CD247C
Units_08CD247C:
	UNIT CHARACTER_CITIZEN_DA, CLASS_BARD, CHARACTER_NONE, 1, FACTION_ID_GREEN, 0, 20, 7, 20, 7, ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0x6, 0x3, 0x2
	UNIT_END

	.section .rodata.ev_08CD2694, "a"

	.global EventScr_08CD2694
EventScr_08CD2694:
	LOU1 Units_08CD237C
	ENUN
	REMA
	ENDA

	.global EventScr_08CD26A8
EventScr_08CD26A8:
	LOU1 Units_08CD23AC
	ENUN
	REMA
	ENDA

	.global EventScr_08CD26BC
EventScr_08CD26BC:
	LOU1 Units_08CD23DC
	ENUN
	REMA
	ENDA

	.global EventScr_08CD26D0
EventScr_08CD26D0:
	LOU1 Units_08CD23FC
	ENUN
	REMA
	ENDA

	.global EventScr_08CD26E4
EventScr_08CD26E4:	@ unreferenced
	LOU1 Units_08CD242C
	ENUN
	REMA
	ENDA

	.global EventScr_08CD26F8
EventScr_08CD26F8:	@ unreferenced
	LOU1 Units_08CD247C
	ENUN
	REMA
	ENDA

	.global EventScr_08CD270C
EventScr_08CD270C:	@ unreferenced
	LOU1 Units_08CD249C
	ENUN
	REMA
	ENDA

	.global EventScr_08CD2720
EventScr_08CD2720:	@ unreferenced
	LOU1 Units_08CD251C
	ENUN
	REMA
	ENDA
