@ Chapter 0x3A
@ Generated by tools/evdis.py

#include "event_macros.inc"

	.section .rodata.ev_08CA6BD0, "a"

	.global EvList_Ch3A_Turn
EvList_Ch3A_Turn:
	TURN 0, EventScr_08CE1114, 1, 0, 0, 0
	EVLIST_END

	.global EvList_Ch3A_Character
EvList_Ch3A_Character:
	EVLIST_END

	.global EvList_Ch3A_Location
EvList_Ch3A_Location:
	EVLIST_END

	.global EvList_Ch3A_Misc
EvList_Ch3A_Misc:
	EVLIST_END

	.global ChapterEvents_Ch3A
ChapterEvents_Ch3A:
	.4byte EvList_Ch3A_Turn                  @ turn
	.4byte EvList_Ch3A_Character             @ character
	.4byte EvList_Ch3A_Location              @ location
	.4byte EvList_Ch3A_Misc                  @ misc
	.4byte Traps_Ch3A                        @ traps
	.4byte Traps_Ch3A_Hector                 @ traps (Hector mode)
	.4byte Units_Ch3A_Initial                @ units loaded at start
	.4byte Units_Ch3A_Initial                @ (hard)
	.4byte Units_Ch3A_Initial                @ (Hector mode)
	.4byte Units_Ch3A_Initial                @ (Hector mode, hard)
	.4byte Units_Ch3A_Player                 @ player units
	.4byte Units_Ch3A_Player                 @ (hard)
	.4byte Units_Ch3A_Player                 @ (Hector mode)
	.4byte Units_Ch3A_Player                 @ (Hector mode, hard)
	.4byte EventScr_Ch3A_Beginning           @ beginning scene
	.4byte EventScr_Ch3A_Ending              @ ending scene

	.section .rodata.ev_08CC04CC, "a"

	.global EventScr_Ch3A_Beginning
EventScr_Ch3A_Beginning:
	REMA
	ENDA

	.global EventScr_Ch3A_Ending
EventScr_Ch3A_Ending:
	REMA
	ENDA

	.section .rodata.ev_08CE10E4, "a"

	.global Units_Ch3A_Player
Units_Ch3A_Player:
	UNIT CHARACTER_ELIWOOD, CLASS_LORD_ELIWOOD, CHARACTER_NONE, 1, FACTION_ID_BLUE, 0, 8, 8, 8, 8, ITEM_SWORD_RAPIER, ITEM_VULNERARY
	UNIT_END

	.global Units_Ch3A_Initial
Units_Ch3A_Initial:
	UNIT_END

	.global EventScr_08CE1114
EventScr_08CE1114:
	LOU1 Units_Ch3A_Player
	ENUN
	REMA
	ENDA

	.global EventScr_08CE1128
EventScr_08CE1128:	@ unreferenced
	UNIT_CAM_OFF
	EVBIT_NOSKIP
	LOU1 Units_Ch3A_Initial
	ENUN
	REMA
	ENDA
