// Chapter 0x08: Ch. 7x: The Black Shadow
// Generated by tools/evdis.py

#include "gbafe.h"
#include "event_macros.h"

// event data defined further down or in other files
extern const EventScr EventScr_08CAD43C[];
extern const EventScr EventScr_08CAD454[];
extern const EventScr EventScr_08CC0928[];
extern const EventScr EventScr_08CC70E0[];
extern const EventScr EventScr_Ch08_Beginning[];
extern const EventScr EventScr_Ch08_Ending[];
extern const struct TrapData Traps_Ch08[];
extern const struct TrapData Traps_Ch08_Hector[];
extern const struct UnitDefinition Units_08CC6CD8[];
extern const struct UnitDefinition Units_08CC6D18[];
extern const struct UnitDefinition Units_08CC6D58[];
extern const struct UnitDefinition Units_08CC6D98[];
extern const struct UnitDefinition Units_08CC6FE8[];
extern const struct UnitDefinition Units_Ch08_Initial[];
extern const struct UnitDefinition Units_Ch08_Player[];
extern const struct UnitDefinition Units_Ch08_PlayerHard[];
extern const EventScr gEvent_GameOver[];

// code
extern void UpdatePrevDeployStates();
extern void sub_08018888();
extern void sub_08079FE8();
extern void sub_0807A868();

SECTION(".rodata.ev_08CA13E0")
const EventListScr EvList_Ch08_Turn[] = {
    TURN(0, EventScr_08CAD43C, 1, 0, FACTION_BLUE, 0),
    TURN(0, EventScr_08CAD454, 3, 0, FACTION_BLUE, 0),
    TURN(0, EventScr_08CC70E0, 4, 0, FACTION_BLUE, 0),
    EVLIST_END
};

SECTION(".rodata.ev_08CA13E0")
const EventListScr EvList_Ch08_TutorialD[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA13E0")
const EventListScr EvList_Ch08_Character[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA13E0")
const EventListScr EvList_Ch08_Location[] = {
    DOOR(0, EVENT_NOSCRIPT, 2, 3, 0x10),
    DOOR(0, EVENT_NOSCRIPT, 3, 5, 0x10),
    CHES(0, ITEM_AXE_HAMMER, 0, 3, 9, 0x12),
    EVLIST_END
};

SECTION(".rodata.ev_08CA13E0")
const EventListScr EvList_Ch08_TutorialC[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA13E0")
const EventListScr EvList_Ch08_TutorialA[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA13E0")
const EventListScr EvList_Ch08_TutorialB[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA13E0")
const EventListScr EvList_Ch08_Misc[] = {
    ASME(0, EventScr_Ch08_Ending, sub_08079FE8),
    AFEV(0, gEvent_GameOver, 0x65),
    EVLIST_END
};

SECTION(".rodata.ev_08CA13E0")
const struct ChapterEventGroup ChapterEvents_Ch08 = {
    EvList_Ch08_Turn,                     // turn
    EvList_Ch08_Character,                // character
    EvList_Ch08_Location,                 // location
    EvList_Ch08_Misc,                     // misc
    Traps_Ch08,                           // traps
    Traps_Ch08_Hector,                    // traps (Hector mode)
    {
        Units_Ch08_Initial,               // units loaded at start
        Units_Ch08_Initial,               // (hard)
        Units_Ch08_Initial,               // (Hector mode)
        Units_Ch08_Initial,               // (Hector mode, hard)
    },
    {
        Units_Ch08_Player,                // player units
        Units_Ch08_PlayerHard,            // (hard)
        Units_Ch08_Player,                // (Hector mode)
        Units_Ch08_Player,                // (Hector mode, hard)
    },
    EventScr_Ch08_Beginning,              // beginning scene
    EventScr_Ch08_Ending,                 // ending scene
};

SECTION(".rodata.ev_08CAD2A8")
const EventScr EventScr_Ch08_Beginning[] = {
    UNIT_CAM_OFF,
    ASMC(UpdatePrevDeployStates),
    CAM1_POS(0, 0),
    LOU1(Units_08CC6D98),
    LOU1(Units_Ch08_Initial),
    ENUN,
    MNCH_MAP(1),
    MOVE_INSTANT(CHARACTER_BEYARD, 9, 3),
    MOVE_POS_INSTANT(1, 2, 11, 5),
    MOVE_POS_INSTANT(3, 12, 8, 5),
    FADE_FROM_OPENING,
    STAL(0x40),
    CURF(CHARACTER_URSULA_51),
    FADI(0x10),
    EXIT_MAP,
    BACG(0x15),
    FADU(0x10),
    ENTER_MAP,
    TEX1(MSG_9A8),                               // So the brother escaped, and the sister was rescu
    CLEAN,
    MUEN(6),
    MOVE(CHARACTER_URSULA_51, 5, -1),
    ENUN,
    DISA(CHARACTER_URSULA_51),
    STAL(0x40),
    MOVE(CHARACTER_BEYARD, 2, 1),
    MOVE_POS(11, 5, 1, 2),
    MOVE_POS(8, 5, 3, 12),
    ENUN,
    SOUN(SONG_B1),
    MNCH_MAP(0),
    STAL(0x40),
    FADI(4),
    EXIT_MAP,
    ASMC(sub_0807A868),
    LOMA(0x31, 0, 0),
    MAC_INSTANT(0),
    STAL(0x40),
    FADU(4),
    ENTER_MAP,
    STAL(0x10),
    LOU1(Units_08CC6CD8),
    STAL(4),
    LOU1(Units_08CC6D18),
    STAL(4),
    LOU1(Units_08CC6D58),
    ENUN,
    STAL(0x80),
    MUSC(0x3A4),
    FADI(0x10),
    EXIT_MAP,
    BACG(0x3F),
    FADU(0x10),
    ENTER_MAP,
    TEX1(MSG_9A9),                               // I believe they went in here. Milady, are you rea
    MUSC(SONG_32),
    FADI(0x10),
    EXIT_MAP,
    BACG(0x3F),
    FADU(0x10),
    ENTER_MAP,
    TEX1(MSG_9AA),                               // Milady Lyndis! There are more of the foe inside
    FADI(0x10),
    EXIT_MAP,
    LOMA(CHAPTER_08, 0, 0),
    ASMC(sub_08018888),
    REMA_PREP,
    ENDA,
};

SECTION(".rodata.ev_08CAD2A8")
const EventScr EventScr_08CAD43C[] = {
    LOU2(Units_Ch08_Player),
    ENUN,
    FADE_FROM_OPENING,
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CAD2A8")
const EventScr EventScr_08CAD454[] = {
    CAM1(CHARACTER_BEYARD),
    CURF(CHARACTER_BEYARD),
    TEX1(MSG_9AB),                               // How? This can't be... They should be dead! Every
    CLEAN,
    LOU1(Units_08CC6FE8),
    ENUN,
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CAD2A8")
const EventScr EventScr_Ch08_Ending[] = {
    MENU_OVERRIDE_CLEAR,
    MUEN(4),
    STAL(0x40),
    MUSC(0x52),
    FADI(4),
    EXIT_MAP,
    ASMC(sub_0807A868),
    BACG(0x42),
    FADU(4),
    ENTER_MAP,
    TEX1(MSG_9AE),                               // Aaah... No... I... I cannot... Give us the ring!
    SOUN(0x2D9),
    TEX2(MSG_9AF),                               // What?! Poison? He took his own life... These are
    MUEN(2),
    STAL(0x1E),
    MUSC(0x3A),
    TEX2(MSG_9B0),                               // Nils, Ninian. Everything's going to be fine. As
    FADI(4),
    EXIT_MAP,
    BACG(0x5B),
    CALL(EventScr_08CC0928),
    CLEAR_ON_SKIP_ASM,
    MNCH(CHAPTER_09),
    STAL(1),
    ENDB,
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CC6CD8")
const struct UnitDefinition Units_08CC6CD8[] = {
    UNIT(CHARACTER_WIL_TUTORIAL, CLASS_ARCHER, CHARACTER_LYN_TUTORIAL, 3, FACTION_ID_BLUE, 0, 6, 9, 13, 9, ITEM_BOW_IRON, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_LYN_TUTORIAL, CLASS_LORD_LYN, CHARACTER_NONE, 1, FACTION_ID_BLUE, 0, 4, 9, 11, 8, ITEM_SWORD_MKATTI, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_KENT_TUTORIAL, CLASS_CAVALIER, CHARACTER_LYN_TUTORIAL, 1, FACTION_ID_BLUE, 0, 5, 9, 12, 7, ITEM_SWORD_IRON, ITEM_LANCE_IRON, ITEM_VULNERARY, ITEM_NONE, 0, 0, 0, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC6CD8")
const struct UnitDefinition Units_08CC6D18[] = {
    UNIT(CHARACTER_SAIN_TUTORIAL, CLASS_CAVALIER, CHARACTER_LYN_TUTORIAL, 1, FACTION_ID_BLUE, 0, 6, 9, 10, 7, ITEM_SWORD_IRON, ITEM_LANCE_IRON, ITEM_VULNERARY, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_NILS, CLASS_BARD, CHARACTER_LYN_TUTORIAL, 3, FACTION_ID_BLUE, 0, 5, 9, 11, 9, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_CITIZEN_DA, CLASS_DANCER, CHARACTER_NONE, 1, FACTION_ID_GREEN, 0, 4, 9, 10, 9, ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC6CD8")
const struct UnitDefinition Units_08CC6D58[] = {
    UNIT(CHARACTER_MATTHEW, CLASS_THIEF, CHARACTER_LYN_TUTORIAL, 2, FACTION_ID_BLUE, 0, 6, 9, 8, 7, ITEM_SWORD_IRON, ITEM_LOCKPICK, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_FLORINA_TUTORIAL, CLASS_PEGASUS_KNIGHT, CHARACTER_LYN_TUTORIAL, 1, FACTION_ID_BLUE, 0, 5, 9, 9, 8, ITEM_LANCE_SLIM, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_TACTICIAN, CLASS_PRINCE_51, CHARACTER_NONE, 1, FACTION_ID_GREEN, 0, 4, 9, 8, 9, ITEM_NONE, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC6CD8")
const struct UnitDefinition Units_08CC6D98[] = {
    UNIT(CHARACTER_URSULA_51, CLASS_VALKYRIE, CHARACTER_NONE, 15, FACTION_ID_RED, 0, 10, 2, 10, 2, ITEM_ANIMA_BOLTING, ITEM_ANIMA_ELFIRE, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC6CD8")
const struct UnitDefinition Units_Ch08_Player[] = {
    UNIT(CHARACTER_LYN_TUTORIAL, CLASS_LORD_LYN, CHARACTER_NONE, 1, FACTION_ID_BLUE, 0, 12, 14, 12, 14, ITEM_SWORD_MKATTI, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_KENT_TUTORIAL, CLASS_CAVALIER, CHARACTER_LYN_TUTORIAL, 1, FACTION_ID_BLUE, 0, 7, 16, 7, 16, ITEM_SWORD_IRON, ITEM_LANCE_IRON, ITEM_VULNERARY, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_FLORINA_TUTORIAL, CLASS_PEGASUS_KNIGHT, CHARACTER_LYN_TUTORIAL, 1, FACTION_ID_BLUE, 0, 13, 14, 13, 14, ITEM_LANCE_SLIM, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_DORCAS, CLASS_FIGHTER, CHARACTER_LYN_TUTORIAL, 3, FACTION_ID_BLUE, 0, 10, 14, 10, 14, ITEM_AXE_IRON, ITEM_AXE_HANDAXE, ITEM_VULNERARY, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_SERRA, CLASS_CLERIC, CHARACTER_LYN_TUTORIAL, 1, FACTION_ID_BLUE, 0, 11, 15, 11, 15, ITEM_STAFF_HEAL, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_ERK, CLASS_MAGE, CHARACTER_LYN_TUTORIAL, 1, FACTION_ID_BLUE, 0, 12, 16, 12, 16, ITEM_ANIMA_FIRE, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_RATH_TUTORIAL, CLASS_NOMAD, CHARACTER_LYN_TUTORIAL, 7, FACTION_ID_BLUE, 0, 8, 15, 8, 15, ITEM_BOW_SHORTBOW, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_MATTHEW, CLASS_THIEF, CHARACTER_LYN_TUTORIAL, 2, FACTION_ID_BLUE, 0, 9, 16, 9, 16, ITEM_SWORD_IRON, ITEM_LOCKPICK, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_LUCIUS, CLASS_MONK, CHARACTER_LYN_TUTORIAL, 3, FACTION_ID_BLUE, 0, 7, 15, 7, 15, ITEM_LIGHT_LIGHTNING, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_NILS, CLASS_BARD, CHARACTER_LYN_TUTORIAL, 1, FACTION_ID_BLUE, 0, 11, 13, 11, 13, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC6CD8")
const struct UnitDefinition Units_Ch08_PlayerHard[] = {
    UNIT(CHARACTER_LYN_TUTORIAL, CLASS_LORD_LYN, CHARACTER_NONE, 1, FACTION_ID_BLUE, 0, 12, 14, 12, 14, ITEM_SWORD_MKATTI, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_KENT_TUTORIAL, CLASS_CAVALIER, CHARACTER_LYN_TUTORIAL, 1, FACTION_ID_BLUE, 0, 7, 16, 7, 16, ITEM_SWORD_IRON, ITEM_LANCE_IRON, ITEM_VULNERARY, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_FLORINA_TUTORIAL, CLASS_PEGASUS_KNIGHT, CHARACTER_LYN_TUTORIAL, 1, FACTION_ID_BLUE, 0, 13, 14, 13, 14, ITEM_LANCE_SLIM, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_DORCAS, CLASS_FIGHTER, CHARACTER_LYN_TUTORIAL, 3, FACTION_ID_BLUE, 0, 10, 14, 10, 14, ITEM_AXE_IRON, ITEM_AXE_HANDAXE, ITEM_VULNERARY, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_SERRA, CLASS_CLERIC, CHARACTER_LYN_TUTORIAL, 1, FACTION_ID_BLUE, 0, 11, 15, 11, 15, ITEM_STAFF_HEAL, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_ERK, CLASS_MAGE, CHARACTER_LYN_TUTORIAL, 1, FACTION_ID_BLUE, 0, 12, 16, 12, 16, ITEM_ANIMA_FIRE, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_RATH_TUTORIAL, CLASS_NOMAD, CHARACTER_LYN_TUTORIAL, 7, FACTION_ID_BLUE, 0, 8, 15, 8, 15, ITEM_BOW_SHORTBOW, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_MATTHEW, CLASS_THIEF, CHARACTER_LYN_TUTORIAL, 2, FACTION_ID_BLUE, 0, 9, 16, 9, 16, ITEM_SWORD_IRON, ITEM_LOCKPICK, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_LUCIUS, CLASS_MONK, CHARACTER_LYN_TUTORIAL, 3, FACTION_ID_BLUE, 0, 7, 15, 7, 15, ITEM_LIGHT_LIGHTNING, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_NILS, CLASS_BARD, CHARACTER_LYN_TUTORIAL, 1, FACTION_ID_BLUE, 0, 11, 13, 11, 13, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC6CD8")
const struct UnitDefinition Units_Ch08_Initial[] = {
    UNIT(CHARACTER_BEYARD, CLASS_MERCENARY, CHARACTER_NONE, 7, FACTION_ID_RED, 0, 2, 1, 2, 1, ITEM_SWORD_STEEL, ITEM_NONE, ITEM_NONE, ITEM_NONE, 3, 3, 1, 0),
    UNIT(CHARACTER_BLACK_FANG_B2, CLASS_THIEF, CHARACTER_BEYARD, 1, FACTION_ID_RED, 1, 2, 2, 2, 2, ITEM_SWORD_IRON, ITEM_LOCKPICK, ITEM_NONE, ITEM_NONE, 6, 5, 1, 0),
    UNIT(CHARACTER_BLACK_FANG_B0, CLASS_ARCHER, CHARACTER_BEYARD, 2, FACTION_ID_RED, 1, 3, 7, 3, 7, ITEM_BOW_IRON, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 1, 0),
    UNIT(CHARACTER_BLACK_FANG_B1, CLASS_SOLDIER, CHARACTER_BEYARD, 1, FACTION_ID_RED, 1, 1, 2, 1, 2, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 1, 0),
    UNIT(CHARACTER_BLACK_FANG_B3, CLASS_CAVALIER, CHARACTER_BEYARD, 1, FACTION_ID_RED, 1, 14, 1, 14, 1, ITEM_LANCE_IRON, ITEM_SWORD_IRON, ITEM_VULNERARY, ITEM_NONE, 0, 0, 1, 0),
    UNIT(CHARACTER_BLACK_FANG_B1, CLASS_SOLDIER, CHARACTER_BEYARD, 1, FACTION_ID_RED, 1, 12, 9, 12, 9, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0x1B, 1, 0),
    UNIT(CHARACTER_BLACK_FANG_DD, CLASS_SOLDIER, CHARACTER_BEYARD, 2, FACTION_ID_RED, 1, 3, 12, 3, 12, ITEM_LANCE_IRON, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 1, 0),
    UNIT(CHARACTER_BLACK_FANG_B5, CLASS_MAGE, CHARACTER_BEYARD, 1, FACTION_ID_RED, 1, 10, 7, 10, 7, ITEM_ANIMA_THUNDER, ITEM_DOORKEY, ITEM_NONE, ITEM_NONE, 0, 3, 1, 0),
    UNIT(CHARACTER_BLACK_FANG_AF, CLASS_MERCENARY, CHARACTER_BEYARD, 2, FACTION_ID_RED, 1, 8, 2, 8, 2, ITEM_SWORD_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 1, 0),
    UNIT(CHARACTER_BLACK_FANG_AE, CLASS_BRIGAND, CHARACTER_BEYARD, 2, FACTION_ID_RED, 1, 7, 8, 7, 8, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 1, 0),
    UNIT(CHARACTER_BLACK_FANG_AE, CLASS_BRIGAND, CHARACTER_BEYARD, 2, FACTION_ID_RED, 1, 4, 4, 4, 4, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 1, 0),
    UNIT(CHARACTER_BLACK_FANG_AF, CLASS_MERCENARY, CHARACTER_BEYARD, 2, FACTION_ID_RED, 1, 11, 2, 11, 2, ITEM_SWORD_IRON, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 3, 1, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC6CD8")
const struct UnitDefinition Units_08CC6FE8[] = {
    UNIT(CHARACTER_BLACK_FANG_B1, CLASS_SOLDIER, CHARACTER_BEYARD, 1, FACTION_ID_RED, 1, 11, 9, 11, 9, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0x1B, 1, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC6CD8")
const struct UnitDefinition Units_08CC7008[] = {
    UNIT(CHARACTER_BLACK_FANG_B5, CLASS_MAGE, CHARACTER_BEYARD, 1, FACTION_ID_RED, 1, 3, 1, 3, 1, ITEM_ANIMA_FIRE, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 1, 0),
    UNIT(CHARACTER_BLACK_FANG_B4, CLASS_SHAMAN, CHARACTER_BEYARD, 1, FACTION_ID_RED, 1, 1, 1, 1, 1, ITEM_DARK_FLUX, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 1, 0),
    UNIT_END,
};

// unreferenced
SECTION(".rodata.ev_08CC6CD8")
const EventScr EventScr_08CC7038[] = {
    LOU1(Units_08CC6CD8),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC6CD8")
const EventScr EventScr_08CC704C[] = {
    LOU1(Units_08CC6D18),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC6CD8")
const EventScr EventScr_08CC7060[] = {
    LOU1(Units_08CC6D58),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC6CD8")
const EventScr EventScr_08CC7074[] = {
    LOU1(Units_08CC6D98),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC6CD8")
const EventScr EventScr_08CC7088[] = {
    LOU1(Units_Ch08_Player),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC6CD8")
const EventScr EventScr_08CC709C[] = {
    LOU1(Units_Ch08_PlayerHard),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC6CD8")
const EventScr EventScr_08CC70B0[] = {
    UNIT_CAM_OFF,
    EVBIT_NOSKIP,
    LOU1(Units_Ch08_Initial),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC6CD8")
const EventScr EventScr_08CC70CC[] = {
    LOU1(Units_08CC6FE8),
    ENUN,
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CC6CD8")
const EventScr EventScr_08CC70E0[] = {
    LOU1(Units_08CC7008),
    ENUN,
    REMA,
    ENDA,
};
