// Chapter 0x0E: Ch. 12: Birds of a Feather
// Generated by tools/evdis.py

#include "gbafe.h"
#include "event_macros.h"

// event data defined further down or in other files
extern const EventScr EventScr_08CAEE0C[];
extern const EventScr EventScr_08CAEF14[];
extern const EventScr EventScr_08CAF03C[];
extern const EventScr EventScr_08CAF07C[];
extern const EventScr EventScr_08CAF0AC[];
extern const EventScr EventScr_08CAF0DC[];
extern const EventScr EventScr_08CAF10C[];
extern const EventScr EventScr_08CC0C14[];
extern const EventScr EventScr_Ch0E_Beginning[];
extern const EventScr EventScr_Ch0E_Ending[];
extern const u16 ShopList_08CA6F76[];
extern const u16 ShopList_08CA6F7A[];
extern const struct TrapData Traps_Ch0E[];
extern const struct TrapData Traps_Ch0E_Hector[];
extern const struct UnitDefinition Units_08CC835C[];
extern const struct UnitDefinition Units_08CC83BC[];
extern const struct UnitDefinition Units_08CC840C[];
extern const struct UnitDefinition Units_08CC842C[];
extern const struct UnitDefinition Units_08CC844C[];
extern const struct UnitDefinition Units_08CC84AC[];
extern const struct UnitDefinition Units_08CC84EC[];
extern const struct UnitDefinition Units_08CC85BC[];
extern const struct UnitDefinition Units_Ch0E_Initial[];
extern const struct UnitDefinition Units_Ch0E_InitialHector[];
extern const struct UnitDefinition Units_Ch0E_Player[];
extern const struct UnitDefinition Units_Ch0E_PlayerHector[];
extern const EventScr gEvent_GameOver[];

// code
extern void sub_08079D7C();
extern void sub_08079DBC();
extern void sub_08079E0C();
extern void sub_08079FE8();
extern void sub_0807A3B8();
extern void sub_0807A868();

SECTION(".rodata.ev_08CA1A74")
const EventListScr EvList_Ch0E_Turn[] = {
    TURN(0, EventScr_Ch0E_Beginning, 1, 0, FACTION_BLUE, 0),
    TURN(0, EventScr_08CAEE0C, 4, 0, FACTION_BLUE, 1),
    TURN(0, EventScr_08CAEF14, 3, 0, FACTION_RED, 1),
    TURN(0, EventScr_08CAEF14, 2, 0, FACTION_RED, 2),
    TURN(0, EventScr_08CAEE0C, 4, 0, FACTION_BLUE, 3),
    TURN(0, EventScr_08CAEF14, 3, 0, FACTION_RED, 3),
    TURN(0, EventScr_08CAEF14, 3, 0, FACTION_RED, 4),
    EVLIST_END
};

SECTION(".rodata.ev_08CA1A74")
const EventListScr EvList_Ch0E_Character[] = {
    CHAR(7, EventScr_08CAF03C, CHARACTER_ELIWOOD, CHARACTER_HECTOR, 0, 0),
    CHAR(7, EventScr_08CAF03C, CHARACTER_HECTOR, CHARACTER_ELIWOOD, 0, 0),
    EVLIST_END
};

SECTION(".rodata.ev_08CA1A74")
const EventListScr EvList_Ch0E_Location[] = {
    LOCA(0, EventScr_08CAF07C, 0, 0xD, 0xE),
    LOCA(0, EventScr_08CAF0AC, 7, 4, 0xE),
    LOCA(0, EventScr_08CAF0DC, 7, 0xF, 0xE),
    VILL(8, EventScr_08CAF10C, 1, 8, 0xE),
    LOCA(8, EVENT_NOSCRIPT, 1, 7, 0x1D),
    SHOP(0, ShopList_08CA6F76, 1, 0xD, 0x14),
    SHOP(0, ShopList_08CA6F7A, 7, 0xA, 0x13),
    EVLIST_END
};

SECTION(".rodata.ev_08CA1A74")
const EventListScr EvList_Ch0E_Misc[] = {
    ASME(0, EventScr_Ch0E_Ending, sub_08079FE8),
    AFEV(0, gEvent_GameOver, 0x65),
    EVLIST_END
};

SECTION(".rodata.ev_08CA1A74")
const u8 EvPad_08CA1A74_4[4] = { 0 };

SECTION(".rodata.ev_08CA1A74")
const struct ChapterEventGroup ChapterEvents_Ch0E = {
    EvList_Ch0E_Turn,                     // turn
    EvList_Ch0E_Character,                // character
    EvList_Ch0E_Location,                 // location
    EvList_Ch0E_Misc,                     // misc
    Traps_Ch0E,                           // traps
    Traps_Ch0E_Hector,                    // traps (Hector mode)
    {
        Units_Ch0E_Initial,               // units loaded at start
        Units_Ch0E_Initial,               // (hard)
        Units_Ch0E_InitialHector,         // (Hector mode)
        Units_Ch0E_Initial,               // (Hector mode, hard)
    },
    {
        Units_Ch0E_Player,                // player units
        Units_Ch0E_Player,                // (hard)
        Units_Ch0E_PlayerHector,          // (Hector mode)
        Units_Ch0E_Player,                // (Hector mode, hard)
    },
    EventScr_Ch0E_Beginning,              // beginning scene
    EventScr_Ch0E_Ending,                 // ending scene
};

SECTION(".rodata.ev_08CAE9CC")
const u8 MoveScr_08CAE9CC[] EV_ALIGN4 = {
    MV_LEFT, MV_HALT,
};

SECTION(".rodata.ev_08CAE9CC")
const u8 MoveScr_08CAE9CE[] = {
    MV_LEFT, MV_LEFT, MV_HALT,
};

SECTION(".rodata.ev_08CAE9CC")
const u8 MoveScr_08CAE9D1[] = {
    MV_DOWN, MV_HALT,
};

SECTION(".rodata.ev_08CAE9CC")
const u8 MoveScr_08CAE9D3[] = {
    MV_SPEED, 0x12, MV_DOWN, MV_DOWN, MV_DOWN, MV_RIGHT, MV_RIGHT, MV_RIGHT, MV_DOWN, MV_DOWN, MV_HALT,
};

SECTION(".rodata.ev_08CAE9CC")
const EventScr EventScr_Ch0E_Beginning[] = {
    UNIT_CAM_OFF,
    IFHM(0x1E),
    LOMA(0x33, 0, 0),
    FADU(4),
    ENTER_MAP,
    BROWN_TEXTBOX(MSG_5DB, 120, 12),             // Santaruz Castle
    STAL(0x64),
    BROWN_TEXTBOX_END,
    STAL(0x20),
    CURF_POS(8, 5),
    FADI(0x10),
    EXIT_MAP,
    BACG(0x10),
    FADU(0x10),
    ENTER_MAP,
    TEX1(MSG_A1B),                               // What? Eliwood is here? Yes. He has set camp up o
    CLEAN,
    STAL(0x3C),
    FADI(4),
    EXIT_MAP,
    STAL(0x20),
    LOMA(CHAPTER_0E, 0, 0),
    LOU2_IF_MODE(2, Units_Ch0E_Player),
    ENUN,
    MOVE_INSTANT(CHARACTER_ELIWOOD, 9, 15),
    MOVE_INSTANT(CHARACTER_MARCUS, 11, 15),
    SKIP_IFN_ASM(1, sub_0807A3B8),
    LOAD_UNIT(CHARACTER_TACTICIAN, CLASS_PRINCE_51, 0xA, 0xF),
    ENUN,
    FADU(4),
    ENTER_MAP,
    MUEN(4),
    CAM1_POS(0xA, 0xB),
    MOVE(CHARACTER_ELIWOOD, 9, 11),
    MOVE(CHARACTER_MARCUS, 11, 11),
    SKIP_IFN_ASM(1, sub_0807A3B8),
    MOVE_SPEED(CHARACTER_TACTICIAN, 10, 12, 0x18),
    ENUN,
    FADI(0x10),
    EXIT_MAP,
    BACG(0x1C),
    MUSC(SONG_33),
    FADU(4),
    ENTER_MAP,
    TEX1_IF_ASM(sub_0807A3B8, MSG_A1D, MSG_A1C), // Instead of entering Laus with such a small group / This is taking too long. I agree, and yet... San
    MUSC(SONG_32),
    TEX2(MSG_A1E),                               // What? Lord Eliwood! Beware!
    CLEAN,
    LOU1_IF_MODE(2, 0, Units_08CC84AC),
    CAM1_POS(0xA, 0xA),
    ENUN,
    MOVE_SCR(CHARACTER_MARCUS, MoveScr_08CAE9CE),
    MOVE(CHARACTER_ELIWOOD, 9, 12),
    MOVE_SCR(CHARACTER_ZAGAN, MoveScr_08CAE9D3),
    ENUN,
    FADI(0x10),
    EXIT_MAP,
    BACG(0x1C),
    FADU(0x10),
    ENTER_MAP,
    TEX1(MSG_A1F),                               // Heh heh heh... Noble sirs. Alms for a poor villa
    CLEAN,
    IFAF(5, sub_0807A3B8),
    MOVE_SCR(CHARACTER_TACTICIAN, MoveScr_08CAE9CC),
    ENUN,
    DISA(CHARACTER_TACTICIAN),
    LABEL(5),
    IFAT(6, sub_08079D7C),
    MOVE_SCR(CHARACTER_MARCUS, MoveScr_08CAE9D1),
    ENUN,
    HIDE(CHARACTER_MARCUS),
    LABEL(6),
    STAL(0x1E),
    CAM1_POS(0x10, 0),
    MOVE(CHARACTER_ZAGAN, 6, 4),
    ENUN,
    MOVE_POS(8, 8, 8, 1),
    MOVE_POS(10, 8, 7, 2),
    ENUN,
    MOVE(CHARACTER_ELIWOOD, 3, 14),
    SKIP_IFN_ASM(1, sub_08079D7C),
    MOVE(CHARACTER_MARCUS, 3, 12),
    ENUN,
    LOU1(Units_08CC84EC),
    ENUN,
    MOVE(CHARACTER_ZAGAN, 15, 1),
    ENUN,
    LOU1_IF_MODE(2, 1, Units_08CC835C),
    IFAF(8, sub_0807A3B8),
    IFDEPLOYED(0, 8, CHARACTER_DORCAS),
    STAL(0x3C),
    MUEN(4),
    CAM1(CHARACTER_DORCAS),
    CURF(CHARACTER_DORCAS),
    MUSC(SONG_01),
    TEX1(MSG_A20),                               // Here we go again, eh, ? Just like old times... S
    CLEAN,
    LABEL(8),
    GOTO(0x28),
    LABEL(0x1E),
    FADI(0x10),
    EXIT_MAP,
    BACG(0x1C),
    LOU1(Units_Ch0E_InitialHector),
    FADU(4),
    ENTER_MAP,
    IFAF(0x14, sub_08079DBC),
    TEX1(MSG_A26),                               // Lord Hector! I have it! I know where Lord Eliwoo
    TEX2(MSG_A28),                               // You're going to meet Lord Eliwood, right? Well,
    MUSC(SONG_32),
    TEX2(MSG_A29),                               // Lord Hector! Up ahead! There appears to be fight
    GOTO(0x15),
    LABEL(0x14),
    TEX1(MSG_A27),                               // Eliwood and his men... If they left Pherae three
    TEX2(MSG_A28),                               // You're going to meet Lord Eliwood, right? Well,
    MUSC(SONG_32),
    TEX2(MSG_A2A),                               // Lord Hector! There seems to be a fight up ahead.
    LABEL(0x15),
    CLEAN,
    CAM1_POS(0, 0),
    STAL(0x20),
    LOU1(Units_08CC840C),
    LOU1(Units_08CC85BC),
    ENUN,
    STAL(0x10),
    FADI(0x10),
    EXIT_MAP,
    BACG(0x1C),
    LOU1(Units_Ch0E_Player),
    FADU(0x10),
    ENTER_MAP,
    TEX1(MSG_A23),                               // Hey! What's going on over there? Looks like some
    SOUN(SONG_D2),
    TEX2(MSG_A24),                               // ...Urrrgh!! Sorry, but I'm in a hurry.
    DISA(CHARACTER_TACTICIAN),
    CLEAN,
    ENUN,
    SKIP_IFN_ASM(1, sub_08079DBC),
    LOU1(Units_08CC842C),
    LOU1(Units_08CC844C),
    ENUN,
    STAL(0x10),
    FADI(0x10),
    EXIT_MAP,
    BACG(0x1C),
    FADU(0x10),
    ENTER_MAP,
    TEX1_IF_ASM(sub_08079DBC, MSG_A2B, MSG_A2C), // Ewww! That's terrible! I loathe violence! Nicely / Ewww! That's terrible! I loathe violence! I cann
    CLEAN,
    MURE(6),
    MOVE(CHARACTER_HECTOR, 4, 2),
    ENUN,
    MOVE(CHARACTER_OSWIN, 3, 2),
    ENUN,
    LOU1_IF_MODE(3, 1, Units_08CC83BC),
    LABEL(0x28),
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CAE9CC")
const EventScr EventScr_08CAEE0C[] = {
    CAM1(CHARACTER_ELIWOOD),
    CURF(CHARACTER_ELIWOOD),
    TEX1(MSG_A22),                               // How many are there? This looks--
    CLEAN,
    CAM1_POS(0, 0),
    STAL(0x20),
    LOU1(Units_08CC840C),
    LOU1(Units_08CC85BC),
    ENUN,
    MUEN(4),
    STAL(0x10),
    FADI(0x10),
    EXIT_MAP,
    BACG(0x1C),
    FADU(0x10),
    ENTER_MAP,
    MUSS(0x42),
    TEX1(MSG_A23),                               // Hey! What's going on over there? Looks like some
    SOUN(SONG_D2),
    TEX2(MSG_A24),                               // ...Urrrgh!! Sorry, but I'm in a hurry.
    DISA(CHARACTER_TACTICIAN),
    CLEAN,
    ENUN,
    LOU1(Units_08CC842C),
    LOU1(Units_08CC844C),
    ENUN,
    STAL(0x10),
    FADI(0x10),
    EXIT_MAP,
    BACG(0x1C),
    FADU(0x10),
    ENTER_MAP,
    TEX1(MSG_A25),                               // Ewww! That's terrible! I loathe violence! Nicely
    CLEAN,
    MURE(6),
    MOVE(CHARACTER_HECTOR, 4, 2),
    ENUN,
    MOVE(CHARACTER_OSWIN, 3, 2),
    ENUN,
    MOVE(CHARACTER_MATTHEW, 1, -1),
    MOVE(CHARACTER_SERRA, 2, -1),
    ENUN,
    HIDE(CHARACTER_MATTHEW),
    HIDE(CHARACTER_SERRA),
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CAE9CC")
const EventScr EventScr_08CAEF14[] = {
    IFHM(1),
    MUSC(SONG_0C),
    CAM1(CHARACTER_ZAGAN),
    CURF(CHARACTER_ZAGAN),
    TEX1(MSG_A21),                               // Bah! He puts up a good fight for a pampered nobl
    CLEAN,
    CHAI_POS(15, 1, 0xE00),
    CHAI_POS(16, 3, 0xE00),
    CHAI_POS(16, 5, 0xE00),
    CHAI_POS(14, 0, 0xE00),
    CHAI_POS(15, 5, 0x0),
    CHAI_POS(15, 9, 0x0),
    CHAI_POS(14, 4, 0x0),
    CHAI_POS(14, 6, 0x0),
    CHAI_POS(14, 2, 0xE00),
    CHAI_POS(15, 3, 0xE00),
    CHAI_POS(12, 4, 0xE00),
    CHAI_POS(14, 14, 0x0),
    CHAI_POS(15, 15, 0x0),
    GOTO(2),
    LABEL(1),
    CHAI_POS(11, 5, 0x0),
    CHAI_POS(16, 0, 0x0),
    CHAI_POS(14, 2, 0xF00),
    CHAI_POS(15, 3, 0xF00),
    CHAI_POS(15, 9, 0xF00),
    CHAI_POS(9, 0, 0xF00),
    LABEL(2),
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CAE9CC")
const EventScr EventScr_08CAF03C[] = {
    IFHM(1),
    MUSS(SONG_3D),
    GOTO(2),
    LABEL(1),
    MUSS(SONG_3E),
    LABEL(2),
    TEX1(MSG_A2D),                               // Eliwood! Are you all right? Hector! What are you
    CLEAN,
    MURE(6),
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CAE9CC")
const EventScr EventScr_08CAF07C[] = {
    MUSI,
    FADI(0x10),
    EXIT_MAP,
    BACG(1),
    FADU(0x10),
    ENTER_MAP,
    TEX1(MSG_A2F),                               // I saw them, I did. About a month ago... Marquess
    CLEAN,
    MUNO,
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CAE9CC")
const EventScr EventScr_08CAF0AC[] = {
    MUSI,
    FADI(0x10),
    EXIT_MAP,
    BACG(1),
    FADU(0x10),
    ENTER_MAP,
    TEX1(MSG_A30),                               // The marquess who leads Santaruz is Lord Helman.
    CLEAN,
    MUNO,
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CAE9CC")
const EventScr EventScr_08CAF0DC[] = {
    MUSI,
    FADI(0x10),
    EXIT_MAP,
    BACG(1),
    FADU(0x10),
    ENTER_MAP,
    TEX1(MSG_A31),                               // It's really important to trust your companions,
    CLEAN,
    MUNO,
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CAE9CC")
const EventScr EventScr_08CAF10C[] = {
    MUSI,
    FADI(0x10),
    EXIT_MAP,
    BACG(2),
    FADU(0x10),
    ENTER_MAP,
    TEX1(MSG_A2E),                               // Hmm... You look like you've some experience with
    CLEAN,
    MUNO,
    EVBIT_NOSKIP,
    ENTER_MAP,
    ITGV(ITEM_BOOSTER_SKL),
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CAE9CC")
const EventScr EventScr_Ch0E_Ending[] = {
    MUSC(SONG_3E),
    STAL(0x3C),
    FADI(4),
    EXIT_MAP,
    ASMC(sub_0807A868),
    BACG(0x1C),
    FADU(4),
    ENTER_MAP,
    TEX1(MSG_A34),                               // Whew... Is that all of them? Hector! Where did y
    MUEN(2),
    STAL(0x1E),
    MUSC_FADE(0x38, 2),
    TEX2(MSG_A35),                               // You know Oswin, don't you? Well met, Lord Eliwoo
    IFHM(0xA),
    TEX2(MSG_A36),                               // Lord Hector! Why didn't you tell me the fighting
    GOTO(0xF),
    LABEL(0xA),
    IFAF(0xC, sub_08079DBC),
    IFAF(0xD, sub_08079E0C),
    TEX2(MSG_A36),                               // Lord Hector! Why didn't you tell me the fighting
    GOTO(0xF),
    LABEL(0xC),
    IFAF(0xE, sub_08079E0C),
    TEX2(MSG_A37),                               // Lord Hector! Why didn't you tell me the fighting
    GOTO(0xF),
    LABEL(0xD),
    TEX2(MSG_A38),                               // I apologize for the interruption. Lord Oswin cal
    GOTO(0xF),
    LABEL(0xE),
    TEX2(MSG_A39),                               // Enough pleasantries for now. Eliwood, this journ
    LABEL(0xF),
    SKIP_IFN_ASM(1, sub_08079DBC),
    UNIT_CLEAR_STATE(CHARACTER_MATTHEW, 0x10000),
    UNIT_CLEAR_STATE(CHARACTER_SERRA, 0x10000),
    TEX2(MSG_A3A),                               // What is it, Hector? Do you know something? Nothi
    IFAF(5, sub_0807A3B8),
    FADI(4),
    EXIT_MAP,
    STAL(0x1E),
    BACG(0x1C),
    FADU(4),
    ENTER_MAP,
    TEX1(MSG_A3B),                               // So, . What do you think?
    TEXTEND,
    STAL(0x3C),
    TEX2(MSG_A3C),                               // ... You might be right. Something may have happe
    TEX2(MSG_A3D),                               // Eliwood! Who is this? This is . I required tacti
    IFAF(5, sub_08079DBC),
    IFAF(5, sub_08079E0C),
    FADI(0x10),
    EXIT_MAP,
    BACG(0x1C),
    FADU(0x10),
    ENTER_MAP,
    TEX1(MSG_A3E),                               // Hello! How have you been, ? Eh? My secret's reve
    LABEL(5),
    CALL(EventScr_08CC0C14),
    CLEAR_ON_SKIP_ASM,
    FADI(4),
    EXIT_MAP,
    BACG(0x5B),
    MNCH(CHAPTER_0F),
    STAL(1),
    ENDB,
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CC820C")
const struct UnitDefinition Units_Ch0E_Player[] = {
    UNIT(CHARACTER_ELIWOOD, CLASS_LORD_ELIWOOD, CHARACTER_NONE, 1, FACTION_ID_BLUE, 0, 3, 14, 3, 14, ITEM_SWORD_RAPIER, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_MARCUS, CLASS_PALADIN, CHARACTER_ELIWOOD, 1, FACTION_ID_BLUE, 0, 3, 12, 3, 12, ITEM_SWORD_IRON, ITEM_LANCE_SILVER, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_REBECCA, CLASS_ARCHER_F, CHARACTER_ELIWOOD, 1, FACTION_ID_BLUE, 0, 2, 13, 2, 13, ITEM_BOW_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_LOWEN, CLASS_CAVALIER, CHARACTER_ELIWOOD, 2, FACTION_ID_BLUE, 0, 4, 13, 4, 13, ITEM_SWORD_IRON, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_DORCAS, CLASS_FIGHTER, CHARACTER_ELIWOOD, 3, FACTION_ID_BLUE, 0, 5, 14, 5, 14, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_BARTRE, CLASS_FIGHTER, CHARACTER_ELIWOOD, 2, FACTION_ID_BLUE, 0, 4, 15, 4, 15, ITEM_AXE_IRON, ITEM_AXE_HANDAXE, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC820C")
const struct UnitDefinition Units_Ch0E_Initial[] = {
    UNIT_END,
};

SECTION(".rodata.ev_08CC820C")
const struct UnitDefinition Units_Ch0E_InitialHector[] = {
    UNIT(CHARACTER_ZAGAN, CLASS_FIGHTER, CHARACTER_NONE, 9, FACTION_ID_RED, 0, 16, 0, 16, 0, ITEM_AXE_STEEL, ITEM_NONE, ITEM_NONE, ITEM_NONE, 3, 3, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_BRIGAND, CHARACTER_ZAGAN, 2, FACTION_ID_RED, 1, 9, 0, 9, 0, ITEM_AXE_HANDAXE, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_PEGASUS_KNIGHT, CHARACTER_ZAGAN, 5, FACTION_ID_RED, 1, 15, 9, 15, 9, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_MERCENARY, CHARACTER_ZAGAN, 1, FACTION_ID_RED, 1, 6, 9, 6, 9, ITEM_SWORD_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_BRIGAND, CHARACTER_ZAGAN, 3, FACTION_ID_RED, 1, 12, 13, 12, 13, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_BRIGAND, CHARACTER_ZAGAN, 1, FACTION_ID_RED, 1, 16, 10, 16, 10, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_PEGASUS_KNIGHT, CHARACTER_ZAGAN, 3, FACTION_ID_RED, 1, 15, 3, 15, 3, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_PEGASUS_KNIGHT, CHARACTER_ZAGAN, 3, FACTION_ID_RED, 1, 14, 2, 14, 2, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 0x29, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_ARCHER, CHARACTER_ZAGAN, 2, FACTION_ID_RED, 1, 10, 9, 10, 9, ITEM_BOW_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 0x29, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_BRIGAND, CHARACTER_ZAGAN, 1, FACTION_ID_RED, 1, 5, 5, 5, 5, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_ARCHER, CHARACTER_ZAGAN, 2, FACTION_ID_RED, 1, 7, 6, 7, 6, ITEM_BOW_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 0x29, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_PEGASUS_KNIGHT, CHARACTER_ZAGAN, 3, FACTION_ID_RED, 1, 12, 6, 12, 6, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 9, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC820C")
const struct UnitDefinition Units_08CC835C[] = {
    UNIT(CHARACTER_BANDIT_42, CLASS_BRIGAND, CHARACTER_ZAGAN, 2, FACTION_ID_RED, 1, 16, 4, 16, 5, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_BRIGAND, CHARACTER_ZAGAN, 2, FACTION_ID_RED, 1, 16, 4, 14, 0, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_BRIGAND, CHARACTER_ZAGAN, 2, FACTION_ID_RED, 1, 16, 4, 15, 14, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_BRIGAND, CHARACTER_ZAGAN, 2, FACTION_ID_RED, 1, 16, 4, 6, 8, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_BRIGAND, CHARACTER_ZAGAN, 2, FACTION_ID_RED, 1, 16, 4, 6, 1, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 9, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC820C")
const struct UnitDefinition Units_08CC83BC[] = {
    UNIT(CHARACTER_BANDIT_42, CLASS_PEGASUS_KNIGHT, CHARACTER_ZAGAN, 3, FACTION_ID_RED, 1, 14, 2, 8, 2, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 0x29, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_PEGASUS_KNIGHT, CHARACTER_ZAGAN, 3, FACTION_ID_RED, 1, 14, 2, 13, 15, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 0x29, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_PEGASUS_KNIGHT, CHARACTER_ZAGAN, 3, FACTION_ID_RED, 1, 14, 2, 11, 5, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 0x29, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_BRIGAND, CHARACTER_ZAGAN, 1, FACTION_ID_RED, 1, 5, 5, 14, 12, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 9, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC820C")
const struct UnitDefinition Units_08CC840C[] = {
    UNIT(CHARACTER_HECTOR, CLASS_LORD_HECTOR, CHARACTER_ELIWOOD, 1, FACTION_ID_BLUE, 0, 2, 0, 2, 1, ITEM_AXE_WOLF_BEIL, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC820C")
const struct UnitDefinition Units_08CC842C[] = {
    UNIT(CHARACTER_MATTHEW, CLASS_THIEF, CHARACTER_ELIWOOD, 2, FACTION_ID_BLUE, 0, 1, 0, 1, 0, ITEM_SWORD_IRON, ITEM_LOCKPICK, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC820C")
const struct UnitDefinition Units_08CC844C[] = {
    UNIT(CHARACTER_OSWIN, CLASS_KNIGHT, CHARACTER_ELIWOOD, 9, FACTION_ID_BLUE, 0, 2, 0, 2, 0, ITEM_LANCE_IRON, ITEM_LANCE_JAVELIN, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_SERRA, CLASS_CLERIC, CHARACTER_ELIWOOD, 1, FACTION_ID_BLUE, 0, 1, 0, 1, 1, ITEM_STAFF_HEAL, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC820C")
const struct UnitDefinition Units_Ch0E_PlayerHector[] = {
    UNIT(CHARACTER_HECTOR, CLASS_LORD_HECTOR, CHARACTER_ELIWOOD, 1, FACTION_ID_BLUE, 0, 4, 2, 4, 2, ITEM_AXE_WOLF_BEIL, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT(CHARACTER_OSWIN, CLASS_KNIGHT, CHARACTER_ELIWOOD, 9, FACTION_ID_BLUE, 0, 3, 2, 3, 2, ITEM_LANCE_IRON, ITEM_LANCE_JAVELIN, ITEM_VULNERARY, ITEM_NONE, 0, 0, 0, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC820C")
const struct UnitDefinition Units_08CC84AC[] = {
    UNIT(CHARACTER_ZAGAN, CLASS_FIGHTER, CHARACTER_NONE, 9, FACTION_ID_RED, 0, 6, 2, 6, 4, ITEM_AXE_STEEL, ITEM_NONE, ITEM_NONE, ITEM_NONE, 3, 3, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_SOLDIER, CHARACTER_ZAGAN, 2, FACTION_ID_RED, 1, 5, 3, 8, 8, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 6, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_SOLDIER, CHARACTER_ZAGAN, 1, FACTION_ID_RED, 1, 6, 3, 10, 8, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 9, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC820C")
const struct UnitDefinition Units_08CC84EC[] = {
    UNIT(CHARACTER_BANDIT_42, CLASS_BRIGAND, CHARACTER_ZAGAN, 1, FACTION_ID_RED, 1, 16, 9, 15, 9, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_MERCENARY, CHARACTER_ZAGAN, 1, FACTION_ID_RED, 1, 7, 7, 8, 6, ITEM_SWORD_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_MERCENARY, CHARACTER_ZAGAN, 1, FACTION_ID_RED, 1, 15, 1, 14, 4, ITEM_SWORD_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_MERCENARY, CHARACTER_ZAGAN, 2, FACTION_ID_RED, 1, 15, 1, 15, 5, ITEM_SWORD_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_BRIGAND, CHARACTER_ZAGAN, 3, FACTION_ID_RED, 1, 12, 12, 12, 13, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_BRIGAND, CHARACTER_ZAGAN, 1, FACTION_ID_RED, 1, 16, 9, 14, 6, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 0, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_FIGHTER, CHARACTER_ZAGAN, 1, FACTION_ID_RED, 1, 15, 1, 16, 3, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_ARCHER, CHARACTER_ZAGAN, 2, FACTION_ID_RED, 1, 16, 1, 14, 2, ITEM_BOW_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 0x29, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_ARCHER, CHARACTER_ZAGAN, 2, FACTION_ID_RED, 1, 6, 7, 4, 5, ITEM_BOW_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 0x29, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_SOLDIER, CHARACTER_ZAGAN, 2, FACTION_ID_RED, 1, 5, 7, 7, 5, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 0x29, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_SOLDIER, CHARACTER_ZAGAN, 1, FACTION_ID_RED, 1, 5, 8, 5, 6, ITEM_LANCE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 9, 0),
    UNIT(CHARACTER_BANDIT_42, CLASS_FIGHTER, CHARACTER_ZAGAN, 2, FACTION_ID_RED, 1, 16, 4, 12, 4, ITEM_AXE_IRON, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 9, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CC820C")
const struct UnitDefinition Units_08CC85BC[] = {
    UNIT(CHARACTER_TACTICIAN, CLASS_SOLDIER, CHARACTER_ZAGAN, 2, FACTION_ID_RED, 1, 3, 1, 2, 2, ITEM_AXE_HANDAXE, ITEM_NONE, ITEM_NONE, ITEM_NONE, 0, 3, 9, 0),
    UNIT_END,
};

// unreferenced
SECTION(".rodata.ev_08CC820C")
const EventScr EventScr_08CC85DC[] = {
    LOU1(Units_Ch0E_Player),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC820C")
const EventScr EventScr_08CC85F0[] = {
    UNIT_CAM_OFF,
    EVBIT_NOSKIP,
    LOU1(Units_Ch0E_Initial),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC820C")
const EventScr EventScr_08CC860C[] = {
    LOU1(Units_Ch0E_InitialHector),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC820C")
const EventScr EventScr_08CC8620[] = {
    LOU1(Units_08CC835C),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC820C")
const EventScr EventScr_08CC8634[] = {
    LOU1(Units_08CC83BC),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC820C")
const EventScr EventScr_08CC8648[] = {
    LOU1(Units_08CC840C),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC820C")
const EventScr EventScr_08CC865C[] = {
    LOU1(Units_08CC842C),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC820C")
const EventScr EventScr_08CC8670[] = {
    LOU1(Units_08CC844C),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC820C")
const EventScr EventScr_08CC8684[] = {
    LOU1(Units_Ch0E_PlayerHector),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC820C")
const EventScr EventScr_08CC8698[] = {
    LOU1(Units_08CC84AC),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC820C")
const EventScr EventScr_08CC86AC[] = {
    LOU1(Units_08CC84EC),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CC820C")
const EventScr EventScr_08CC86C0[] = {
    LOU1(Units_08CC85BC),
    ENUN,
    REMA,
    ENDA,
};
