// Chapter 0x30
// Generated by tools/evdis.py

#include "gbafe.h"
#include "event_macros.h"

// event data defined further down or in other files
extern const EventScr EventScr_08CE0D54[];
extern const EventScr EventScr_Ch2F_Ending[];
extern const EventScr EventScr_Ch30_Ending[];
extern const struct TrapData Traps_Ch30[];
extern const struct TrapData Traps_Ch30_Hector[];
extern const struct UnitDefinition Units_Ch30_Initial[];
extern const struct UnitDefinition Units_Ch30_Player[];

SECTION(".rodata.ev_08CA6810")
const EventListScr EvList_Ch30_Turn[] = {
    TURN(0, EventScr_08CE0D54, 1, 0, FACTION_BLUE, 0),
    EVLIST_END
};

SECTION(".rodata.ev_08CA6810")
const EventListScr EvList_Ch30_Character[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA6810")
const EventListScr EvList_Ch30_Location[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA6810")
const EventListScr EvList_Ch30_Misc[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA6810")
const struct ChapterEventGroup ChapterEvents_Ch30 = {
    EvList_Ch30_Turn,                     // turn
    EvList_Ch30_Character,                // character
    EvList_Ch30_Location,                 // location
    EvList_Ch30_Misc,                     // misc
    Traps_Ch30,                           // traps
    Traps_Ch30_Hector,                    // traps (Hector mode)
    {
        Units_Ch30_Initial,               // units loaded at start
        Units_Ch30_Initial,               // (hard)
        Units_Ch30_Initial,               // (Hector mode)
        Units_Ch30_Initial,               // (Hector mode, hard)
    },
    {
        Units_Ch30_Player,                // player units
        Units_Ch30_Player,                // (hard)
        Units_Ch30_Player,                // (Hector mode)
        Units_Ch30_Player,                // (Hector mode, hard)
    },
    &EventScr_Ch2F_Ending[22],            // beginning scene
    EventScr_Ch30_Ending,                 // ending scene
};

SECTION(".rodata.ev_08CC0434")
const EventScr EventScr_Ch30_Ending[] = {
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CE0D24")
const struct UnitDefinition Units_Ch30_Player[] = {
    UNIT(CHARACTER_ELIWOOD, CLASS_LORD_ELIWOOD, CHARACTER_NONE, 1, FACTION_ID_BLUE, 0, 8, 8, 8, 8, ITEM_SWORD_RAPIER, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CE0D24")
const struct UnitDefinition Units_Ch30_Initial[] = {
    UNIT_END,
};

SECTION(".rodata.ev_08CE0D24")
const EventScr EventScr_08CE0D54[] = {
    LOU1(Units_Ch30_Player),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CE0D24")
const EventScr EventScr_08CE0D68[] = {
    UNIT_CAM_OFF,
    EVBIT_NOSKIP,
    LOU1(Units_Ch30_Initial),
    ENUN,
    REMA,
    ENDA,
};
