// Chapter 0x33
// Generated by tools/evdis.py

#include "gbafe.h"
#include "event_macros.h"

// event data defined further down or in other files
extern const EventScr EventScr_08CE0E74[];
extern const EventScr EventScr_Ch33_Beginning[];
extern const EventScr EventScr_Ch33_Ending[];
extern const struct TrapData Traps_Ch33[];
extern const struct TrapData Traps_Ch33_Hector[];
extern const struct UnitDefinition Units_Ch33_Initial[];
extern const struct UnitDefinition Units_Ch33_Player[];

SECTION(".rodata.ev_08CA6930")
const EventListScr EvList_Ch33_Turn[] = {
    TURN(0, EventScr_08CE0E74, 1, 0, FACTION_BLUE, 0),
    EVLIST_END
};

SECTION(".rodata.ev_08CA6930")
const EventListScr EvList_Ch33_Character[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA6930")
const EventListScr EvList_Ch33_Location[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA6930")
const EventListScr EvList_Ch33_Misc[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA6930")
const struct ChapterEventGroup ChapterEvents_Ch33 = {
    EvList_Ch33_Turn,                     // turn
    EvList_Ch33_Character,                // character
    EvList_Ch33_Location,                 // location
    EvList_Ch33_Misc,                     // misc
    Traps_Ch33,                           // traps
    Traps_Ch33_Hector,                    // traps (Hector mode)
    {
        Units_Ch33_Initial,               // units loaded at start
        Units_Ch33_Initial,               // (hard)
        Units_Ch33_Initial,               // (Hector mode)
        Units_Ch33_Initial,               // (Hector mode, hard)
    },
    {
        Units_Ch33_Player,                // player units
        Units_Ch33_Player,                // (hard)
        Units_Ch33_Player,                // (Hector mode)
        Units_Ch33_Player,                // (Hector mode, hard)
    },
    EventScr_Ch33_Beginning,              // beginning scene
    EventScr_Ch33_Ending,                 // ending scene
};

SECTION(".rodata.ev_08CC045C")
const EventScr EventScr_Ch33_Beginning[] = {
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CC045C")
const EventScr EventScr_Ch33_Ending[] = {
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CE0E44")
const struct UnitDefinition Units_Ch33_Player[] = {
    UNIT(CHARACTER_ELIWOOD, CLASS_LORD_ELIWOOD, CHARACTER_NONE, 1, FACTION_ID_BLUE, 0, 8, 8, 8, 8, ITEM_SWORD_RAPIER, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CE0E44")
const struct UnitDefinition Units_Ch33_Initial[] = {
    UNIT_END,
};

SECTION(".rodata.ev_08CE0E44")
const EventScr EventScr_08CE0E74[] = {
    LOU1(Units_Ch33_Player),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CE0E44")
const EventScr EventScr_08CE0E88[] = {
    UNIT_CAM_OFF,
    EVBIT_NOSKIP,
    LOU1(Units_Ch33_Initial),
    ENUN,
    REMA,
    ENDA,
};
