// Chapter 0x35
// Generated by tools/evdis.py

#include "gbafe.h"
#include "event_macros.h"

// event data defined further down or in other files
extern const EventScr EventScr_08CE0F34[];
extern const EventScr EventScr_Ch35_Beginning[];
extern const EventScr EventScr_Ch35_Ending[];
extern const struct TrapData Traps_Ch35[];
extern const struct TrapData Traps_Ch35_Hector[];
extern const struct UnitDefinition Units_Ch35_Initial[];
extern const struct UnitDefinition Units_Ch35_Player[];

SECTION(".rodata.ev_08CA69F0")
const EventListScr EvList_Ch35_Turn[] = {
    TURN(0, EventScr_08CE0F34, 1, 0, FACTION_BLUE, 0),
    EVLIST_END
};

SECTION(".rodata.ev_08CA69F0")
const EventListScr EvList_Ch35_Character[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA69F0")
const EventListScr EvList_Ch35_Location[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA69F0")
const EventListScr EvList_Ch35_Misc[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA69F0")
const struct ChapterEventGroup ChapterEvents_Ch35 = {
    EvList_Ch35_Turn,                     // turn
    EvList_Ch35_Character,                // character
    EvList_Ch35_Location,                 // location
    EvList_Ch35_Misc,                     // misc
    Traps_Ch35,                           // traps
    Traps_Ch35_Hector,                    // traps (Hector mode)
    {
        Units_Ch35_Initial,               // units loaded at start
        Units_Ch35_Initial,               // (hard)
        Units_Ch35_Initial,               // (Hector mode)
        Units_Ch35_Initial,               // (Hector mode, hard)
    },
    {
        Units_Ch35_Player,                // player units
        Units_Ch35_Player,                // (hard)
        Units_Ch35_Player,                // (Hector mode)
        Units_Ch35_Player,                // (Hector mode, hard)
    },
    EventScr_Ch35_Beginning,              // beginning scene
    EventScr_Ch35_Ending,                 // ending scene
};

SECTION(".rodata.ev_08CC047C")
const EventScr EventScr_Ch35_Beginning[] = {
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CC047C")
const EventScr EventScr_Ch35_Ending[] = {
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CE0F04")
const struct UnitDefinition Units_Ch35_Player[] = {
    UNIT(CHARACTER_ELIWOOD, CLASS_LORD_ELIWOOD, CHARACTER_NONE, 1, FACTION_ID_BLUE, 0, 8, 8, 8, 8, ITEM_SWORD_RAPIER, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CE0F04")
const struct UnitDefinition Units_Ch35_Initial[] = {
    UNIT_END,
};

SECTION(".rodata.ev_08CE0F04")
const EventScr EventScr_08CE0F34[] = {
    LOU1(Units_Ch35_Player),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CE0F04")
const EventScr EventScr_08CE0F48[] = {
    UNIT_CAM_OFF,
    EVBIT_NOSKIP,
    LOU1(Units_Ch35_Initial),
    ENUN,
    REMA,
    ENDA,
};
