// Chapter 0x3D
// Generated by tools/evdis.py

#include "gbafe.h"
#include "event_macros.h"

// event data defined further down or in other files
extern const EventScr EventScr_08CE1234[];
extern const EventScr EventScr_Ch3D_Beginning[];
extern const EventScr EventScr_Ch3D_Ending[];
extern const struct TrapData Traps_Ch3D[];
extern const struct TrapData Traps_Ch3D_Hector[];
extern const struct UnitDefinition Units_Ch3D_Initial[];
extern const struct UnitDefinition Units_Ch3D_Player[];

SECTION(".rodata.ev_08CA6CF0")
const EventListScr EvList_Ch3D_Turn[] = {
    TURN(0, EventScr_08CE1234, 1, 0, FACTION_BLUE, 0),
    EVLIST_END
};

SECTION(".rodata.ev_08CA6CF0")
const EventListScr EvList_Ch3D_Character[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA6CF0")
const EventListScr EvList_Ch3D_Location[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA6CF0")
const EventListScr EvList_Ch3D_Misc[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA6CF0")
const struct ChapterEventGroup ChapterEvents_Ch3D = {
    EvList_Ch3D_Turn,                     // turn
    EvList_Ch3D_Character,                // character
    EvList_Ch3D_Location,                 // location
    EvList_Ch3D_Misc,                     // misc
    Traps_Ch3D,                           // traps
    Traps_Ch3D_Hector,                    // traps (Hector mode)
    {
        Units_Ch3D_Initial,               // units loaded at start
        Units_Ch3D_Initial,               // (hard)
        Units_Ch3D_Initial,               // (Hector mode)
        Units_Ch3D_Initial,               // (Hector mode, hard)
    },
    {
        Units_Ch3D_Player,                // player units
        Units_Ch3D_Player,                // (hard)
        Units_Ch3D_Player,                // (Hector mode)
        Units_Ch3D_Player,                // (Hector mode, hard)
    },
    EventScr_Ch3D_Beginning,              // beginning scene
    EventScr_Ch3D_Ending,                 // ending scene
};

SECTION(".rodata.ev_08CC04EC")
const EventScr EventScr_Ch3D_Beginning[] = {
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CC04EC")
const EventScr EventScr_Ch3D_Ending[] = {
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CE1204")
const struct UnitDefinition Units_Ch3D_Player[] = {
    UNIT(CHARACTER_ELIWOOD, CLASS_LORD_ELIWOOD, CHARACTER_NONE, 1, FACTION_ID_BLUE, 0, 8, 8, 8, 8, ITEM_SWORD_RAPIER, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CE1204")
const struct UnitDefinition Units_Ch3D_Initial[] = {
    UNIT_END,
};

SECTION(".rodata.ev_08CE1204")
const EventScr EventScr_08CE1234[] = {
    LOU1(Units_Ch3D_Player),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CE1204")
const EventScr EventScr_08CE1248[] = {
    UNIT_CAM_OFF,
    EVBIT_NOSKIP,
    LOU1(Units_Ch3D_Initial),
    ENUN,
    REMA,
    ENDA,
};
