// Chapter 0x3E
// Generated by tools/evdis.py

#include "gbafe.h"
#include "event_macros.h"

// event data defined further down or in other files
extern const EventScr EventScr_08CE1294[];
extern const EventScr EventScr_Ch3E_Beginning[];
extern const EventScr EventScr_Ch3E_Ending[];
extern const struct TrapData Traps_Ch3E[];
extern const struct TrapData Traps_Ch3E_Hector[];
extern const struct UnitDefinition Units_Ch3E_Initial[];
extern const struct UnitDefinition Units_Ch3E_Player[];

SECTION(".rodata.ev_08CA6D50")
const EventListScr EvList_Ch3E_Turn[] = {
    TURN(0, EventScr_08CE1294, 1, 0, FACTION_BLUE, 0),
    EVLIST_END
};

SECTION(".rodata.ev_08CA6D50")
const EventListScr EvList_Ch3E_Character[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA6D50")
const EventListScr EvList_Ch3E_Location[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA6D50")
const EventListScr EvList_Ch3E_Misc[] = {
    EVLIST_END
};

SECTION(".rodata.ev_08CA6D50")
const struct ChapterEventGroup ChapterEvents_Ch3E = {
    EvList_Ch3E_Turn,                     // turn
    EvList_Ch3E_Character,                // character
    EvList_Ch3E_Location,                 // location
    EvList_Ch3E_Misc,                     // misc
    Traps_Ch3E,                           // traps
    Traps_Ch3E_Hector,                    // traps (Hector mode)
    {
        Units_Ch3E_Initial,               // units loaded at start
        Units_Ch3E_Initial,               // (hard)
        Units_Ch3E_Initial,               // (Hector mode)
        Units_Ch3E_Initial,               // (Hector mode, hard)
    },
    {
        Units_Ch3E_Player,                // player units
        Units_Ch3E_Player,                // (hard)
        Units_Ch3E_Player,                // (Hector mode)
        Units_Ch3E_Player,                // (Hector mode, hard)
    },
    EventScr_Ch3E_Beginning,              // beginning scene
    EventScr_Ch3E_Ending,                 // ending scene
};

SECTION(".rodata.ev_08CC050C")
const EventScr EventScr_Ch3E_Beginning[] = {
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CC050C")
const EventScr EventScr_Ch3E_Ending[] = {
    REMA,
    ENDA,
};

SECTION(".rodata.ev_08CE1264")
const struct UnitDefinition Units_Ch3E_Player[] = {
    UNIT(CHARACTER_ELIWOOD, CLASS_LORD_ELIWOOD, CHARACTER_NONE, 1, FACTION_ID_BLUE, 0, 8, 8, 8, 8, ITEM_SWORD_RAPIER, ITEM_VULNERARY, ITEM_NONE, ITEM_NONE, 0, 0, 0, 0),
    UNIT_END,
};

SECTION(".rodata.ev_08CE1264")
const struct UnitDefinition Units_Ch3E_Initial[] = {
    UNIT_END,
};

SECTION(".rodata.ev_08CE1264")
const EventScr EventScr_08CE1294[] = {
    LOU1(Units_Ch3E_Player),
    ENUN,
    REMA,
    ENDA,
};

// unreferenced
SECTION(".rodata.ev_08CE1264")
const EventScr EventScr_08CE12A8[] = {
    UNIT_CAM_OFF,
    EVBIT_NOSKIP,
    LOU1(Units_Ch3E_Initial),
    ENUN,
    REMA,
    ENDA,
};
