@ ROM data 0x084e0de8-0x0851f48c (not yet in source)
@ Generated by tools/datasplit.py: labels, incbin and .4byte pointers.
@ Labels may be renamed here; rerun the tool then (it rewrites the
@ .4byte references) and after changing data/layout.txt.

	.section .rodata.084E0DE8, "a"

	.global gUnk_084E0DE8
gUnk_084E0DE8:
	.incbin "baserom.gba", 0x4e0de8, 0x4b4

	.global gUnk_084E129C
gUnk_084E129C:  @ LZ77
	.incbin "build/graphics/cg/cg_22.lz"

	.global gUnk_084E456C
gUnk_084E456C:
	.incbin "graphics/cg/cg_22_pal.gbapal"
	.incbin "baserom.gba", 0x4e45ec, 0x80

	.global gUnk_084E466C
gUnk_084E466C:
	.incbin "baserom.gba", 0x4e466c, 0x25c

	.global gUnk_084E48C8
gUnk_084E48C8:
	.incbin "baserom.gba", 0x4e48c8, 0x258

	.global gUnk_084E4B20
gUnk_084E4B20:  @ LZ77
	.incbin "build/graphics/cg/cg_23.lz"

	.global gUnk_084E5F00
gUnk_084E5F00:
	.incbin "graphics/cg/cg_23_pal.gbapal"
	.incbin "baserom.gba", 0x4e5f20, 0xe0

	.global gUnk_084E6000
gUnk_084E6000:
	.incbin "baserom.gba", 0x4e6000, 0x4b4

	.global gUnk_084E64B4
gUnk_084E64B4:  @ LZ77
	.incbin "build/graphics/cg/cg_24.lz"

	.global gUnk_084EBA20
gUnk_084EBA20:
	.incbin "graphics/cg/cg_24_pal.gbapal"
	.incbin "baserom.gba", 0x4ebae0, 0x40

	.global gUnk_084EBB20
gUnk_084EBB20:
	.incbin "baserom.gba", 0x4ebb20, 0x504

	.global gUnk_084EC024
gUnk_084EC024:  @ LZ77
	.incbin "build/graphics/cg/cg_25.lz"

	.global gUnk_084F0E90
gUnk_084F0E90:
	.incbin "graphics/cg/cg_25_pal.gbapal"
	.incbin "baserom.gba", 0x4f0f50, 0x40

	.global gUnk_084F0F90
gUnk_084F0F90:
	.incbin "baserom.gba", 0x4f0f90, 0x4b4

	.global gUnk_084F1444
gUnk_084F1444:  @ LZ77
	.incbin "build/graphics/cg/cg_26.lz"

	.global gUnk_084F65A0
gUnk_084F65A0:
	.incbin "graphics/cg/cg_26_pal.gbapal"
	.incbin "baserom.gba", 0x4f65e0, 0xc0

	.global gUnk_084F66A0
gUnk_084F66A0:
	.incbin "baserom.gba", 0x4f66a0, 0x4b4

	.global gUnk_084F6B54
gUnk_084F6B54:  @ LZ77
	.incbin "build/graphics/cg/cg_27.lz"

	.global gUnk_084FBCC0
gUnk_084FBCC0:
	.incbin "graphics/cg/cg_27_pal.gbapal"
	.incbin "baserom.gba", 0x4fbd00, 0xc0

	.global gUnk_084FBDC0
gUnk_084FBDC0:
	.incbin "baserom.gba", 0x4fbdc0, 0x4b4

	.global gUnk_084FC274
gUnk_084FC274:  @ LZ77
	.incbin "build/graphics/cg/cg_28.lz"

	.global gUnk_0850135C
gUnk_0850135C:
	.incbin "graphics/cg/cg_28_pal.gbapal"
	.incbin "baserom.gba", 0x50139c, 0xc0

	.global gUnk_0850145C
gUnk_0850145C:
	.incbin "baserom.gba", 0x50145c, 0x4b4

	.global gUnk_08501910
gUnk_08501910:  @ LZ77
	.incbin "build/graphics/cg/cg_29.lz"

	.global gUnk_08506B08
gUnk_08506B08:
	.incbin "graphics/cg/cg_29_pal.gbapal"
	.incbin "baserom.gba", 0x506bc8, 0x40

	.global gUnk_08506C08
gUnk_08506C08:
	.incbin "baserom.gba", 0x506c08, 0x4b4

	.global gUnk_085070BC
gUnk_085070BC:  @ LZ77
	.incbin "build/graphics/cg/cg_2A.lz"

	.global gUnk_0850BD54
gUnk_0850BD54:
	.incbin "graphics/cg/cg_2A_pal.gbapal"
	.incbin "baserom.gba", 0x50bd74, 0xe0

	.global gUnk_0850BE54
gUnk_0850BE54:
	.incbin "baserom.gba", 0x50be54, 0x4b4

	.global gUnk_0850C308
gUnk_0850C308:  @ LZ77
	.incbin "build/graphics/cg/cg_2B.lz"

	.global gUnk_08511264
gUnk_08511264:
	.incbin "graphics/cg/cg_2B_pal.gbapal"
	.incbin "baserom.gba", 0x511324, 0x40

	.global gUnk_08511364
gUnk_08511364:
	.incbin "baserom.gba", 0x511364, 0x4b4

	.global gUnk_08511818
gUnk_08511818:  @ LZ77
	.incbin "build/graphics/cg/cg_2C.lz"

	.global gUnk_0851614C
gUnk_0851614C:
	.incbin "graphics/cg/cg_2C_pal.gbapal"
	.incbin "baserom.gba", 0x51620c, 0x40

	.global gUnk_0851624C
gUnk_0851624C:
	.incbin "baserom.gba", 0x51624c, 0x4b4

	.global gUnk_08516700
gUnk_08516700:  @ LZ77
	.incbin "build/graphics/cg/cg_2D.lz"

	.global gUnk_08519910
gUnk_08519910:
	.incbin "graphics/cg/cg_2D_pal.gbapal"
	.incbin "baserom.gba", 0x5199d0, 0x40

	.global gUnk_08519A10
gUnk_08519A10:
	.incbin "baserom.gba", 0x519a10, 0x334

	.global gUnk_08519D44
gUnk_08519D44:
	.incbin "baserom.gba", 0x519d44, 0x100

	.global gUnk_08519E44
gUnk_08519E44:
	.incbin "baserom.gba", 0x519e44, 0x80

	.global gUnk_08519EC4
gUnk_08519EC4:  @ LZ77
	.incbin "build/graphics/cg/cg_2E.lz"

	.global gUnk_0851EED8
gUnk_0851EED8:
	.incbin "graphics/cg/cg_2E_pal.gbapal"
	.incbin "baserom.gba", 0x51ef98, 0x40

	.global gUnk_0851EFD8
gUnk_0851EFD8:
	.incbin "baserom.gba", 0x51efd8, 0x208

	.global gUnk_0851F1E0
gUnk_0851F1E0:
	.incbin "baserom.gba", 0x51f1e0, 0x2ac
