@ ROM data 0x0845865c-0x0849695c (not yet in source)
@ Generated by tools/datasplit.py: labels, incbin and .4byte pointers.
@ Labels may be renamed here; rerun the tool then (it rewrites the
@ .4byte references) and after changing data/layout.txt.

	.section .rodata.0845865C, "a"

	.global gUnk_0845865C
gUnk_0845865C:  @ LZ77
	.incbin "build/graphics/gUnk_0845865C.lz"

	.global gUnk_08458EBC
gUnk_08458EBC:  @ LZ77
	.incbin "build/graphics/gUnk_08458EBC.lz"

	.global gUnk_08459720
gUnk_08459720:  @ LZ77
	.incbin "build/graphics/gUnk_08459720.lz"

	.global gUnk_08459F6C
gUnk_08459F6C:  @ LZ77
	.incbin "build/graphics/gUnk_08459F6C.lz"

	.global gUnk_0845A7B0
gUnk_0845A7B0:  @ LZ77
	.incbin "build/graphics/gUnk_0845A7B0.lz"

	.global gUnk_0845AFB4
gUnk_0845AFB4:
	.incbin "baserom.gba", 0x45afb4, 0x100

	.global gUnk_0845B0B4
gUnk_0845B0B4:
	.incbin "baserom.gba", 0x45b0b4, 0xfc

	.global gUnk_0845B1B0
gUnk_0845B1B0:
	.incbin "baserom.gba", 0x45b1b0, 0x3b8

	.global gUnk_0845B568
gUnk_0845B568:  @ LZ77
	.incbin "build/graphics/gUnk_0845B568.lz"

	.global gUnk_0845BD9C
gUnk_0845BD9C:  @ LZ77
	.incbin "build/graphics/gUnk_0845BD9C.lz"

	.global gUnk_0845C5F8
gUnk_0845C5F8:  @ LZ77
	.incbin "build/graphics/gUnk_0845C5F8.lz"

	.global gUnk_0845CE4C
gUnk_0845CE4C:  @ LZ77
	.incbin "build/graphics/gUnk_0845CE4C.lz"

	.global gUnk_0845D6BC
gUnk_0845D6BC:  @ LZ77
	.incbin "build/graphics/gUnk_0845D6BC.lz"

	.global gUnk_0845DF0C
gUnk_0845DF0C:  @ LZ77
	.incbin "build/graphics/gUnk_0845DF0C.lz"

	.global gUnk_0845E76C
gUnk_0845E76C:  @ LZ77
	.incbin "build/graphics/gUnk_0845E76C.lz"

	.global gUnk_0845EF5C
gUnk_0845EF5C:  @ LZ77
	.incbin "build/graphics/gUnk_0845EF5C.lz"

	.global gUnk_0845F718
gUnk_0845F718:  @ LZ77
	.incbin "build/graphics/gUnk_0845F718.lz"

	.global gUnk_0845FF30
gUnk_0845FF30:  @ LZ77
	.incbin "build/graphics/gUnk_0845FF30.lz"

	.global gUnk_08460768
gUnk_08460768:
	.incbin "baserom.gba", 0x460768, 0xec

	.global gUnk_08460854
gUnk_08460854:
	.incbin "baserom.gba", 0x460854, 0x14

	.global gUnk_08460868
gUnk_08460868:
	.incbin "baserom.gba", 0x460868, 0x7c

	.global gUnk_084608E4
gUnk_084608E4:
	.incbin "baserom.gba", 0x4608e4, 0x438

	.global gUnk_08460D1C
gUnk_08460D1C:  @ LZ77
	.incbin "build/graphics/gUnk_08460D1C.lz"

	.global gUnk_08461544
gUnk_08461544:  @ LZ77
	.incbin "build/graphics/gUnk_08461544.lz"

	.global gUnk_08461D90
gUnk_08461D90:  @ LZ77
	.incbin "build/graphics/gUnk_08461D90.lz"

	.global gUnk_084625DC
gUnk_084625DC:  @ LZ77
	.incbin "build/graphics/gUnk_084625DC.lz"

	.global gUnk_08462E1C
gUnk_08462E1C:  @ LZ77
	.incbin "build/graphics/gUnk_08462E1C.lz"

	.global gUnk_08463658
gUnk_08463658:  @ LZ77
	.incbin "build/graphics/gUnk_08463658.lz"

	.global gUnk_08463E68
gUnk_08463E68:  @ LZ77
	.incbin "build/graphics/gUnk_08463E68.lz"

	.global gUnk_08464688
gUnk_08464688:  @ LZ77
	.incbin "build/graphics/gUnk_08464688.lz"

	.global gUnk_08464EAC
gUnk_08464EAC:  @ LZ77
	.incbin "build/graphics/gUnk_08464EAC.lz"

	.global gUnk_084656E0
gUnk_084656E0:  @ LZ77
	.incbin "build/graphics/gUnk_084656E0.lz"

	.global gUnk_08465EEC
gUnk_08465EEC:
	.incbin "baserom.gba", 0x465eec, 0x100

	.global gUnk_08465FEC
gUnk_08465FEC:
	.incbin "baserom.gba", 0x465fec, 0x1b0

	.global gUnk_0846619C
gUnk_0846619C:
	.incbin "baserom.gba", 0x46619c, 0x304

	.global gUnk_084664A0
gUnk_084664A0:  @ LZ77
	.incbin "build/graphics/gUnk_084664A0.lz"

	.global gUnk_0846B4A8
gUnk_0846B4A8:
	.incbin "baserom.gba", 0x46b4a8, 0x100

	.global gUnk_0846B5A8
gUnk_0846B5A8:
	.incbin "baserom.gba", 0x46b5a8, 0x354

	.global gUnk_0846B8FC
gUnk_0846B8FC:
	.incbin "baserom.gba", 0x46b8fc, 0x160

	.global gUnk_0846BA5C
gUnk_0846BA5C:  @ LZ77
	.incbin "build/graphics/gUnk_0846BA5C.lz"

	.global gUnk_08470844
gUnk_08470844:
	.incbin "baserom.gba", 0x470844, 0x100

	.global gUnk_08470944
gUnk_08470944:
	.incbin "baserom.gba", 0x470944, 0x4b4

	.global gUnk_08470DF8
gUnk_08470DF8:  @ LZ77
	.incbin "build/graphics/gUnk_08470DF8.lz"

	.global gUnk_084759FC
gUnk_084759FC:
	.incbin "baserom.gba", 0x4759fc, 0x100

	.global gUnk_08475AFC
gUnk_08475AFC:
	.incbin "baserom.gba", 0x475afc, 0x4b4

	.global gUnk_08475FB0
gUnk_08475FB0:  @ LZ77
	.incbin "build/graphics/gUnk_08475FB0.lz"

	.global gUnk_0847B04C
gUnk_0847B04C:
	.incbin "baserom.gba", 0x47b04c, 0x100

	.global gUnk_0847B14C
gUnk_0847B14C:
	.incbin "baserom.gba", 0x47b14c, 0x4b4

	.global gUnk_0847B600
gUnk_0847B600:  @ LZ77
	.incbin "build/graphics/gUnk_0847B600.lz"

	.global gUnk_08480598
gUnk_08480598:
	.incbin "baserom.gba", 0x480598, 0x100

	.global gUnk_08480698
gUnk_08480698:
	.incbin "baserom.gba", 0x480698, 0x4b4

	.global gUnk_08480B4C
gUnk_08480B4C:  @ LZ77
	.incbin "build/graphics/gUnk_08480B4C.lz"

	.global gUnk_08485864
gUnk_08485864:
	.incbin "baserom.gba", 0x485864, 0x100

	.global gUnk_08485964
gUnk_08485964:
	.incbin "baserom.gba", 0x485964, 0x4b4

	.global gUnk_08485E18
gUnk_08485E18:  @ LZ77
	.incbin "build/graphics/gUnk_08485E18.lz"

	.global gUnk_0848B0E0
gUnk_0848B0E0:
	.incbin "baserom.gba", 0x48b0e0, 0x100

	.global gUnk_0848B1E0
gUnk_0848B1E0:
	.incbin "baserom.gba", 0x48b1e0, 0x4b4

	.global gUnk_0848B694
gUnk_0848B694:  @ LZ77
	.incbin "build/graphics/gUnk_0848B694.lz"

	.global gUnk_08490AE0
gUnk_08490AE0:
	.incbin "baserom.gba", 0x490ae0, 0x100

	.global gUnk_08490BE0
gUnk_08490BE0:
	.incbin "baserom.gba", 0x490be0, 0x4b4

	.global gUnk_08491094
gUnk_08491094:  @ LZ77
	.incbin "build/graphics/gUnk_08491094.lz"

	.global gUnk_084963A8
gUnk_084963A8:
	.incbin "baserom.gba", 0x4963a8, 0x100

	.global gUnk_084964A8
gUnk_084964A8:
	.incbin "baserom.gba", 0x4964a8, 0x4b4
