@ ROM data 0x08d501a0-0x08d8bd00 (not yet in source)
@ Generated by tools/datasplit.py: labels, incbin and .4byte pointers.
@ Labels may be renamed here; rerun the tool then (it rewrites the
@ .4byte references) and after changing data/layout.txt.

	.section .rodata.08D501A0, "a"

	.global gUnk_08D501A0
gUnk_08D501A0:
	.incbin "baserom.gba", 0xd501a0, 0x3bb60
