@ ROM data 0x08421c78-0x08461544 (not yet in source)
@ Generated by tools/datasplit.py: labels, incbin and .4byte pointers.
@ Labels may be renamed here; rerun the tool then (it rewrites the
@ .4byte references) and after changing data/layout.txt.

	.section .rodata.08421C78, "a"

	.global Img_Wm_08421C78
Img_Wm_08421C78:  @ LZ77
	.incbin "build/graphics/Img_Wm_08421C78.lz"

	.global Sprite_WmIcon
Sprite_WmIcon:
	.incbin "baserom.gba", 0x422160, 0x74

	.global Pal_Wm_084221D4
Pal_Wm_084221D4:
	.incbin "baserom.gba", 0x4221d4, 0x3d4

	.global Pal_Wm_084225A8
Pal_Wm_084225A8:
	.incbin "baserom.gba", 0x4225a8, 0x20

	.global Img_WmSpriteAnim_00
Img_WmSpriteAnim_00:  @ LZ77
	.incbin "build/graphics/world_map/WmSpriteAnimTable_00.lz"

	.global gUnk_08422AC4
gUnk_08422AC4:
	.incbin "baserom.gba", 0x422ac4, 0xb8

	.global Img_WmSpriteAnim_01
Img_WmSpriteAnim_01:  @ LZ77
	.incbin "build/graphics/world_map/WmSpriteAnimTable_01.lz"

	.global gUnk_08423080
gUnk_08423080:
	.incbin "baserom.gba", 0x423080, 0xe8

	.global Img_WmSpriteAnim_02
Img_WmSpriteAnim_02:  @ LZ77
	.incbin "build/graphics/world_map/WmSpriteAnimTable_02.lz"

	.global gUnk_084236A4
gUnk_084236A4:
	.incbin "baserom.gba", 0x4236a4, 0x138

	.global Img_WmSpriteAnim_04
Img_WmSpriteAnim_04:  @ LZ77
	.incbin "build/graphics/world_map/WmSpriteAnimTable_04.lz"

	.global gUnk_08423B48
gUnk_08423B48:
	.incbin "baserom.gba", 0x423b48, 0xb4

	.global Img_WmSpriteAnim_03
Img_WmSpriteAnim_03:  @ LZ77
	.incbin "build/graphics/world_map/WmSpriteAnimTable_03.lz"

	.global gUnk_0842418C
gUnk_0842418C:
	.incbin "baserom.gba", 0x42418c, 0xb4

	.global Img_WmSpriteAnim_05
Img_WmSpriteAnim_05:  @ LZ77
	.incbin "build/graphics/world_map/WmSpriteAnimTable_05.lz"

	.global gUnk_0842458C
gUnk_0842458C:
	.incbin "baserom.gba", 0x42458c, 0xb4

	.global Img_WmSpriteAnim_06
Img_WmSpriteAnim_06:  @ LZ77
	.incbin "build/graphics/world_map/WmSpriteAnimTable_06.lz"

	.global gUnk_084249C0
gUnk_084249C0:
	.incbin "baserom.gba", 0x4249c0, 0x88

	.global Img_WmSpriteAnim_07
Img_WmSpriteAnim_07:  @ LZ77
	.incbin "build/graphics/world_map/WmSpriteAnimTable_07.lz"

	.global gUnk_08424BB0
gUnk_08424BB0:
	.incbin "baserom.gba", 0x424bb0, 0x3c

	.global Img_WmSpriteAnim_08
Img_WmSpriteAnim_08:  @ LZ77
	.incbin "build/graphics/world_map/WmSpriteAnimTable_08.lz"

	.global gUnk_08424C9C
gUnk_08424C9C:
	.incbin "baserom.gba", 0x424c9c, 0x3c

	.global Pal_Wm_08424CD8
Pal_Wm_08424CD8:
	.incbin "baserom.gba", 0x424cd8, 0x3e4

	.global Pal_WmUnitAnimB
Pal_WmUnitAnimB:
	.incbin "baserom.gba", 0x4250bc, 0x80

	.global Pal_WmUnitAnimA
Pal_WmUnitAnimA:
	.incbin "baserom.gba", 0x42513c, 0x80

	.global Img_BrownTextBox
Img_BrownTextBox:  @ LZ77
	.incbin "build/graphics/Img_BrownTextBox.lz"

	.global Pal_BrownTextBox
Pal_BrownTextBox:
	.incbin "baserom.gba", 0x42535c, 0x11c

	.global Img_CandleFlame
Img_CandleFlame:  @ LZ77
	.incbin "build/graphics/Img_CandleFlame.lz"

	.global Pal_CandleFlame
Pal_CandleFlame:
	.incbin "graphics/Pal_CandleFlame.gbapal"

	.global Tsa_CandleFlame
Tsa_CandleFlame:
	.incbin "baserom.gba", 0x425578, 0xf4

	.global gUnk_0842566C
gUnk_0842566C:
	.incbin "baserom.gba", 0x42566c, 0x4b4

	.global gUnk_08425B20
gUnk_08425B20:
	.incbin "baserom.gba", 0x425b20, 0x100

	.global gUnk_08425C20
gUnk_08425C20:
	.incbin "baserom.gba", 0x425c20, 0x100

	.global Img_EpilogueScroll_00
Img_EpilogueScroll_00:  @ LZ77
	.incbin "build/graphics/ending/epilogue_scroll_00.lz"

	.global Img_EpilogueScroll_01
Img_EpilogueScroll_01:  @ LZ77
	.incbin "build/graphics/ending/epilogue_scroll_01.lz"

	.global Img_EpilogueScroll_02
Img_EpilogueScroll_02:  @ LZ77
	.incbin "build/graphics/ending/epilogue_scroll_02.lz"

	.global Img_EpilogueScroll_03
Img_EpilogueScroll_03:  @ LZ77
	.incbin "build/graphics/ending/epilogue_scroll_03.lz"

	.global Img_EpilogueScroll_04
Img_EpilogueScroll_04:  @ LZ77
	.incbin "build/graphics/ending/epilogue_scroll_04.lz"

	.global Img_EpilogueScroll_05
Img_EpilogueScroll_05:  @ LZ77
	.incbin "build/graphics/ending/epilogue_scroll_05.lz"

	.global Img_EpilogueScroll_06
Img_EpilogueScroll_06:  @ LZ77
	.incbin "build/graphics/ending/epilogue_scroll_06.lz"

	.global Img_EpilogueScroll_07
Img_EpilogueScroll_07:  @ LZ77
	.incbin "build/graphics/ending/epilogue_scroll_07.lz"

	.global Img_EpilogueScroll_08
Img_EpilogueScroll_08:  @ LZ77
	.incbin "build/graphics/ending/epilogue_scroll_08.lz"

	.global Img_EpilogueScroll_09
Img_EpilogueScroll_09:  @ LZ77
	.incbin "build/graphics/ending/epilogue_scroll_09.lz"

	.global Img_Cg_0A_0
Img_Cg_0A_0:  @ LZ77
	.incbin "build/graphics/cg/cg_0A_part_0.lz"

	.global Img_Cg_0A_1
Img_Cg_0A_1:  @ LZ77
	.incbin "build/graphics/cg/cg_0A_part_1.lz"

	.global Img_Cg_0A_2
Img_Cg_0A_2:  @ LZ77
	.incbin "build/graphics/cg/cg_0A_part_2.lz"

	.global Img_Cg_0A_3
Img_Cg_0A_3:  @ LZ77
	.incbin "build/graphics/cg/cg_0A_part_3.lz"

	.global Img_Cg_0A_4
Img_Cg_0A_4:  @ LZ77
	.incbin "build/graphics/cg/cg_0A_part_4.lz"

	.global Img_Cg_0A_5
Img_Cg_0A_5:  @ LZ77
	.incbin "build/graphics/cg/cg_0A_part_5.lz"

	.global Img_Cg_0A_6
Img_Cg_0A_6:  @ LZ77
	.incbin "build/graphics/cg/cg_0A_part_6.lz"

	.global Img_Cg_0A_7
Img_Cg_0A_7:  @ LZ77
	.incbin "build/graphics/cg/cg_0A_part_7.lz"

	.global Img_Cg_0A_8
Img_Cg_0A_8:  @ LZ77
	.incbin "build/graphics/cg/cg_0A_part_8.lz"

	.global Img_Cg_0A_9
Img_Cg_0A_9:  @ LZ77
	.incbin "build/graphics/cg/cg_0A_part_9.lz"

	.global gUnk_0842F1A0
gUnk_0842F1A0:
	.incbin "baserom.gba", 0x42f1a0, 0x7c

	.global gUnk_0842F21C
gUnk_0842F21C:
	.incbin "baserom.gba", 0x42f21c, 0x7c

	.global gUnk_0842F298
gUnk_0842F298:
	.incbin "baserom.gba", 0x42f298, 0x7c

	.global gUnk_0842F314
gUnk_0842F314:
	.incbin "baserom.gba", 0x42f314, 0x7c

	.global gUnk_0842F390
gUnk_0842F390:
	.incbin "baserom.gba", 0x42f390, 0x7c

	.global gUnk_0842F40C
gUnk_0842F40C:
	.incbin "baserom.gba", 0x42f40c, 0x7c

	.global gUnk_0842F488
gUnk_0842F488:
	.incbin "baserom.gba", 0x42f488, 0x8

	.global gUnk_0842F490
gUnk_0842F490:
	.incbin "baserom.gba", 0x42f490, 0x74

	.global gUnk_0842F504
gUnk_0842F504:
	.incbin "baserom.gba", 0x42f504, 0x7c

	.global gUnk_0842F580
gUnk_0842F580:
	.incbin "baserom.gba", 0x42f580, 0x7c

	.global gUnk_0842F5FC
gUnk_0842F5FC:
	.incbin "baserom.gba", 0x42f5fc, 0x7c

	.global gUnk_0842F678
gUnk_0842F678:
	.incbin "baserom.gba", 0x42f678, 0x7c

	.global gUnk_0842F6F4
gUnk_0842F6F4:
	.incbin "baserom.gba", 0x42f6f4, 0x7c

	.global gUnk_0842F770
gUnk_0842F770:
	.incbin "baserom.gba", 0x42f770, 0x7c

	.global gUnk_0842F7EC
gUnk_0842F7EC:
	.incbin "baserom.gba", 0x42f7ec, 0x7c

	.global gUnk_0842F868
gUnk_0842F868:
	.incbin "baserom.gba", 0x42f868, 0x7c

	.global gUnk_0842F8E4
gUnk_0842F8E4:
	.incbin "baserom.gba", 0x42f8e4, 0x7c

	.global gUnk_0842F960
gUnk_0842F960:
	.incbin "baserom.gba", 0x42f960, 0x7c

	.global gUnk_0842F9DC
gUnk_0842F9DC:
	.incbin "baserom.gba", 0x42f9dc, 0x7c

	.global gUnk_0842FA58
gUnk_0842FA58:
	.incbin "baserom.gba", 0x42fa58, 0x7c

	.global gUnk_0842FAD4
gUnk_0842FAD4:
	.incbin "baserom.gba", 0x42fad4, 0x7c

	.global gUnk_0842FB50
gUnk_0842FB50:
	.incbin "baserom.gba", 0x42fb50, 0xec

	.global gUnk_0842FC3C
gUnk_0842FC3C:
	.incbin "baserom.gba", 0x42fc3c, 0x3c8

	.global Pal_Cg_0A
Pal_Cg_0A:
	.incbin "graphics/cg/cg_0A_pal.gbapal"

	.global Img_Cg_00_0
Img_Cg_00_0:  @ LZ77
	.incbin "build/graphics/cg/cg_00_part_0.lz"

	.global Img_Cg_00_1
Img_Cg_00_1:  @ LZ77
	.incbin "build/graphics/cg/cg_00_part_1.lz"

	.global Img_Cg_00_2
Img_Cg_00_2:  @ LZ77
	.incbin "build/graphics/cg/cg_00_part_2.lz"

	.global Img_Cg_00_3
Img_Cg_00_3:  @ LZ77
	.incbin "build/graphics/cg/cg_00_part_3.lz"

	.global Img_Cg_00_4
Img_Cg_00_4:  @ LZ77
	.incbin "build/graphics/cg/cg_00_part_4.lz"

	.global Img_Cg_00_5
Img_Cg_00_5:  @ LZ77
	.incbin "build/graphics/cg/cg_00_part_5.lz"

	.global Img_Cg_00_6
Img_Cg_00_6:  @ LZ77
	.incbin "build/graphics/cg/cg_00_part_6.lz"

	.global Img_Cg_00_7
Img_Cg_00_7:  @ LZ77
	.incbin "build/graphics/cg/cg_00_part_7.lz"

	.global Img_Cg_00_8
Img_Cg_00_8:  @ LZ77
	.incbin "build/graphics/cg/cg_00_part_8.lz"

	.global Img_Cg_00_9
Img_Cg_00_9:  @ LZ77
	.incbin "build/graphics/cg/cg_00_part_9.lz"

	.global Pal_Cg_00
Pal_Cg_00:
	.incbin "graphics/cg/cg_00_pal.gbapal"
	.incbin "baserom.gba", 0x4354b8, 0x40

	.global gUnk_084354F8
gUnk_084354F8:
	.incbin "baserom.gba", 0x4354f8, 0x4b4

	.global Img_Cg_01_0
Img_Cg_01_0:  @ LZ77
	.incbin "build/graphics/cg/cg_01_part_0.lz"

	.global Img_Cg_01_1
Img_Cg_01_1:  @ LZ77
	.incbin "build/graphics/cg/cg_01_part_1.lz"

	.global Img_Cg_01_2
Img_Cg_01_2:  @ LZ77
	.incbin "build/graphics/cg/cg_01_part_2.lz"

	.global Img_Cg_01_3
Img_Cg_01_3:  @ LZ77
	.incbin "build/graphics/cg/cg_01_part_3.lz"

	.global Img_Cg_01_4
Img_Cg_01_4:  @ LZ77
	.incbin "build/graphics/cg/cg_01_part_4.lz"

	.global Img_Cg_01_5
Img_Cg_01_5:  @ LZ77
	.incbin "build/graphics/cg/cg_01_part_5.lz"

	.global Img_Cg_01_6
Img_Cg_01_6:  @ LZ77
	.incbin "build/graphics/cg/cg_01_part_6.lz"

	.global Img_Cg_01_7
Img_Cg_01_7:  @ LZ77
	.incbin "build/graphics/cg/cg_01_part_7.lz"

	.global Img_Cg_01_8
Img_Cg_01_8:  @ LZ77
	.incbin "build/graphics/cg/cg_01_part_8.lz"

	.global Img_Cg_01_9
Img_Cg_01_9:  @ LZ77
	.incbin "build/graphics/cg/cg_01_part_9.lz"

	.global Pal_Cg_01
Pal_Cg_01:
	.incbin "graphics/cg/cg_01_pal.gbapal"
	.incbin "baserom.gba", 0x43ab98, 0x40

	.global gUnk_0843ABD8
gUnk_0843ABD8:
	.incbin "baserom.gba", 0x43abd8, 0x164

	.global gUnk_0843AD3C
gUnk_0843AD3C:
	.incbin "baserom.gba", 0x43ad3c, 0x350

	.global Img_Cg_02_0
Img_Cg_02_0:  @ LZ77
	.incbin "build/graphics/cg/cg_02_part_0.lz"

	.global Img_Cg_02_1
Img_Cg_02_1:  @ LZ77
	.incbin "build/graphics/cg/cg_02_part_1.lz"

	.global Img_Cg_02_2
Img_Cg_02_2:  @ LZ77
	.incbin "build/graphics/cg/cg_02_part_2.lz"

	.global Img_Cg_02_3
Img_Cg_02_3:  @ LZ77
	.incbin "build/graphics/cg/cg_02_part_3.lz"

	.global Img_Cg_02_4
Img_Cg_02_4:  @ LZ77
	.incbin "build/graphics/cg/cg_02_part_4.lz"

	.global Img_Cg_02_5
Img_Cg_02_5:  @ LZ77
	.incbin "build/graphics/cg/cg_02_part_5.lz"

	.global Img_Cg_02_6
Img_Cg_02_6:  @ LZ77
	.incbin "build/graphics/cg/cg_02_part_6.lz"

	.global Img_Cg_02_7
Img_Cg_02_7:  @ LZ77
	.incbin "build/graphics/cg/cg_02_part_7.lz"

	.global Img_Cg_02_8
Img_Cg_02_8:  @ LZ77
	.incbin "build/graphics/cg/cg_02_part_8.lz"

	.global Img_Cg_02_9
Img_Cg_02_9:  @ LZ77
	.incbin "build/graphics/cg/cg_02_part_9.lz"

	.global Pal_Cg_02
Pal_Cg_02:
	.incbin "graphics/cg/cg_02_pal.gbapal"
	.incbin "baserom.gba", 0x4403e4, 0x8

	.global gUnk_084403EC
gUnk_084403EC:
	.incbin "baserom.gba", 0x4403ec, 0x58

	.global gUnk_08440444
gUnk_08440444:
	.incbin "baserom.gba", 0x440444, 0x4b4

	.global Img_Cg_03_0
Img_Cg_03_0:  @ LZ77
	.incbin "build/graphics/cg/cg_03_part_0.lz"

	.global Img_Cg_03_1
Img_Cg_03_1:  @ LZ77
	.incbin "build/graphics/cg/cg_03_part_1.lz"

	.global Img_Cg_03_2
Img_Cg_03_2:  @ LZ77
	.incbin "build/graphics/cg/cg_03_part_2.lz"

	.global Img_Cg_03_3
Img_Cg_03_3:  @ LZ77
	.incbin "build/graphics/cg/cg_03_part_3.lz"

	.global Img_Cg_03_4
Img_Cg_03_4:  @ LZ77
	.incbin "build/graphics/cg/cg_03_part_4.lz"

	.global Img_Cg_03_5
Img_Cg_03_5:  @ LZ77
	.incbin "build/graphics/cg/cg_03_part_5.lz"

	.global Img_Cg_03_6
Img_Cg_03_6:  @ LZ77
	.incbin "build/graphics/cg/cg_03_part_6.lz"

	.global Img_Cg_03_7
Img_Cg_03_7:  @ LZ77
	.incbin "build/graphics/cg/cg_03_part_7.lz"

	.global Img_Cg_03_8
Img_Cg_03_8:  @ LZ77
	.incbin "build/graphics/cg/cg_03_part_8.lz"

	.global Img_Cg_03_9
Img_Cg_03_9:  @ LZ77
	.incbin "build/graphics/cg/cg_03_part_9.lz"

	.global Pal_Cg_03
Pal_Cg_03:
	.incbin "graphics/cg/cg_03_pal.gbapal"
	.incbin "baserom.gba", 0x445770, 0x40

	.global gUnk_084457B0
gUnk_084457B0:
	.incbin "baserom.gba", 0x4457b0, 0x4b4

	.global Img_Cg_04_0
Img_Cg_04_0:  @ LZ77
	.incbin "build/graphics/cg/cg_04_part_0.lz"

	.global Img_Cg_04_1
Img_Cg_04_1:  @ LZ77
	.incbin "build/graphics/cg/cg_04_part_1.lz"

	.global Img_Cg_04_2
Img_Cg_04_2:  @ LZ77
	.incbin "build/graphics/cg/cg_04_part_2.lz"

	.global Img_Cg_04_3
Img_Cg_04_3:  @ LZ77
	.incbin "build/graphics/cg/cg_04_part_3.lz"

	.global Img_Cg_04_4
Img_Cg_04_4:  @ LZ77
	.incbin "build/graphics/cg/cg_04_part_4.lz"

	.global Img_Cg_04_5
Img_Cg_04_5:  @ LZ77
	.incbin "build/graphics/cg/cg_04_part_5.lz"

	.global Img_Cg_04_6
Img_Cg_04_6:  @ LZ77
	.incbin "build/graphics/cg/cg_04_part_6.lz"

	.global Img_Cg_04_7
Img_Cg_04_7:  @ LZ77
	.incbin "build/graphics/cg/cg_04_part_7.lz"

	.global Img_Cg_04_8
Img_Cg_04_8:  @ LZ77
	.incbin "build/graphics/cg/cg_04_part_8.lz"

	.global Img_Cg_04_9
Img_Cg_04_9:  @ LZ77
	.incbin "build/graphics/cg/cg_04_part_9.lz"

	.global Pal_Cg_04
Pal_Cg_04:
	.incbin "graphics/cg/cg_04_pal.gbapal"
	.incbin "baserom.gba", 0x44abe4, 0x40

	.global gUnk_0844AC24
gUnk_0844AC24:
	.incbin "baserom.gba", 0x44ac24, 0x410

	.global gUnk_0844B034
gUnk_0844B034:
	.incbin "baserom.gba", 0x44b034, 0xa4

	.global Img_Cg_05_0
Img_Cg_05_0:  @ LZ77
	.incbin "build/graphics/cg/cg_05_part_0.lz"

	.global Img_Cg_05_1
Img_Cg_05_1:  @ LZ77
	.incbin "build/graphics/cg/cg_05_part_1.lz"

	.global Img_Cg_05_2
Img_Cg_05_2:  @ LZ77
	.incbin "build/graphics/cg/cg_05_part_2.lz"

	.global Img_Cg_05_3
Img_Cg_05_3:  @ LZ77
	.incbin "build/graphics/cg/cg_05_part_3.lz"

	.global Img_Cg_05_4
Img_Cg_05_4:  @ LZ77
	.incbin "build/graphics/cg/cg_05_part_4.lz"

	.global Img_Cg_05_5
Img_Cg_05_5:  @ LZ77
	.incbin "build/graphics/cg/cg_05_part_5.lz"

	.global Img_Cg_05_6
Img_Cg_05_6:  @ LZ77
	.incbin "build/graphics/cg/cg_05_part_6.lz"

	.global Img_Cg_05_7
Img_Cg_05_7:  @ LZ77
	.incbin "build/graphics/cg/cg_05_part_7.lz"

	.global Img_Cg_05_8
Img_Cg_05_8:  @ LZ77
	.incbin "build/graphics/cg/cg_05_part_8.lz"

	.global Img_Cg_05_9
Img_Cg_05_9:  @ LZ77
	.incbin "build/graphics/cg/cg_05_part_9.lz"

	.global Pal_Cg_05
Pal_Cg_05:
	.incbin "graphics/cg/cg_05_pal.gbapal"
	.incbin "baserom.gba", 0x4502e4, 0x40

	.global gUnk_08450324
gUnk_08450324:
	.incbin "baserom.gba", 0x450324, 0x230

	.global gUnk_08450554
gUnk_08450554:
	.incbin "baserom.gba", 0x450554, 0x284

	.global Img_Cg_06_0
Img_Cg_06_0:  @ LZ77
	.incbin "build/graphics/cg/cg_06_part_0.lz"

	.global Img_Cg_06_1
Img_Cg_06_1:  @ LZ77
	.incbin "build/graphics/cg/cg_06_part_1.lz"

	.global Img_Cg_06_2
Img_Cg_06_2:  @ LZ77
	.incbin "build/graphics/cg/cg_06_part_2.lz"

	.global Img_Cg_06_3
Img_Cg_06_3:  @ LZ77
	.incbin "build/graphics/cg/cg_06_part_3.lz"

	.global Img_Cg_06_4
Img_Cg_06_4:  @ LZ77
	.incbin "build/graphics/cg/cg_06_part_4.lz"

	.global Img_Cg_06_5
Img_Cg_06_5:  @ LZ77
	.incbin "build/graphics/cg/cg_06_part_5.lz"

	.global Img_Cg_06_6
Img_Cg_06_6:  @ LZ77
	.incbin "build/graphics/cg/cg_06_part_6.lz"

	.global Img_Cg_06_7
Img_Cg_06_7:  @ LZ77
	.incbin "build/graphics/cg/cg_06_part_7.lz"

	.global Img_Cg_06_8
Img_Cg_06_8:  @ LZ77
	.incbin "build/graphics/cg/cg_06_part_8.lz"

	.global Img_Cg_06_9
Img_Cg_06_9:  @ LZ77
	.incbin "build/graphics/cg/cg_06_part_9.lz"

	.global Pal_Cg_06
Pal_Cg_06:
	.incbin "graphics/cg/cg_06_pal.gbapal"
	.incbin "baserom.gba", 0x45585c, 0x40

	.global gUnk_0845589C
gUnk_0845589C:
	.incbin "baserom.gba", 0x45589c, 0x2fc

	.global gUnk_08455B98
gUnk_08455B98:
	.incbin "baserom.gba", 0x455b98, 0x1b8

	.global Img_Cg_07_0
Img_Cg_07_0:  @ LZ77
	.incbin "build/graphics/cg/cg_07_part_0.lz"

	.global Img_Cg_07_1
Img_Cg_07_1:  @ LZ77
	.incbin "build/graphics/cg/cg_07_part_1.lz"

	.global Img_Cg_07_2
Img_Cg_07_2:  @ LZ77
	.incbin "build/graphics/cg/cg_07_part_2.lz"

	.global Img_Cg_07_3
Img_Cg_07_3:  @ LZ77
	.incbin "build/graphics/cg/cg_07_part_3.lz"

	.global Img_Cg_07_4
Img_Cg_07_4:  @ LZ77
	.incbin "build/graphics/cg/cg_07_part_4.lz"

	.global Img_Cg_07_5
Img_Cg_07_5:  @ LZ77
	.incbin "build/graphics/cg/cg_07_part_5.lz"

	.global Img_Cg_07_6
Img_Cg_07_6:  @ LZ77
	.incbin "build/graphics/cg/cg_07_part_6.lz"

	.global Img_Cg_07_7
Img_Cg_07_7:  @ LZ77
	.incbin "build/graphics/cg/cg_07_part_7.lz"

	.global Img_Cg_07_8
Img_Cg_07_8:  @ LZ77
	.incbin "build/graphics/cg/cg_07_part_8.lz"

	.global Img_Cg_07_9
Img_Cg_07_9:  @ LZ77
	.incbin "build/graphics/cg/cg_07_part_9.lz"

	.global Pal_Cg_07
Pal_Cg_07:
	.incbin "graphics/cg/cg_07_pal.gbapal"
	.incbin "baserom.gba", 0x45b074, 0x40

	.global gUnk_0845B0B4
gUnk_0845B0B4:
	.incbin "baserom.gba", 0x45b0b4, 0xfc

	.global gUnk_0845B1B0
gUnk_0845B1B0:
	.incbin "baserom.gba", 0x45b1b0, 0x3b8

	.global Img_Cg_08_0
Img_Cg_08_0:  @ LZ77
	.incbin "build/graphics/cg/cg_08_part_0.lz"

	.global Img_Cg_08_1
Img_Cg_08_1:  @ LZ77
	.incbin "build/graphics/cg/cg_08_part_1.lz"

	.global Img_Cg_08_2
Img_Cg_08_2:  @ LZ77
	.incbin "build/graphics/cg/cg_08_part_2.lz"

	.global Img_Cg_08_3
Img_Cg_08_3:  @ LZ77
	.incbin "build/graphics/cg/cg_08_part_3.lz"

	.global Img_Cg_08_4
Img_Cg_08_4:  @ LZ77
	.incbin "build/graphics/cg/cg_08_part_4.lz"

	.global Img_Cg_08_5
Img_Cg_08_5:  @ LZ77
	.incbin "build/graphics/cg/cg_08_part_5.lz"

	.global Img_Cg_08_6
Img_Cg_08_6:  @ LZ77
	.incbin "build/graphics/cg/cg_08_part_6.lz"

	.global Img_Cg_08_7
Img_Cg_08_7:  @ LZ77
	.incbin "build/graphics/cg/cg_08_part_7.lz"

	.global Img_Cg_08_8
Img_Cg_08_8:  @ LZ77
	.incbin "build/graphics/cg/cg_08_part_8.lz"

	.global Img_Cg_08_9
Img_Cg_08_9:  @ LZ77
	.incbin "build/graphics/cg/cg_08_part_9.lz"

	.global Pal_Cg_08
Pal_Cg_08:
	.incbin "graphics/cg/cg_08_pal.gbapal"
	.incbin "baserom.gba", 0x460828, 0x2c

	.global gUnk_08460854
gUnk_08460854:
	.incbin "baserom.gba", 0x460854, 0x14

	.global gUnk_08460868
gUnk_08460868:
	.incbin "baserom.gba", 0x460868, 0x7c

	.global gUnk_084608E4
gUnk_084608E4:
	.incbin "baserom.gba", 0x4608e4, 0x438

	.global Img_Cg_09_0
Img_Cg_09_0:  @ LZ77
	.incbin "build/graphics/cg/cg_09_part_0.lz"
