@ ROM data 0x08e54bf4-0x08e946f8 (not yet in source)
@ Generated by tools/datasplit.py: labels, incbin and .4byte pointers.
@ Labels may be renamed here; rerun the tool then (it rewrites the
@ .4byte references) and after changing data/layout.txt.

	.section .rodata.08E54BF4, "a"

	.global gUnk_08E54BF4
gUnk_08E54BF4:  @ LZ77
	.incbin "build/graphics/gUnk_08E54BF4.lz"

	.global gUnk_08E55B68
gUnk_08E55B68:  @ LZ77
	.incbin "build/graphics/gUnk_08E55B68.lz"

	.global gUnk_08E55BBC
gUnk_08E55BBC:  @ LZ77
	.incbin "build/graphics/gUnk_08E55BBC.lz"

	.global gUnk_08E55EF4
gUnk_08E55EF4:  @ LZ77
	.incbin "build/graphics/gUnk_08E55EF4.lz"

	.global gUnk_08E56228
gUnk_08E56228:  @ LZ77
	.incbin "build/graphics/gUnk_08E56228.lz"

	.global gUnk_08E56370
gUnk_08E56370:
	.incbin "baserom.gba", 0xe56370, 0x60

	.global gUnk_08E563D0
gUnk_08E563D0:  @ LZ77
	.incbin "build/graphics/gUnk_08E563D0.lz"

	.global gUnk_08E56424
gUnk_08E56424:  @ LZ77
	.incbin "build/graphics/gUnk_08E56424.lz"

	.global gUnk_08E566AC
gUnk_08E566AC:  @ LZ77
	.incbin "build/graphics/gUnk_08E566AC.lz"

	.global gUnk_08E56934
gUnk_08E56934:  @ LZ77
	.incbin "build/graphics/gUnk_08E56934.lz"

	.global gUnk_08E56A34
gUnk_08E56A34:
	.incbin "baserom.gba", 0xe56a34, 0x60

	.global gUnk_08E56A94
gUnk_08E56A94:  @ LZ77
	.incbin "build/graphics/gUnk_08E56A94.lz"

	.global gUnk_08E56AE8
gUnk_08E56AE8:  @ LZ77
	.incbin "build/graphics/gUnk_08E56AE8.lz"

	.global gUnk_08E56B98
gUnk_08E56B98:  @ LZ77
	.incbin "build/graphics/gUnk_08E56B98.lz"

	.global gUnk_08E56C48
gUnk_08E56C48:  @ LZ77
	.incbin "build/graphics/gUnk_08E56C48.lz"

	.global gUnk_08E56CCC
gUnk_08E56CCC:
	.incbin "baserom.gba", 0xe56ccc, 0x60

	.global gUnk_08E56D2C
gUnk_08E56D2C:  @ LZ77
	.incbin "build/graphics/gUnk_08E56D2C.lz"

	.global gUnk_08E57F58
gUnk_08E57F58:  @ LZ77
	.incbin "build/graphics/gUnk_08E57F58.lz"

	.global gUnk_08E58EB4
gUnk_08E58EB4:  @ LZ77
	.incbin "build/graphics/gUnk_08E58EB4.lz"

	.global gUnk_08E5A2C8
gUnk_08E5A2C8:  @ LZ77
	.incbin "build/graphics/gUnk_08E5A2C8.lz"

	.global gUnk_08E5B4D4
gUnk_08E5B4D4:  @ LZ77
	.incbin "build/graphics/gUnk_08E5B4D4.lz"

	.global gUnk_08E5B520
gUnk_08E5B520:  @ LZ77
	.incbin "build/graphics/gUnk_08E5B520.lz"

	.global gUnk_08E5BDB4
gUnk_08E5BDB4:  @ LZ77
	.incbin "build/graphics/gUnk_08E5BDB4.lz"

	.global gUnk_08E5C63C
gUnk_08E5C63C:  @ LZ77
	.incbin "build/graphics/gUnk_08E5C63C.lz"

	.global gUnk_08E5C8CC
gUnk_08E5C8CC:
	.incbin "baserom.gba", 0xe5c8cc, 0x60

	.global gUnk_08E5C92C
gUnk_08E5C92C:  @ LZ77
	.incbin "build/graphics/gUnk_08E5C92C.lz"

	.global gUnk_08E5C978
gUnk_08E5C978:  @ LZ77
	.incbin "build/graphics/gUnk_08E5C978.lz"

	.global gUnk_08E5CBF0
gUnk_08E5CBF0:  @ LZ77
	.incbin "build/graphics/gUnk_08E5CBF0.lz"

	.global gUnk_08E5CE60
gUnk_08E5CE60:  @ LZ77
	.incbin "build/graphics/gUnk_08E5CE60.lz"

	.global gUnk_08E5CF7C
gUnk_08E5CF7C:
	.incbin "baserom.gba", 0xe5cf7c, 0x60

	.global gUnk_08E5CFDC
gUnk_08E5CFDC:  @ LZ77
	.incbin "build/graphics/gUnk_08E5CFDC.lz"

	.global gUnk_08E5D028
gUnk_08E5D028:  @ LZ77
	.incbin "build/graphics/gUnk_08E5D028.lz"

	.global gUnk_08E5D130
gUnk_08E5D130:  @ LZ77
	.incbin "build/graphics/gUnk_08E5D130.lz"

	.global gUnk_08E5D234
gUnk_08E5D234:  @ LZ77
	.incbin "build/graphics/gUnk_08E5D234.lz"

	.global gUnk_08E5D2BC
gUnk_08E5D2BC:
	.incbin "baserom.gba", 0xe5d2bc, 0x60

	.global gUnk_08E5D31C
gUnk_08E5D31C:  @ LZ77
	.incbin "build/graphics/gUnk_08E5D31C.lz"

	.global gUnk_08E5E5A4
gUnk_08E5E5A4:  @ LZ77
	.incbin "build/graphics/gUnk_08E5E5A4.lz"

	.global gUnk_08E5F554
gUnk_08E5F554:  @ LZ77
	.incbin "build/graphics/gUnk_08E5F554.lz"

	.global gUnk_08E60724
gUnk_08E60724:  @ LZ77
	.incbin "build/graphics/gUnk_08E60724.lz"

	.global gUnk_08E61810
gUnk_08E61810:  @ LZ77
	.incbin "build/graphics/gUnk_08E61810.lz"

	.global gUnk_08E6185C
gUnk_08E6185C:  @ LZ77
	.incbin "build/graphics/gUnk_08E6185C.lz"

	.global gUnk_08E621C8
gUnk_08E621C8:  @ LZ77
	.incbin "build/graphics/gUnk_08E621C8.lz"

	.global gUnk_08E62B30
gUnk_08E62B30:  @ LZ77
	.incbin "build/graphics/gUnk_08E62B30.lz"

	.global gUnk_08E62DCC
gUnk_08E62DCC:
	.incbin "baserom.gba", 0xe62dcc, 0x60

	.global gUnk_08E62E2C
gUnk_08E62E2C:  @ LZ77
	.incbin "build/graphics/gUnk_08E62E2C.lz"

	.global gUnk_08E62E78
gUnk_08E62E78:  @ LZ77
	.incbin "build/graphics/gUnk_08E62E78.lz"

	.global gUnk_08E63144
gUnk_08E63144:  @ LZ77
	.incbin "build/graphics/gUnk_08E63144.lz"

	.global gUnk_08E63414
gUnk_08E63414:  @ LZ77
	.incbin "build/graphics/gUnk_08E63414.lz"

	.global gUnk_08E6353C
gUnk_08E6353C:
	.incbin "baserom.gba", 0xe6353c, 0x60

	.global gUnk_08E6359C
gUnk_08E6359C:  @ LZ77
	.incbin "build/graphics/gUnk_08E6359C.lz"

	.global gUnk_08E635E8
gUnk_08E635E8:  @ LZ77
	.incbin "build/graphics/gUnk_08E635E8.lz"

	.global gUnk_08E636B4
gUnk_08E636B4:  @ LZ77
	.incbin "build/graphics/gUnk_08E636B4.lz"

	.global gUnk_08E63778
gUnk_08E63778:  @ LZ77
	.incbin "build/graphics/gUnk_08E63778.lz"

	.global gUnk_08E637CC
gUnk_08E637CC:
	.incbin "baserom.gba", 0xe637cc, 0x60

	.global gUnk_08E6382C
gUnk_08E6382C:  @ LZ77
	.incbin "build/graphics/gUnk_08E6382C.lz"

	.global gUnk_08E647E8
gUnk_08E647E8:  @ LZ77
	.incbin "build/graphics/gUnk_08E647E8.lz"

	.global gUnk_08E658F0
gUnk_08E658F0:  @ LZ77
	.incbin "build/graphics/gUnk_08E658F0.lz"

	.global gUnk_08E665E0
gUnk_08E665E0:  @ LZ77
	.incbin "build/graphics/gUnk_08E665E0.lz"

	.global gUnk_08E67484
gUnk_08E67484:  @ LZ77
	.incbin "build/graphics/gUnk_08E67484.lz"

	.global gUnk_08E685C4
gUnk_08E685C4:  @ LZ77
	.incbin "build/graphics/gUnk_08E685C4.lz"

	.global gUnk_08E695EC
gUnk_08E695EC:  @ LZ77
	.incbin "build/graphics/gUnk_08E695EC.lz"

	.global gUnk_08E6A564
gUnk_08E6A564:  @ LZ77
	.incbin "build/graphics/gUnk_08E6A564.lz"

	.global gUnk_08E6B45C
gUnk_08E6B45C:  @ LZ77
	.incbin "build/graphics/gUnk_08E6B45C.lz"

	.global gUnk_08E6B4A8
gUnk_08E6B4A8:  @ LZ77
	.incbin "build/graphics/gUnk_08E6B4A8.lz"

	.global gUnk_08E6C29C
gUnk_08E6C29C:  @ LZ77
	.incbin "build/graphics/gUnk_08E6C29C.lz"

	.global gUnk_08E6D0A8
gUnk_08E6D0A8:  @ LZ77
	.incbin "build/graphics/gUnk_08E6D0A8.lz"

	.global gUnk_08E6D4A0
gUnk_08E6D4A0:
	.incbin "baserom.gba", 0xe6d4a0, 0x60

	.global gUnk_08E6D500
gUnk_08E6D500:  @ LZ77
	.incbin "build/graphics/gUnk_08E6D500.lz"

	.global gUnk_08E6D54C
gUnk_08E6D54C:  @ LZ77
	.incbin "build/graphics/gUnk_08E6D54C.lz"

	.global gUnk_08E6E040
gUnk_08E6E040:  @ LZ77
	.incbin "build/graphics/gUnk_08E6E040.lz"

	.global gUnk_08E6EB4C
gUnk_08E6EB4C:  @ LZ77
	.incbin "build/graphics/gUnk_08E6EB4C.lz"

	.global gUnk_08E6ED2C
gUnk_08E6ED2C:
	.incbin "baserom.gba", 0xe6ed2c, 0x60

	.global gUnk_08E6ED8C
gUnk_08E6ED8C:  @ LZ77
	.incbin "build/graphics/gUnk_08E6ED8C.lz"

	.global gUnk_08E6FEE8
gUnk_08E6FEE8:  @ LZ77
	.incbin "build/graphics/gUnk_08E6FEE8.lz"

	.global gUnk_08E709D8
gUnk_08E709D8:  @ LZ77
	.incbin "build/graphics/gUnk_08E709D8.lz"

	.global gUnk_08E71534
gUnk_08E71534:  @ LZ77
	.incbin "build/graphics/gUnk_08E71534.lz"

	.global gUnk_08E71FAC
gUnk_08E71FAC:  @ LZ77
	.incbin "build/graphics/gUnk_08E71FAC.lz"

	.global gUnk_08E71FF8
gUnk_08E71FF8:  @ LZ77
	.incbin "build/graphics/gUnk_08E71FF8.lz"

	.global gUnk_08E724FC
gUnk_08E724FC:  @ LZ77
	.incbin "build/graphics/gUnk_08E724FC.lz"

	.global gUnk_08E729E8
gUnk_08E729E8:  @ LZ77
	.incbin "build/graphics/gUnk_08E729E8.lz"

	.global gUnk_08E72BC8
gUnk_08E72BC8:
	.incbin "baserom.gba", 0xe72bc8, 0x60

	.global gUnk_08E72C28
gUnk_08E72C28:  @ LZ77
	.incbin "build/graphics/gUnk_08E72C28.lz"

	.global gUnk_08E72C74
gUnk_08E72C74:  @ LZ77
	.incbin "build/graphics/gUnk_08E72C74.lz"

	.global gUnk_08E72D0C
gUnk_08E72D0C:  @ LZ77
	.incbin "build/graphics/gUnk_08E72D0C.lz"

	.global gUnk_08E72DA0
gUnk_08E72DA0:  @ LZ77
	.incbin "build/graphics/gUnk_08E72DA0.lz"

	.global gUnk_08E72E18
gUnk_08E72E18:
	.incbin "baserom.gba", 0xe72e18, 0x58

	.global gUnk_08E72E70
gUnk_08E72E70:  @ LZ77
	.incbin "build/graphics/gUnk_08E72E70.lz"

	.global gUnk_08E73B88
gUnk_08E73B88:  @ LZ77
	.incbin "build/graphics/gUnk_08E73B88.lz"

	.global gUnk_08E74724
gUnk_08E74724:  @ LZ77
	.incbin "build/graphics/gUnk_08E74724.lz"

	.global gUnk_08E74CFC
gUnk_08E74CFC:  @ LZ77
	.incbin "build/graphics/gUnk_08E74CFC.lz"

	.global gUnk_08E74D64
gUnk_08E74D64:  @ LZ77
	.incbin "build/graphics/gUnk_08E74D64.lz"

	.global gUnk_08E751D8
gUnk_08E751D8:  @ LZ77
	.incbin "build/graphics/gUnk_08E751D8.lz"

	.global gUnk_08E75654
gUnk_08E75654:  @ LZ77
	.incbin "build/graphics/gUnk_08E75654.lz"

	.global gUnk_08E75834
gUnk_08E75834:
	.incbin "baserom.gba", 0xe75834, 0x60

	.global gUnk_08E75894
gUnk_08E75894:  @ LZ77
	.incbin "build/graphics/gUnk_08E75894.lz"

	.global gUnk_08E758FC
gUnk_08E758FC:  @ LZ77
	.incbin "build/graphics/gUnk_08E758FC.lz"

	.global gUnk_08E759C8
gUnk_08E759C8:  @ LZ77
	.incbin "build/graphics/gUnk_08E759C8.lz"

	.global gUnk_08E75A90
gUnk_08E75A90:  @ LZ77
	.incbin "build/graphics/gUnk_08E75A90.lz"

	.global gUnk_08E75AE8
gUnk_08E75AE8:
	.incbin "baserom.gba", 0xe75ae8, 0x60

	.global gUnk_08E75B48
gUnk_08E75B48:  @ LZ77
	.incbin "build/graphics/gUnk_08E75B48.lz"

	.global gUnk_08E767B8
gUnk_08E767B8:  @ LZ77
	.incbin "build/graphics/gUnk_08E767B8.lz"

	.global gUnk_08E77328
gUnk_08E77328:  @ LZ77
	.incbin "build/graphics/gUnk_08E77328.lz"

	.global gUnk_08E778EC
gUnk_08E778EC:  @ LZ77
	.incbin "build/graphics/gUnk_08E778EC.lz"

	.global gUnk_08E77954
gUnk_08E77954:  @ LZ77
	.incbin "build/graphics/gUnk_08E77954.lz"

	.global gUnk_08E77DC8
gUnk_08E77DC8:  @ LZ77
	.incbin "build/graphics/gUnk_08E77DC8.lz"

	.global gUnk_08E78244
gUnk_08E78244:  @ LZ77
	.incbin "build/graphics/gUnk_08E78244.lz"

	.global gUnk_08E78424
gUnk_08E78424:
	.incbin "baserom.gba", 0xe78424, 0x60

	.global gUnk_08E78484
gUnk_08E78484:  @ LZ77
	.incbin "build/graphics/gUnk_08E78484.lz"

	.global gUnk_08E784EC
gUnk_08E784EC:  @ LZ77
	.incbin "build/graphics/gUnk_08E784EC.lz"

	.global gUnk_08E785B8
gUnk_08E785B8:  @ LZ77
	.incbin "build/graphics/gUnk_08E785B8.lz"

	.global gUnk_08E78680
gUnk_08E78680:  @ LZ77
	.incbin "build/graphics/gUnk_08E78680.lz"

	.global gUnk_08E786D8
gUnk_08E786D8:
	.incbin "baserom.gba", 0xe786d8, 0x60

	.global gUnk_08E78738
gUnk_08E78738:  @ LZ77
	.incbin "build/graphics/gUnk_08E78738.lz"

	.global gUnk_08E79374
gUnk_08E79374:  @ LZ77
	.incbin "build/graphics/gUnk_08E79374.lz"

	.global gUnk_08E79E28
gUnk_08E79E28:  @ LZ77
	.incbin "build/graphics/gUnk_08E79E28.lz"

	.global gUnk_08E7A5D0
gUnk_08E7A5D0:  @ LZ77
	.incbin "build/graphics/gUnk_08E7A5D0.lz"

	.global gUnk_08E7A638
gUnk_08E7A638:  @ LZ77
	.incbin "build/graphics/gUnk_08E7A638.lz"

	.global gUnk_08E7AAD8
gUnk_08E7AAD8:  @ LZ77
	.incbin "build/graphics/gUnk_08E7AAD8.lz"

	.global gUnk_08E7AF78
gUnk_08E7AF78:  @ LZ77
	.incbin "build/graphics/gUnk_08E7AF78.lz"

	.global gUnk_08E7B15C
gUnk_08E7B15C:
	.incbin "baserom.gba", 0xe7b15c, 0x60

	.global gUnk_08E7B1BC
gUnk_08E7B1BC:  @ LZ77
	.incbin "build/graphics/gUnk_08E7B1BC.lz"

	.global gUnk_08E7B224
gUnk_08E7B224:  @ LZ77
	.incbin "build/graphics/gUnk_08E7B224.lz"

	.global gUnk_08E7B2D0
gUnk_08E7B2D0:  @ LZ77
	.incbin "build/graphics/gUnk_08E7B2D0.lz"

	.global gUnk_08E7B378
gUnk_08E7B378:  @ LZ77
	.incbin "build/graphics/gUnk_08E7B378.lz"

	.global gUnk_08E7B3D0
gUnk_08E7B3D0:
	.incbin "baserom.gba", 0xe7b3d0, 0x60

	.global gUnk_08E7B430
gUnk_08E7B430:  @ LZ77
	.incbin "build/graphics/gUnk_08E7B430.lz"

	.global gUnk_08E7BF4C
gUnk_08E7BF4C:  @ LZ77
	.incbin "build/graphics/gUnk_08E7BF4C.lz"

	.global gUnk_08E7C998
gUnk_08E7C998:  @ LZ77
	.incbin "build/graphics/gUnk_08E7C998.lz"

	.global gUnk_08E7D0FC
gUnk_08E7D0FC:  @ LZ77
	.incbin "build/graphics/gUnk_08E7D0FC.lz"

	.global gUnk_08E7D164
gUnk_08E7D164:  @ LZ77
	.incbin "build/graphics/gUnk_08E7D164.lz"

	.global gUnk_08E7D604
gUnk_08E7D604:  @ LZ77
	.incbin "build/graphics/gUnk_08E7D604.lz"

	.global gUnk_08E7DAA4
gUnk_08E7DAA4:  @ LZ77
	.incbin "build/graphics/gUnk_08E7DAA4.lz"

	.global gUnk_08E7DC88
gUnk_08E7DC88:
	.incbin "baserom.gba", 0xe7dc88, 0x60

	.global gUnk_08E7DCE8
gUnk_08E7DCE8:  @ LZ77
	.incbin "build/graphics/gUnk_08E7DCE8.lz"

	.global gUnk_08E7DD50
gUnk_08E7DD50:  @ LZ77
	.incbin "build/graphics/gUnk_08E7DD50.lz"

	.global gUnk_08E7DDFC
gUnk_08E7DDFC:  @ LZ77
	.incbin "build/graphics/gUnk_08E7DDFC.lz"

	.global gUnk_08E7DEA4
gUnk_08E7DEA4:  @ LZ77
	.incbin "build/graphics/gUnk_08E7DEA4.lz"

	.global gUnk_08E7DEFC
gUnk_08E7DEFC:
	.incbin "baserom.gba", 0xe7defc, 0x60

	.global gUnk_08E7DF5C
gUnk_08E7DF5C:  @ LZ77
	.incbin "build/graphics/gUnk_08E7DF5C.lz"

	.global gUnk_08E7F22C
gUnk_08E7F22C:  @ LZ77
	.incbin "build/graphics/gUnk_08E7F22C.lz"

	.global gUnk_08E80474
gUnk_08E80474:  @ LZ77
	.incbin "build/graphics/gUnk_08E80474.lz"
	.incbin "baserom.gba", 0xe8162c, 0x3d0

	.global gUnk_08E819FC
gUnk_08E819FC:  @ LZ77
	.incbin "build/graphics/gUnk_08E819FC.lz"

	.global gUnk_08E81A58
gUnk_08E81A58:  @ LZ77
	.incbin "build/graphics/gUnk_08E81A58.lz"

	.global gUnk_08E828A0
gUnk_08E828A0:  @ LZ77
	.incbin "build/graphics/gUnk_08E828A0.lz"

	.global gUnk_08E836C8
gUnk_08E836C8:  @ LZ77
	.incbin "build/graphics/gUnk_08E836C8.lz"

	.global gUnk_08E83B5C
gUnk_08E83B5C:
	.incbin "baserom.gba", 0xe83b5c, 0x60

	.global gUnk_08E83BBC
gUnk_08E83BBC:  @ LZ77
	.incbin "build/graphics/gUnk_08E83BBC.lz"

	.global gUnk_08E83C18
gUnk_08E83C18:  @ LZ77
	.incbin "build/graphics/gUnk_08E83C18.lz"

	.global gUnk_08E83CC4
gUnk_08E83CC4:  @ LZ77
	.incbin "build/graphics/gUnk_08E83CC4.lz"

	.global gUnk_08E83D74
gUnk_08E83D74:  @ LZ77
	.incbin "build/graphics/gUnk_08E83D74.lz"

	.global gUnk_08E83DF8
gUnk_08E83DF8:
	.incbin "baserom.gba", 0xe83df8, 0x60

	.global gUnk_08E83E58
gUnk_08E83E58:  @ LZ77
	.incbin "build/graphics/gUnk_08E83E58.lz"

	.global gUnk_08E84E5C
gUnk_08E84E5C:  @ LZ77
	.incbin "build/graphics/gUnk_08E84E5C.lz"

	.global gUnk_08E85F28
gUnk_08E85F28:  @ LZ77
	.incbin "build/graphics/gUnk_08E85F28.lz"

	.global gUnk_08E87188
gUnk_08E87188:  @ LZ77
	.incbin "build/graphics/gUnk_08E87188.lz"

	.global gUnk_08E880CC
gUnk_08E880CC:  @ LZ77
	.incbin "build/graphics/gUnk_08E880CC.lz"

	.global gUnk_08E88118
gUnk_08E88118:  @ LZ77
	.incbin "build/graphics/gUnk_08E88118.lz"

	.global gUnk_08E896E0
gUnk_08E896E0:  @ LZ77
	.incbin "build/graphics/gUnk_08E896E0.lz"

	.global gUnk_08E8ACA0
gUnk_08E8ACA0:  @ LZ77
	.incbin "build/graphics/gUnk_08E8ACA0.lz"

	.global gUnk_08E8B398
gUnk_08E8B398:
	.incbin "baserom.gba", 0xe8b398, 0x60

	.global gUnk_08E8B3F8
gUnk_08E8B3F8:  @ LZ77
	.incbin "build/graphics/gUnk_08E8B3F8.lz"

	.global gUnk_08E8B444
gUnk_08E8B444:  @ LZ77
	.incbin "build/graphics/gUnk_08E8B444.lz"

	.global gUnk_08E8CB0C
gUnk_08E8CB0C:  @ LZ77
	.incbin "build/graphics/gUnk_08E8CB0C.lz"

	.global gUnk_08E8E1D0
gUnk_08E8E1D0:  @ LZ77
	.incbin "build/graphics/gUnk_08E8E1D0.lz"

	.global gUnk_08E8E8B8
gUnk_08E8E8B8:
	.incbin "baserom.gba", 0xe8e8b8, 0x60

	.global gUnk_08E8E918
gUnk_08E8E918:  @ LZ77
	.incbin "build/graphics/gUnk_08E8E918.lz"

	.global gUnk_08E8F344
gUnk_08E8F344:  @ LZ77
	.incbin "build/graphics/gUnk_08E8F344.lz"

	.global gUnk_08E8F390
gUnk_08E8F390:  @ LZ77
	.incbin "build/graphics/gUnk_08E8F390.lz"

	.global gUnk_08E8F5EC
gUnk_08E8F5EC:  @ LZ77
	.incbin "build/graphics/gUnk_08E8F5EC.lz"

	.global gUnk_08E8F83C
gUnk_08E8F83C:  @ LZ77
	.incbin "build/graphics/gUnk_08E8F83C.lz"

	.global gUnk_08E8F984
gUnk_08E8F984:
	.incbin "baserom.gba", 0xe8f984, 0x60

	.global gUnk_08E8F9E4
gUnk_08E8F9E4:  @ LZ77
	.incbin "build/graphics/gUnk_08E8F9E4.lz"

	.global gUnk_08E8FA30
gUnk_08E8FA30:  @ LZ77
	.incbin "build/graphics/gUnk_08E8FA30.lz"

	.global gUnk_08E8FB10
gUnk_08E8FB10:  @ LZ77
	.incbin "build/graphics/gUnk_08E8FB10.lz"

	.global gUnk_08E8FBEC
gUnk_08E8FBEC:  @ LZ77
	.incbin "build/graphics/gUnk_08E8FBEC.lz"

	.global gUnk_08E8FC74
gUnk_08E8FC74:
	.incbin "baserom.gba", 0xe8fc74, 0x60

	.global gUnk_08E8FCD4
gUnk_08E8FCD4:  @ LZ77
	.incbin "build/graphics/gUnk_08E8FCD4.lz"

	.global gUnk_08E90D78
gUnk_08E90D78:  @ LZ77
	.incbin "build/graphics/gUnk_08E90D78.lz"

	.global gUnk_08E91E90
gUnk_08E91E90:  @ LZ77
	.incbin "build/graphics/gUnk_08E91E90.lz"

	.global gUnk_08E92E50
gUnk_08E92E50:  @ LZ77
	.incbin "build/graphics/gUnk_08E92E50.lz"

	.global gUnk_08E93AAC
gUnk_08E93AAC:  @ LZ77
	.incbin "build/graphics/gUnk_08E93AAC.lz"

	.global gUnk_08E93B14
gUnk_08E93B14:  @ LZ77
	.incbin "build/graphics/gUnk_08E93B14.lz"
