@ ROM data 0x08e959b0-0x08ed2e88 (not yet in source)
@ Generated by tools/datasplit.py: labels, incbin and .4byte pointers.
@ Labels may be renamed here; rerun the tool then (it rewrites the
@ .4byte references) and after changing data/layout.txt.

	.section .rodata.08E959B0, "a"

	.global Img_Banim_035_swmm_sw1_Sheet0
	.global Img_Banim_035_swmm_sw1_Sheet0
Img_Banim_035_swmm_sw1_Sheet0:  @ LZ77
Img_Banim_035_swmm_sw1_Sheet0:  @ LZ77
	.incbin "build/graphics/banim/035_swmm_sw1/sheet_0.lz"

	.global Img_Banim_035_swmm_sw1_Sheet1
	.global Img_Banim_035_swmm_sw1_Sheet1
Img_Banim_035_swmm_sw1_Sheet1:  @ LZ77
Img_Banim_035_swmm_sw1_Sheet1:  @ LZ77
	.incbin "build/graphics/banim/035_swmm_sw1/sheet_1.lz"

	.global Img_Banim_035_swmm_sw1_Sheet2
	.global Img_Banim_035_swmm_sw1_Sheet2
Img_Banim_035_swmm_sw1_Sheet2:  @ LZ77
Img_Banim_035_swmm_sw1_Sheet2:  @ LZ77
	.incbin "build/graphics/banim/035_swmm_sw1/sheet_2.lz"

	.global Img_Banim_035_swmm_sw1_Sheet3
	.global Img_Banim_035_swmm_sw1_Sheet3
Img_Banim_035_swmm_sw1_Sheet3:  @ LZ77
Img_Banim_035_swmm_sw1_Sheet3:  @ LZ77
	.incbin "build/graphics/banim/035_swmm_sw1/sheet_3.lz"

	.global Pal_Banim_035_swmm_sw1
	.global Pal_Banim_035_swmm_sw1
Pal_Banim_035_swmm_sw1:  @ LZ77
Pal_Banim_035_swmm_sw1:  @ LZ77
	.incbin "build/graphics/banim/035_swmm_sw1/pal.lz"

	.global BanimOam_035_swmm_sw1_L
	.global BanimOam_035_swmm_sw1_L
BanimOam_035_swmm_sw1_L:  @ LZ77
BanimOam_035_swmm_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/035_swmm_sw1/oam_l.lz"

	.global BanimOam_035_swmm_sw1_R
	.global BanimOam_035_swmm_sw1_R
BanimOam_035_swmm_sw1_R:  @ LZ77
BanimOam_035_swmm_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/035_swmm_sw1/oam_r.lz"

	.section .rodata.08E9B190, "a"

	.global Pal_Banim_036_swmm_sw1
	.global Pal_Banim_036_swmm_sw1
Pal_Banim_036_swmm_sw1:  @ LZ77
Pal_Banim_036_swmm_sw1:  @ LZ77
	.incbin "build/graphics/banim/036_swmm_sw1/pal.lz"

	.global BanimOam_036_swmm_sw1_L
	.global BanimOam_036_swmm_sw1_L
BanimOam_036_swmm_sw1_L:  @ LZ77
BanimOam_036_swmm_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/036_swmm_sw1/oam_l.lz"

	.global BanimOam_036_swmm_sw1_R
	.global BanimOam_036_swmm_sw1_R
BanimOam_036_swmm_sw1_R:  @ LZ77
BanimOam_036_swmm_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/036_swmm_sw1/oam_r.lz"

	.section .rodata.08E9B35C, "a"

	.global Img_Banim_037_swlm_sw1_Sheet0
	.global Img_Banim_037_swlm_sw1_Sheet0
Img_Banim_037_swlm_sw1_Sheet0:  @ LZ77
Img_Banim_037_swlm_sw1_Sheet0:  @ LZ77
	.incbin "build/graphics/banim/037_swlm_sw1/sheet_0.lz"

	.global Img_Banim_037_swlm_sw1_Sheet1
	.global Img_Banim_037_swlm_sw1_Sheet1
Img_Banim_037_swlm_sw1_Sheet1:  @ LZ77
Img_Banim_037_swlm_sw1_Sheet1:  @ LZ77
	.incbin "build/graphics/banim/037_swlm_sw1/sheet_1.lz"

	.global Img_Banim_037_swlm_sw1_Sheet2
	.global Img_Banim_037_swlm_sw1_Sheet2
Img_Banim_037_swlm_sw1_Sheet2:  @ LZ77
Img_Banim_037_swlm_sw1_Sheet2:  @ LZ77
	.incbin "build/graphics/banim/037_swlm_sw1/sheet_2.lz"

	.global Img_Banim_037_swlm_sw1_Sheet3
	.global Img_Banim_037_swlm_sw1_Sheet3
Img_Banim_037_swlm_sw1_Sheet3:  @ LZ77
Img_Banim_037_swlm_sw1_Sheet3:  @ LZ77
	.incbin "build/graphics/banim/037_swlm_sw1/sheet_3.lz"

	.global Pal_Banim_037_swlm_sw1
	.global Pal_Banim_037_swlm_sw1
Pal_Banim_037_swlm_sw1:  @ LZ77
Pal_Banim_037_swlm_sw1:  @ LZ77
	.incbin "build/graphics/banim/037_swlm_sw1/pal.lz"

	.global BanimOam_037_swlm_sw1_L
	.global BanimOam_037_swlm_sw1_L
BanimOam_037_swlm_sw1_L:  @ LZ77
BanimOam_037_swlm_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/037_swlm_sw1/oam_l.lz"

	.global BanimOam_037_swlm_sw1_R
	.global BanimOam_037_swlm_sw1_R
BanimOam_037_swlm_sw1_R:  @ LZ77
BanimOam_037_swlm_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/037_swlm_sw1/oam_r.lz"

	.section .rodata.08EA091C, "a"

	.global Pal_Banim_038_swlm_sw1
	.global Pal_Banim_038_swlm_sw1
Pal_Banim_038_swlm_sw1:  @ LZ77
Pal_Banim_038_swlm_sw1:  @ LZ77
	.incbin "build/graphics/banim/038_swlm_sw1/pal.lz"

	.global BanimOam_038_swlm_sw1_L
	.global BanimOam_038_swlm_sw1_L
BanimOam_038_swlm_sw1_L:  @ LZ77
BanimOam_038_swlm_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/038_swlm_sw1/oam_l.lz"

	.global BanimOam_038_swlm_sw1_R
	.global BanimOam_038_swlm_sw1_R
BanimOam_038_swlm_sw1_R:  @ LZ77
BanimOam_038_swlm_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/038_swlm_sw1/oam_r.lz"

	.section .rodata.08EA0ADC, "a"

	.global Img_Banim_039_swmf_sw1_Sheet0
	.global Img_Banim_039_swmf_sw1_Sheet0
Img_Banim_039_swmf_sw1_Sheet0:  @ LZ77
Img_Banim_039_swmf_sw1_Sheet0:  @ LZ77
	.incbin "build/graphics/banim/039_swmf_sw1/sheet_0.lz"

	.global Img_Banim_039_swmf_sw1_Sheet1
	.global Img_Banim_039_swmf_sw1_Sheet1
Img_Banim_039_swmf_sw1_Sheet1:  @ LZ77
Img_Banim_039_swmf_sw1_Sheet1:  @ LZ77
	.incbin "build/graphics/banim/039_swmf_sw1/sheet_1.lz"

	.global Img_Banim_039_swmf_sw1_Sheet2
	.global Img_Banim_039_swmf_sw1_Sheet2
Img_Banim_039_swmf_sw1_Sheet2:  @ LZ77
Img_Banim_039_swmf_sw1_Sheet2:  @ LZ77
	.incbin "build/graphics/banim/039_swmf_sw1/sheet_2.lz"

	.global Img_Banim_039_swmf_sw1_Sheet3
	.global Img_Banim_039_swmf_sw1_Sheet3
Img_Banim_039_swmf_sw1_Sheet3:  @ LZ77
Img_Banim_039_swmf_sw1_Sheet3:  @ LZ77
	.incbin "build/graphics/banim/039_swmf_sw1/sheet_3.lz"

	.global Pal_Banim_039_swmf_sw1
	.global Pal_Banim_039_swmf_sw1
Pal_Banim_039_swmf_sw1:  @ LZ77
Pal_Banim_039_swmf_sw1:  @ LZ77
	.incbin "build/graphics/banim/039_swmf_sw1/pal.lz"

	.global BanimOam_039_swmf_sw1_L
	.global BanimOam_039_swmf_sw1_L
BanimOam_039_swmf_sw1_L:  @ LZ77
BanimOam_039_swmf_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/039_swmf_sw1/oam_l.lz"

	.global BanimOam_039_swmf_sw1_R
	.global BanimOam_039_swmf_sw1_R
BanimOam_039_swmf_sw1_R:  @ LZ77
BanimOam_039_swmf_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/039_swmf_sw1/oam_r.lz"

	.section .rodata.08EA6240, "a"

	.global Pal_Banim_03A_swmf_sw1
	.global Pal_Banim_03A_swmf_sw1
Pal_Banim_03A_swmf_sw1:  @ LZ77
Pal_Banim_03A_swmf_sw1:  @ LZ77
	.incbin "build/graphics/banim/03A_swmf_sw1/pal.lz"

	.global BanimOam_03A_swmf_sw1_L
	.global BanimOam_03A_swmf_sw1_L
BanimOam_03A_swmf_sw1_L:  @ LZ77
BanimOam_03A_swmf_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/03A_swmf_sw1/oam_l.lz"

	.global BanimOam_03A_swmf_sw1_R
	.global BanimOam_03A_swmf_sw1_R
BanimOam_03A_swmf_sw1_R:  @ LZ77
BanimOam_03A_swmf_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/03A_swmf_sw1/oam_r.lz"

	.section .rodata.08EA640C, "a"

	.global Img_Banim_03B_sokm_sp1_Sheet0
	.global Img_Banim_03B_sokm_sp1_Sheet0
Img_Banim_03B_sokm_sp1_Sheet0:  @ LZ77
Img_Banim_03B_sokm_sp1_Sheet0:  @ LZ77
	.incbin "build/graphics/banim/03B_sokm_sp1/sheet_0.lz"

	.global Img_Banim_03B_sokm_sp1_Sheet1
	.global Img_Banim_03B_sokm_sp1_Sheet1
Img_Banim_03B_sokm_sp1_Sheet1:  @ LZ77
Img_Banim_03B_sokm_sp1_Sheet1:  @ LZ77
	.incbin "build/graphics/banim/03B_sokm_sp1/sheet_1.lz"

	.global Img_Banim_03B_sokm_sp1_Sheet2
	.global Img_Banim_03B_sokm_sp1_Sheet2
Img_Banim_03B_sokm_sp1_Sheet2:  @ LZ77
Img_Banim_03B_sokm_sp1_Sheet2:  @ LZ77
	.incbin "build/graphics/banim/03B_sokm_sp1/sheet_2.lz"

	.global Img_Banim_03B_sokm_sp1_Sheet3
	.global Img_Banim_03B_sokm_sp1_Sheet3
Img_Banim_03B_sokm_sp1_Sheet3:  @ LZ77
Img_Banim_03B_sokm_sp1_Sheet3:  @ LZ77
	.incbin "build/graphics/banim/03B_sokm_sp1/sheet_3.lz"

	.global Pal_Banim_03B_sokm_sp1
	.global Pal_Banim_03B_sokm_sp1
Pal_Banim_03B_sokm_sp1:  @ LZ77
Pal_Banim_03B_sokm_sp1:  @ LZ77
	.incbin "build/graphics/banim/03B_sokm_sp1/pal.lz"

	.global BanimOam_03B_sokm_sp1_L
	.global BanimOam_03B_sokm_sp1_L
BanimOam_03B_sokm_sp1_L:  @ LZ77
BanimOam_03B_sokm_sp1_L:  @ LZ77
	.incbin "build/graphics/banim/03B_sokm_sp1/oam_l.lz"

	.global BanimOam_03B_sokm_sp1_R
	.global BanimOam_03B_sokm_sp1_R
BanimOam_03B_sokm_sp1_R:  @ LZ77
BanimOam_03B_sokm_sp1_R:  @ LZ77
	.incbin "build/graphics/banim/03B_sokm_sp1/oam_r.lz"

	.section .rodata.08EAC0CC, "a"

	.global Pal_Banim_03C_sokm_sp1
	.global Pal_Banim_03C_sokm_sp1
Pal_Banim_03C_sokm_sp1:  @ LZ77
Pal_Banim_03C_sokm_sp1:  @ LZ77
	.incbin "build/graphics/banim/03C_sokm_sp1/pal.lz"

	.global BanimOam_03C_sokm_sp1_L
	.global BanimOam_03C_sokm_sp1_L
BanimOam_03C_sokm_sp1_L:  @ LZ77
BanimOam_03C_sokm_sp1_L:  @ LZ77
	.incbin "build/graphics/banim/03C_sokm_sp1/oam_l.lz"

	.global BanimOam_03C_sokm_sp1_R
	.global BanimOam_03C_sokm_sp1_R
BanimOam_03C_sokm_sp1_R:  @ LZ77
BanimOam_03C_sokm_sp1_R:  @ LZ77
	.incbin "build/graphics/banim/03C_sokm_sp1/oam_r.lz"

	.section .rodata.08EAD578, "a"

	.global Pal_Banim_03D_sokm_sp1
	.global Pal_Banim_03D_sokm_sp1
Pal_Banim_03D_sokm_sp1:  @ LZ77
Pal_Banim_03D_sokm_sp1:  @ LZ77
	.incbin "build/graphics/banim/03D_sokm_sp1/pal.lz"

	.global BanimOam_03D_sokm_sp1_L
	.global BanimOam_03D_sokm_sp1_L
BanimOam_03D_sokm_sp1_L:  @ LZ77
BanimOam_03D_sokm_sp1_L:  @ LZ77
	.incbin "build/graphics/banim/03D_sokm_sp1/oam_l.lz"

	.global BanimOam_03D_sokm_sp1_R
	.global BanimOam_03D_sokm_sp1_R
BanimOam_03D_sokm_sp1_R:  @ LZ77
BanimOam_03D_sokm_sp1_R:  @ LZ77
	.incbin "build/graphics/banim/03D_sokm_sp1/oam_r.lz"

	.section .rodata.08EAD890, "a"

	.global Img_Banim_03E_sokf_sp1_Sheet0
	.global Img_Banim_03E_sokf_sp1_Sheet0
Img_Banim_03E_sokf_sp1_Sheet0:  @ LZ77
Img_Banim_03E_sokf_sp1_Sheet0:  @ LZ77
	.incbin "build/graphics/banim/03E_sokf_sp1/sheet_0.lz"

	.global Img_Banim_03E_sokf_sp1_Sheet1
	.global Img_Banim_03E_sokf_sp1_Sheet1
Img_Banim_03E_sokf_sp1_Sheet1:  @ LZ77
Img_Banim_03E_sokf_sp1_Sheet1:  @ LZ77
	.incbin "build/graphics/banim/03E_sokf_sp1/sheet_1.lz"

	.global Img_Banim_03E_sokf_sp1_Sheet2
	.global Img_Banim_03E_sokf_sp1_Sheet2
Img_Banim_03E_sokf_sp1_Sheet2:  @ LZ77
Img_Banim_03E_sokf_sp1_Sheet2:  @ LZ77
	.incbin "build/graphics/banim/03E_sokf_sp1/sheet_2.lz"

	.global Img_Banim_03E_sokf_sp1_Sheet3
	.global Img_Banim_03E_sokf_sp1_Sheet3
Img_Banim_03E_sokf_sp1_Sheet3:  @ LZ77
Img_Banim_03E_sokf_sp1_Sheet3:  @ LZ77
	.incbin "build/graphics/banim/03E_sokf_sp1/sheet_3.lz"

	.global Pal_Banim_03E_sokf_sp1
	.global Pal_Banim_03E_sokf_sp1
Pal_Banim_03E_sokf_sp1:  @ LZ77
Pal_Banim_03E_sokf_sp1:  @ LZ77
	.incbin "build/graphics/banim/03E_sokf_sp1/pal.lz"

	.global BanimOam_03E_sokf_sp1_L
	.global BanimOam_03E_sokf_sp1_L
BanimOam_03E_sokf_sp1_L:  @ LZ77
BanimOam_03E_sokf_sp1_L:  @ LZ77
	.incbin "build/graphics/banim/03E_sokf_sp1/oam_l.lz"

	.global BanimOam_03E_sokf_sp1_R
	.global BanimOam_03E_sokf_sp1_R
BanimOam_03E_sokf_sp1_R:  @ LZ77
BanimOam_03E_sokf_sp1_R:  @ LZ77
	.incbin "build/graphics/banim/03E_sokf_sp1/oam_r.lz"

	.section .rodata.08EB354C, "a"

	.global Img_Banim_03F_asnm_sw1_Sheet0
	.global Img_Banim_03F_asnm_sw1_Sheet0
Img_Banim_03F_asnm_sw1_Sheet0:  @ LZ77
Img_Banim_03F_asnm_sw1_Sheet0:  @ LZ77
	.incbin "build/graphics/banim/03F_asnm_sw1/sheet_0.lz"

	.global Img_Banim_03F_asnm_sw1_Sheet1
	.global Img_Banim_03F_asnm_sw1_Sheet1
Img_Banim_03F_asnm_sw1_Sheet1:  @ LZ77
Img_Banim_03F_asnm_sw1_Sheet1:  @ LZ77
	.incbin "build/graphics/banim/03F_asnm_sw1/sheet_1.lz"

	.global Img_Banim_03F_asnm_sw1_Sheet2
	.global Img_Banim_03F_asnm_sw1_Sheet2
Img_Banim_03F_asnm_sw1_Sheet2:  @ LZ77
Img_Banim_03F_asnm_sw1_Sheet2:  @ LZ77
	.incbin "build/graphics/banim/03F_asnm_sw1/sheet_2.lz"

	.global Img_Banim_03F_asnm_sw1_Sheet3
	.global Img_Banim_03F_asnm_sw1_Sheet3
Img_Banim_03F_asnm_sw1_Sheet3:  @ LZ77
Img_Banim_03F_asnm_sw1_Sheet3:  @ LZ77
	.incbin "build/graphics/banim/03F_asnm_sw1/sheet_3.lz"

	.global Pal_Banim_03F_asnm_sw1
	.global Pal_Banim_03F_asnm_sw1
Pal_Banim_03F_asnm_sw1:  @ LZ77
Pal_Banim_03F_asnm_sw1:  @ LZ77
	.incbin "build/graphics/banim/03F_asnm_sw1/pal.lz"

	.global BanimOam_03F_asnm_sw1_L
	.global BanimOam_03F_asnm_sw1_L
BanimOam_03F_asnm_sw1_L:  @ LZ77
BanimOam_03F_asnm_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/03F_asnm_sw1/oam_l.lz"

	.global BanimOam_03F_asnm_sw1_R
	.global BanimOam_03F_asnm_sw1_R
BanimOam_03F_asnm_sw1_R:  @ LZ77
BanimOam_03F_asnm_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/03F_asnm_sw1/oam_r.lz"

	.section .rodata.08EB928C, "a"

	.global Pal_Banim_040_asnm_sw1
	.global Pal_Banim_040_asnm_sw1
Pal_Banim_040_asnm_sw1:  @ LZ77
Pal_Banim_040_asnm_sw1:  @ LZ77
	.incbin "build/graphics/banim/040_asnm_sw1/pal.lz"

	.global BanimOam_040_asnm_sw1_L
	.global BanimOam_040_asnm_sw1_L
BanimOam_040_asnm_sw1_L:  @ LZ77
BanimOam_040_asnm_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/040_asnm_sw1/oam_l.lz"

	.global BanimOam_040_asnm_sw1_R
	.global BanimOam_040_asnm_sw1_R
BanimOam_040_asnm_sw1_R:  @ LZ77
BanimOam_040_asnm_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/040_asnm_sw1/oam_r.lz"

	.section .rodata.08EB9550, "a"

	.global Img_Banim_041_pakm_sw1_Sheet0
	.global Img_Banim_041_pakm_sw1_Sheet0
Img_Banim_041_pakm_sw1_Sheet0:  @ LZ77
Img_Banim_041_pakm_sw1_Sheet0:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/sheet_0.lz"

	.global Img_Banim_041_pakm_sw1_Sheet1
	.global Img_Banim_041_pakm_sw1_Sheet1
Img_Banim_041_pakm_sw1_Sheet1:  @ LZ77
Img_Banim_041_pakm_sw1_Sheet1:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/sheet_1.lz"

	.global Img_Banim_041_pakm_sw1_Sheet2
	.global Img_Banim_041_pakm_sw1_Sheet2
Img_Banim_041_pakm_sw1_Sheet2:  @ LZ77
Img_Banim_041_pakm_sw1_Sheet2:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/sheet_2.lz"

	.global Img_Banim_041_pakm_sw1_Sheet3
	.global Img_Banim_041_pakm_sw1_Sheet3
Img_Banim_041_pakm_sw1_Sheet3:  @ LZ77
Img_Banim_041_pakm_sw1_Sheet3:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/sheet_3.lz"

	.global Img_Banim_041_pakm_sw1_Sheet4
	.global Img_Banim_041_pakm_sw1_Sheet4
Img_Banim_041_pakm_sw1_Sheet4:  @ LZ77
Img_Banim_041_pakm_sw1_Sheet4:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/sheet_4.lz"

	.global Img_Banim_041_pakm_sw1_Sheet5
	.global Img_Banim_041_pakm_sw1_Sheet5
Img_Banim_041_pakm_sw1_Sheet5:  @ LZ77
Img_Banim_041_pakm_sw1_Sheet5:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/sheet_5.lz"

	.global Img_Banim_041_pakm_sw1_Sheet6
	.global Img_Banim_041_pakm_sw1_Sheet6
Img_Banim_041_pakm_sw1_Sheet6:  @ LZ77
Img_Banim_041_pakm_sw1_Sheet6:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/sheet_6.lz"

	.global Img_Banim_042_pakm_sw1_Sheet4
	.global Img_Banim_042_pakm_sw1_Sheet4
Img_Banim_042_pakm_sw1_Sheet4:  @ LZ77
Img_Banim_042_pakm_sw1_Sheet4:  @ LZ77
	.incbin "build/graphics/banim/042_pakm_sw1/sheet_4.lz"

	.global Pal_Banim_041_pakm_sw1
	.global Pal_Banim_041_pakm_sw1
Pal_Banim_041_pakm_sw1:  @ LZ77
Pal_Banim_041_pakm_sw1:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/pal.lz"

	.global BanimOam_041_pakm_sw1_L
	.global BanimOam_041_pakm_sw1_L
BanimOam_041_pakm_sw1_L:  @ LZ77
BanimOam_041_pakm_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/oam_l.lz"

	.global BanimOam_041_pakm_sw1_R
	.global BanimOam_041_pakm_sw1_R
BanimOam_041_pakm_sw1_R:  @ LZ77
BanimOam_041_pakm_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/oam_r.lz"

	.section .rodata.08EC435C, "a"

	.global Pal_Banim_042_pakm_sw1
	.global Pal_Banim_042_pakm_sw1
Pal_Banim_042_pakm_sw1:  @ LZ77
Pal_Banim_042_pakm_sw1:  @ LZ77
	.incbin "build/graphics/banim/042_pakm_sw1/pal.lz"

	.global BanimOam_042_pakm_sw1_L
	.global BanimOam_042_pakm_sw1_L
BanimOam_042_pakm_sw1_L:  @ LZ77
BanimOam_042_pakm_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/042_pakm_sw1/oam_l.lz"

	.global BanimOam_042_pakm_sw1_R
	.global BanimOam_042_pakm_sw1_R
BanimOam_042_pakm_sw1_R:  @ LZ77
BanimOam_042_pakm_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/042_pakm_sw1/oam_r.lz"

	.section .rodata.08EC5EB4, "a"

	.global Pal_Banim_043_pakm_sw1
	.global Pal_Banim_043_pakm_sw1
Pal_Banim_043_pakm_sw1:  @ LZ77
Pal_Banim_043_pakm_sw1:  @ LZ77
	.incbin "build/graphics/banim/043_pakm_sw1/pal.lz"

	.global BanimOam_043_pakm_sw1_L
	.global BanimOam_043_pakm_sw1_L
BanimOam_043_pakm_sw1_L:  @ LZ77
BanimOam_043_pakm_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/043_pakm_sw1/oam_l.lz"

	.global BanimOam_043_pakm_sw1_R
	.global BanimOam_043_pakm_sw1_R
BanimOam_043_pakm_sw1_R:  @ LZ77
BanimOam_043_pakm_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/043_pakm_sw1/oam_r.lz"

	.section .rodata.08EC7E30, "a"

	.global Pal_Banim_044_pakm_sw1
	.global Pal_Banim_044_pakm_sw1
Pal_Banim_044_pakm_sw1:  @ LZ77
Pal_Banim_044_pakm_sw1:  @ LZ77
	.incbin "build/graphics/banim/044_pakm_sw1/pal.lz"

	.global BanimOam_044_pakm_sw1_L
	.global BanimOam_044_pakm_sw1_L
BanimOam_044_pakm_sw1_L:  @ LZ77
BanimOam_044_pakm_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/044_pakm_sw1/oam_l.lz"

	.global BanimOam_044_pakm_sw1_R
	.global BanimOam_044_pakm_sw1_R
BanimOam_044_pakm_sw1_R:  @ LZ77
BanimOam_044_pakm_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/044_pakm_sw1/oam_r.lz"

	.section .rodata.08ECA590, "a"

	.global Pal_Banim_045_pakm_sw1
	.global Pal_Banim_045_pakm_sw1
Pal_Banim_045_pakm_sw1:  @ LZ77
Pal_Banim_045_pakm_sw1:  @ LZ77
	.incbin "build/graphics/banim/045_pakm_sw1/pal.lz"

	.global BanimOam_045_pakm_sw1_L
	.global BanimOam_045_pakm_sw1_L
BanimOam_045_pakm_sw1_L:  @ LZ77
BanimOam_045_pakm_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/045_pakm_sw1/oam_l.lz"

	.global BanimOam_045_pakm_sw1_R
	.global BanimOam_045_pakm_sw1_R
BanimOam_045_pakm_sw1_R:  @ LZ77
BanimOam_045_pakm_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/045_pakm_sw1/oam_r.lz"

	.section .rodata.08ECA894, "a"

	.global Pal_Banim_046_pakm_sw1
	.global Pal_Banim_046_pakm_sw1
Pal_Banim_046_pakm_sw1:  @ LZ77
Pal_Banim_046_pakm_sw1:  @ LZ77
	.incbin "build/graphics/banim/046_pakm_sw1/pal.lz"

	.global BanimOam_046_pakm_sw1_L
	.global BanimOam_046_pakm_sw1_L
BanimOam_046_pakm_sw1_L:  @ LZ77
BanimOam_046_pakm_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/046_pakm_sw1/oam_l.lz"

	.global BanimOam_046_pakm_sw1_R
	.global BanimOam_046_pakm_sw1_R
BanimOam_046_pakm_sw1_R:  @ LZ77
BanimOam_046_pakm_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/046_pakm_sw1/oam_r.lz"

	.section .rodata.08ECCA34, "a"

	.global Pal_Banim_047_pakm_sw1
	.global Pal_Banim_047_pakm_sw1
Pal_Banim_047_pakm_sw1:  @ LZ77
Pal_Banim_047_pakm_sw1:  @ LZ77
	.incbin "build/graphics/banim/047_pakm_sw1/pal.lz"

	.global BanimOam_047_pakm_sw1_L
	.global BanimOam_047_pakm_sw1_L
BanimOam_047_pakm_sw1_L:  @ LZ77
BanimOam_047_pakm_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/047_pakm_sw1/oam_l.lz"

	.global BanimOam_047_pakm_sw1_R
	.global BanimOam_047_pakm_sw1_R
BanimOam_047_pakm_sw1_R:  @ LZ77
BanimOam_047_pakm_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/047_pakm_sw1/oam_r.lz"

	.section .rodata.08ECE58C, "a"

	.global Pal_Banim_048_pakm_sw1
	.global Pal_Banim_048_pakm_sw1
Pal_Banim_048_pakm_sw1:  @ LZ77
Pal_Banim_048_pakm_sw1:  @ LZ77
	.incbin "build/graphics/banim/048_pakm_sw1/pal.lz"

	.global BanimOam_048_pakm_sw1_L
	.global BanimOam_048_pakm_sw1_L
BanimOam_048_pakm_sw1_L:  @ LZ77
BanimOam_048_pakm_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/048_pakm_sw1/oam_l.lz"

	.global BanimOam_048_pakm_sw1_R
	.global BanimOam_048_pakm_sw1_R
BanimOam_048_pakm_sw1_R:  @ LZ77
BanimOam_048_pakm_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/048_pakm_sw1/oam_r.lz"

	.section .rodata.08ED0508, "a"

	.global Pal_Banim_049_pakm_sw1
	.global Pal_Banim_049_pakm_sw1
Pal_Banim_049_pakm_sw1:  @ LZ77
Pal_Banim_049_pakm_sw1:  @ LZ77
	.incbin "build/graphics/banim/049_pakm_sw1/pal.lz"

	.global BanimOam_049_pakm_sw1_L
	.global BanimOam_049_pakm_sw1_L
BanimOam_049_pakm_sw1_L:  @ LZ77
BanimOam_049_pakm_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/049_pakm_sw1/oam_l.lz"

	.global BanimOam_049_pakm_sw1_R
	.global BanimOam_049_pakm_sw1_R
BanimOam_049_pakm_sw1_R:  @ LZ77
BanimOam_049_pakm_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/049_pakm_sw1/oam_r.lz"

	.section .rodata.08ED2C68, "a"

	.global Pal_Banim_04A_pakm_sw1
	.global Pal_Banim_04A_pakm_sw1
Pal_Banim_04A_pakm_sw1:  @ LZ77
Pal_Banim_04A_pakm_sw1:  @ LZ77
	.incbin "build/graphics/banim/04A_pakm_sw1/pal.lz"

	.global BanimOam_04A_pakm_sw1_L
	.global BanimOam_04A_pakm_sw1_L
BanimOam_04A_pakm_sw1_L:  @ LZ77
BanimOam_04A_pakm_sw1_L:  @ LZ77
	.incbin "build/graphics/banim/04A_pakm_sw1/oam_l.lz"

	.global BanimOam_04A_pakm_sw1_R
	.global BanimOam_04A_pakm_sw1_R
BanimOam_04A_pakm_sw1_R:  @ LZ77
BanimOam_04A_pakm_sw1_R:  @ LZ77
	.incbin "build/graphics/banim/04A_pakm_sw1/oam_r.lz"
