@ ROM data 0x08fa5058-0x08fe2134 (not yet in source)
@ Generated by tools/datasplit.py: labels, incbin and .4byte pointers.
@ Labels may be renamed here; rerun the tool then (it rewrites the
@ .4byte references) and after changing data/layout.txt.

	.section .rodata.08FA5058, "a"
	.incbin "baserom.gba", 0xfa5058, 0xa4ac

	.global gUnk_08FAF504
	.global gUnk_08FAF504
gUnk_08FAF504:
gUnk_08FAF504:
	.incbin "baserom.gba", 0xfaf504, 0x200

	.global gUnk_08FAF704
	.global gUnk_08FAF704
gUnk_08FAF704:
gUnk_08FAF704:
	.incbin "baserom.gba", 0xfaf704, 0x704

	.global gUnk_08FAFE08
	.global gUnk_08FAFE08
gUnk_08FAFE08:
gUnk_08FAFE08:
	.incbin "baserom.gba", 0xfafe08, 0x1ec

	.global gUnk_08FAFFF4
	.global gUnk_08FAFFF4
gUnk_08FAFFF4:
gUnk_08FAFFF4:
	.incbin "baserom.gba", 0xfafff4, 0x1114

	.global gUnk_08FB1108
	.global gUnk_08FB1108
gUnk_08FB1108:
gUnk_08FB1108:
	.incbin "baserom.gba", 0xfb1108, 0x8000

	.global gUnk_08FB9108
	.global gUnk_08FB9108
gUnk_08FB9108:
gUnk_08FB9108:
	.incbin "baserom.gba", 0xfb9108, 0x6f00

	.global battle_terrain_table
	.global battle_terrain_table
battle_terrain_table:
battle_terrain_table:
	.incbin "baserom.gba", 0xfc0008, 0xc
	.4byte gUnk_08FC0C00
	.4byte gUnk_08FC1444
	.incbin "baserom.gba", 0xfc001c, 0x10
	.4byte gUnk_08FC1464
	.4byte gUnk_08FC1C28
	.incbin "baserom.gba", 0xfc0034, 0x10
	.4byte gUnk_08FC1C48
	.4byte gUnk_08FC2570
	.incbin "baserom.gba", 0xfc004c, 0x10
	.4byte gUnk_08FC2590
	.4byte gUnk_08FC2D38
	.incbin "baserom.gba", 0xfc0064, 0x10
	.4byte gUnk_08FC2D58
	.4byte gUnk_08FC34C4
	.incbin "baserom.gba", 0xfc007c, 0x10
	.4byte gUnk_08FC34E4
	.4byte gUnk_08FC3BAC
	.incbin "baserom.gba", 0xfc0094, 0x10
	.4byte gUnk_08FC3BCC
	.4byte gUnk_08FC4394
	.incbin "baserom.gba", 0xfc00ac, 0x10
	.4byte gUnk_08FC43B4
	.4byte gUnk_08FC4C24
	.incbin "baserom.gba", 0xfc00c4, 0x10
	.4byte gUnk_08FC4C44
	.4byte gUnk_08FC54DC
	.incbin "baserom.gba", 0xfc00dc, 0x10
	.4byte gUnk_08FC54FC
	.4byte gUnk_08FC5B30
	.incbin "baserom.gba", 0xfc00f4, 0x10
	.4byte gUnk_08FC5B50
	.4byte gUnk_08FC6224
	.incbin "baserom.gba", 0xfc010c, 0x10
	.4byte gUnk_08FC6244
	.4byte gUnk_08FC6A18
	.incbin "baserom.gba", 0xfc0124, 0x10
	.4byte gUnk_08FC6A38
	.4byte gUnk_08FC7118
	.incbin "baserom.gba", 0xfc013c, 0x10
	.4byte gUnk_08FC7138
	.4byte gUnk_08FC7760
	.incbin "baserom.gba", 0xfc0154, 0x10
	.4byte gUnk_08FC7780
	.4byte gUnk_08FC7F50
	.incbin "baserom.gba", 0xfc016c, 0x10
	.4byte gUnk_08FC7F70
	.4byte gUnk_08FC8760
	.incbin "baserom.gba", 0xfc0184, 0x10
	.4byte gUnk_08FC8780
	.4byte gUnk_08FC9030
	.incbin "baserom.gba", 0xfc019c, 0x10
	.4byte gUnk_08FC9050
	.4byte gUnk_08FC9824
	.incbin "baserom.gba", 0xfc01b4, 0x10
	.4byte gUnk_08FC9844
	.4byte gUnk_08FCA078
	.incbin "baserom.gba", 0xfc01cc, 0x10
	.4byte gUnk_08FCA098
	.4byte gUnk_08FCA910
	.incbin "baserom.gba", 0xfc01e4, 0x10
	.4byte gUnk_08FCA930
	.4byte gUnk_08FCAFF4
	.incbin "baserom.gba", 0xfc01fc, 0x10
	.4byte gUnk_08FCB014
	.4byte gUnk_08FCB69C
	.incbin "baserom.gba", 0xfc0214, 0x10
	.4byte gUnk_08FCB6BC
	.4byte gUnk_08FCBDEC
	.incbin "baserom.gba", 0xfc022c, 0x10
	.4byte gUnk_08FCBE0C
	.4byte gUnk_08FCC4D0
	.incbin "baserom.gba", 0xfc0244, 0x10
	.4byte gUnk_08FCC4F0
	.4byte gUnk_08FCCC6C
	.incbin "baserom.gba", 0xfc025c, 0x10
	.4byte gUnk_08FCCC8C
	.4byte gUnk_08FCD410
	.incbin "baserom.gba", 0xfc0274, 0x10
	.4byte gUnk_08FCD430
	.4byte gUnk_08FCDD38
	.incbin "baserom.gba", 0xfc028c, 0x10
	.4byte gUnk_08FCDD58
	.4byte gUnk_08FCE420
	.incbin "baserom.gba", 0xfc02a4, 0x10
	.4byte gUnk_08FCE440
	.4byte gUnk_08FCEAB8
	.incbin "baserom.gba", 0xfc02bc, 0x10
	.4byte gUnk_08FCEAD8
	.4byte gUnk_08FCF194
	.incbin "baserom.gba", 0xfc02d4, 0x10
	.4byte gUnk_08FCF1B4
	.4byte gUnk_08FCF890
	.incbin "baserom.gba", 0xfc02ec, 0x10
	.4byte gUnk_08FCF8B0
	.4byte gUnk_08FD0014
	.incbin "baserom.gba", 0xfc0304, 0x10
	.4byte gUnk_08FD0034
	.4byte gUnk_08FD08B8
	.incbin "baserom.gba", 0xfc031c, 0x10
	.4byte gUnk_08FD08D8
	.4byte gUnk_08FD0F84
	.incbin "baserom.gba", 0xfc0334, 0x10
	.4byte gUnk_08FD0FA4
	.4byte gUnk_08FD15F8
	.incbin "baserom.gba", 0xfc034c, 0x10
	.4byte gUnk_08FC6244
	.4byte gUnk_08FD1618
	.incbin "baserom.gba", 0xfc0364, 0x10
	.4byte gUnk_08FCA930
	.4byte gUnk_08FD1638
	.incbin "baserom.gba", 0xfc037c, 0x10
	.4byte gUnk_08FC34E4
	.4byte gUnk_08FD1658
	.incbin "baserom.gba", 0xfc0394, 0x10
	.4byte gUnk_08FCA930
	.4byte gUnk_08FD1638
	.incbin "baserom.gba", 0xfc03ac, 0x10
	.4byte gUnk_08FCA930
	.4byte gUnk_08FD1638
	.incbin "baserom.gba", 0xfc03c4, 0x10
	.4byte gUnk_08FC34E4
	.4byte gUnk_08FD1658
	.incbin "baserom.gba", 0xfc03dc, 0x10
	.4byte gUnk_08FCA930
	.4byte gUnk_08FD1638
	.incbin "baserom.gba", 0xfc03f4, 0x10
	.4byte gUnk_08FCF8B0
	.4byte gUnk_08FD1678
	.incbin "baserom.gba", 0xfc040c, 0x10
	.4byte gUnk_08FCEAD8
	.4byte gUnk_08FD1698
	.incbin "baserom.gba", 0xfc0424, 0x10
	.4byte gUnk_08FC34E4
	.4byte gUnk_08FD1658
	.incbin "baserom.gba", 0xfc043c, 0x10
	.4byte gUnk_08FCA930
	.4byte gUnk_08FD1638
	.incbin "baserom.gba", 0xfc0454, 0x10
	.4byte gUnk_08FC0C00
	.4byte gUnk_08FD16B8
	.incbin "baserom.gba", 0xfc046c, 0x10
	.4byte gUnk_08FC1C48
	.4byte gUnk_08FD16D8
	.incbin "baserom.gba", 0xfc0484, 0x10
	.4byte gUnk_08FC2590
	.4byte gUnk_08FD16F8
	.incbin "baserom.gba", 0xfc049c, 0x10
	.4byte gUnk_08FC2D58
	.4byte gUnk_08FD1718
	.incbin "baserom.gba", 0xfc04b4, 0x10
	.4byte gUnk_08FC3BCC
	.4byte gUnk_08FD1738
	.incbin "baserom.gba", 0xfc04cc, 0x10
	.4byte gUnk_08FC4C44
	.4byte gUnk_08FD1758
	.incbin "baserom.gba", 0xfc04e4, 0x10
	.4byte gUnk_08FC5B50
	.4byte gUnk_08FD1778
	.incbin "baserom.gba", 0xfc04fc, 0x10
	.4byte gUnk_08FC6244
	.4byte gUnk_08FD1798
	.incbin "baserom.gba", 0xfc0514, 0x10
	.4byte gUnk_08FC7138
	.4byte gUnk_08FD17B8
	.incbin "baserom.gba", 0xfc052c, 0x10
	.4byte gUnk_08FC7F70
	.4byte gUnk_08FD17D8
	.incbin "baserom.gba", 0xfc0544, 0x10
	.4byte gUnk_08FC8780
	.4byte gUnk_08FD17F8
	.incbin "baserom.gba", 0xfc055c, 0x10
	.4byte gUnk_08FC9050
	.4byte gUnk_08FD1818
	.incbin "baserom.gba", 0xfc0574, 0x10
	.4byte gUnk_08FC9844
	.4byte gUnk_08FD1838
	.incbin "baserom.gba", 0xfc058c, 0x10
	.4byte gUnk_08FCA098
	.4byte gUnk_08FD1858
	.incbin "baserom.gba", 0xfc05a4, 0x10
	.4byte gUnk_08FCB6BC
	.4byte gUnk_08FD1878
	.incbin "baserom.gba", 0xfc05bc, 0x10
	.4byte gUnk_08FCC4F0
	.4byte gUnk_08FD1898
	.incbin "baserom.gba", 0xfc05d4, 0x10
	.4byte gUnk_08FCCC8C
	.4byte gUnk_08FD18B8
	.incbin "baserom.gba", 0xfc05ec, 0x10
	.4byte gUnk_08FD0034
	.4byte gUnk_08FD18D8
	.incbin "baserom.gba", 0xfc0604, 0x10
	.4byte gUnk_08FCBE0C
	.4byte gUnk_08FD18F8
	.incbin "baserom.gba", 0xfc061c, 0x10
	.4byte gUnk_08FC5B50
	.4byte gUnk_08FD1918
	.incbin "baserom.gba", 0xfc0634, 0x10
	.4byte gUnk_08FCA930
	.4byte gUnk_08FD1938
	.incbin "baserom.gba", 0xfc064c, 0x10
	.4byte gUnk_08FCF8B0
	.4byte gUnk_08FD1958
	.incbin "baserom.gba", 0xfc0664, 0x10
	.4byte gUnk_08FCEAD8
	.4byte gUnk_08FD1978
	.incbin "baserom.gba", 0xfc067c, 0x10
	.4byte gUnk_08FC34E4
	.4byte gUnk_08FD1998
	.incbin "baserom.gba", 0xfc0694, 0x10
	.4byte gUnk_08FCF1B4
	.4byte gUnk_08FD19B8
	.incbin "baserom.gba", 0xfc06ac, 0x10
	.4byte gUnk_08FCA930
	.4byte gUnk_08FD1638
	.incbin "baserom.gba", 0xfc06c4, 0x10
	.4byte gUnk_08FCF8B0
	.4byte gUnk_08FD1678
	.incbin "baserom.gba", 0xfc06dc, 0x10
	.4byte gUnk_08FCEAD8
	.4byte gUnk_08FD1698
	.incbin "baserom.gba", 0xfc06f4, 0x10
	.4byte gUnk_08FC34E4
	.4byte gUnk_08FD1658
	.incbin "baserom.gba", 0xfc070c, 0x10
	.4byte gUnk_08FCF1B4
	.4byte gUnk_08FD19D8
	.incbin "baserom.gba", 0xfc0724, 0x10
	.4byte gUnk_08FC0C00
	.4byte gUnk_08FD19F8
	.incbin "baserom.gba", 0xfc073c, 0x10
	.4byte gUnk_08FC5B50
	.4byte gUnk_08FD1A18
	.incbin "baserom.gba", 0xfc0754, 0x10
	.4byte gUnk_08FCA930
	.4byte gUnk_08FD1A38
	.incbin "baserom.gba", 0xfc076c, 0x10
	.4byte gUnk_08FCF8B0
	.4byte gUnk_08FD1A58
	.incbin "baserom.gba", 0xfc0784, 0x10
	.4byte gUnk_08FCEAD8
	.4byte gUnk_08FD1A78
	.incbin "baserom.gba", 0xfc079c, 0x10
	.4byte gUnk_08FC34E4
	.4byte gUnk_08FD1A98
	.incbin "baserom.gba", 0xfc07b4, 0x10
	.4byte gUnk_08FCF1B4
	.4byte gUnk_08FD1AB8
	.incbin "baserom.gba", 0xfc07cc, 0x10
	.4byte gUnk_08FC0C00
	.4byte gUnk_08FD1AD8
	.incbin "baserom.gba", 0xfc07e4, 0x10
	.4byte gUnk_08FC5B50
	.4byte gUnk_08FD1AF8
	.incbin "baserom.gba", 0xfc07fc, 0x10
	.4byte gUnk_08FD1B18
	.4byte gUnk_08FD2260
	.incbin "baserom.gba", 0xfc0814, 0x10
	.4byte gUnk_08FC4C44
	.4byte gUnk_08FD2280
	.incbin "baserom.gba", 0xfc082c, 0x10
	.4byte gUnk_08FC6244
	.4byte gUnk_08FD22A0
	.incbin "baserom.gba", 0xfc0844, 0x10
	.4byte gUnk_08FCA930
	.4byte gUnk_08FD22C0
	.incbin "baserom.gba", 0xfc085c, 0x10
	.4byte gUnk_08FCF8B0
	.4byte gUnk_08FD22E0
	.incbin "baserom.gba", 0xfc0874, 0x10
	.4byte gUnk_08FCEAD8
	.4byte gUnk_08FD2300
	.incbin "baserom.gba", 0xfc088c, 0x10
	.4byte gUnk_08FC34E4
	.4byte gUnk_08FD2320
	.incbin "baserom.gba", 0xfc08a4, 0x10
	.4byte gUnk_08FCF1B4
	.4byte gUnk_08FD2340
	.incbin "baserom.gba", 0xfc08bc, 0x10
	.4byte gUnk_08FC0C00
	.4byte gUnk_08FD2360
	.incbin "baserom.gba", 0xfc08d4, 0x10
	.4byte gUnk_08FC5B50
	.4byte gUnk_08FD2380
	.incbin "baserom.gba", 0xfc08ec, 0x10
	.4byte gUnk_08FC2D58
	.4byte gUnk_08FD23A0
	.incbin "baserom.gba", 0xfc0904, 0x10
	.4byte gUnk_08FCA930
	.4byte gUnk_08FD23C0
	.incbin "baserom.gba", 0xfc091c, 0x10
	.4byte gUnk_08FCF8B0
	.4byte gUnk_08FD23E0
	.incbin "baserom.gba", 0xfc0934, 0x10
	.4byte gUnk_08FCEAD8
	.4byte gUnk_08FD2400
	.incbin "baserom.gba", 0xfc094c, 0x10
	.4byte gUnk_08FC34E4
	.4byte gUnk_08FD2420
	.incbin "baserom.gba", 0xfc0964, 0x10
	.4byte gUnk_08FCF1B4
	.4byte gUnk_08FD2440
	.incbin "baserom.gba", 0xfc097c, 0x10
	.4byte gUnk_08FC0C00
	.4byte gUnk_08FD2460
	.incbin "baserom.gba", 0xfc0994, 0x10
	.4byte gUnk_08FCA098
	.4byte gUnk_08FD2480
	.incbin "baserom.gba", 0xfc09ac, 0x10
	.4byte gUnk_08FD1B18
	.4byte gUnk_08FD24A0
	.incbin "baserom.gba", 0xfc09c4, 0x10
	.4byte gUnk_08FD24C0
	.4byte gUnk_08FD2DB8
	.incbin "baserom.gba", 0xfc09dc, 0x10
	.4byte gUnk_08FCA098
	.4byte gUnk_08FD2DD8
	.incbin "baserom.gba", 0xfc09f4, 0x20c

	.global gUnk_08FC0C00
	.global gUnk_08FC0C00
gUnk_08FC0C00:  @ LZ77
gUnk_08FC0C00:  @ LZ77
	.incbin "build/graphics/btl_terrain/00_heichi1.lz"

	.global gUnk_08FC1444
	.global gUnk_08FC1444
gUnk_08FC1444:
gUnk_08FC1444:
	.incbin "graphics/btl_terrain/00_heichi1_pal.gbapal"

	.global gUnk_08FC1464
	.global gUnk_08FC1464
gUnk_08FC1464:  @ LZ77
gUnk_08FC1464:  @ LZ77
	.incbin "build/graphics/btl_terrain/01_arechi1.lz"

	.global gUnk_08FC1C28
	.global gUnk_08FC1C28
gUnk_08FC1C28:
gUnk_08FC1C28:
	.incbin "graphics/btl_terrain/01_arechi1_pal.gbapal"

	.global gUnk_08FC1C48
	.global gUnk_08FC1C48
gUnk_08FC1C48:  @ LZ77
gUnk_08FC1C48:  @ LZ77
	.incbin "build/graphics/btl_terrain/02_jyoumon1.lz"

	.global gUnk_08FC2570
	.global gUnk_08FC2570
gUnk_08FC2570:
gUnk_08FC2570:
	.incbin "graphics/btl_terrain/02_jyoumon1_pal.gbapal"

	.global gUnk_08FC2590
	.global gUnk_08FC2590
gUnk_08FC2590:  @ LZ77
gUnk_08FC2590:  @ LZ77
	.incbin "build/graphics/btl_terrain/03_bukiya1.lz"

	.global gUnk_08FC2D38
	.global gUnk_08FC2D38
gUnk_08FC2D38:
gUnk_08FC2D38:
	.incbin "graphics/btl_terrain/03_bukiya1_pal.gbapal"

	.global gUnk_08FC2D58
	.global gUnk_08FC2D58
gUnk_08FC2D58:  @ LZ77
gUnk_08FC2D58:  @ LZ77
	.incbin "build/graphics/btl_terrain/04_gake1.lz"

	.global gUnk_08FC34C4
	.global gUnk_08FC34C4
gUnk_08FC34C4:
gUnk_08FC34C4:
	.incbin "graphics/btl_terrain/04_gake1_pal.gbapal"

	.global gUnk_08FC34E4
	.global gUnk_08FC34E4
gUnk_08FC34E4:  @ LZ77
gUnk_08FC34E4:  @ LZ77
	.incbin "build/graphics/btl_terrain/05_gyokuza1.lz"

	.global gUnk_08FC3BAC
	.global gUnk_08FC3BAC
gUnk_08FC3BAC:
gUnk_08FC3BAC:
	.incbin "graphics/btl_terrain/05_gyokuza1_pal.gbapal"

	.global gUnk_08FC3BCC
	.global gUnk_08FC3BCC
gUnk_08FC3BCC:  @ LZ77
gUnk_08FC3BCC:  @ LZ77
	.incbin "build/graphics/btl_terrain/06_haikyo1.lz"

	.global gUnk_08FC4394
	.global gUnk_08FC4394
gUnk_08FC4394:
gUnk_08FC4394:
	.incbin "graphics/btl_terrain/06_haikyo1_pal.gbapal"

	.global gUnk_08FC43B4
	.global gUnk_08FC43B4
gUnk_08FC43B4:  @ LZ77
gUnk_08FC43B4:  @ LZ77
	.incbin "build/graphics/btl_terrain/07_hanebashi1.lz"

	.global gUnk_08FC4C24
	.global gUnk_08FC4C24
gUnk_08FC4C24:
gUnk_08FC4C24:
	.incbin "graphics/btl_terrain/07_hanebashi1_pal.gbapal"

	.global gUnk_08FC4C44
	.global gUnk_08FC4C44
gUnk_08FC4C44:  @ LZ77
gUnk_08FC4C44:  @ LZ77
	.incbin "build/graphics/btl_terrain/08_hasi1.lz"

	.global gUnk_08FC54DC
	.global gUnk_08FC54DC
gUnk_08FC54DC:
gUnk_08FC54DC:
	.incbin "graphics/btl_terrain/08_hasi1_pal.gbapal"

	.global gUnk_08FC54FC
	.global gUnk_08FC54FC
gUnk_08FC54FC:  @ LZ77
gUnk_08FC54FC:  @ LZ77
	.incbin "build/graphics/btl_terrain/09_sabaku1.lz"

	.global gUnk_08FC5B30
	.global gUnk_08FC5B30
gUnk_08FC5B30:
gUnk_08FC5B30:
	.incbin "graphics/btl_terrain/09_sabaku1_pal.gbapal"

	.global gUnk_08FC5B50
	.global gUnk_08FC5B50
gUnk_08FC5B50:  @ LZ77
gUnk_08FC5B50:  @ LZ77
	.incbin "build/graphics/btl_terrain/0A_kawa1.lz"

	.global gUnk_08FC6224
	.global gUnk_08FC6224
gUnk_08FC6224:
gUnk_08FC6224:
	.incbin "graphics/btl_terrain/0A_kawa1_pal.gbapal"

	.global gUnk_08FC6244
	.global gUnk_08FC6244
gUnk_08FC6244:  @ LZ77
gUnk_08FC6244:  @ LZ77
	.incbin "build/graphics/btl_terrain/0B_mura1.lz"

	.global gUnk_08FC6A18
	.global gUnk_08FC6A18
gUnk_08FC6A18:
gUnk_08FC6A18:
	.incbin "graphics/btl_terrain/0B_mura1_pal.gbapal"

	.global gUnk_08FC6A38
	.global gUnk_08FC6A38
gUnk_08FC6A38:  @ LZ77
gUnk_08FC6A38:  @ LZ77
	.incbin "build/graphics/btl_terrain/0C_umi1.lz"

	.global gUnk_08FC7118
	.global gUnk_08FC7118
gUnk_08FC7118:
gUnk_08FC7118:
	.incbin "graphics/btl_terrain/0C_umi1_pal.gbapal"

	.global gUnk_08FC7138
	.global gUnk_08FC7138
gUnk_08FC7138:  @ LZ77
gUnk_08FC7138:  @ LZ77
	.incbin "build/graphics/btl_terrain/0D_mizuiumi1.lz"

	.global gUnk_08FC7760
	.global gUnk_08FC7760
gUnk_08FC7760:
gUnk_08FC7760:
	.incbin "graphics/btl_terrain/0D_mizuiumi1_pal.gbapal"

	.global gUnk_08FC7780
	.global gUnk_08FC7780
gUnk_08FC7780:  @ LZ77
gUnk_08FC7780:  @ LZ77
	.incbin "build/graphics/btl_terrain/0E_azukarijo1.lz"

	.global gUnk_08FC7F50
	.global gUnk_08FC7F50
gUnk_08FC7F50:
gUnk_08FC7F50:
	.incbin "graphics/btl_terrain/0E_azukarijo1_pal.gbapal"

	.global gUnk_08FC7F70
	.global gUnk_08FC7F70
gUnk_08FC7F70:  @ LZ77
gUnk_08FC7F70:  @ LZ77
	.incbin "build/graphics/btl_terrain/0F_douguya1.lz"

	.global gUnk_08FC8760
	.global gUnk_08FC8760
gUnk_08FC8760:
gUnk_08FC8760:
	.incbin "graphics/btl_terrain/0F_douguya1_pal.gbapal"

	.global gUnk_08FC8780
	.global gUnk_08FC8780
gUnk_08FC8780:  @ LZ77
gUnk_08FC8780:  @ LZ77
	.incbin "build/graphics/btl_terrain/10_fukaimori1.lz"

	.global gUnk_08FC9030
	.global gUnk_08FC9030
gUnk_08FC9030:
gUnk_08FC9030:
	.incbin "graphics/btl_terrain/10_fukaimori1_pal.gbapal"

	.global gUnk_08FC9050
	.global gUnk_08FC9050
gUnk_08FC9050:  @ LZ77
gUnk_08FC9050:  @ LZ77
	.incbin "build/graphics/btl_terrain/11_michi1.lz"

	.global gUnk_08FC9824
	.global gUnk_08FC9824
gUnk_08FC9824:
gUnk_08FC9824:
	.incbin "graphics/btl_terrain/11_michi1_pal.gbapal"

	.global gUnk_08FC9844
	.global gUnk_08FC9844
gUnk_08FC9844:  @ LZ77
gUnk_08FC9844:  @ LZ77
	.incbin "build/graphics/btl_terrain/12_minka1.lz"

	.global gUnk_08FCA078
	.global gUnk_08FCA078
gUnk_08FCA078:
gUnk_08FCA078:
	.incbin "graphics/btl_terrain/12_minka1_pal.gbapal"

	.global gUnk_08FCA098
	.global gUnk_08FCA098
gUnk_08FCA098:  @ LZ77
gUnk_08FCA098:  @ LZ77
	.incbin "build/graphics/btl_terrain/13_mori1.lz"

	.global gUnk_08FCA910
	.global gUnk_08FCA910
gUnk_08FCA910:
gUnk_08FCA910:
	.incbin "graphics/btl_terrain/13_mori1_pal.gbapal"

	.global gUnk_08FCA930
	.global gUnk_08FCA930
gUnk_08FCA930:  @ LZ77
gUnk_08FCA930:  @ LZ77
	.incbin "build/graphics/btl_terrain/14_siroyuka1.lz"

	.global gUnk_08FCAFF4
	.global gUnk_08FCAFF4
gUnk_08FCAFF4:
gUnk_08FCAFF4:
	.incbin "graphics/btl_terrain/14_siroyuka1_pal.gbapal"

	.global gUnk_08FCB014
	.global gUnk_08FCB014
gUnk_08FCB014:  @ LZ77
gUnk_08FCB014:  @ LZ77
	.incbin "build/graphics/btl_terrain/15_sunachi1.lz"

	.global gUnk_08FCB69C
	.global gUnk_08FCB69C
gUnk_08FCB69C:
gUnk_08FCB69C:
	.incbin "graphics/btl_terrain/15_sunachi1_pal.gbapal"

	.global gUnk_08FCB6BC
	.global gUnk_08FCB6BC
gUnk_08FCB6BC:  @ LZ77
gUnk_08FCB6BC:  @ LZ77
	.incbin "build/graphics/btl_terrain/16_takaiyama1.lz"

	.global gUnk_08FCBDEC
	.global gUnk_08FCBDEC
gUnk_08FCBDEC:
gUnk_08FCBDEC:
	.incbin "graphics/btl_terrain/16_takaiyama1_pal.gbapal"

	.global gUnk_08FCBE0C
	.global gUnk_08FCBE0C
gUnk_08FCBE0C:  @ LZ77
gUnk_08FCBE0C:  @ LZ77
	.incbin "build/graphics/btl_terrain/17_toride1.lz"

	.global gUnk_08FCC4D0
	.global gUnk_08FCC4D0
gUnk_08FCC4D0:
gUnk_08FCC4D0:
	.incbin "graphics/btl_terrain/17_toride1_pal.gbapal"

	.global gUnk_08FCC4F0
	.global gUnk_08FCC4F0
gUnk_08FCC4F0:  @ LZ77
gUnk_08FCC4F0:  @ LZ77
	.incbin "build/graphics/btl_terrain/18_tougijou1.lz"

	.global gUnk_08FCCC6C
	.global gUnk_08FCCC6C
gUnk_08FCCC6C:
gUnk_08FCCC6C:
	.incbin "graphics/btl_terrain/18_tougijou1_pal.gbapal"

	.global gUnk_08FCCC8C
	.global gUnk_08FCCC8C
gUnk_08FCCC8C:  @ LZ77
gUnk_08FCCC8C:  @ LZ77
	.incbin "build/graphics/btl_terrain/19_yama1.lz"

	.global gUnk_08FCD410
	.global gUnk_08FCD410
gUnk_08FCD410:
gUnk_08FCD410:
	.incbin "graphics/btl_terrain/19_yama1_pal.gbapal"

	.global gUnk_08FCD430
	.global gUnk_08FCD430
gUnk_08FCD430:  @ LZ77
gUnk_08FCD430:  @ LZ77
	.incbin "build/graphics/btl_terrain/1A_mahouyuka1.lz"

	.global gUnk_08FCDD38
	.global gUnk_08FCDD38
gUnk_08FCDD38:
gUnk_08FCDD38:
	.incbin "graphics/btl_terrain/1A_mahouyuka1_pal.gbapal"

	.global gUnk_08FCDD58
	.global gUnk_08FCDD58
gUnk_08FCDD58:  @ LZ77
gUnk_08FCDD58:  @ LZ77
	.incbin "build/graphics/btl_terrain/1B_kabe1.lz"

	.global gUnk_08FCE420
	.global gUnk_08FCE420
gUnk_08FCE420:
gUnk_08FCE420:
	.incbin "graphics/btl_terrain/1B_kabe1_pal.gbapal"

	.global gUnk_08FCE440
	.global gUnk_08FCE440
gUnk_08FCE440:  @ LZ77
gUnk_08FCE440:  @ LZ77
	.incbin "build/graphics/btl_terrain/1C_kowaretakabe.lz"

	.global gUnk_08FCEAB8
	.global gUnk_08FCEAB8
gUnk_08FCEAB8:
gUnk_08FCEAB8:
	.incbin "graphics/btl_terrain/1C_kowaretakabe_pal.gbapal"

	.global gUnk_08FCEAD8
	.global gUnk_08FCEAD8
gUnk_08FCEAD8:  @ LZ77
gUnk_08FCEAD8:  @ LZ77
	.incbin "build/graphics/btl_terrain/1D_kowaretakabe.lz"

	.global gUnk_08FCF194
	.global gUnk_08FCF194
gUnk_08FCF194:
gUnk_08FCF194:
	.incbin "graphics/btl_terrain/1D_kowaretakabe_pal.gbapal"

	.global gUnk_08FCF1B4
	.global gUnk_08FCF1B4
gUnk_08FCF1B4:  @ LZ77
gUnk_08FCF1B4:  @ LZ77
	.incbin "build/graphics/btl_terrain/1E_hasira1.lz"

	.global gUnk_08FCF890
	.global gUnk_08FCF890
gUnk_08FCF890:
gUnk_08FCF890:
	.incbin "graphics/btl_terrain/1E_hasira1_pal.gbapal"

	.global gUnk_08FCF8B0
	.global gUnk_08FCF8B0
gUnk_08FCF8B0:  @ LZ77
gUnk_08FCF8B0:  @ LZ77
	.incbin "build/graphics/btl_terrain/1F_takarabako1.lz"

	.global gUnk_08FD0014
	.global gUnk_08FD0014
gUnk_08FD0014:
gUnk_08FD0014:
	.incbin "graphics/btl_terrain/1F_takarabako1_pal.gbapal"

	.global gUnk_08FD0034
	.global gUnk_08FD0034
gUnk_08FD0034:  @ LZ77
gUnk_08FD0034:  @ LZ77
	.incbin "build/graphics/btl_terrain/20_killerarechi.lz"

	.global gUnk_08FD08B8
	.global gUnk_08FD08B8
gUnk_08FD08B8:
gUnk_08FD08B8:
	.incbin "graphics/btl_terrain/20_killerarechi_pal.gbapal"

	.global gUnk_08FD08D8
	.global gUnk_08FD08D8
gUnk_08FD08D8:  @ LZ77
gUnk_08FD08D8:  @ LZ77
	.incbin "build/graphics/btl_terrain/21_mon1.lz"

	.global gUnk_08FD0F84
	.global gUnk_08FD0F84
gUnk_08FD0F84:
gUnk_08FD0F84:
	.incbin "graphics/btl_terrain/21_mon1_pal.gbapal"

	.global gUnk_08FD0FA4
	.global gUnk_08FD0FA4
gUnk_08FD0FA4:  @ LZ77
gUnk_08FD0FA4:  @ LZ77
	.incbin "build/graphics/btl_terrain/22_tuusintougi1.lz"

	.global gUnk_08FD15F8
	.global gUnk_08FD15F8
gUnk_08FD15F8:
gUnk_08FD15F8:
	.incbin "graphics/btl_terrain/22_tuusintougi1_pal.gbapal"

	.global gUnk_08FD1618
	.global gUnk_08FD1618
gUnk_08FD1618:
gUnk_08FD1618:
	.incbin "baserom.gba", 0xfd1618, 0x20

	.global gUnk_08FD1638
	.global gUnk_08FD1638
gUnk_08FD1638:
gUnk_08FD1638:
	.incbin "baserom.gba", 0xfd1638, 0x20

	.global gUnk_08FD1658
	.global gUnk_08FD1658
gUnk_08FD1658:
gUnk_08FD1658:
	.incbin "baserom.gba", 0xfd1658, 0x20

	.global gUnk_08FD1678
	.global gUnk_08FD1678
gUnk_08FD1678:
gUnk_08FD1678:
	.incbin "baserom.gba", 0xfd1678, 0x20

	.global gUnk_08FD1698
	.global gUnk_08FD1698
gUnk_08FD1698:
gUnk_08FD1698:
	.incbin "baserom.gba", 0xfd1698, 0x20

	.global gUnk_08FD16B8
	.global gUnk_08FD16B8
gUnk_08FD16B8:
gUnk_08FD16B8:
	.incbin "baserom.gba", 0xfd16b8, 0x20

	.global gUnk_08FD16D8
	.global gUnk_08FD16D8
gUnk_08FD16D8:
gUnk_08FD16D8:
	.incbin "baserom.gba", 0xfd16d8, 0x20

	.global gUnk_08FD16F8
	.global gUnk_08FD16F8
gUnk_08FD16F8:
gUnk_08FD16F8:
	.incbin "baserom.gba", 0xfd16f8, 0x20

	.global gUnk_08FD1718
	.global gUnk_08FD1718
gUnk_08FD1718:
gUnk_08FD1718:
	.incbin "baserom.gba", 0xfd1718, 0x20

	.global gUnk_08FD1738
	.global gUnk_08FD1738
gUnk_08FD1738:
gUnk_08FD1738:
	.incbin "baserom.gba", 0xfd1738, 0x20

	.global gUnk_08FD1758
	.global gUnk_08FD1758
gUnk_08FD1758:
gUnk_08FD1758:
	.incbin "baserom.gba", 0xfd1758, 0x20

	.global gUnk_08FD1778
	.global gUnk_08FD1778
gUnk_08FD1778:
gUnk_08FD1778:
	.incbin "baserom.gba", 0xfd1778, 0x20

	.global gUnk_08FD1798
	.global gUnk_08FD1798
gUnk_08FD1798:
gUnk_08FD1798:
	.incbin "baserom.gba", 0xfd1798, 0x20

	.global gUnk_08FD17B8
	.global gUnk_08FD17B8
gUnk_08FD17B8:
gUnk_08FD17B8:
	.incbin "baserom.gba", 0xfd17b8, 0x20

	.global gUnk_08FD17D8
	.global gUnk_08FD17D8
gUnk_08FD17D8:
gUnk_08FD17D8:
	.incbin "baserom.gba", 0xfd17d8, 0x20

	.global gUnk_08FD17F8
	.global gUnk_08FD17F8
gUnk_08FD17F8:
gUnk_08FD17F8:
	.incbin "baserom.gba", 0xfd17f8, 0x20

	.global gUnk_08FD1818
	.global gUnk_08FD1818
gUnk_08FD1818:
gUnk_08FD1818:
	.incbin "baserom.gba", 0xfd1818, 0x20

	.global gUnk_08FD1838
	.global gUnk_08FD1838
gUnk_08FD1838:
gUnk_08FD1838:
	.incbin "baserom.gba", 0xfd1838, 0x20

	.global gUnk_08FD1858
	.global gUnk_08FD1858
gUnk_08FD1858:
gUnk_08FD1858:
	.incbin "baserom.gba", 0xfd1858, 0x20

	.global gUnk_08FD1878
	.global gUnk_08FD1878
gUnk_08FD1878:
gUnk_08FD1878:
	.incbin "baserom.gba", 0xfd1878, 0x20

	.global gUnk_08FD1898
	.global gUnk_08FD1898
gUnk_08FD1898:
gUnk_08FD1898:
	.incbin "baserom.gba", 0xfd1898, 0x20

	.global gUnk_08FD18B8
	.global gUnk_08FD18B8
gUnk_08FD18B8:
gUnk_08FD18B8:
	.incbin "baserom.gba", 0xfd18b8, 0x20

	.global gUnk_08FD18D8
	.global gUnk_08FD18D8
gUnk_08FD18D8:
gUnk_08FD18D8:
	.incbin "baserom.gba", 0xfd18d8, 0x20

	.global gUnk_08FD18F8
	.global gUnk_08FD18F8
gUnk_08FD18F8:
gUnk_08FD18F8:
	.incbin "baserom.gba", 0xfd18f8, 0x20

	.global gUnk_08FD1918
	.global gUnk_08FD1918
gUnk_08FD1918:
gUnk_08FD1918:
	.incbin "baserom.gba", 0xfd1918, 0x20

	.global gUnk_08FD1938
	.global gUnk_08FD1938
gUnk_08FD1938:
gUnk_08FD1938:
	.incbin "baserom.gba", 0xfd1938, 0x20

	.global gUnk_08FD1958
	.global gUnk_08FD1958
gUnk_08FD1958:
gUnk_08FD1958:
	.incbin "baserom.gba", 0xfd1958, 0x20

	.global gUnk_08FD1978
	.global gUnk_08FD1978
gUnk_08FD1978:
gUnk_08FD1978:
	.incbin "baserom.gba", 0xfd1978, 0x20

	.global gUnk_08FD1998
	.global gUnk_08FD1998
gUnk_08FD1998:
gUnk_08FD1998:
	.incbin "baserom.gba", 0xfd1998, 0x20

	.global gUnk_08FD19B8
	.global gUnk_08FD19B8
gUnk_08FD19B8:
gUnk_08FD19B8:
	.incbin "baserom.gba", 0xfd19b8, 0x20

	.global gUnk_08FD19D8
	.global gUnk_08FD19D8
gUnk_08FD19D8:
gUnk_08FD19D8:
	.incbin "baserom.gba", 0xfd19d8, 0x20

	.global gUnk_08FD19F8
	.global gUnk_08FD19F8
gUnk_08FD19F8:
gUnk_08FD19F8:
	.incbin "baserom.gba", 0xfd19f8, 0x20

	.global gUnk_08FD1A18
	.global gUnk_08FD1A18
gUnk_08FD1A18:
gUnk_08FD1A18:
	.incbin "baserom.gba", 0xfd1a18, 0x20

	.global gUnk_08FD1A38
	.global gUnk_08FD1A38
gUnk_08FD1A38:
gUnk_08FD1A38:
	.incbin "baserom.gba", 0xfd1a38, 0x20

	.global gUnk_08FD1A58
	.global gUnk_08FD1A58
gUnk_08FD1A58:
gUnk_08FD1A58:
	.incbin "baserom.gba", 0xfd1a58, 0x20

	.global gUnk_08FD1A78
	.global gUnk_08FD1A78
gUnk_08FD1A78:
gUnk_08FD1A78:
	.incbin "baserom.gba", 0xfd1a78, 0x20

	.global gUnk_08FD1A98
	.global gUnk_08FD1A98
gUnk_08FD1A98:
gUnk_08FD1A98:
	.incbin "baserom.gba", 0xfd1a98, 0x20

	.global gUnk_08FD1AB8
	.global gUnk_08FD1AB8
gUnk_08FD1AB8:
gUnk_08FD1AB8:
	.incbin "baserom.gba", 0xfd1ab8, 0x20

	.global gUnk_08FD1AD8
	.global gUnk_08FD1AD8
gUnk_08FD1AD8:
gUnk_08FD1AD8:
	.incbin "baserom.gba", 0xfd1ad8, 0x20

	.global gUnk_08FD1AF8
	.global gUnk_08FD1AF8
gUnk_08FD1AF8:
gUnk_08FD1AF8:
	.incbin "baserom.gba", 0xfd1af8, 0x20

	.global gUnk_08FD1B18
	.global gUnk_08FD1B18
gUnk_08FD1B18:  @ LZ77
gUnk_08FD1B18:  @ LZ77
	.incbin "build/graphics/btl_terrain/55_maruta1.lz"

	.global gUnk_08FD2260
	.global gUnk_08FD2260
gUnk_08FD2260:
gUnk_08FD2260:
	.incbin "graphics/btl_terrain/55_maruta1_pal.gbapal"

	.global gUnk_08FD2280
	.global gUnk_08FD2280
gUnk_08FD2280:
gUnk_08FD2280:
	.incbin "baserom.gba", 0xfd2280, 0x20

	.global gUnk_08FD22A0
	.global gUnk_08FD22A0
gUnk_08FD22A0:
gUnk_08FD22A0:
	.incbin "baserom.gba", 0xfd22a0, 0x20

	.global gUnk_08FD22C0
	.global gUnk_08FD22C0
gUnk_08FD22C0:
gUnk_08FD22C0:
	.incbin "baserom.gba", 0xfd22c0, 0x20

	.global gUnk_08FD22E0
	.global gUnk_08FD22E0
gUnk_08FD22E0:
gUnk_08FD22E0:
	.incbin "baserom.gba", 0xfd22e0, 0x20

	.global gUnk_08FD2300
	.global gUnk_08FD2300
gUnk_08FD2300:
gUnk_08FD2300:
	.incbin "baserom.gba", 0xfd2300, 0x20

	.global gUnk_08FD2320
	.global gUnk_08FD2320
gUnk_08FD2320:
gUnk_08FD2320:
	.incbin "baserom.gba", 0xfd2320, 0x20

	.global gUnk_08FD2340
	.global gUnk_08FD2340
gUnk_08FD2340:
gUnk_08FD2340:
	.incbin "baserom.gba", 0xfd2340, 0x20

	.global gUnk_08FD2360
	.global gUnk_08FD2360
gUnk_08FD2360:
gUnk_08FD2360:
	.incbin "baserom.gba", 0xfd2360, 0x20

	.global gUnk_08FD2380
	.global gUnk_08FD2380
gUnk_08FD2380:
gUnk_08FD2380:
	.incbin "baserom.gba", 0xfd2380, 0x20

	.global gUnk_08FD23A0
	.global gUnk_08FD23A0
gUnk_08FD23A0:
gUnk_08FD23A0:
	.incbin "baserom.gba", 0xfd23a0, 0x20

	.global gUnk_08FD23C0
	.global gUnk_08FD23C0
gUnk_08FD23C0:
gUnk_08FD23C0:
	.incbin "baserom.gba", 0xfd23c0, 0x20

	.global gUnk_08FD23E0
	.global gUnk_08FD23E0
gUnk_08FD23E0:
gUnk_08FD23E0:
	.incbin "baserom.gba", 0xfd23e0, 0x20

	.global gUnk_08FD2400
	.global gUnk_08FD2400
gUnk_08FD2400:
gUnk_08FD2400:
	.incbin "baserom.gba", 0xfd2400, 0x20

	.global gUnk_08FD2420
	.global gUnk_08FD2420
gUnk_08FD2420:
gUnk_08FD2420:
	.incbin "baserom.gba", 0xfd2420, 0x20

	.global gUnk_08FD2440
	.global gUnk_08FD2440
gUnk_08FD2440:
gUnk_08FD2440:
	.incbin "baserom.gba", 0xfd2440, 0x20

	.global gUnk_08FD2460
	.global gUnk_08FD2460
gUnk_08FD2460:
gUnk_08FD2460:
	.incbin "baserom.gba", 0xfd2460, 0x20

	.global gUnk_08FD2480
	.global gUnk_08FD2480
gUnk_08FD2480:
gUnk_08FD2480:
	.incbin "baserom.gba", 0xfd2480, 0x20

	.global gUnk_08FD24A0
	.global gUnk_08FD24A0
gUnk_08FD24A0:
gUnk_08FD24A0:
	.incbin "baserom.gba", 0xfd24a0, 0x20

	.global gUnk_08FD24C0
	.global gUnk_08FD24C0
gUnk_08FD24C0:  @ LZ77
gUnk_08FD24C0:  @ LZ77
	.incbin "build/graphics/btl_terrain/68_fune1.lz"

	.global gUnk_08FD2DB8
	.global gUnk_08FD2DB8
gUnk_08FD2DB8:
gUnk_08FD2DB8:
	.incbin "graphics/btl_terrain/68_fune1_pal.gbapal"

	.global gUnk_08FD2DD8
	.global gUnk_08FD2DD8
gUnk_08FD2DD8:
gUnk_08FD2DD8:
	.incbin "baserom.gba", 0xfd2dd8, 0x5230

	.global character_battle_animation_palette_table
	.global character_battle_animation_palette_table
character_battle_animation_palette_table:
character_battle_animation_palette_table:
	.incbin "baserom.gba", 0xfd8008, 0xc
	.4byte gUnk_08FD9000
	.incbin "baserom.gba", 0xfd8018, 0xc
	.4byte gUnk_08FD9050
	.incbin "baserom.gba", 0xfd8028, 0xc
	.4byte gUnk_08FD90B4
	.incbin "baserom.gba", 0xfd8038, 0xc
	.4byte gUnk_08FD9114
	.incbin "baserom.gba", 0xfd8048, 0xc
	.4byte gUnk_08FD9180
	.incbin "baserom.gba", 0xfd8058, 0xc
	.4byte gUnk_08FD91EC
	.incbin "baserom.gba", 0xfd8068, 0xc
	.4byte gUnk_08FD9258
	.incbin "baserom.gba", 0xfd8078, 0xc
	.4byte gUnk_08FD92D8
	.incbin "baserom.gba", 0xfd8088, 0xc
	.4byte gUnk_08FD935C
	.incbin "baserom.gba", 0xfd8098, 0xc
	.4byte gUnk_08FD93DC
	.incbin "baserom.gba", 0xfd80a8, 0xc
	.4byte gUnk_08FD9448
	.incbin "baserom.gba", 0xfd80b8, 0xc
	.4byte gUnk_08FD94B4
	.incbin "baserom.gba", 0xfd80c8, 0xc
	.4byte gUnk_08FD9508
	.incbin "baserom.gba", 0xfd80d8, 0xc
	.4byte gUnk_08FD955C
	.incbin "baserom.gba", 0xfd80e8, 0xc
	.4byte gUnk_08FD95B8
	.incbin "baserom.gba", 0xfd80f8, 0xc
	.4byte gUnk_08FD9610
	.incbin "baserom.gba", 0xfd8108, 0xc
	.4byte gUnk_08FD9664
	.incbin "baserom.gba", 0xfd8118, 0xc
	.4byte gUnk_08FD96B4
	.incbin "baserom.gba", 0xfd8128, 0xc
	.4byte gUnk_08FD9704
	.incbin "baserom.gba", 0xfd8138, 0xc
	.4byte gUnk_08FD9754
	.incbin "baserom.gba", 0xfd8148, 0xc
	.4byte gUnk_08FD97A8
	.incbin "baserom.gba", 0xfd8158, 0xc
	.4byte gUnk_08FD97F8
	.incbin "baserom.gba", 0xfd8168, 0xc
	.4byte gUnk_08FD9848
	.incbin "baserom.gba", 0xfd8178, 0xc
	.4byte gUnk_08FD98A8
	.incbin "baserom.gba", 0xfd8188, 0xc
	.4byte gUnk_08FD9908
	.incbin "baserom.gba", 0xfd8198, 0xc
	.4byte gUnk_08FD9970
	.incbin "baserom.gba", 0xfd81a8, 0xc
	.4byte gUnk_08FD99DC
	.incbin "baserom.gba", 0xfd81b8, 0xc
	.4byte gUnk_08FD9A2C
	.incbin "baserom.gba", 0xfd81c8, 0xc
	.4byte gUnk_08FD9A84
	.incbin "baserom.gba", 0xfd81d8, 0xc
	.4byte gUnk_08FD9AD4
	.incbin "baserom.gba", 0xfd81e8, 0xc
	.4byte gUnk_08FD9B2C
	.incbin "baserom.gba", 0xfd81f8, 0xc
	.4byte gUnk_08FD9B7C
	.incbin "baserom.gba", 0xfd8208, 0xc
	.4byte gUnk_08FD9BDC
	.incbin "baserom.gba", 0xfd8218, 0xc
	.4byte gUnk_08FD9C34
	.incbin "baserom.gba", 0xfd8228, 0xc
	.4byte gUnk_08FD9C84
	.incbin "baserom.gba", 0xfd8238, 0xc
	.4byte gUnk_08FD9CD4
	.incbin "baserom.gba", 0xfd8248, 0xc
	.4byte gUnk_08FD9D44
	.incbin "baserom.gba", 0xfd8258, 0xc
	.4byte gUnk_08FD9DB4
	.incbin "baserom.gba", 0xfd8268, 0xc
	.4byte gUnk_08FD9E34
	.incbin "baserom.gba", 0xfd8278, 0xc
	.4byte gUnk_08FD9EAC
	.incbin "baserom.gba", 0xfd8288, 0xc
	.4byte gUnk_08FD9F08
	.incbin "baserom.gba", 0xfd8298, 0xc
	.4byte gUnk_08FD9F5C
	.incbin "baserom.gba", 0xfd82a8, 0xc
	.4byte gUnk_08FD9FAC
	.incbin "baserom.gba", 0xfd82b8, 0xc
	.4byte gUnk_08FDA00C
	.incbin "baserom.gba", 0xfd82c8, 0xc
	.4byte gUnk_08FDA07C
	.incbin "baserom.gba", 0xfd82d8, 0xc
	.4byte gUnk_08FDA0EC
	.incbin "baserom.gba", 0xfd82e8, 0xc
	.4byte gUnk_08FDA15C
	.incbin "baserom.gba", 0xfd82f8, 0xc
	.4byte gUnk_08FDA1B4
	.incbin "baserom.gba", 0xfd8308, 0xc
	.4byte gUnk_08FDA20C
	.incbin "baserom.gba", 0xfd8318, 0xc
	.4byte gUnk_08FDA27C
	.incbin "baserom.gba", 0xfd8328, 0xc
	.4byte gUnk_08FDA2EC
	.incbin "baserom.gba", 0xfd8338, 0xc
	.4byte gUnk_08FDA374
	.incbin "baserom.gba", 0xfd8348, 0xc
	.4byte gUnk_08FDA3FC
	.incbin "baserom.gba", 0xfd8358, 0xc
	.4byte gUnk_08FDA46C
	.incbin "baserom.gba", 0xfd8368, 0xc
	.4byte gUnk_08FDA4C8
	.incbin "baserom.gba", 0xfd8378, 0xc
	.4byte gUnk_08FDA524
	.incbin "baserom.gba", 0xfd8388, 0xc
	.4byte gUnk_08FDA57C
	.incbin "baserom.gba", 0xfd8398, 0xc
	.4byte gUnk_08FDA5E8
	.incbin "baserom.gba", 0xfd83a8, 0xc
	.4byte gUnk_08FDA65C
	.incbin "baserom.gba", 0xfd83b8, 0xc
	.4byte gUnk_08FDA6B8
	.incbin "baserom.gba", 0xfd83c8, 0xc
	.4byte gUnk_08FDA714
	.incbin "baserom.gba", 0xfd83d8, 0xc
	.4byte gUnk_08FDA780
	.incbin "baserom.gba", 0xfd83e8, 0xc
	.4byte gUnk_08FDA7DC
	.incbin "baserom.gba", 0xfd83f8, 0xc
	.4byte gUnk_08FDA83C
	.incbin "baserom.gba", 0xfd8408, 0xc
	.4byte gUnk_08FDA89C
	.incbin "baserom.gba", 0xfd8418, 0xc
	.4byte gUnk_08FDA910
	.incbin "baserom.gba", 0xfd8428, 0xc
	.4byte gUnk_08FDA984
	.incbin "baserom.gba", 0xfd8438, 0xc
	.4byte gUnk_08FDAA14
	.incbin "baserom.gba", 0xfd8448, 0xc
	.4byte gUnk_08FDAA8C
	.incbin "baserom.gba", 0xfd8458, 0xc
	.4byte gUnk_08FDAB04
	.incbin "baserom.gba", 0xfd8468, 0xc
	.4byte gUnk_08FDAB7C
	.incbin "baserom.gba", 0xfd8478, 0xc
	.4byte gUnk_08FDABF4
	.incbin "baserom.gba", 0xfd8488, 0xc
	.4byte gUnk_08FDAC6C
	.incbin "baserom.gba", 0xfd8498, 0xc
	.4byte gUnk_08FDACF8
	.incbin "baserom.gba", 0xfd84a8, 0xc
	.4byte gUnk_08FDAD84
	.incbin "baserom.gba", 0xfd84b8, 0xc
	.4byte gUnk_08FDAE10
	.incbin "baserom.gba", 0xfd84c8, 0xc
	.4byte gUnk_08FDAE88
	.incbin "baserom.gba", 0xfd84d8, 0xc
	.4byte gUnk_08FDAF00
	.incbin "baserom.gba", 0xfd84e8, 0xc
	.4byte gUnk_08FDAF8C
	.incbin "baserom.gba", 0xfd84f8, 0xc
	.4byte gUnk_08FDAFF8
	.incbin "baserom.gba", 0xfd8508, 0xc
	.4byte gUnk_08FDB064
	.incbin "baserom.gba", 0xfd8518, 0xc
	.4byte gUnk_08FDB0D4
	.incbin "baserom.gba", 0xfd8528, 0xc
	.4byte gUnk_08FDB134
	.incbin "baserom.gba", 0xfd8538, 0xc
	.4byte gUnk_08FDB194
	.incbin "baserom.gba", 0xfd8548, 0xc
	.4byte gUnk_08FDB1FC
	.incbin "baserom.gba", 0xfd8558, 0xc
	.4byte gUnk_08FDB26C
	.incbin "baserom.gba", 0xfd8568, 0xc
	.4byte gUnk_08FDB2D4
	.incbin "baserom.gba", 0xfd8578, 0xc
	.4byte gUnk_08FDB340
	.incbin "baserom.gba", 0xfd8588, 0xc
	.4byte gUnk_08FDB3B8
	.incbin "baserom.gba", 0xfd8598, 0xc
	.4byte gUnk_08FDB430
	.incbin "baserom.gba", 0xfd85a8, 0xc
	.4byte gUnk_08FDB484
	.incbin "baserom.gba", 0xfd85b8, 0xc
	.4byte gUnk_08FDB4D4
	.incbin "baserom.gba", 0xfd85c8, 0xc
	.4byte gUnk_08FDB524
	.incbin "baserom.gba", 0xfd85d8, 0xc
	.4byte gUnk_08FDB588
	.incbin "baserom.gba", 0xfd85e8, 0xc
	.4byte gUnk_08FDB5EC
	.incbin "baserom.gba", 0xfd85f8, 0xc
	.4byte gUnk_08FDB644
	.incbin "baserom.gba", 0xfd8608, 0xc
	.4byte gUnk_08FDB6A4
	.incbin "baserom.gba", 0xfd8618, 0xc
	.4byte gUnk_08FDB720
	.incbin "baserom.gba", 0xfd8628, 0xc
	.4byte gUnk_08FDB798
	.incbin "baserom.gba", 0xfd8638, 0xc
	.4byte gUnk_08FDB810
	.incbin "baserom.gba", 0xfd8648, 0xc
	.4byte gUnk_08FDB888
	.incbin "baserom.gba", 0xfd8658, 0xc
	.4byte gUnk_08FDB8E4
	.incbin "baserom.gba", 0xfd8668, 0xc
	.4byte gUnk_08FDB944
	.incbin "baserom.gba", 0xfd8678, 0xc
	.4byte gUnk_08FDB9A8
	.incbin "baserom.gba", 0xfd8688, 0xc
	.4byte gUnk_08FDBA08
	.incbin "baserom.gba", 0xfd8698, 0xc
	.4byte gUnk_08FDBA58
	.incbin "baserom.gba", 0xfd86a8, 0xc
	.4byte gUnk_08FDBAA8
	.incbin "baserom.gba", 0xfd86b8, 0xc
	.4byte gUnk_08FDBB0C
	.incbin "baserom.gba", 0xfd86c8, 0xc
	.4byte gUnk_08FDBB74
	.incbin "baserom.gba", 0xfd86d8, 0xc
	.4byte gUnk_08FDBBD0
	.incbin "baserom.gba", 0xfd86e8, 0xc
	.4byte gUnk_08FDBC3C
	.incbin "baserom.gba", 0xfd86f8, 0xc
	.4byte gUnk_08FDBCA0
	.incbin "baserom.gba", 0xfd8708, 0xc
	.4byte gUnk_08FDBCFC
	.incbin "baserom.gba", 0xfd8718, 0xc
	.4byte gUnk_08FDBD58
	.incbin "baserom.gba", 0xfd8728, 0xc
	.4byte gUnk_08FDBDB4
	.incbin "baserom.gba", 0xfd8738, 0xc
	.4byte gUnk_08FDBE14
	.incbin "baserom.gba", 0xfd8748, 0xc
	.4byte gUnk_08FDBE70
	.incbin "baserom.gba", 0xfd8758, 0xc
	.4byte gUnk_08FDBECC
	.incbin "baserom.gba", 0xfd8768, 0xc
	.4byte gUnk_08FDBF28
	.incbin "baserom.gba", 0xfd8778, 0xc
	.4byte gUnk_08FDBF64
	.incbin "baserom.gba", 0xfd8788, 0x878

	.global gUnk_08FD9000
	.global gUnk_08FD9000
gUnk_08FD9000:  @ LZ77
gUnk_08FD9000:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/01_lin.lz"

	.global gUnk_08FD9050
	.global gUnk_08FD9050
gUnk_08FD9050:  @ LZ77
gUnk_08FD9050:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/02_rebacca.lz"

	.global gUnk_08FD90B4
	.global gUnk_08FD90B4
gUnk_08FD90B4:  @ LZ77
gUnk_08FD90B4:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/03_will.lz"

	.global gUnk_08FD9114
	.global gUnk_08FD9114
gUnk_08FD9114:  @ LZ77
gUnk_08FD9114:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/04_boies.lz"

	.global gUnk_08FD9180
	.global gUnk_08FD9180
gUnk_08FD9180:  @ LZ77
gUnk_08FD9180:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/05_bool.lz"

	.global gUnk_08FD91EC
	.global gUnk_08FD91EC
gUnk_08FD91EC:  @ LZ77
gUnk_08FD91EC:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/06_bowker.lz"

	.global gUnk_08FD9258
	.global gUnk_08FD9258
gUnk_08FD9258:  @ LZ77
gUnk_08FD9258:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/07_eagler.lz"

	.global gUnk_08FD92D8
	.global gUnk_08FD92D8
gUnk_08FD92D8:  @ LZ77
gUnk_08FD92D8:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/08_osin.lz"

	.global gUnk_08FD935C
	.global gUnk_08FD935C
gUnk_08FD935C:  @ LZ77
gUnk_08FD935C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/09_wallace.lz"

	.global gUnk_08FD93DC
	.global gUnk_08FD93DC
gUnk_08FD93DC:  @ LZ77
gUnk_08FD93DC:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/0A_wire.lz"

	.global gUnk_08FD9448
	.global gUnk_08FD9448
gUnk_08FD9448:  @ LZ77
gUnk_08FD9448:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/0B_yog.lz"

	.global gUnk_08FD94B4
	.global gUnk_08FD94B4
gUnk_08FD94B4:  @ LZ77
gUnk_08FD94B4:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/0C_jaffar.lz"

	.global gUnk_08FD9508
	.global gUnk_08FD9508
gUnk_08FD9508:  @ LZ77
gUnk_08FD9508:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/0D_jerme.lz"

	.global gUnk_08FD955C
	.global gUnk_08FD955C
gUnk_08FD955C:  @ LZ77
gUnk_08FD955C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/0E_lagarto.lz"

	.global gUnk_08FD95B8
	.global gUnk_08FD95B8
gUnk_08FD95B8:  @ LZ77
gUnk_08FD95B8:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/0F_matthew.lz"

	.global gUnk_08FD9610
	.global gUnk_08FD9610
gUnk_08FD9610:  @ LZ77
gUnk_08FD9610:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/10_batta.lz"

	.global gUnk_08FD9664
	.global gUnk_08FD9664
gUnk_08FD9664:  @ LZ77
gUnk_08FD9664:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/11_bug.lz"

	.global gUnk_08FD96B4
	.global gUnk_08FD96B4
gUnk_08FD96B4:  @ LZ77
gUnk_08FD96B4:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/12_carjiga.lz"

	.global gUnk_08FD9704
	.global gUnk_08FD9704
gUnk_08FD9704:  @ LZ77
gUnk_08FD9704:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/13_migal.lz"

	.global gUnk_08FD9754
	.global gUnk_08FD9754
gUnk_08FD9754:  @ LZ77
gUnk_08FD9754:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/14_zagan.lz"

	.global gUnk_08FD97A8
	.global gUnk_08FD97A8
gUnk_08FD97A8:  @ LZ77
gUnk_08FD97A8:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/15_zugu.lz"

	.global gUnk_08FD97F8
	.global gUnk_08FD97F8
gUnk_08FD97F8:  @ LZ77
gUnk_08FD97F8:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/16_hawkeye.lz"

	.global gUnk_08FD9848
	.global gUnk_08FD9848
gUnk_08FD9848:  @ LZ77
gUnk_08FD9848:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/17_serra.lz"

	.global gUnk_08FD98A8
	.global gUnk_08FD98A8
gUnk_08FD98A8:  @ LZ77
gUnk_08FD98A8:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/18_kenneth.lz"

	.global gUnk_08FD9908
	.global gUnk_08FD9908
gUnk_08FD9908:  @ LZ77
gUnk_08FD9908:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/19_renato.lz"

	.global gUnk_08FD9970
	.global gUnk_08FD9970
gUnk_08FD9970:  @ LZ77
gUnk_08FD9970:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/1A_ruthea.lz"

	.global gUnk_08FD99DC
	.global gUnk_08FD99DC
gUnk_08FD99DC:  @ LZ77
gUnk_08FD99DC:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/1B_lin.lz"

	.global gUnk_08FD9A2C
	.global gUnk_08FD9A2C
gUnk_08FD9A2C:  @ LZ77
gUnk_08FD9A2C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/1C_haken.lz"

	.global gUnk_08FD9A84
	.global gUnk_08FD9A84
gUnk_08FD9A84:  @ LZ77
gUnk_08FD9A84:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/1D_kaim.lz"

	.global gUnk_08FD9AD4
	.global gUnk_08FD9AD4
gUnk_08FD9AD4:  @ LZ77
gUnk_08FD9AD4:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/1E_leyvan.lz"

	.global gUnk_08FD9B2C
	.global gUnk_08FD9B2C
gUnk_08FD9B2C:  @ LZ77
gUnk_08FD9B2C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/1F_linus.lz"

	.global gUnk_08FD9B7C
	.global gUnk_08FD9B7C
gUnk_08FD9B7C:  @ LZ77
gUnk_08FD9B7C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/20_nils.lz"

	.global gUnk_08FD9BDC
	.global gUnk_08FD9BDC
gUnk_08FD9BDC:  @ LZ77
gUnk_08FD9BDC:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/21_darts.lz"

	.global gUnk_08FD9C34
	.global gUnk_08FD9C34
gUnk_08FD9C34:  @ LZ77
gUnk_08FD9C34:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/22_fergus.lz"

	.global gUnk_08FD9C84
	.global gUnk_08FD9C84
gUnk_08FD9C84:  @ LZ77
gUnk_08FD9C84:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/23_georg.lz"

	.global gUnk_08FD9CD4
	.global gUnk_08FD9CD4
gUnk_08FD9CD4:  @ LZ77
gUnk_08FD9CD4:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/24_ninian.lz"

	.global gUnk_08FD9D44
	.global gUnk_08FD9D44
gUnk_08FD9D44:  @ LZ77
gUnk_08FD9D44:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/25_heath.lz"

	.global gUnk_08FD9DB4
	.global gUnk_08FD9DB4
gUnk_08FD9DB4:  @ LZ77
gUnk_08FD9DB4:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/26_heath.lz"

	.global gUnk_08FD9E34
	.global gUnk_08FD9E34
gUnk_08FD9E34:  @ LZ77
gUnk_08FD9E34:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/27_vaida.lz"

	.global gUnk_08FD9EAC
	.global gUnk_08FD9EAC
gUnk_08FD9EAC:  @ LZ77
gUnk_08FD9EAC:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/28_nergal.lz"

	.global gUnk_08FD9F08
	.global gUnk_08FD9F08
gUnk_08FD9F08:  @ LZ77
gUnk_08FD9F08:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/29_canas.lz"

	.global gUnk_08FD9F5C
	.global gUnk_08FD9F5C
gUnk_08FD9F5C:  @ LZ77
gUnk_08FD9F5C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/2A_teodor.lz"

	.global gUnk_08FD9FAC
	.global gUnk_08FD9FAC
gUnk_08FD9FAC:  @ LZ77
gUnk_08FD9FAC:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/2B_eliwod.lz"

	.global gUnk_08FDA00C
	.global gUnk_08FDA00C
gUnk_08FDA00C:  @ LZ77
gUnk_08FDA00C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/2C_farina.lz"

	.global gUnk_08FDA07C
	.global gUnk_08FDA07C
gUnk_08FDA07C:  @ LZ77
gUnk_08FDA07C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/2D_fiora.lz"

	.global gUnk_08FDA0EC
	.global gUnk_08FDA0EC
gUnk_08FDA0EC:  @ LZ77
gUnk_08FDA0EC:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/2E_flolina.lz"

	.global gUnk_08FDA15C
	.global gUnk_08FDA15C
gUnk_08FDA15C:  @ LZ77
gUnk_08FDA15C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/2F_bartr.lz"

	.global gUnk_08FDA1B4
	.global gUnk_08FDA1B4
gUnk_08FDA1B4:  @ LZ77
gUnk_08FDA1B4:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/30_dorcas.lz"

	.global gUnk_08FDA20C
	.global gUnk_08FDA20C
gUnk_08FDA20C:  @ LZ77
gUnk_08FDA20C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/31_belnald.lz"

	.global gUnk_08FDA27C
	.global gUnk_08FDA27C
gUnk_08FDA27C:  @ LZ77
gUnk_08FDA27C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/32_darren.lz"

	.global gUnk_08FDA2EC
	.global gUnk_08FDA2EC
gUnk_08FDA2EC:  @ LZ77
gUnk_08FDA2EC:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/33_osin.lz"

	.global gUnk_08FDA374
	.global gUnk_08FDA374
gUnk_08FDA374:  @ LZ77
gUnk_08FDA374:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/34_wallace.lz"

	.global gUnk_08FDA3FC
	.global gUnk_08FDA3FC
gUnk_08FDA3FC:  @ LZ77
gUnk_08FDA3FC:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/35_wranglen.lz"

	.global gUnk_08FDA46C
	.global gUnk_08FDA46C
gUnk_08FDA46C:  @ LZ77
gUnk_08FDA46C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/36_hector.lz"

	.global gUnk_08FDA4C8
	.global gUnk_08FDA4C8
gUnk_08FDA4C8:  @ LZ77
gUnk_08FDA4C8:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/37_hector.lz"

	.global gUnk_08FDA524
	.global gUnk_08FDA524
gUnk_08FDA524:  @ LZ77
gUnk_08FDA524:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/38_eliwod.lz"

	.global gUnk_08FDA57C
	.global gUnk_08FDA57C
gUnk_08FDA57C:  @ LZ77
gUnk_08FDA57C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/39_nino.lz"

	.global gUnk_08FDA5E8
	.global gUnk_08FDA5E8
gUnk_08FDA5E8:  @ LZ77
gUnk_08FDA5E8:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/3A_erk.lz"

	.global gUnk_08FDA65C
	.global gUnk_08FDA65C
gUnk_08FDA65C:  @ LZ77
gUnk_08FDA65C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/3B_beard.lz"

	.global gUnk_08FDA6B8
	.global gUnk_08FDA6B8
gUnk_08FDA6B8:  @ LZ77
gUnk_08FDA6B8:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/3C_glass.lz"

	.global gUnk_08FDA714
	.global gUnk_08FDA714
gUnk_08FDA714:  @ LZ77
gUnk_08FDA714:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/3D_leyvan.lz"

	.global gUnk_08FDA780
	.global gUnk_08FDA780
gUnk_08FDA780:  @ LZ77
gUnk_08FDA780:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/3E_pson.lz"

	.global gUnk_08FDA7DC
	.global gUnk_08FDA7DC
gUnk_08FDA7DC:  @ LZ77
gUnk_08FDA7DC:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/3F_ruthea.lz"

	.global gUnk_08FDA83C
	.global gUnk_08FDA83C
gUnk_08FDA83C:  @ LZ77
gUnk_08FDA83C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/40_guy.lz"

	.global gUnk_08FDA89C
	.global gUnk_08FDA89C
gUnk_08FDA89C:  @ LZ77
gUnk_08FDA89C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/41_ruth.lz"

	.global gUnk_08FDA910
	.global gUnk_08FDA910
gUnk_08FDA910:  @ LZ77
gUnk_08FDA910:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/42_siren.lz"

	.global gUnk_08FDA984
	.global gUnk_08FDA984
gUnk_08FDA984:  @ LZ77
gUnk_08FDA984:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/43_ruth.lz"

	.global gUnk_08FDAA14
	.global gUnk_08FDAA14
gUnk_08FDAA14:  @ LZ77
gUnk_08FDAA14:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/44_uhai.lz"

	.global gUnk_08FDAA8C
	.global gUnk_08FDAA8C
gUnk_08FDAA8C:  @ LZ77
gUnk_08FDAA8C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/45_isadora.lz"

	.global gUnk_08FDAB04
	.global gUnk_08FDAB04
gUnk_08FDAB04:  @ LZ77
gUnk_08FDAB04:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/46_camlann.lz"

	.global gUnk_08FDAB7C
	.global gUnk_08FDAB7C
gUnk_08FDAB7C:  @ LZ77
gUnk_08FDAB7C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/47_damian.lz"

	.global gUnk_08FDABF4
	.global gUnk_08FDABF4
gUnk_08FDABF4:  @ LZ77
gUnk_08FDABF4:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/48_ubands.lz"

	.global gUnk_08FDAC6C
	.global gUnk_08FDAC6C
gUnk_08FDAC6C:  @ LZ77
gUnk_08FDAC6C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/49_kent.lz"

	.global gUnk_08FDACF8
	.global gUnk_08FDACF8
gUnk_08FDACF8:  @ LZ77
gUnk_08FDACF8:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/4A_lowen.lz"

	.global gUnk_08FDAD84
	.global gUnk_08FDAD84
gUnk_08FDAD84:  @ LZ77
gUnk_08FDAD84:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/4B_marcus.lz"

	.global gUnk_08FDAE10
	.global gUnk_08FDAE10
gUnk_08FDAE10:  @ LZ77
gUnk_08FDAE10:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/4C_maxime.lz"

	.global gUnk_08FDAE88
	.global gUnk_08FDAE88
gUnk_08FDAE88:  @ LZ77
gUnk_08FDAE88:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/4D_pascal.lz"

	.global gUnk_08FDAF00
	.global gUnk_08FDAF00
gUnk_08FDAF00:  @ LZ77
gUnk_08FDAF00:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/4E_sain.lz"

	.global gUnk_08FDAF8C
	.global gUnk_08FDAF8C
gUnk_08FDAF8C:  @ LZ77
gUnk_08FDAF8C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/4F_farina.lz"

	.global gUnk_08FDAFF8
	.global gUnk_08FDAFF8
gUnk_08FDAFF8:  @ LZ77
gUnk_08FDAFF8:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/50_fiora.lz"

	.global gUnk_08FDB064
	.global gUnk_08FDB064
gUnk_08FDB064:  @ LZ77
gUnk_08FDB064:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/51_flolina.lz"

	.global gUnk_08FDB0D4
	.global gUnk_08FDB0D4
gUnk_08FDB0D4:  @ LZ77
gUnk_08FDB0D4:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/52_darts.lz"

	.global gUnk_08FDB134
	.global gUnk_08FDB134
gUnk_08FDB134:  @ LZ77
gUnk_08FDB134:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/53_serra.lz"

	.global gUnk_08FDB194
	.global gUnk_08FDB194
gUnk_08FDB194:  @ LZ77
gUnk_08FDB194:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/54_limstella.lz"

	.global gUnk_08FDB1FC
	.global gUnk_08FDB1FC
gUnk_08FDB1FC:  @ LZ77
gUnk_08FDB1FC:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/55_nino.lz"

	.global gUnk_08FDB26C
	.global gUnk_08FDB26C
gUnk_08FDB26C:  @ LZ77
gUnk_08FDB26C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/56_sonia.lz"

	.global gUnk_08FDB2D4
	.global gUnk_08FDB2D4
gUnk_08FDB2D4:  @ LZ77
gUnk_08FDB2D4:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/57_aion.lz"

	.global gUnk_08FDB340
	.global gUnk_08FDB340
gUnk_08FDB340:  @ LZ77
gUnk_08FDB340:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/58_erk.lz"

	.global gUnk_08FDB3B8
	.global gUnk_08FDB3B8
gUnk_08FDB3B8:  @ LZ77
gUnk_08FDB3B8:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/59_pant.lz"

	.global gUnk_08FDB430
	.global gUnk_08FDB430
gUnk_08FDB430:  @ LZ77
gUnk_08FDB430:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/5A_canas.lz"

	.global gUnk_08FDB484
	.global gUnk_08FDB484
gUnk_08FDB484:  @ LZ77
gUnk_08FDB484:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/5B_hintz.lz"

	.global gUnk_08FDB4D4
	.global gUnk_08FDB4D4
gUnk_08FDB4D4:  @ LZ77
gUnk_08FDB4D4:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/5C_zoldam.lz"

	.global gUnk_08FDB524
	.global gUnk_08FDB524
gUnk_08FDB524:  @ LZ77
gUnk_08FDB524:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/5D_luise.lz"

	.global gUnk_08FDB588
	.global gUnk_08FDB588
gUnk_08FDB588:  @ LZ77
gUnk_08FDB588:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/5E_rebacca.lz"

	.global gUnk_08FDB5EC
	.global gUnk_08FDB5EC
gUnk_08FDB5EC:  @ LZ77
gUnk_08FDB5EC:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/5F_denning.lz"

	.global gUnk_08FDB644
	.global gUnk_08FDB644
gUnk_08FDB644:  @ LZ77
gUnk_08FDB644:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/60_will.lz"

	.global gUnk_08FDB6A4
	.global gUnk_08FDB6A4
gUnk_08FDB6A4:  @ LZ77
gUnk_08FDB6A4:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/61_elic.lz"

	.global gUnk_08FDB720
	.global gUnk_08FDB720
gUnk_08FDB720:  @ LZ77
gUnk_08FDB720:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/62_kent.lz"

	.global gUnk_08FDB798
	.global gUnk_08FDB798
gUnk_08FDB798:  @ LZ77
gUnk_08FDB798:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/63_lowen.lz"

	.global gUnk_08FDB810
	.global gUnk_08FDB810
gUnk_08FDB810:  @ LZ77
gUnk_08FDB810:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/64_sain.lz"

	.global gUnk_08FDB888
	.global gUnk_08FDB888
gUnk_08FDB888:  @ LZ77
gUnk_08FDB888:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/65_athos.lz"

	.global gUnk_08FDB8E4
	.global gUnk_08FDB8E4
gUnk_08FDB8E4:  @ LZ77
gUnk_08FDB8E4:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/66_karla.lz"

	.global gUnk_08FDB944
	.global gUnk_08FDB944
gUnk_08FDB944:  @ LZ77
gUnk_08FDB944:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/67_guy.lz"

	.global gUnk_08FDB9A8
	.global gUnk_08FDB9A8
gUnk_08FDB9A8:  @ LZ77
gUnk_08FDB9A8:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/68_karel.lz"

	.global gUnk_08FDBA08
	.global gUnk_08FDBA08
gUnk_08FDBA08:  @ LZ77
gUnk_08FDBA08:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/69_lloyd.lz"

	.global gUnk_08FDBA58
	.global gUnk_08FDBA58
gUnk_08FDBA58:  @ LZ77
gUnk_08FDBA58:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/6A_laila.lz"

	.global gUnk_08FDBAA8
	.global gUnk_08FDBAA8
gUnk_08FDBAA8:  @ LZ77
gUnk_08FDBAA8:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/6B_lagarto.lz"

	.global gUnk_08FDBB0C
	.global gUnk_08FDBB0C
gUnk_08FDBB0C:  @ LZ77
gUnk_08FDBB0C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/6C_matthew.lz"

	.global gUnk_08FDBB74
	.global gUnk_08FDBB74
gUnk_08FDBB74:  @ LZ77
gUnk_08FDBB74:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/6D_priscilla.lz"

	.global gUnk_08FDBBD0
	.global gUnk_08FDBBD0
gUnk_08FDBBD0:  @ LZ77
gUnk_08FDBBD0:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/6E_priscilla.lz"

	.global gUnk_08FDBC3C
	.global gUnk_08FDBC3C
gUnk_08FDBC3C:  @ LZ77
gUnk_08FDBC3C:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/6F_ursula.lz"

	.global gUnk_08FDBCA0
	.global gUnk_08FDBCA0
gUnk_08FDBCA0:  @ LZ77
gUnk_08FDBCA0:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/70_baltr.lz"

	.global gUnk_08FDBCFC
	.global gUnk_08FDBCFC
gUnk_08FDBCFC:  @ LZ77
gUnk_08FDBCFC:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/71_brendan.lz"

	.global gUnk_08FDBD58
	.global gUnk_08FDBD58
gUnk_08FDBD58:  @ LZ77
gUnk_08FDBD58:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/72_dorcas.lz"

	.global gUnk_08FDBDB4
	.global gUnk_08FDBDB4
gUnk_08FDBDB4:  @ LZ77
gUnk_08FDBDB4:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/73_gaitz.lz"

	.global gUnk_08FDBE14
	.global gUnk_08FDBE14
gUnk_08FDBE14:  @ LZ77
gUnk_08FDBE14:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/74_jasmine.lz"

	.global gUnk_08FDBE70
	.global gUnk_08FDBE70
gUnk_08FDBE70:  @ LZ77
gUnk_08FDBE70:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/75_olg.lz"

	.global gUnk_08FDBECC
	.global gUnk_08FDBECC
gUnk_08FDBECC:  @ LZ77
gUnk_08FDBECC:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/76_paul.lz"

	.global gUnk_08FDBF28
	.global gUnk_08FDBF28
gUnk_08FDBF28:  @ LZ77
gUnk_08FDBF28:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/77_kishuna.lz"

	.global gUnk_08FDBF64
	.global gUnk_08FDBF64
gUnk_08FDBF64:  @ LZ77
gUnk_08FDBF64:  @ LZ77
	.incbin "build/graphics/banim/chara_pal/78_groznyi.lz"
	.incbin "baserom.gba", 0xfdbfb8, 0x2d34

	.global gUnk_08FDECEC
	.global gUnk_08FDECEC
gUnk_08FDECEC:
gUnk_08FDECEC:
	.incbin "baserom.gba", 0xfdecec, 0x60c

	.global gUnk_08FDF2F8
	.global gUnk_08FDF2F8
gUnk_08FDF2F8:
gUnk_08FDF2F8:
	.incbin "baserom.gba", 0xfdf2f8, 0x410

	.global gUnk_08FDF708
	.global gUnk_08FDF708
gUnk_08FDF708:
gUnk_08FDF708:
	.incbin "baserom.gba", 0xfdf708, 0xc18

	.global gUnk_08FE0320
	.global gUnk_08FE0320
gUnk_08FE0320:
gUnk_08FE0320:
	.incbin "baserom.gba", 0xfe0320, 0xe00

	.global gUnk_08FE1120
	.global gUnk_08FE1120
gUnk_08FE1120:
gUnk_08FE1120:
	.incbin "baserom.gba", 0xfe1120, 0x1014
