@ ROM data 0x08e52100-0x08e8fc74 (not yet in source)
@ Generated by tools/datasplit.py: labels, incbin and .4byte pointers.
@ Labels may be renamed here; rerun the tool then (it rewrites the
@ .4byte references) and after changing data/layout.txt.

	.section .rodata.08E52100, "a"

	.global gUnk_08E52100
gUnk_08E52100:  @ LZ77
	.incbin "baserom.gba", 0xe52100, 0x68c

	.global gUnk_08E5278C
gUnk_08E5278C:  @ LZ77
	.incbin "baserom.gba", 0xe5278c, 0x678

	.global gUnk_08E52E04
gUnk_08E52E04:  @ LZ77
	.incbin "baserom.gba", 0xe52e04, 0x278

	.global gUnk_08E5307C
gUnk_08E5307C:
	.incbin "baserom.gba", 0xe5307c, 0x60

	.global gUnk_08E530DC
gUnk_08E530DC:  @ LZ77
	.incbin "baserom.gba", 0xe530dc, 0x4c

	.global gUnk_08E53128
gUnk_08E53128:  @ LZ77
	.incbin "baserom.gba", 0xe53128, 0x218

	.global gUnk_08E53340
gUnk_08E53340:  @ LZ77
	.incbin "baserom.gba", 0xe53340, 0x214

	.global gUnk_08E53554
gUnk_08E53554:  @ LZ77
	.incbin "baserom.gba", 0xe53554, 0x11c

	.global gUnk_08E53670
gUnk_08E53670:
	.incbin "baserom.gba", 0xe53670, 0x60

	.global gUnk_08E536D0
gUnk_08E536D0:  @ LZ77
	.incbin "baserom.gba", 0xe536d0, 0x4c

	.global gUnk_08E5371C
gUnk_08E5371C:  @ LZ77
	.incbin "baserom.gba", 0xe5371c, 0x88

	.global gUnk_08E537A4
gUnk_08E537A4:  @ LZ77
	.incbin "baserom.gba", 0xe537a4, 0x84

	.global gUnk_08E53828
gUnk_08E53828:  @ LZ77
	.incbin "baserom.gba", 0xe53828, 0x84

	.global gUnk_08E538AC
gUnk_08E538AC:
	.incbin "baserom.gba", 0xe538ac, 0x22bc

	.global gUnk_08E55B68
gUnk_08E55B68:  @ LZ77
	.incbin "baserom.gba", 0xe55b68, 0x54

	.global gUnk_08E55BBC
gUnk_08E55BBC:  @ LZ77
	.incbin "baserom.gba", 0xe55bbc, 0x338

	.global gUnk_08E55EF4
gUnk_08E55EF4:  @ LZ77
	.incbin "baserom.gba", 0xe55ef4, 0x334

	.global gUnk_08E56228
gUnk_08E56228:  @ LZ77
	.incbin "baserom.gba", 0xe56228, 0x148

	.global gUnk_08E56370
gUnk_08E56370:
	.incbin "baserom.gba", 0xe56370, 0x60

	.global gUnk_08E563D0
gUnk_08E563D0:  @ LZ77
	.incbin "baserom.gba", 0xe563d0, 0x54

	.global gUnk_08E56424
gUnk_08E56424:  @ LZ77
	.incbin "baserom.gba", 0xe56424, 0x288

	.global gUnk_08E566AC
gUnk_08E566AC:  @ LZ77
	.incbin "baserom.gba", 0xe566ac, 0x288

	.global gUnk_08E56934
gUnk_08E56934:  @ LZ77
	.incbin "baserom.gba", 0xe56934, 0x100

	.global gUnk_08E56A34
gUnk_08E56A34:
	.incbin "baserom.gba", 0xe56a34, 0x60

	.global gUnk_08E56A94
gUnk_08E56A94:  @ LZ77
	.incbin "baserom.gba", 0xe56a94, 0x54

	.global gUnk_08E56AE8
gUnk_08E56AE8:  @ LZ77
	.incbin "baserom.gba", 0xe56ae8, 0xb0

	.global gUnk_08E56B98
gUnk_08E56B98:  @ LZ77
	.incbin "baserom.gba", 0xe56b98, 0xb0

	.global gUnk_08E56C48
gUnk_08E56C48:  @ LZ77
	.incbin "baserom.gba", 0xe56c48, 0x84

	.global gUnk_08E56CCC
gUnk_08E56CCC:
	.incbin "baserom.gba", 0xe56ccc, 0x4808

	.global gUnk_08E5B4D4
gUnk_08E5B4D4:  @ LZ77
	.incbin "baserom.gba", 0xe5b4d4, 0x4c

	.global gUnk_08E5B520
gUnk_08E5B520:  @ LZ77
	.incbin "baserom.gba", 0xe5b520, 0x894

	.global gUnk_08E5BDB4
gUnk_08E5BDB4:  @ LZ77
	.incbin "baserom.gba", 0xe5bdb4, 0x888

	.global gUnk_08E5C63C
gUnk_08E5C63C:  @ LZ77
	.incbin "baserom.gba", 0xe5c63c, 0x290

	.global gUnk_08E5C8CC
gUnk_08E5C8CC:
	.incbin "baserom.gba", 0xe5c8cc, 0x60

	.global gUnk_08E5C92C
gUnk_08E5C92C:  @ LZ77
	.incbin "baserom.gba", 0xe5c92c, 0x4c

	.global gUnk_08E5C978
gUnk_08E5C978:  @ LZ77
	.incbin "baserom.gba", 0xe5c978, 0x278

	.global gUnk_08E5CBF0
gUnk_08E5CBF0:  @ LZ77
	.incbin "baserom.gba", 0xe5cbf0, 0x270

	.global gUnk_08E5CE60
gUnk_08E5CE60:  @ LZ77
	.incbin "baserom.gba", 0xe5ce60, 0x11c

	.global gUnk_08E5CF7C
gUnk_08E5CF7C:
	.incbin "baserom.gba", 0xe5cf7c, 0x60

	.global gUnk_08E5CFDC
gUnk_08E5CFDC:  @ LZ77
	.incbin "baserom.gba", 0xe5cfdc, 0x4c

	.global gUnk_08E5D028
gUnk_08E5D028:  @ LZ77
	.incbin "baserom.gba", 0xe5d028, 0x108

	.global gUnk_08E5D130
gUnk_08E5D130:  @ LZ77
	.incbin "baserom.gba", 0xe5d130, 0x104

	.global gUnk_08E5D234
gUnk_08E5D234:  @ LZ77
	.incbin "baserom.gba", 0xe5d234, 0x88

	.global gUnk_08E5D2BC
gUnk_08E5D2BC:
	.incbin "baserom.gba", 0xe5d2bc, 0x4554

	.global gUnk_08E61810
gUnk_08E61810:  @ LZ77
	.incbin "baserom.gba", 0xe61810, 0x4c

	.global gUnk_08E6185C
gUnk_08E6185C:  @ LZ77
	.incbin "baserom.gba", 0xe6185c, 0x96c

	.global gUnk_08E621C8
gUnk_08E621C8:  @ LZ77
	.incbin "baserom.gba", 0xe621c8, 0x968

	.global gUnk_08E62B30
gUnk_08E62B30:  @ LZ77
	.incbin "baserom.gba", 0xe62b30, 0x29c

	.global gUnk_08E62DCC
gUnk_08E62DCC:
	.incbin "baserom.gba", 0xe62dcc, 0x60

	.global gUnk_08E62E2C
gUnk_08E62E2C:  @ LZ77
	.incbin "baserom.gba", 0xe62e2c, 0x4c

	.global gUnk_08E62E78
gUnk_08E62E78:  @ LZ77
	.incbin "baserom.gba", 0xe62e78, 0x2cc

	.global gUnk_08E63144
gUnk_08E63144:  @ LZ77
	.incbin "baserom.gba", 0xe63144, 0x2d0

	.global gUnk_08E63414
gUnk_08E63414:  @ LZ77
	.incbin "baserom.gba", 0xe63414, 0x128

	.global gUnk_08E6353C
gUnk_08E6353C:
	.incbin "baserom.gba", 0xe6353c, 0x60

	.global gUnk_08E6359C
gUnk_08E6359C:  @ LZ77
	.incbin "baserom.gba", 0xe6359c, 0x4c

	.global gUnk_08E635E8
gUnk_08E635E8:  @ LZ77
	.incbin "baserom.gba", 0xe635e8, 0xcc

	.global gUnk_08E636B4
gUnk_08E636B4:  @ LZ77
	.incbin "baserom.gba", 0xe636b4, 0xc4

	.global gUnk_08E63778
gUnk_08E63778:  @ LZ77
	.incbin "baserom.gba", 0xe63778, 0x54

	.global gUnk_08E637CC
gUnk_08E637CC:
	.incbin "baserom.gba", 0xe637cc, 0x7c90

	.global gUnk_08E6B45C
gUnk_08E6B45C:  @ LZ77
	.incbin "baserom.gba", 0xe6b45c, 0x4c

	.global gUnk_08E6B4A8
gUnk_08E6B4A8:  @ LZ77
	.incbin "baserom.gba", 0xe6b4a8, 0xdf4

	.global gUnk_08E6C29C
gUnk_08E6C29C:  @ LZ77
	.incbin "baserom.gba", 0xe6c29c, 0xe0c

	.global gUnk_08E6D0A8
gUnk_08E6D0A8:  @ LZ77
	.incbin "baserom.gba", 0xe6d0a8, 0x3f8

	.global gUnk_08E6D4A0
gUnk_08E6D4A0:
	.incbin "baserom.gba", 0xe6d4a0, 0x60

	.global gUnk_08E6D500
gUnk_08E6D500:  @ LZ77
	.incbin "baserom.gba", 0xe6d500, 0x4c

	.global gUnk_08E6D54C
gUnk_08E6D54C:  @ LZ77
	.incbin "baserom.gba", 0xe6d54c, 0xaf4

	.global gUnk_08E6E040
gUnk_08E6E040:  @ LZ77
	.incbin "baserom.gba", 0xe6e040, 0xb0c

	.global gUnk_08E6EB4C
gUnk_08E6EB4C:  @ LZ77
	.incbin "baserom.gba", 0xe6eb4c, 0x1e0

	.global gUnk_08E6ED2C
gUnk_08E6ED2C:
	.incbin "baserom.gba", 0xe6ed2c, 0x3280

	.global gUnk_08E71FAC
gUnk_08E71FAC:  @ LZ77
	.incbin "baserom.gba", 0xe71fac, 0x4c

	.global gUnk_08E71FF8
gUnk_08E71FF8:  @ LZ77
	.incbin "baserom.gba", 0xe71ff8, 0x504

	.global gUnk_08E724FC
gUnk_08E724FC:  @ LZ77
	.incbin "baserom.gba", 0xe724fc, 0x4ec

	.global gUnk_08E729E8
gUnk_08E729E8:  @ LZ77
	.incbin "baserom.gba", 0xe729e8, 0x1e0

	.global gUnk_08E72BC8
gUnk_08E72BC8:
	.incbin "baserom.gba", 0xe72bc8, 0x60

	.global gUnk_08E72C28
gUnk_08E72C28:  @ LZ77
	.incbin "baserom.gba", 0xe72c28, 0x4c

	.global gUnk_08E72C74
gUnk_08E72C74:  @ LZ77
	.incbin "baserom.gba", 0xe72c74, 0x98

	.global gUnk_08E72D0C
gUnk_08E72D0C:  @ LZ77
	.incbin "baserom.gba", 0xe72d0c, 0x94

	.global gUnk_08E72DA0
gUnk_08E72DA0:  @ LZ77
	.incbin "baserom.gba", 0xe72da0, 0x78

	.global gUnk_08E72E18
gUnk_08E72E18:
	.incbin "baserom.gba", 0xe72e18, 0x1ee4

	.global gUnk_08E74CFC
gUnk_08E74CFC:  @ LZ77
	.incbin "baserom.gba", 0xe74cfc, 0x68

	.global gUnk_08E74D64
gUnk_08E74D64:  @ LZ77
	.incbin "baserom.gba", 0xe74d64, 0x474

	.global gUnk_08E751D8
gUnk_08E751D8:  @ LZ77
	.incbin "baserom.gba", 0xe751d8, 0x47c

	.global gUnk_08E75654
gUnk_08E75654:  @ LZ77
	.incbin "baserom.gba", 0xe75654, 0x1e0

	.global gUnk_08E75834
gUnk_08E75834:
	.incbin "baserom.gba", 0xe75834, 0x60

	.global gUnk_08E75894
gUnk_08E75894:  @ LZ77
	.incbin "baserom.gba", 0xe75894, 0x68

	.global gUnk_08E758FC
gUnk_08E758FC:  @ LZ77
	.incbin "baserom.gba", 0xe758fc, 0xcc

	.global gUnk_08E759C8
gUnk_08E759C8:  @ LZ77
	.incbin "baserom.gba", 0xe759c8, 0xc8

	.global gUnk_08E75A90
gUnk_08E75A90:  @ LZ77
	.incbin "baserom.gba", 0xe75a90, 0x58

	.global gUnk_08E75AE8
gUnk_08E75AE8:
	.incbin "baserom.gba", 0xe75ae8, 0x1e04

	.global gUnk_08E778EC
gUnk_08E778EC:  @ LZ77
	.incbin "baserom.gba", 0xe778ec, 0x68

	.global gUnk_08E77954
gUnk_08E77954:  @ LZ77
	.incbin "baserom.gba", 0xe77954, 0x474

	.global gUnk_08E77DC8
gUnk_08E77DC8:  @ LZ77
	.incbin "baserom.gba", 0xe77dc8, 0x47c

	.global gUnk_08E78244
gUnk_08E78244:  @ LZ77
	.incbin "baserom.gba", 0xe78244, 0x1e0

	.global gUnk_08E78424
gUnk_08E78424:
	.incbin "baserom.gba", 0xe78424, 0x60

	.global gUnk_08E78484
gUnk_08E78484:  @ LZ77
	.incbin "baserom.gba", 0xe78484, 0x68

	.global gUnk_08E784EC
gUnk_08E784EC:  @ LZ77
	.incbin "baserom.gba", 0xe784ec, 0xcc

	.global gUnk_08E785B8
gUnk_08E785B8:  @ LZ77
	.incbin "baserom.gba", 0xe785b8, 0xc8

	.global gUnk_08E78680
gUnk_08E78680:  @ LZ77
	.incbin "baserom.gba", 0xe78680, 0x58

	.global gUnk_08E786D8
gUnk_08E786D8:
	.incbin "baserom.gba", 0xe786d8, 0x1ef8

	.global gUnk_08E7A5D0
gUnk_08E7A5D0:  @ LZ77
	.incbin "baserom.gba", 0xe7a5d0, 0x68

	.global gUnk_08E7A638
gUnk_08E7A638:  @ LZ77
	.incbin "baserom.gba", 0xe7a638, 0x4a0

	.global gUnk_08E7AAD8
gUnk_08E7AAD8:  @ LZ77
	.incbin "baserom.gba", 0xe7aad8, 0x4a0

	.global gUnk_08E7AF78
gUnk_08E7AF78:  @ LZ77
	.incbin "baserom.gba", 0xe7af78, 0x1e4

	.global gUnk_08E7B15C
gUnk_08E7B15C:
	.incbin "baserom.gba", 0xe7b15c, 0x60

	.global gUnk_08E7B1BC
gUnk_08E7B1BC:  @ LZ77
	.incbin "baserom.gba", 0xe7b1bc, 0x68

	.global gUnk_08E7B224
gUnk_08E7B224:  @ LZ77
	.incbin "baserom.gba", 0xe7b224, 0xac

	.global gUnk_08E7B2D0
gUnk_08E7B2D0:  @ LZ77
	.incbin "baserom.gba", 0xe7b2d0, 0xa8

	.global gUnk_08E7B378
gUnk_08E7B378:  @ LZ77
	.incbin "baserom.gba", 0xe7b378, 0x58

	.global gUnk_08E7B3D0
gUnk_08E7B3D0:
	.incbin "baserom.gba", 0xe7b3d0, 0x1d2c

	.global gUnk_08E7D0FC
gUnk_08E7D0FC:  @ LZ77
	.incbin "baserom.gba", 0xe7d0fc, 0x68

	.global gUnk_08E7D164
gUnk_08E7D164:  @ LZ77
	.incbin "baserom.gba", 0xe7d164, 0x4a0

	.global gUnk_08E7D604
gUnk_08E7D604:  @ LZ77
	.incbin "baserom.gba", 0xe7d604, 0x4a0

	.global gUnk_08E7DAA4
gUnk_08E7DAA4:  @ LZ77
	.incbin "baserom.gba", 0xe7daa4, 0x1e4

	.global gUnk_08E7DC88
gUnk_08E7DC88:
	.incbin "baserom.gba", 0xe7dc88, 0x60

	.global gUnk_08E7DCE8
gUnk_08E7DCE8:  @ LZ77
	.incbin "baserom.gba", 0xe7dce8, 0x68

	.global gUnk_08E7DD50
gUnk_08E7DD50:  @ LZ77
	.incbin "baserom.gba", 0xe7dd50, 0xac

	.global gUnk_08E7DDFC
gUnk_08E7DDFC:  @ LZ77
	.incbin "baserom.gba", 0xe7ddfc, 0xa8

	.global gUnk_08E7DEA4
gUnk_08E7DEA4:  @ LZ77
	.incbin "baserom.gba", 0xe7dea4, 0x58

	.global gUnk_08E7DEFC
gUnk_08E7DEFC:
	.incbin "baserom.gba", 0xe7defc, 0x3b00

	.global gUnk_08E819FC
gUnk_08E819FC:  @ LZ77
	.incbin "baserom.gba", 0xe819fc, 0x5c

	.global gUnk_08E81A58
gUnk_08E81A58:  @ LZ77
	.incbin "baserom.gba", 0xe81a58, 0xe48

	.global gUnk_08E828A0
gUnk_08E828A0:  @ LZ77
	.incbin "baserom.gba", 0xe828a0, 0xe28

	.global gUnk_08E836C8
gUnk_08E836C8:  @ LZ77
	.incbin "baserom.gba", 0xe836c8, 0x494

	.global gUnk_08E83B5C
gUnk_08E83B5C:
	.incbin "baserom.gba", 0xe83b5c, 0x60

	.global gUnk_08E83BBC
gUnk_08E83BBC:  @ LZ77
	.incbin "baserom.gba", 0xe83bbc, 0x5c

	.global gUnk_08E83C18
gUnk_08E83C18:  @ LZ77
	.incbin "baserom.gba", 0xe83c18, 0xac

	.global gUnk_08E83CC4
gUnk_08E83CC4:  @ LZ77
	.incbin "baserom.gba", 0xe83cc4, 0xb0

	.global gUnk_08E83D74
gUnk_08E83D74:  @ LZ77
	.incbin "baserom.gba", 0xe83d74, 0x84

	.global gUnk_08E83DF8
gUnk_08E83DF8:
	.incbin "baserom.gba", 0xe83df8, 0x42d4

	.global gUnk_08E880CC
gUnk_08E880CC:  @ LZ77
	.incbin "baserom.gba", 0xe880cc, 0x4c

	.global gUnk_08E88118
gUnk_08E88118:  @ LZ77
	.incbin "baserom.gba", 0xe88118, 0x15c8

	.global gUnk_08E896E0
gUnk_08E896E0:  @ LZ77
	.incbin "baserom.gba", 0xe896e0, 0x15c0

	.global gUnk_08E8ACA0
gUnk_08E8ACA0:  @ LZ77
	.incbin "baserom.gba", 0xe8aca0, 0x6f8

	.global gUnk_08E8B398
gUnk_08E8B398:
	.incbin "baserom.gba", 0xe8b398, 0x60

	.global gUnk_08E8B3F8
gUnk_08E8B3F8:  @ LZ77
	.incbin "baserom.gba", 0xe8b3f8, 0x4c

	.global gUnk_08E8B444
gUnk_08E8B444:  @ LZ77
	.incbin "baserom.gba", 0xe8b444, 0x16c8

	.global gUnk_08E8CB0C
gUnk_08E8CB0C:  @ LZ77
	.incbin "baserom.gba", 0xe8cb0c, 0x16c4

	.global gUnk_08E8E1D0
gUnk_08E8E1D0:  @ LZ77
	.incbin "baserom.gba", 0xe8e1d0, 0x6e8

	.global gUnk_08E8E8B8
gUnk_08E8E8B8:
	.incbin "baserom.gba", 0xe8e8b8, 0xa8c

	.global gUnk_08E8F344
gUnk_08E8F344:  @ LZ77
	.incbin "baserom.gba", 0xe8f344, 0x4c

	.global gUnk_08E8F390
gUnk_08E8F390:  @ LZ77
	.incbin "baserom.gba", 0xe8f390, 0x25c

	.global gUnk_08E8F5EC
gUnk_08E8F5EC:  @ LZ77
	.incbin "baserom.gba", 0xe8f5ec, 0x250

	.global gUnk_08E8F83C
gUnk_08E8F83C:  @ LZ77
	.incbin "baserom.gba", 0xe8f83c, 0x148

	.global gUnk_08E8F984
gUnk_08E8F984:
	.incbin "baserom.gba", 0xe8f984, 0x60

	.global gUnk_08E8F9E4
gUnk_08E8F9E4:  @ LZ77
	.incbin "baserom.gba", 0xe8f9e4, 0x4c

	.global gUnk_08E8FA30
gUnk_08E8FA30:  @ LZ77
	.incbin "baserom.gba", 0xe8fa30, 0xe0

	.global gUnk_08E8FB10
gUnk_08E8FB10:  @ LZ77
	.incbin "baserom.gba", 0xe8fb10, 0xdc

	.global gUnk_08E8FBEC
gUnk_08E8FBEC:  @ LZ77
	.incbin "baserom.gba", 0xe8fbec, 0x88
