@ ROM data 0x08fcc4f0-0x09000000 (not yet in source)
@ Generated by tools/datasplit.py: labels + incbin only.  Labels may be
@ renamed here; rerun the tool after changing data/layout.txt.

	.section .rodata.08FCC4F0, "a"

	.global gUnk_08FCC4F0
gUnk_08FCC4F0:  @ LZ77
	.incbin "baserom.gba", 0xfcc4f0, 0x77c

	.global gUnk_08FCCC6C
gUnk_08FCCC6C:
	.incbin "baserom.gba", 0xfccc6c, 0x20

	.global gUnk_08FCCC8C
gUnk_08FCCC8C:  @ LZ77
	.incbin "baserom.gba", 0xfccc8c, 0x784

	.global gUnk_08FCD410
gUnk_08FCD410:
	.incbin "baserom.gba", 0xfcd410, 0x20

	.global gUnk_08FCD430
gUnk_08FCD430:  @ LZ77
	.incbin "baserom.gba", 0xfcd430, 0x908

	.global gUnk_08FCDD38
gUnk_08FCDD38:
	.incbin "baserom.gba", 0xfcdd38, 0x20

	.global gUnk_08FCDD58
gUnk_08FCDD58:  @ LZ77
	.incbin "baserom.gba", 0xfcdd58, 0x6c8

	.global gUnk_08FCE420
gUnk_08FCE420:
	.incbin "baserom.gba", 0xfce420, 0x20

	.global gUnk_08FCE440
gUnk_08FCE440:  @ LZ77
	.incbin "baserom.gba", 0xfce440, 0x678

	.global gUnk_08FCEAB8
gUnk_08FCEAB8:
	.incbin "baserom.gba", 0xfceab8, 0x20

	.global gUnk_08FCEAD8
gUnk_08FCEAD8:  @ LZ77
	.incbin "baserom.gba", 0xfcead8, 0x6bc

	.global gUnk_08FCF194
gUnk_08FCF194:
	.incbin "baserom.gba", 0xfcf194, 0x20

	.global gUnk_08FCF1B4
gUnk_08FCF1B4:  @ LZ77
	.incbin "baserom.gba", 0xfcf1b4, 0x6dc

	.global gUnk_08FCF890
gUnk_08FCF890:
	.incbin "baserom.gba", 0xfcf890, 0x20

	.global gUnk_08FCF8B0
gUnk_08FCF8B0:  @ LZ77
	.incbin "baserom.gba", 0xfcf8b0, 0x764

	.global gUnk_08FD0014
gUnk_08FD0014:
	.incbin "baserom.gba", 0xfd0014, 0x20

	.global gUnk_08FD0034
gUnk_08FD0034:  @ LZ77
	.incbin "baserom.gba", 0xfd0034, 0x884

	.global gUnk_08FD08B8
gUnk_08FD08B8:
	.incbin "baserom.gba", 0xfd08b8, 0x20

	.global gUnk_08FD08D8
gUnk_08FD08D8:  @ LZ77
	.incbin "baserom.gba", 0xfd08d8, 0x6ac

	.global gUnk_08FD0F84
gUnk_08FD0F84:
	.incbin "baserom.gba", 0xfd0f84, 0x20

	.global gUnk_08FD0FA4
gUnk_08FD0FA4:  @ LZ77
	.incbin "baserom.gba", 0xfd0fa4, 0x654

	.global gUnk_08FD15F8
gUnk_08FD15F8:
	.incbin "baserom.gba", 0xfd15f8, 0x20

	.global gUnk_08FD1618
gUnk_08FD1618:
	.incbin "baserom.gba", 0xfd1618, 0x20

	.global gUnk_08FD1638
gUnk_08FD1638:
	.incbin "baserom.gba", 0xfd1638, 0x20

	.global gUnk_08FD1658
gUnk_08FD1658:
	.incbin "baserom.gba", 0xfd1658, 0x20

	.global gUnk_08FD1678
gUnk_08FD1678:
	.incbin "baserom.gba", 0xfd1678, 0x20

	.global gUnk_08FD1698
gUnk_08FD1698:
	.incbin "baserom.gba", 0xfd1698, 0x20

	.global gUnk_08FD16B8
gUnk_08FD16B8:
	.incbin "baserom.gba", 0xfd16b8, 0x20

	.global gUnk_08FD16D8
gUnk_08FD16D8:
	.incbin "baserom.gba", 0xfd16d8, 0x20

	.global gUnk_08FD16F8
gUnk_08FD16F8:
	.incbin "baserom.gba", 0xfd16f8, 0x20

	.global gUnk_08FD1718
gUnk_08FD1718:
	.incbin "baserom.gba", 0xfd1718, 0x20

	.global gUnk_08FD1738
gUnk_08FD1738:
	.incbin "baserom.gba", 0xfd1738, 0x20

	.global gUnk_08FD1758
gUnk_08FD1758:
	.incbin "baserom.gba", 0xfd1758, 0x20

	.global gUnk_08FD1778
gUnk_08FD1778:
	.incbin "baserom.gba", 0xfd1778, 0x20

	.global gUnk_08FD1798
gUnk_08FD1798:
	.incbin "baserom.gba", 0xfd1798, 0x20

	.global gUnk_08FD17B8
gUnk_08FD17B8:
	.incbin "baserom.gba", 0xfd17b8, 0x20

	.global gUnk_08FD17D8
gUnk_08FD17D8:
	.incbin "baserom.gba", 0xfd17d8, 0x20

	.global gUnk_08FD17F8
gUnk_08FD17F8:
	.incbin "baserom.gba", 0xfd17f8, 0x20

	.global gUnk_08FD1818
gUnk_08FD1818:
	.incbin "baserom.gba", 0xfd1818, 0x20

	.global gUnk_08FD1838
gUnk_08FD1838:
	.incbin "baserom.gba", 0xfd1838, 0x20

	.global gUnk_08FD1858
gUnk_08FD1858:
	.incbin "baserom.gba", 0xfd1858, 0x20

	.global gUnk_08FD1878
gUnk_08FD1878:
	.incbin "baserom.gba", 0xfd1878, 0x20

	.global gUnk_08FD1898
gUnk_08FD1898:
	.incbin "baserom.gba", 0xfd1898, 0x20

	.global gUnk_08FD18B8
gUnk_08FD18B8:
	.incbin "baserom.gba", 0xfd18b8, 0x20

	.global gUnk_08FD18D8
gUnk_08FD18D8:
	.incbin "baserom.gba", 0xfd18d8, 0x20

	.global gUnk_08FD18F8
gUnk_08FD18F8:
	.incbin "baserom.gba", 0xfd18f8, 0x20

	.global gUnk_08FD1918
gUnk_08FD1918:
	.incbin "baserom.gba", 0xfd1918, 0x20

	.global gUnk_08FD1938
gUnk_08FD1938:
	.incbin "baserom.gba", 0xfd1938, 0x20

	.global gUnk_08FD1958
gUnk_08FD1958:
	.incbin "baserom.gba", 0xfd1958, 0x20

	.global gUnk_08FD1978
gUnk_08FD1978:
	.incbin "baserom.gba", 0xfd1978, 0x20

	.global gUnk_08FD1998
gUnk_08FD1998:
	.incbin "baserom.gba", 0xfd1998, 0x20

	.global gUnk_08FD19B8
gUnk_08FD19B8:
	.incbin "baserom.gba", 0xfd19b8, 0x20

	.global gUnk_08FD19D8
gUnk_08FD19D8:
	.incbin "baserom.gba", 0xfd19d8, 0x20

	.global gUnk_08FD19F8
gUnk_08FD19F8:
	.incbin "baserom.gba", 0xfd19f8, 0x20

	.global gUnk_08FD1A18
gUnk_08FD1A18:
	.incbin "baserom.gba", 0xfd1a18, 0x20

	.global gUnk_08FD1A38
gUnk_08FD1A38:
	.incbin "baserom.gba", 0xfd1a38, 0x20

	.global gUnk_08FD1A58
gUnk_08FD1A58:
	.incbin "baserom.gba", 0xfd1a58, 0x20

	.global gUnk_08FD1A78
gUnk_08FD1A78:
	.incbin "baserom.gba", 0xfd1a78, 0x20

	.global gUnk_08FD1A98
gUnk_08FD1A98:
	.incbin "baserom.gba", 0xfd1a98, 0x20

	.global gUnk_08FD1AB8
gUnk_08FD1AB8:
	.incbin "baserom.gba", 0xfd1ab8, 0x20

	.global gUnk_08FD1AD8
gUnk_08FD1AD8:
	.incbin "baserom.gba", 0xfd1ad8, 0x20

	.global gUnk_08FD1AF8
gUnk_08FD1AF8:
	.incbin "baserom.gba", 0xfd1af8, 0x20

	.global gUnk_08FD1B18
gUnk_08FD1B18:  @ LZ77
	.incbin "baserom.gba", 0xfd1b18, 0x748

	.global gUnk_08FD2260
gUnk_08FD2260:
	.incbin "baserom.gba", 0xfd2260, 0x20

	.global gUnk_08FD2280
gUnk_08FD2280:
	.incbin "baserom.gba", 0xfd2280, 0x20

	.global gUnk_08FD22A0
gUnk_08FD22A0:
	.incbin "baserom.gba", 0xfd22a0, 0x20

	.global gUnk_08FD22C0
gUnk_08FD22C0:
	.incbin "baserom.gba", 0xfd22c0, 0x20

	.global gUnk_08FD22E0
gUnk_08FD22E0:
	.incbin "baserom.gba", 0xfd22e0, 0x20

	.global gUnk_08FD2300
gUnk_08FD2300:
	.incbin "baserom.gba", 0xfd2300, 0x20

	.global gUnk_08FD2320
gUnk_08FD2320:
	.incbin "baserom.gba", 0xfd2320, 0x20

	.global gUnk_08FD2340
gUnk_08FD2340:
	.incbin "baserom.gba", 0xfd2340, 0x20

	.global gUnk_08FD2360
gUnk_08FD2360:
	.incbin "baserom.gba", 0xfd2360, 0x20

	.global gUnk_08FD2380
gUnk_08FD2380:
	.incbin "baserom.gba", 0xfd2380, 0x20

	.global gUnk_08FD23A0
gUnk_08FD23A0:
	.incbin "baserom.gba", 0xfd23a0, 0x20

	.global gUnk_08FD23C0
gUnk_08FD23C0:
	.incbin "baserom.gba", 0xfd23c0, 0x20

	.global gUnk_08FD23E0
gUnk_08FD23E0:
	.incbin "baserom.gba", 0xfd23e0, 0x20

	.global gUnk_08FD2400
gUnk_08FD2400:
	.incbin "baserom.gba", 0xfd2400, 0x20

	.global gUnk_08FD2420
gUnk_08FD2420:
	.incbin "baserom.gba", 0xfd2420, 0x20

	.global gUnk_08FD2440
gUnk_08FD2440:
	.incbin "baserom.gba", 0xfd2440, 0x20

	.global gUnk_08FD2460
gUnk_08FD2460:
	.incbin "baserom.gba", 0xfd2460, 0x20

	.global gUnk_08FD2480
gUnk_08FD2480:
	.incbin "baserom.gba", 0xfd2480, 0x20

	.global gUnk_08FD24A0
gUnk_08FD24A0:
	.incbin "baserom.gba", 0xfd24a0, 0x20

	.global gUnk_08FD24C0
gUnk_08FD24C0:  @ LZ77
	.incbin "baserom.gba", 0xfd24c0, 0x8f8

	.global gUnk_08FD2DB8
gUnk_08FD2DB8:
	.incbin "baserom.gba", 0xfd2db8, 0x20

	.global gUnk_08FD2DD8
gUnk_08FD2DD8:
	.incbin "baserom.gba", 0xfd2dd8, 0x5230

	.global character_battle_animation_palette_table
character_battle_animation_palette_table:
	.incbin "baserom.gba", 0xfd8008, 0xff8

	.global gUnk_08FD9000
gUnk_08FD9000:  @ LZ77
	.incbin "baserom.gba", 0xfd9000, 0x50

	.global gUnk_08FD9050
gUnk_08FD9050:  @ LZ77
	.incbin "baserom.gba", 0xfd9050, 0x64

	.global gUnk_08FD90B4
gUnk_08FD90B4:  @ LZ77
	.incbin "baserom.gba", 0xfd90b4, 0x60

	.global gUnk_08FD9114
gUnk_08FD9114:  @ LZ77
	.incbin "baserom.gba", 0xfd9114, 0x6c

	.global gUnk_08FD9180
gUnk_08FD9180:  @ LZ77
	.incbin "baserom.gba", 0xfd9180, 0x6c

	.global gUnk_08FD91EC
gUnk_08FD91EC:  @ LZ77
	.incbin "baserom.gba", 0xfd91ec, 0x6c

	.global gUnk_08FD9258
gUnk_08FD9258:  @ LZ77
	.incbin "baserom.gba", 0xfd9258, 0x80

	.global gUnk_08FD92D8
gUnk_08FD92D8:  @ LZ77
	.incbin "baserom.gba", 0xfd92d8, 0x84

	.global gUnk_08FD935C
gUnk_08FD935C:  @ LZ77
	.incbin "baserom.gba", 0xfd935c, 0x80

	.global gUnk_08FD93DC
gUnk_08FD93DC:  @ LZ77
	.incbin "baserom.gba", 0xfd93dc, 0x6c

	.global gUnk_08FD9448
gUnk_08FD9448:  @ LZ77
	.incbin "baserom.gba", 0xfd9448, 0x6c

	.global gUnk_08FD94B4
gUnk_08FD94B4:  @ LZ77
	.incbin "baserom.gba", 0xfd94b4, 0x54

	.global gUnk_08FD9508
gUnk_08FD9508:  @ LZ77
	.incbin "baserom.gba", 0xfd9508, 0x54

	.global gUnk_08FD955C
gUnk_08FD955C:  @ LZ77
	.incbin "baserom.gba", 0xfd955c, 0x5c

	.global gUnk_08FD95B8
gUnk_08FD95B8:  @ LZ77
	.incbin "baserom.gba", 0xfd95b8, 0x58

	.global gUnk_08FD9610
gUnk_08FD9610:  @ LZ77
	.incbin "baserom.gba", 0xfd9610, 0x54

	.global gUnk_08FD9664
gUnk_08FD9664:  @ LZ77
	.incbin "baserom.gba", 0xfd9664, 0x50

	.global gUnk_08FD96B4
gUnk_08FD96B4:  @ LZ77
	.incbin "baserom.gba", 0xfd96b4, 0x50

	.global gUnk_08FD9704
gUnk_08FD9704:  @ LZ77
	.incbin "baserom.gba", 0xfd9704, 0x50

	.global gUnk_08FD9754
gUnk_08FD9754:  @ LZ77
	.incbin "baserom.gba", 0xfd9754, 0x54

	.global gUnk_08FD97A8
gUnk_08FD97A8:  @ LZ77
	.incbin "baserom.gba", 0xfd97a8, 0x50

	.global gUnk_08FD97F8
gUnk_08FD97F8:  @ LZ77
	.incbin "baserom.gba", 0xfd97f8, 0x50

	.global gUnk_08FD9848
gUnk_08FD9848:  @ LZ77
	.incbin "baserom.gba", 0xfd9848, 0x60

	.global gUnk_08FD98A8
gUnk_08FD98A8:  @ LZ77
	.incbin "baserom.gba", 0xfd98a8, 0x60

	.global gUnk_08FD9908
gUnk_08FD9908:  @ LZ77
	.incbin "baserom.gba", 0xfd9908, 0x68

	.global gUnk_08FD9970
gUnk_08FD9970:  @ LZ77
	.incbin "baserom.gba", 0xfd9970, 0x6c

	.global gUnk_08FD99DC
gUnk_08FD99DC:  @ LZ77
	.incbin "baserom.gba", 0xfd99dc, 0x50

	.global gUnk_08FD9A2C
gUnk_08FD9A2C:  @ LZ77
	.incbin "baserom.gba", 0xfd9a2c, 0x58

	.global gUnk_08FD9A84
gUnk_08FD9A84:  @ LZ77
	.incbin "baserom.gba", 0xfd9a84, 0x50

	.global gUnk_08FD9AD4
gUnk_08FD9AD4:  @ LZ77
	.incbin "baserom.gba", 0xfd9ad4, 0x58

	.global gUnk_08FD9B2C
gUnk_08FD9B2C:  @ LZ77
	.incbin "baserom.gba", 0xfd9b2c, 0x50

	.global gUnk_08FD9B7C
gUnk_08FD9B7C:  @ LZ77
	.incbin "baserom.gba", 0xfd9b7c, 0x60

	.global gUnk_08FD9BDC
gUnk_08FD9BDC:  @ LZ77
	.incbin "baserom.gba", 0xfd9bdc, 0x58

	.global gUnk_08FD9C34
gUnk_08FD9C34:  @ LZ77
	.incbin "baserom.gba", 0xfd9c34, 0x50

	.global gUnk_08FD9C84
gUnk_08FD9C84:  @ LZ77
	.incbin "baserom.gba", 0xfd9c84, 0x50

	.global gUnk_08FD9CD4
gUnk_08FD9CD4:  @ LZ77
	.incbin "baserom.gba", 0xfd9cd4, 0x70

	.global gUnk_08FD9D44
gUnk_08FD9D44:  @ LZ77
	.incbin "baserom.gba", 0xfd9d44, 0x70

	.global gUnk_08FD9DB4
gUnk_08FD9DB4:  @ LZ77
	.incbin "baserom.gba", 0xfd9db4, 0x80

	.global gUnk_08FD9E34
gUnk_08FD9E34:  @ LZ77
	.incbin "baserom.gba", 0xfd9e34, 0x78

	.global gUnk_08FD9EAC
gUnk_08FD9EAC:  @ LZ77
	.incbin "baserom.gba", 0xfd9eac, 0x5c

	.global gUnk_08FD9F08
gUnk_08FD9F08:  @ LZ77
	.incbin "baserom.gba", 0xfd9f08, 0x54

	.global gUnk_08FD9F5C
gUnk_08FD9F5C:  @ LZ77
	.incbin "baserom.gba", 0xfd9f5c, 0x50

	.global gUnk_08FD9FAC
gUnk_08FD9FAC:  @ LZ77
	.incbin "baserom.gba", 0xfd9fac, 0x60

	.global gUnk_08FDA00C
gUnk_08FDA00C:  @ LZ77
	.incbin "baserom.gba", 0xfda00c, 0x70

	.global gUnk_08FDA07C
gUnk_08FDA07C:  @ LZ77
	.incbin "baserom.gba", 0xfda07c, 0x70

	.global gUnk_08FDA0EC
gUnk_08FDA0EC:  @ LZ77
	.incbin "baserom.gba", 0xfda0ec, 0x70

	.global gUnk_08FDA15C
gUnk_08FDA15C:  @ LZ77
	.incbin "baserom.gba", 0xfda15c, 0x58

	.global gUnk_08FDA1B4
gUnk_08FDA1B4:  @ LZ77
	.incbin "baserom.gba", 0xfda1b4, 0x58

	.global gUnk_08FDA20C
gUnk_08FDA20C:  @ LZ77
	.incbin "baserom.gba", 0xfda20c, 0x70

	.global gUnk_08FDA27C
gUnk_08FDA27C:  @ LZ77
	.incbin "baserom.gba", 0xfda27c, 0x70

	.global gUnk_08FDA2EC
gUnk_08FDA2EC:  @ LZ77
	.incbin "baserom.gba", 0xfda2ec, 0x88

	.global gUnk_08FDA374
gUnk_08FDA374:  @ LZ77
	.incbin "baserom.gba", 0xfda374, 0x88

	.global gUnk_08FDA3FC
gUnk_08FDA3FC:  @ LZ77
	.incbin "baserom.gba", 0xfda3fc, 0x70

	.global gUnk_08FDA46C
gUnk_08FDA46C:  @ LZ77
	.incbin "baserom.gba", 0xfda46c, 0x5c

	.global gUnk_08FDA4C8
gUnk_08FDA4C8:  @ LZ77
	.incbin "baserom.gba", 0xfda4c8, 0x5c

	.global gUnk_08FDA524
gUnk_08FDA524:  @ LZ77
	.incbin "baserom.gba", 0xfda524, 0x58

	.global gUnk_08FDA57C
gUnk_08FDA57C:  @ LZ77
	.incbin "baserom.gba", 0xfda57c, 0x6c

	.global gUnk_08FDA5E8
gUnk_08FDA5E8:  @ LZ77
	.incbin "baserom.gba", 0xfda5e8, 0x74

	.global gUnk_08FDA65C
gUnk_08FDA65C:  @ LZ77
	.incbin "baserom.gba", 0xfda65c, 0x5c

	.global gUnk_08FDA6B8
gUnk_08FDA6B8:  @ LZ77
	.incbin "baserom.gba", 0xfda6b8, 0x5c

	.global gUnk_08FDA714
gUnk_08FDA714:  @ LZ77
	.incbin "baserom.gba", 0xfda714, 0x6c

	.global gUnk_08FDA780
gUnk_08FDA780:  @ LZ77
	.incbin "baserom.gba", 0xfda780, 0x5c

	.global gUnk_08FDA7DC
gUnk_08FDA7DC:  @ LZ77
	.incbin "baserom.gba", 0xfda7dc, 0x60

	.global gUnk_08FDA83C
gUnk_08FDA83C:  @ LZ77
	.incbin "baserom.gba", 0xfda83c, 0x60

	.global gUnk_08FDA89C
gUnk_08FDA89C:  @ LZ77
	.incbin "baserom.gba", 0xfda89c, 0x74

	.global gUnk_08FDA910
gUnk_08FDA910:  @ LZ77
	.incbin "baserom.gba", 0xfda910, 0x74

	.global gUnk_08FDA984
gUnk_08FDA984:  @ LZ77
	.incbin "baserom.gba", 0xfda984, 0x90

	.global gUnk_08FDAA14
gUnk_08FDAA14:  @ LZ77
	.incbin "baserom.gba", 0xfdaa14, 0x78

	.global gUnk_08FDAA8C
gUnk_08FDAA8C:  @ LZ77
	.incbin "baserom.gba", 0xfdaa8c, 0x78

	.global gUnk_08FDAB04
gUnk_08FDAB04:  @ LZ77
	.incbin "baserom.gba", 0xfdab04, 0x78

	.global gUnk_08FDAB7C
gUnk_08FDAB7C:  @ LZ77
	.incbin "baserom.gba", 0xfdab7c, 0x78

	.global gUnk_08FDABF4
gUnk_08FDABF4:  @ LZ77
	.incbin "baserom.gba", 0xfdabf4, 0x78

	.global gUnk_08FDAC6C
gUnk_08FDAC6C:  @ LZ77
	.incbin "baserom.gba", 0xfdac6c, 0x8c

	.global gUnk_08FDACF8
gUnk_08FDACF8:  @ LZ77
	.incbin "baserom.gba", 0xfdacf8, 0x8c

	.global gUnk_08FDAD84
gUnk_08FDAD84:  @ LZ77
	.incbin "baserom.gba", 0xfdad84, 0x8c

	.global gUnk_08FDAE10
gUnk_08FDAE10:  @ LZ77
	.incbin "baserom.gba", 0xfdae10, 0x78

	.global gUnk_08FDAE88
gUnk_08FDAE88:  @ LZ77
	.incbin "baserom.gba", 0xfdae88, 0x78

	.global gUnk_08FDAF00
gUnk_08FDAF00:  @ LZ77
	.incbin "baserom.gba", 0xfdaf00, 0x8c

	.global gUnk_08FDAF8C
gUnk_08FDAF8C:  @ LZ77
	.incbin "baserom.gba", 0xfdaf8c, 0x6c

	.global gUnk_08FDAFF8
gUnk_08FDAFF8:  @ LZ77
	.incbin "baserom.gba", 0xfdaff8, 0x6c

	.global gUnk_08FDB064
gUnk_08FDB064:  @ LZ77
	.incbin "baserom.gba", 0xfdb064, 0x70

	.global gUnk_08FDB0D4
gUnk_08FDB0D4:  @ LZ77
	.incbin "baserom.gba", 0xfdb0d4, 0x60

	.global gUnk_08FDB134
gUnk_08FDB134:  @ LZ77
	.incbin "baserom.gba", 0xfdb134, 0x60

	.global gUnk_08FDB194
gUnk_08FDB194:  @ LZ77
	.incbin "baserom.gba", 0xfdb194, 0x68

	.global gUnk_08FDB1FC
gUnk_08FDB1FC:  @ LZ77
	.incbin "baserom.gba", 0xfdb1fc, 0x70

	.global gUnk_08FDB26C
gUnk_08FDB26C:  @ LZ77
	.incbin "baserom.gba", 0xfdb26c, 0x68

	.global gUnk_08FDB2D4
gUnk_08FDB2D4:  @ LZ77
	.incbin "baserom.gba", 0xfdb2d4, 0x6c

	.global gUnk_08FDB340
gUnk_08FDB340:  @ LZ77
	.incbin "baserom.gba", 0xfdb340, 0x78

	.global gUnk_08FDB3B8
gUnk_08FDB3B8:  @ LZ77
	.incbin "baserom.gba", 0xfdb3b8, 0x78

	.global gUnk_08FDB430
gUnk_08FDB430:  @ LZ77
	.incbin "baserom.gba", 0xfdb430, 0x54

	.global gUnk_08FDB484
gUnk_08FDB484:  @ LZ77
	.incbin "baserom.gba", 0xfdb484, 0x50

	.global gUnk_08FDB4D4
gUnk_08FDB4D4:  @ LZ77
	.incbin "baserom.gba", 0xfdb4d4, 0x50

	.global gUnk_08FDB524
gUnk_08FDB524:  @ LZ77
	.incbin "baserom.gba", 0xfdb524, 0x64

	.global gUnk_08FDB588
gUnk_08FDB588:  @ LZ77
	.incbin "baserom.gba", 0xfdb588, 0x64

	.global gUnk_08FDB5EC
gUnk_08FDB5EC:  @ LZ77
	.incbin "baserom.gba", 0xfdb5ec, 0x58

	.global gUnk_08FDB644
gUnk_08FDB644:  @ LZ77
	.incbin "baserom.gba", 0xfdb644, 0x60

	.global gUnk_08FDB6A4
gUnk_08FDB6A4:  @ LZ77
	.incbin "baserom.gba", 0xfdb6a4, 0x7c

	.global gUnk_08FDB720
gUnk_08FDB720:  @ LZ77
	.incbin "baserom.gba", 0xfdb720, 0x78

	.global gUnk_08FDB798
gUnk_08FDB798:  @ LZ77
	.incbin "baserom.gba", 0xfdb798, 0x78

	.global gUnk_08FDB810
gUnk_08FDB810:  @ LZ77
	.incbin "baserom.gba", 0xfdb810, 0x78

	.global gUnk_08FDB888
gUnk_08FDB888:  @ LZ77
	.incbin "baserom.gba", 0xfdb888, 0x5c

	.global gUnk_08FDB8E4
gUnk_08FDB8E4:  @ LZ77
	.incbin "baserom.gba", 0xfdb8e4, 0x60

	.global gUnk_08FDB944
gUnk_08FDB944:  @ LZ77
	.incbin "baserom.gba", 0xfdb944, 0x64

	.global gUnk_08FDB9A8
gUnk_08FDB9A8:  @ LZ77
	.incbin "baserom.gba", 0xfdb9a8, 0x60

	.global gUnk_08FDBA08
gUnk_08FDBA08:  @ LZ77
	.incbin "baserom.gba", 0xfdba08, 0x50

	.global gUnk_08FDBA58
gUnk_08FDBA58:  @ LZ77
	.incbin "baserom.gba", 0xfdba58, 0x50

	.global gUnk_08FDBAA8
gUnk_08FDBAA8:  @ LZ77
	.incbin "baserom.gba", 0xfdbaa8, 0x64

	.global gUnk_08FDBB0C
gUnk_08FDBB0C:  @ LZ77
	.incbin "baserom.gba", 0xfdbb0c, 0x68

	.global gUnk_08FDBB74
gUnk_08FDBB74:  @ LZ77
	.incbin "baserom.gba", 0xfdbb74, 0x5c

	.global gUnk_08FDBBD0
gUnk_08FDBBD0:  @ LZ77
	.incbin "baserom.gba", 0xfdbbd0, 0x6c

	.global gUnk_08FDBC3C
gUnk_08FDBC3C:  @ LZ77
	.incbin "baserom.gba", 0xfdbc3c, 0x64

	.global gUnk_08FDBCA0
gUnk_08FDBCA0:  @ LZ77
	.incbin "baserom.gba", 0xfdbca0, 0x5c

	.global gUnk_08FDBCFC
gUnk_08FDBCFC:  @ LZ77
	.incbin "baserom.gba", 0xfdbcfc, 0x5c

	.global gUnk_08FDBD58
gUnk_08FDBD58:  @ LZ77
	.incbin "baserom.gba", 0xfdbd58, 0x5c

	.global gUnk_08FDBDB4
gUnk_08FDBDB4:  @ LZ77
	.incbin "baserom.gba", 0xfdbdb4, 0x60

	.global gUnk_08FDBE14
gUnk_08FDBE14:  @ LZ77
	.incbin "baserom.gba", 0xfdbe14, 0x5c

	.global gUnk_08FDBE70
gUnk_08FDBE70:  @ LZ77
	.incbin "baserom.gba", 0xfdbe70, 0x5c

	.global gUnk_08FDBECC
gUnk_08FDBECC:  @ LZ77
	.incbin "baserom.gba", 0xfdbecc, 0x5c

	.global gUnk_08FDBF28
gUnk_08FDBF28:  @ LZ77
	.incbin "baserom.gba", 0xfdbf28, 0x3c

	.global gUnk_08FDBF64
gUnk_08FDBF64:  @ LZ77
	.incbin "baserom.gba", 0xfdbf64, 0x2d88

	.global gUnk_08FDECEC
gUnk_08FDECEC:
	.incbin "baserom.gba", 0xfdecec, 0x60c

	.global gUnk_08FDF2F8
gUnk_08FDF2F8:
	.incbin "baserom.gba", 0xfdf2f8, 0x410

	.global gUnk_08FDF708
gUnk_08FDF708:
	.incbin "baserom.gba", 0xfdf708, 0xc18

	.global gUnk_08FE0320
gUnk_08FE0320:
	.incbin "baserom.gba", 0xfe0320, 0xe00

	.global gUnk_08FE1120
gUnk_08FE1120:
	.incbin "baserom.gba", 0xfe1120, 0x1014

	.global gUnk_08FE2134
gUnk_08FE2134:
	.incbin "baserom.gba", 0xfe2134, 0xd7d0

	.global gUnk_08FEF904
gUnk_08FEF904:
	.incbin "baserom.gba", 0xfef904, 0x2e4

	.global gUnk_08FEFBE8
gUnk_08FEFBE8:
	.incbin "baserom.gba", 0xfefbe8, 0xb18

	.global gUnk_08FF0700
gUnk_08FF0700:
	.incbin "baserom.gba", 0xff0700, 0x310

	.global gUnk_08FF0A10
gUnk_08FF0A10:
	.incbin "baserom.gba", 0xff0a10, 0xeee8

	.global gUnk_08FFF8F8
gUnk_08FFF8F8:
	.incbin "baserom.gba", 0xfff8f8, 0x708
