@ ROM data 0x086501a4-0x08677370 (not yet in source)
@ Generated by tools/datasplit.py: labels, incbin and .4byte pointers.
@ Labels may be renamed here; rerun the tool then (it rewrites the
@ .4byte references) and after changing data/layout.txt.

	.section .rodata.086501A4, "a"

	.global FireRingBgfx_086501A4
FireRingBgfx_086501A4:  @ LZ77
	.incbin "build/graphics/FireRingBgfx_086501A4.lz"

	.global FireRingBgfx_08650974
FireRingBgfx_08650974:  @ LZ77
	.incbin "build/graphics/FireRingBgfx_08650974.lz"

	.global FireRingBgfx_086512A8
FireRingBgfx_086512A8:  @ LZ77
	.incbin "build/graphics/FireRingBgfx_086512A8.lz"

	.global OpBmBgfx_08651548
OpBmBgfx_08651548:
	.incbin "baserom.gba", 0x651548, 0x20

	.global OpBmBgfx_08651568
OpBmBgfx_08651568:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_08651568.lz"

	.global OpBmBgfx_08651EA4
OpBmBgfx_08651EA4:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_08651EA4.lz"

	.global OpBmBgfx_0865286C
OpBmBgfx_0865286C:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_0865286C.lz"

	.global OpBmBgfx_08652D48
OpBmBgfx_08652D48:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_08652D48.lz"

	.global OpBmBgfx_086535A8
OpBmBgfx_086535A8:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_086535A8.lz"

	.global OpBmBgfx_08653EB0
OpBmBgfx_08653EB0:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_08653EB0.lz"

	.global OpBmBgfx_08654388
OpBmBgfx_08654388:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_08654388.lz"

	.global OpBmBgfx_08654C50
OpBmBgfx_08654C50:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_08654C50.lz"

	.global OpBmBgfx_0865549C
OpBmBgfx_0865549C:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_0865549C.lz"

	.global OpBmBgfx_08655980
OpBmBgfx_08655980:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_08655980.lz"

	.global OpBmBgfx_086561FC
OpBmBgfx_086561FC:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_086561FC.lz"

	.global OpBmBgfx_08656A8C
OpBmBgfx_08656A8C:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_08656A8C.lz"

	.global OpBmBgfx_08656F54
OpBmBgfx_08656F54:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_08656F54.lz"

	.global OpBmBgfx_08657818
OpBmBgfx_08657818:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_08657818.lz"

	.global OpBmBgfx_086580DC
OpBmBgfx_086580DC:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_086580DC.lz"

	.global OpBmBgfx_086585C0
OpBmBgfx_086585C0:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_086585C0.lz"

	.global OpBmBgfx_08658EC8
OpBmBgfx_08658EC8:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_08658EC8.lz"

	.global OpBmBgfx_086597C4
OpBmBgfx_086597C4:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_086597C4.lz"

	.global gUnk_08659C9C
gUnk_08659C9C:
	.incbin "baserom.gba", 0x659c9c, 0x40

	.global OpBmBgfx_08659CDC
OpBmBgfx_08659CDC:
	.incbin "baserom.gba", 0x659cdc, 0xbc

	.global gUnk_08659D98
gUnk_08659D98:
	.incbin "baserom.gba", 0x659d98, 0x2c0

	.global gUnk_0865A058
gUnk_0865A058:
	.incbin "baserom.gba", 0x65a058, 0x93c

	.global gUnk_0865A994
gUnk_0865A994:
	.incbin "baserom.gba", 0x65a994, 0x9c8

	.global gUnk_0865B35C
gUnk_0865B35C:
	.incbin "baserom.gba", 0x65b35c, 0x4dc

	.global gUnk_0865B838
gUnk_0865B838:
	.incbin "baserom.gba", 0x65b838, 0x4a4

	.global OpBmBgfx_0865BCDC
OpBmBgfx_0865BCDC:
	.incbin "baserom.gba", 0x65bcdc, 0x3bc

	.global gUnk_0865C098
gUnk_0865C098:
	.incbin "baserom.gba", 0x65c098, 0x908

	.global gUnk_0865C9A0
gUnk_0865C9A0:
	.incbin "baserom.gba", 0x65c9a0, 0x4d8

	.global gUnk_0865CE78
gUnk_0865CE78:
	.incbin "baserom.gba", 0x65ce78, 0x8c8

	.global gUnk_0865D740
gUnk_0865D740:
	.incbin "baserom.gba", 0x65d740, 0x59c

	.global OpBmBgfx_0865DCDC
OpBmBgfx_0865DCDC:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_0865DCDC.lz"

	.global OpBmBgfx_0865E1C4
OpBmBgfx_0865E1C4:
	.incbin "baserom.gba", 0x65e1c4, 0x2ac

	.global gUnk_0865E470
gUnk_0865E470:
	.incbin "baserom.gba", 0x65e470, 0x87c

	.global gUnk_0865ECEC
gUnk_0865ECEC:
	.incbin "baserom.gba", 0x65ecec, 0x890

	.global gUnk_0865F57C
gUnk_0865F57C:
	.incbin "baserom.gba", 0x65f57c, 0x4c8

	.global gUnk_0865FA44
gUnk_0865FA44:
	.incbin "baserom.gba", 0x65fa44, 0x780

	.global OpBmBgfx_086601C4
OpBmBgfx_086601C4:
	.incbin "baserom.gba", 0x6601c4, 0x144

	.global gUnk_08660308
gUnk_08660308:
	.incbin "baserom.gba", 0x660308, 0x4c8

	.global gUnk_086607D0
gUnk_086607D0:
	.incbin "baserom.gba", 0x6607d0, 0x3fc

	.global gUnk_08660BCC
gUnk_08660BCC:
	.incbin "baserom.gba", 0x660bcc, 0x4e4

	.global gUnk_086610B0
gUnk_086610B0:
	.incbin "baserom.gba", 0x6610b0, 0x908

	.global gUnk_086619B8
gUnk_086619B8:
	.incbin "baserom.gba", 0x6619b8, 0x80c

	.global OpBmBgfx_086621C4
OpBmBgfx_086621C4:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_086621C4.lz"

	.global OpBmBgfx_086626A8
OpBmBgfx_086626A8:
	.incbin "baserom.gba", 0x6626a8, 0xe4

	.global gUnk_0866278C
gUnk_0866278C:
	.incbin "baserom.gba", 0x66278c, 0x40

	.global gUnk_086627CC
gUnk_086627CC:
	.incbin "baserom.gba", 0x6627cc, 0x1edc

	.global OpBmBgfx_086646A8
OpBmBgfx_086646A8:
	.incbin "baserom.gba", 0x6646a8, 0x124

	.global gUnk_086647CC
gUnk_086647CC:
	.incbin "baserom.gba", 0x6647cc, 0x1abc

	.global OpBmBgfx_08666288
OpBmBgfx_08666288:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_08666288.lz"

	.global OpBmBgfx_086666EC
OpBmBgfx_086666EC:
	.incbin "baserom.gba", 0x6666ec, 0xe0

	.global gUnk_086667CC
gUnk_086667CC:
	.incbin "baserom.gba", 0x6667cc, 0x4e8

	.global gUnk_08666CB4
gUnk_08666CB4:
	.incbin "baserom.gba", 0x666cb4, 0x1a38

	.global OpBmBgfx_086686EC
OpBmBgfx_086686EC:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_086686EC.lz"

	.global OpBmBgfx_08668E08
OpBmBgfx_08668E08:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_08668E08.lz"

	.global OpBmBgfx_08669174
OpBmBgfx_08669174:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_08669174.lz"

	.global OpBmBgfx_086699F0
OpBmBgfx_086699F0:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_086699F0.lz"

	.global OpBmBgfx_08669E90
OpBmBgfx_08669E90:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_08669E90.lz"

	.global OpBmBgfx_0866A0DC
OpBmBgfx_0866A0DC:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_0866A0DC.lz"

	.global OpBmBgfx_0866A4C4
OpBmBgfx_0866A4C4:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_0866A4C4.lz"

	.global OpBmBgfx_0866A838
OpBmBgfx_0866A838:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_0866A838.lz"

	.global OpBmBgfx_0866A99C
OpBmBgfx_0866A99C:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_0866A99C.lz"

	.global OpBmBgfx_0866AA74
OpBmBgfx_0866AA74:  @ LZ77
	.incbin "build/graphics/OpBmBgfx_0866AA74.lz"

	.global Pal_TitleTextShadow
Pal_TitleTextShadow:
	.incbin "baserom.gba", 0x66ab28, 0x20

	.global Img_TitleTextShadow
Img_TitleTextShadow:  @ LZ77
	.incbin "build/graphics/Img_TitleTextShadow.lz"

	.global Tsa_TitleTextShadow
Tsa_TitleTextShadow:  @ LZ77
	.incbin "build/graphics/Tsa_TitleTextShadow.lz"

	.global Pal_TitleBg
Pal_TitleBg:
	.incbin "baserom.gba", 0x66af6c, 0x20

	.global Img_TitleBg
Img_TitleBg:  @ LZ77
	.incbin "build/graphics/Img_TitleBg.lz"

	.global Tsa_TitleBg
Tsa_TitleBg:
	.incbin "baserom.gba", 0x66edc0, 0x41c

	.global gUnk_0866F1DC
gUnk_0866F1DC:
	.incbin "baserom.gba", 0x66f1dc, 0x98

	.global Pal_TitleAxe
Pal_TitleAxe:
	.incbin "baserom.gba", 0x66f274, 0x20

	.global Img_TitleAxe
Img_TitleAxe:  @ LZ77
	.incbin "build/graphics/Img_TitleAxe.lz"

	.global Tsa_TitleAxe
Tsa_TitleAxe:  @ LZ77
	.incbin "build/graphics/Tsa_TitleAxe.lz"

	.global Pal_TitleSprites
Pal_TitleSprites:
	.incbin "baserom.gba", 0x66fce0, 0xa0

	.global Img_TitleSprites
Img_TitleSprites:  @ LZ77
	.incbin "build/graphics/Img_TitleSprites.lz"

	.global SpirteAnim_TitleText
SpirteAnim_TitleText:
	.incbin "baserom.gba", 0x672570, 0x270

	.global gUnk_086727E0
gUnk_086727E0:
	.incbin "baserom.gba", 0x6727e0, 0x20

	.global gUnk_08672800
gUnk_08672800:  @ LZ77
	.incbin "build/graphics/gUnk_08672800.lz"

	.global gUnk_08673AD8
gUnk_08673AD8:  @ LZ77
	.incbin "build/graphics/gUnk_08673AD8.lz"

	.global gUnk_08673D38
gUnk_08673D38:
	.incbin "baserom.gba", 0x673d38, 0x20

	.global gUnk_08673D58
gUnk_08673D58:  @ LZ77
	.incbin "build/graphics/gUnk_08673D58.lz"

	.global gUnk_086740B4
gUnk_086740B4:
	.incbin "baserom.gba", 0x6740b4, 0x468

	.global gUnk_0867451C
gUnk_0867451C:
	.incbin "baserom.gba", 0x67451c, 0x20

	.global gUnk_0867453C
gUnk_0867453C:  @ LZ77
	.incbin "build/graphics/gUnk_0867453C.lz"

	.global gUnk_086756A0
gUnk_086756A0:  @ LZ77
	.incbin "build/graphics/gUnk_086756A0.lz"

	.global gUnk_086758C0
gUnk_086758C0:
	.incbin "baserom.gba", 0x6758c0, 0x20

	.global gUnk_086758E0
gUnk_086758E0:  @ LZ77
	.incbin "build/graphics/gUnk_086758E0.lz"

	.global gUnk_08676BB8
gUnk_08676BB8:  @ LZ77
	.incbin "build/graphics/gUnk_08676BB8.lz"

	.global Pal_TitleTextFlame
Pal_TitleTextFlame:
	.incbin "baserom.gba", 0x676e04, 0x20

	.global Img_TitleTextFlame
Img_TitleTextFlame:  @ LZ77
	.incbin "build/graphics/Img_TitleTextFlame.lz"

	.global Tsa_TitleTextFlame
Tsa_TitleTextFlame:  @ LZ77
	.incbin "build/graphics/Tsa_TitleTextFlame.lz"

	.section .rodata.0867736C, "a"
	.incbin "baserom.gba", 0x67736c, 0x4
