@ ROM data 0x08e946f8-0x08ed4384 (not yet in source)
@ Generated by tools/datasplit.py: labels, incbin and .4byte pointers.
@ Labels may be renamed here; rerun the tool then (it rewrites the
@ .4byte references) and after changing data/layout.txt.

	.section .rodata.08E946F8, "a"

	.global gUnk_08E946F8
gUnk_08E946F8:  @ LZ77
	.incbin "build/graphics/banim/033_myrm_sw1/oam_r.lz"

	.global gUnk_08E952CC
gUnk_08E952CC:  @ LZ77
	.incbin "build/graphics/gUnk_08E952CC.lz"

	.global gUnk_08E95698
gUnk_08E95698:
	.incbin "baserom.gba", 0xe95698, 0x60

	.global gUnk_08E956F8
gUnk_08E956F8:  @ LZ77
	.incbin "build/graphics/banim/034_myrm_sw1/pal.lz"

	.global gUnk_08E95760
gUnk_08E95760:  @ LZ77
	.incbin "build/graphics/banim/034_myrm_sw1/oam_l.lz"

	.global gUnk_08E95814
gUnk_08E95814:  @ LZ77
	.incbin "build/graphics/banim/034_myrm_sw1/oam_r.lz"

	.global gUnk_08E958C8
gUnk_08E958C8:  @ LZ77
	.incbin "build/graphics/gUnk_08E958C8.lz"

	.global gUnk_08E95950
gUnk_08E95950:
	.incbin "baserom.gba", 0xe95950, 0x60

	.global gUnk_08E959B0
gUnk_08E959B0:  @ LZ77
	.incbin "build/graphics/banim/035_swmm_sw1/sheet_0.lz"

	.global gUnk_08E96A68
gUnk_08E96A68:  @ LZ77
	.incbin "build/graphics/banim/035_swmm_sw1/sheet_1.lz"

	.global gUnk_08E97908
gUnk_08E97908:  @ LZ77
	.incbin "build/graphics/banim/035_swmm_sw1/sheet_2.lz"

	.global gUnk_08E98BA0
gUnk_08E98BA0:  @ LZ77
	.incbin "build/graphics/banim/035_swmm_sw1/sheet_3.lz"

	.global gUnk_08E99428
gUnk_08E99428:  @ LZ77
	.incbin "build/graphics/banim/035_swmm_sw1/pal.lz"

	.global gUnk_08E9948C
gUnk_08E9948C:  @ LZ77
	.incbin "build/graphics/banim/035_swmm_sw1/oam_l.lz"

	.global gUnk_08E9A098
gUnk_08E9A098:  @ LZ77
	.incbin "build/graphics/banim/035_swmm_sw1/oam_r.lz"

	.global gUnk_08E9AC94
gUnk_08E9AC94:  @ LZ77
	.incbin "build/graphics/gUnk_08E9AC94.lz"

	.global gUnk_08E9B130
gUnk_08E9B130:
	.incbin "baserom.gba", 0xe9b130, 0x60

	.global gUnk_08E9B190
gUnk_08E9B190:  @ LZ77
	.incbin "build/graphics/banim/036_swmm_sw1/pal.lz"

	.global gUnk_08E9B1F4
gUnk_08E9B1F4:  @ LZ77
	.incbin "build/graphics/banim/036_swmm_sw1/oam_l.lz"

	.global gUnk_08E9B248
gUnk_08E9B248:  @ LZ77
	.incbin "build/graphics/banim/036_swmm_sw1/oam_r.lz"

	.global gUnk_08E9B298
gUnk_08E9B298:  @ LZ77
	.incbin "build/graphics/gUnk_08E9B298.lz"

	.global gUnk_08E9B2FC
gUnk_08E9B2FC:
	.incbin "baserom.gba", 0xe9b2fc, 0x60

	.global gUnk_08E9B35C
gUnk_08E9B35C:  @ LZ77
	.incbin "build/graphics/banim/037_swlm_sw1/sheet_0.lz"

	.global gUnk_08E9C2DC
gUnk_08E9C2DC:  @ LZ77
	.incbin "build/graphics/banim/037_swlm_sw1/sheet_1.lz"

	.global gUnk_08E9CFEC
gUnk_08E9CFEC:  @ LZ77
	.incbin "build/graphics/banim/037_swlm_sw1/sheet_2.lz"

	.global gUnk_08E9E258
gUnk_08E9E258:  @ LZ77
	.incbin "build/graphics/banim/037_swlm_sw1/sheet_3.lz"

	.global gUnk_08E9EAE0
gUnk_08E9EAE0:  @ LZ77
	.incbin "build/graphics/banim/037_swlm_sw1/pal.lz"

	.global gUnk_08E9EB44
gUnk_08E9EB44:  @ LZ77
	.incbin "build/graphics/banim/037_swlm_sw1/oam_l.lz"

	.global gUnk_08E9F79C
gUnk_08E9F79C:  @ LZ77
	.incbin "build/graphics/banim/037_swlm_sw1/oam_r.lz"

	.global gUnk_08EA03EC
gUnk_08EA03EC:  @ LZ77
	.incbin "build/graphics/gUnk_08EA03EC.lz"

	.global gUnk_08EA08BC
gUnk_08EA08BC:
	.incbin "baserom.gba", 0xea08bc, 0x60

	.global gUnk_08EA091C
gUnk_08EA091C:  @ LZ77
	.incbin "build/graphics/banim/038_swlm_sw1/pal.lz"

	.global gUnk_08EA0980
gUnk_08EA0980:  @ LZ77
	.incbin "build/graphics/banim/038_swlm_sw1/oam_l.lz"

	.global gUnk_08EA09CC
gUnk_08EA09CC:  @ LZ77
	.incbin "build/graphics/banim/038_swlm_sw1/oam_r.lz"

	.global gUnk_08EA0A18
gUnk_08EA0A18:  @ LZ77
	.incbin "build/graphics/gUnk_08EA0A18.lz"

	.global gUnk_08EA0A7C
gUnk_08EA0A7C:
	.incbin "baserom.gba", 0xea0a7c, 0x60

	.global gUnk_08EA0ADC
gUnk_08EA0ADC:  @ LZ77
	.incbin "build/graphics/banim/039_swmf_sw1/sheet_0.lz"

	.global gUnk_08EA1B14
gUnk_08EA1B14:  @ LZ77
	.incbin "build/graphics/banim/039_swmf_sw1/sheet_1.lz"

	.global gUnk_08EA29C4
gUnk_08EA29C4:  @ LZ77
	.incbin "build/graphics/banim/039_swmf_sw1/sheet_2.lz"

	.global gUnk_08EA3C50
gUnk_08EA3C50:  @ LZ77
	.incbin "build/graphics/banim/039_swmf_sw1/sheet_3.lz"

	.global gUnk_08EA44D8
gUnk_08EA44D8:  @ LZ77
	.incbin "build/graphics/banim/039_swmf_sw1/pal.lz"

	.global gUnk_08EA453C
gUnk_08EA453C:  @ LZ77
	.incbin "build/graphics/banim/039_swmf_sw1/oam_l.lz"

	.global gUnk_08EA5148
gUnk_08EA5148:  @ LZ77
	.incbin "build/graphics/banim/039_swmf_sw1/oam_r.lz"

	.global gUnk_08EA5D44
gUnk_08EA5D44:  @ LZ77
	.incbin "build/graphics/gUnk_08EA5D44.lz"

	.global gUnk_08EA61E0
gUnk_08EA61E0:
	.incbin "baserom.gba", 0xea61e0, 0x60

	.global gUnk_08EA6240
gUnk_08EA6240:  @ LZ77
	.incbin "build/graphics/banim/03A_swmf_sw1/pal.lz"

	.global gUnk_08EA62A4
gUnk_08EA62A4:  @ LZ77
	.incbin "build/graphics/banim/03A_swmf_sw1/oam_l.lz"

	.global gUnk_08EA62F8
gUnk_08EA62F8:  @ LZ77
	.incbin "build/graphics/banim/03A_swmf_sw1/oam_r.lz"

	.global gUnk_08EA6348
gUnk_08EA6348:  @ LZ77
	.incbin "build/graphics/gUnk_08EA6348.lz"

	.global gUnk_08EA63AC
gUnk_08EA63AC:
	.incbin "baserom.gba", 0xea63ac, 0x60

	.global gUnk_08EA640C
gUnk_08EA640C:  @ LZ77
	.incbin "build/graphics/banim/03B_sokm_sp1/sheet_0.lz"

	.global gUnk_08EA7238
gUnk_08EA7238:  @ LZ77
	.incbin "build/graphics/banim/03B_sokm_sp1/sheet_1.lz"

	.global gUnk_08EA8308
gUnk_08EA8308:  @ LZ77
	.incbin "build/graphics/banim/03B_sokm_sp1/sheet_2.lz"

	.global gUnk_08EA9254
gUnk_08EA9254:  @ LZ77
	.incbin "build/graphics/banim/03B_sokm_sp1/sheet_3.lz"

	.global gUnk_08EAA4A8
gUnk_08EAA4A8:  @ LZ77
	.incbin "build/graphics/banim/03B_sokm_sp1/pal.lz"

	.global gUnk_08EAA514
gUnk_08EAA514:  @ LZ77
	.incbin "build/graphics/banim/03B_sokm_sp1/oam_l.lz"

	.global gUnk_08EAB140
gUnk_08EAB140:  @ LZ77
	.incbin "build/graphics/banim/03B_sokm_sp1/oam_r.lz"

	.global gUnk_08EABD64
gUnk_08EABD64:  @ LZ77
	.incbin "build/graphics/gUnk_08EABD64.lz"

	.global gUnk_08EAC06C
gUnk_08EAC06C:
	.incbin "baserom.gba", 0xeac06c, 0x60

	.global gUnk_08EAC0CC
gUnk_08EAC0CC:  @ LZ77
	.incbin "build/graphics/banim/03C_sokm_sp1/pal.lz"

	.global gUnk_08EAC138
gUnk_08EAC138:  @ LZ77
	.incbin "build/graphics/banim/03C_sokm_sp1/oam_l.lz"

	.global gUnk_08EAC9C8
gUnk_08EAC9C8:  @ LZ77
	.incbin "build/graphics/banim/03C_sokm_sp1/oam_r.lz"

	.global gUnk_08EAD248
gUnk_08EAD248:  @ LZ77
	.incbin "build/graphics/gUnk_08EAD248.lz"

	.global gUnk_08EAD518
gUnk_08EAD518:
	.incbin "baserom.gba", 0xead518, 0x60

	.global gUnk_08EAD578
gUnk_08EAD578:  @ LZ77
	.incbin "build/graphics/banim/03D_sokm_sp1/pal.lz"

	.global gUnk_08EAD5E4
gUnk_08EAD5E4:  @ LZ77
	.incbin "build/graphics/banim/03D_sokm_sp1/oam_l.lz"

	.global gUnk_08EAD6C8
gUnk_08EAD6C8:  @ LZ77
	.incbin "build/graphics/banim/03D_sokm_sp1/oam_r.lz"

	.global gUnk_08EAD7AC
gUnk_08EAD7AC:  @ LZ77
	.incbin "build/graphics/gUnk_08EAD7AC.lz"

	.global gUnk_08EAD830
gUnk_08EAD830:
	.incbin "baserom.gba", 0xead830, 0x60

	.global gUnk_08EAD890
gUnk_08EAD890:  @ LZ77
	.incbin "build/graphics/banim/03E_sokf_sp1/sheet_0.lz"

	.global gUnk_08EAE6BC
gUnk_08EAE6BC:  @ LZ77
	.incbin "build/graphics/banim/03E_sokf_sp1/sheet_1.lz"

	.global gUnk_08EAF78C
gUnk_08EAF78C:  @ LZ77
	.incbin "build/graphics/banim/03E_sokf_sp1/sheet_2.lz"

	.global gUnk_08EB06D8
gUnk_08EB06D8:  @ LZ77
	.incbin "build/graphics/banim/03E_sokf_sp1/sheet_3.lz"

	.global gUnk_08EB192C
gUnk_08EB192C:  @ LZ77
	.incbin "build/graphics/banim/03E_sokf_sp1/pal.lz"

	.global gUnk_08EB1994
gUnk_08EB1994:  @ LZ77
	.incbin "build/graphics/banim/03E_sokf_sp1/oam_l.lz"

	.global gUnk_08EB25C0
gUnk_08EB25C0:  @ LZ77
	.incbin "build/graphics/banim/03E_sokf_sp1/oam_r.lz"

	.global gUnk_08EB31E4
gUnk_08EB31E4:  @ LZ77
	.incbin "build/graphics/gUnk_08EB31E4.lz"

	.global gUnk_08EB34EC
gUnk_08EB34EC:
	.incbin "baserom.gba", 0xeb34ec, 0x60

	.global gUnk_08EB354C
gUnk_08EB354C:  @ LZ77
	.incbin "build/graphics/banim/03F_asnm_sw1/sheet_0.lz"

	.global gUnk_08EB4604
gUnk_08EB4604:  @ LZ77
	.incbin "build/graphics/banim/03F_asnm_sw1/sheet_1.lz"

	.global gUnk_08EB55AC
gUnk_08EB55AC:  @ LZ77
	.incbin "build/graphics/banim/03F_asnm_sw1/sheet_2.lz"

	.global gUnk_08EB6518
gUnk_08EB6518:  @ LZ77
	.incbin "build/graphics/banim/03F_asnm_sw1/sheet_3.lz"

	.global gUnk_08EB72F8
gUnk_08EB72F8:  @ LZ77
	.incbin "build/graphics/banim/03F_asnm_sw1/pal.lz"

	.global gUnk_08EB7350
gUnk_08EB7350:  @ LZ77
	.incbin "build/graphics/banim/03F_asnm_sw1/oam_l.lz"

	.global gUnk_08EB8048
gUnk_08EB8048:  @ LZ77
	.incbin "build/graphics/banim/03F_asnm_sw1/oam_r.lz"

	.global gUnk_08EB8D4C
gUnk_08EB8D4C:  @ LZ77
	.incbin "build/graphics/gUnk_08EB8D4C.lz"

	.global gUnk_08EB922C
gUnk_08EB922C:
	.incbin "baserom.gba", 0xeb922c, 0x60

	.global gUnk_08EB928C
gUnk_08EB928C:  @ LZ77
	.incbin "build/graphics/banim/040_asnm_sw1/pal.lz"

	.global gUnk_08EB92E4
gUnk_08EB92E4:  @ LZ77
	.incbin "build/graphics/banim/040_asnm_sw1/oam_l.lz"

	.global gUnk_08EB93A4
gUnk_08EB93A4:  @ LZ77
	.incbin "build/graphics/banim/040_asnm_sw1/oam_r.lz"

	.global gUnk_08EB9464
gUnk_08EB9464:  @ LZ77
	.incbin "build/graphics/gUnk_08EB9464.lz"

	.global gUnk_08EB94F0
gUnk_08EB94F0:
	.incbin "baserom.gba", 0xeb94f0, 0x60

	.global gUnk_08EB9550
gUnk_08EB9550:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/sheet_0.lz"

	.global gUnk_08EBAA0C
gUnk_08EBAA0C:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/sheet_1.lz"

	.global gUnk_08EBBD8C
gUnk_08EBBD8C:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/sheet_2.lz"

	.global gUnk_08EBD284
gUnk_08EBD284:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/sheet_3.lz"

	.global gUnk_08EBE798
gUnk_08EBE798:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/sheet_4.lz"

	.global gUnk_08EBFA10
gUnk_08EBFA10:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/sheet_5.lz"

	.global gUnk_08EC0BD4
gUnk_08EC0BD4:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/sheet_6.lz"

	.global gUnk_08EC1DEC
gUnk_08EC1DEC:  @ LZ77
	.incbin "build/graphics/banim/042_pakm_sw1/sheet_4.lz"

	.global gUnk_08EC21BC
gUnk_08EC21BC:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/pal.lz"

	.global gUnk_08EC2230
gUnk_08EC2230:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/oam_l.lz"

	.global gUnk_08EC3078
gUnk_08EC3078:  @ LZ77
	.incbin "build/graphics/banim/041_pakm_sw1/oam_r.lz"

	.global gUnk_08EC3E84
gUnk_08EC3E84:  @ LZ77
	.incbin "build/graphics/gUnk_08EC3E84.lz"

	.global gUnk_08EC42FC
gUnk_08EC42FC:
	.incbin "baserom.gba", 0xec42fc, 0x60

	.global gUnk_08EC435C
gUnk_08EC435C:  @ LZ77
	.incbin "build/graphics/banim/042_pakm_sw1/pal.lz"

	.global gUnk_08EC43D0
gUnk_08EC43D0:  @ LZ77
	.incbin "build/graphics/banim/042_pakm_sw1/oam_l.lz"

	.global gUnk_08EC4FF0
gUnk_08EC4FF0:  @ LZ77
	.incbin "build/graphics/banim/042_pakm_sw1/oam_r.lz"

	.global gUnk_08EC5C04
gUnk_08EC5C04:  @ LZ77
	.incbin "build/graphics/gUnk_08EC5C04.lz"

	.global gUnk_08EC5E54
gUnk_08EC5E54:
	.incbin "baserom.gba", 0xec5e54, 0x60

	.global gUnk_08EC5EB4
gUnk_08EC5EB4:  @ LZ77
	.incbin "build/graphics/banim/043_pakm_sw1/pal.lz"

	.global gUnk_08EC5F28
gUnk_08EC5F28:  @ LZ77
	.incbin "build/graphics/banim/043_pakm_sw1/oam_l.lz"

	.global gUnk_08EC6C5C
gUnk_08EC6C5C:  @ LZ77
	.incbin "build/graphics/banim/043_pakm_sw1/oam_r.lz"

	.global gUnk_08EC7974
gUnk_08EC7974:  @ LZ77
	.incbin "build/graphics/gUnk_08EC7974.lz"

	.global gUnk_08EC7DD0
gUnk_08EC7DD0:
	.incbin "baserom.gba", 0xec7dd0, 0x60

	.global gUnk_08EC7E30
gUnk_08EC7E30:  @ LZ77
	.incbin "build/graphics/banim/044_pakm_sw1/pal.lz"

	.global gUnk_08EC7EA4
gUnk_08EC7EA4:  @ LZ77
	.incbin "build/graphics/banim/044_pakm_sw1/oam_l.lz"

	.global gUnk_08EC8FB8
gUnk_08EC8FB8:  @ LZ77
	.incbin "build/graphics/banim/044_pakm_sw1/oam_r.lz"

	.global gUnk_08ECA098
gUnk_08ECA098:  @ LZ77
	.incbin "build/graphics/gUnk_08ECA098.lz"

	.global gUnk_08ECA530
gUnk_08ECA530:
	.incbin "baserom.gba", 0xeca530, 0x60

	.global gUnk_08ECA590
gUnk_08ECA590:  @ LZ77
	.incbin "build/graphics/banim/045_pakm_sw1/pal.lz"

	.global gUnk_08ECA604
gUnk_08ECA604:  @ LZ77
	.incbin "build/graphics/banim/045_pakm_sw1/oam_l.lz"

	.global gUnk_08ECA6DC
gUnk_08ECA6DC:  @ LZ77
	.incbin "build/graphics/banim/045_pakm_sw1/oam_r.lz"

	.global gUnk_08ECA7B0
gUnk_08ECA7B0:  @ LZ77
	.incbin "build/graphics/gUnk_08ECA7B0.lz"

	.global gUnk_08ECA834
gUnk_08ECA834:
	.incbin "baserom.gba", 0xeca834, 0x60

	.global gUnk_08ECA894
gUnk_08ECA894:  @ LZ77
	.incbin "build/graphics/banim/046_pakm_sw1/pal.lz"

	.global gUnk_08ECA908
gUnk_08ECA908:  @ LZ77
	.incbin "build/graphics/banim/046_pakm_sw1/oam_l.lz"

	.global gUnk_08ECB750
gUnk_08ECB750:  @ LZ77
	.incbin "build/graphics/banim/046_pakm_sw1/oam_r.lz"

	.global gUnk_08ECC55C
gUnk_08ECC55C:  @ LZ77
	.incbin "build/graphics/gUnk_08ECC55C.lz"

	.global gUnk_08ECC9D4
gUnk_08ECC9D4:
	.incbin "baserom.gba", 0xecc9d4, 0x60

	.global gUnk_08ECCA34
gUnk_08ECCA34:  @ LZ77
	.incbin "build/graphics/banim/047_pakm_sw1/pal.lz"

	.global gUnk_08ECCAA8
gUnk_08ECCAA8:  @ LZ77
	.incbin "build/graphics/banim/047_pakm_sw1/oam_l.lz"

	.global gUnk_08ECD6C8
gUnk_08ECD6C8:  @ LZ77
	.incbin "build/graphics/banim/047_pakm_sw1/oam_r.lz"

	.global gUnk_08ECE2DC
gUnk_08ECE2DC:  @ LZ77
	.incbin "build/graphics/gUnk_08ECE2DC.lz"

	.global gUnk_08ECE52C
gUnk_08ECE52C:
	.incbin "baserom.gba", 0xece52c, 0x60

	.global gUnk_08ECE58C
gUnk_08ECE58C:  @ LZ77
	.incbin "build/graphics/banim/048_pakm_sw1/pal.lz"

	.global gUnk_08ECE600
gUnk_08ECE600:  @ LZ77
	.incbin "build/graphics/banim/048_pakm_sw1/oam_l.lz"

	.global gUnk_08ECF334
gUnk_08ECF334:  @ LZ77
	.incbin "build/graphics/banim/048_pakm_sw1/oam_r.lz"

	.global gUnk_08ED004C
gUnk_08ED004C:  @ LZ77
	.incbin "build/graphics/gUnk_08ED004C.lz"

	.global gUnk_08ED04A8
gUnk_08ED04A8:
	.incbin "baserom.gba", 0xed04a8, 0x60

	.global gUnk_08ED0508
gUnk_08ED0508:  @ LZ77
	.incbin "build/graphics/banim/049_pakm_sw1/pal.lz"

	.global gUnk_08ED057C
gUnk_08ED057C:  @ LZ77
	.incbin "build/graphics/banim/049_pakm_sw1/oam_l.lz"

	.global gUnk_08ED1690
gUnk_08ED1690:  @ LZ77
	.incbin "build/graphics/banim/049_pakm_sw1/oam_r.lz"

	.global gUnk_08ED2770
gUnk_08ED2770:  @ LZ77
	.incbin "build/graphics/gUnk_08ED2770.lz"

	.global gUnk_08ED2C08
gUnk_08ED2C08:
	.incbin "baserom.gba", 0xed2c08, 0x60

	.global gUnk_08ED2C68
gUnk_08ED2C68:  @ LZ77
	.incbin "build/graphics/banim/04A_pakm_sw1/pal.lz"

	.global gUnk_08ED2CDC
gUnk_08ED2CDC:  @ LZ77
	.incbin "build/graphics/banim/04A_pakm_sw1/oam_l.lz"

	.global gUnk_08ED2DB4
gUnk_08ED2DB4:  @ LZ77
	.incbin "build/graphics/banim/04A_pakm_sw1/oam_r.lz"

	.global gUnk_08ED2E88
gUnk_08ED2E88:  @ LZ77
	.incbin "build/graphics/gUnk_08ED2E88.lz"

	.global gUnk_08ED2F0C
gUnk_08ED2F0C:
	.incbin "baserom.gba", 0xed2f0c, 0x60

	.global gUnk_08ED2F6C
gUnk_08ED2F6C:  @ LZ77
	.incbin "build/graphics/banim/04B_paif_sw1/sheet_0.lz"
