@ ROM data 0x08927460-0x089665f4 (not yet in source)
@ Generated by tools/datasplit.py: labels + incbin only.  Labels may be
@ renamed here; rerun the tool after changing data/layout.txt.

	.section .rodata.08927460, "a"

	.global gUnk_08927460
gUnk_08927460:
	.incbin "baserom.gba", 0x927460, 0x3c1c

	.global gUnk_0892B07C
gUnk_0892B07C:
	.incbin "baserom.gba", 0x92b07c, 0x8c28

	.global gUnk_08933CA4
gUnk_08933CA4:
	.incbin "baserom.gba", 0x933ca4, 0x4440

	.global gUnk_089380E4
gUnk_089380E4:
	.incbin "baserom.gba", 0x9380e4, 0x2424

	.global gUnk_0893A508
gUnk_0893A508:
	.incbin "baserom.gba", 0x93a508, 0x2fd0

	.global gUnk_0893D4D8
gUnk_0893D4D8:
	.incbin "baserom.gba", 0x93d4d8, 0x1820

	.global gUnk_0893ECF8
gUnk_0893ECF8:
	.incbin "baserom.gba", 0x93ecf8, 0x2140

	.global gUnk_08940E38
gUnk_08940E38:
	.incbin "baserom.gba", 0x940e38, 0x32d4

	.global gUnk_0894410C
gUnk_0894410C:
	.incbin "baserom.gba", 0x94410c, 0x3008

	.global gUnk_08947114
gUnk_08947114:
	.incbin "baserom.gba", 0x947114, 0x1510

	.global gUnk_08948624
gUnk_08948624:
	.incbin "baserom.gba", 0x948624, 0x23cc

	.global gUnk_0894A9F0
gUnk_0894A9F0:
	.incbin "baserom.gba", 0x94a9f0, 0x1798

	.global gUnk_0894C188
gUnk_0894C188:
	.incbin "baserom.gba", 0x94c188, 0x1764

	.global gUnk_0894D8EC
gUnk_0894D8EC:
	.incbin "baserom.gba", 0x94d8ec, 0x35a8

	.global gUnk_08950E94
gUnk_08950E94:
	.incbin "baserom.gba", 0x950e94, 0x3c50

	.global gUnk_08954AE4
gUnk_08954AE4:
	.incbin "baserom.gba", 0x954ae4, 0x908

	.global gUnk_089553EC
gUnk_089553EC:
	.incbin "baserom.gba", 0x9553ec, 0x4e4

	.global gUnk_089558D0
gUnk_089558D0:
	.incbin "baserom.gba", 0x9558d0, 0xa88

	.global gUnk_08956358
gUnk_08956358:
	.incbin "baserom.gba", 0x956358, 0x1154

	.global gUnk_089574AC
gUnk_089574AC:
	.incbin "baserom.gba", 0x9574ac, 0x5d4

	.global gUnk_08957A80
gUnk_08957A80:
	.incbin "baserom.gba", 0x957a80, 0x580

	.global gUnk_08958000
gUnk_08958000:
	.incbin "baserom.gba", 0x958000, 0xa88

	.global gUnk_08958A88
gUnk_08958A88:
	.incbin "baserom.gba", 0x958a88, 0xfc4

	.global gUnk_08959A4C
gUnk_08959A4C:
	.incbin "baserom.gba", 0x959a4c, 0x618

	.global gUnk_0895A064
gUnk_0895A064:
	.incbin "baserom.gba", 0x95a064, 0x4d8

	.global gUnk_0895A53C
gUnk_0895A53C:
	.incbin "baserom.gba", 0x95a53c, 0xa5c

	.global gUnk_0895AF98
gUnk_0895AF98:
	.incbin "baserom.gba", 0x95af98, 0xfc4

	.global gUnk_0895BF5C
gUnk_0895BF5C:
	.incbin "baserom.gba", 0x95bf5c, 0x788

	.global gUnk_0895C6E4
gUnk_0895C6E4:
	.incbin "baserom.gba", 0x95c6e4, 0x700

	.global gUnk_0895CDE4
gUnk_0895CDE4:
	.incbin "baserom.gba", 0x95cde4, 0xa60

	.global gUnk_0895D844
gUnk_0895D844:
	.incbin "baserom.gba", 0x95d844, 0xfc4

	.global gUnk_0895E808
gUnk_0895E808:
	.incbin "baserom.gba", 0x95e808, 0x630

	.global gUnk_0895EE38
gUnk_0895EE38:
	.incbin "baserom.gba", 0x95ee38, 0x54c

	.global gUnk_0895F384
gUnk_0895F384:
	.incbin "baserom.gba", 0x95f384, 0x878

	.global gUnk_0895FBFC
gUnk_0895FBFC:
	.incbin "baserom.gba", 0x95fbfc, 0xd28

	.global gUnk_08960924
gUnk_08960924:
	.incbin "baserom.gba", 0x960924, 0x440

	.global gUnk_08960D64
gUnk_08960D64:
	.incbin "baserom.gba", 0x960d64, 0x4cc

	.global gUnk_08961230
gUnk_08961230:
	.incbin "baserom.gba", 0x961230, 0xbf4

	.global gUnk_08961E24
gUnk_08961E24:
	.incbin "baserom.gba", 0x961e24, 0x964

	.global gUnk_08962788
gUnk_08962788:
	.incbin "baserom.gba", 0x962788, 0x498

	.global gUnk_08962C20
gUnk_08962C20:
	.incbin "baserom.gba", 0x962c20, 0x48c

	.global gUnk_089630AC
gUnk_089630AC:
	.incbin "baserom.gba", 0x9630ac, 0xa04

	.global gUnk_08963AB0
gUnk_08963AB0:
	.incbin "baserom.gba", 0x963ab0, 0x1d90

	.global gUnk_08965840
gUnk_08965840:
	.incbin "baserom.gba", 0x965840, 0xdb4
