@ ROM data 0x086107b0-0x086501a4 (not yet in source)
@ Generated by tools/datasplit.py: labels + incbin only.  Labels may be
@ renamed here; rerun the tool after changing data/layout.txt.

	.section .rodata.086107B0, "a"

	.global gUnk_086107B0
gUnk_086107B0:  @ LZ77
	.incbin "baserom.gba", 0x6107b0, 0x408

	.global gUnk_08610BB8
gUnk_08610BB8:  @ LZ77
	.incbin "baserom.gba", 0x610bb8, 0x3f0

	.global gUnk_08610FA8
gUnk_08610FA8:  @ LZ77
	.incbin "baserom.gba", 0x610fa8, 0x3c8

	.global gUnk_08611370
gUnk_08611370:  @ LZ77
	.incbin "baserom.gba", 0x611370, 0x384

	.global gUnk_086116F4
gUnk_086116F4:  @ LZ77
	.incbin "baserom.gba", 0x6116f4, 0x38c

	.global gUnk_08611A80
gUnk_08611A80:  @ LZ77
	.incbin "baserom.gba", 0x611a80, 0x370

	.global gUnk_08611DF0
gUnk_08611DF0:  @ LZ77
	.incbin "baserom.gba", 0x611df0, 0x364

	.global gUnk_08612154
gUnk_08612154:  @ LZ77
	.incbin "baserom.gba", 0x612154, 0x380

	.global gUnk_086124D4
gUnk_086124D4:  @ LZ77
	.incbin "baserom.gba", 0x6124d4, 0x3c8

	.global gUnk_0861289C
gUnk_0861289C:  @ LZ77
	.incbin "baserom.gba", 0x61289c, 0x41c

	.global gUnk_08612CB8
gUnk_08612CB8:  @ LZ77
	.incbin "baserom.gba", 0x612cb8, 0x444

	.global gUnk_086130FC
gUnk_086130FC:  @ LZ77
	.incbin "baserom.gba", 0x6130fc, 0x444

	.global gUnk_08613540
gUnk_08613540:  @ LZ77
	.incbin "baserom.gba", 0x613540, 0x444

	.global gUnk_08613984
gUnk_08613984:  @ LZ77
	.incbin "baserom.gba", 0x613984, 0x434

	.global gUnk_08613DB8
gUnk_08613DB8:  @ LZ77
	.incbin "baserom.gba", 0x613db8, 0x428

	.global gUnk_086141E0
gUnk_086141E0:  @ LZ77
	.incbin "baserom.gba", 0x6141e0, 0x42c

	.global gUnk_0861460C
gUnk_0861460C:  @ LZ77
	.incbin "baserom.gba", 0x61460c, 0x428

	.global gUnk_08614A34
gUnk_08614A34:  @ LZ77
	.incbin "baserom.gba", 0x614a34, 0x428

	.global gUnk_08614E5C
gUnk_08614E5C:  @ LZ77
	.incbin "baserom.gba", 0x614e5c, 0x3e8

	.global gUnk_08615244
gUnk_08615244:  @ LZ77
	.incbin "baserom.gba", 0x615244, 0x350

	.global gUnk_08615594
gUnk_08615594:  @ LZ77
	.incbin "baserom.gba", 0x615594, 0x250

	.global gUnk_086157E4
gUnk_086157E4:
	.incbin "baserom.gba", 0x6157e4, 0xec

	.global gUnk_086158D0
gUnk_086158D0:
	.incbin "baserom.gba", 0x6158d0, 0x41c

	.global gUnk_08615CEC
gUnk_08615CEC:
	.incbin "baserom.gba", 0x615cec, 0x7c

	.global gUnk_08615D68
gUnk_08615D68:
	.incbin "baserom.gba", 0x615d68, 0x3c0

	.global gUnk_08616128
gUnk_08616128:
	.incbin "baserom.gba", 0x616128, 0x1c4

	.global gUnk_086162EC
gUnk_086162EC:
	.incbin "baserom.gba", 0x6162ec, 0x274

	.global gUnk_08616560
gUnk_08616560:
	.incbin "baserom.gba", 0x616560, 0x310

	.global gUnk_08616870
gUnk_08616870:
	.incbin "baserom.gba", 0x616870, 0x130

	.global gUnk_086169A0
gUnk_086169A0:
	.incbin "baserom.gba", 0x6169a0, 0x3d4

	.global gUnk_08616D74
gUnk_08616D74:
	.incbin "baserom.gba", 0x616d74, 0x20

	.global gUnk_08616D94
gUnk_08616D94:  @ LZ77
	.incbin "baserom.gba", 0x616d94, 0x230

	.global gUnk_08616FC4
gUnk_08616FC4:  @ LZ77
	.incbin "baserom.gba", 0x616fc4, 0xc2c

	.global FireRingBgfx_08617BF0
FireRingBgfx_08617BF0:
	.incbin "baserom.gba", 0x617bf0, 0x20

	.global FireRingBgfx_08617C10
FireRingBgfx_08617C10:  @ LZ77
	.incbin "baserom.gba", 0x617c10, 0xd1c

	.global FireRingBgfx_0861892C
FireRingBgfx_0861892C:  @ LZ77
	.incbin "baserom.gba", 0x61892c, 0xb4

	.global FireRingBgfx_086189E0
FireRingBgfx_086189E0:  @ LZ77
	.incbin "baserom.gba", 0x6189e0, 0xec

	.global FireRingBgfx_08618ACC
FireRingBgfx_08618ACC:  @ LZ77
	.incbin "baserom.gba", 0x618acc, 0x144

	.global FireRingBgfx_08618C10
FireRingBgfx_08618C10:  @ LZ77
	.incbin "baserom.gba", 0x618c10, 0x9ac

	.global FireRingBgfx_086195BC
FireRingBgfx_086195BC:  @ LZ77
	.incbin "baserom.gba", 0x6195bc, 0x178

	.global FireRingBgfx_08619734
FireRingBgfx_08619734:  @ LZ77
	.incbin "baserom.gba", 0x619734, 0x980

	.global FireRingBgfx_0861A0B4
FireRingBgfx_0861A0B4:  @ LZ77
	.incbin "baserom.gba", 0x61a0b4, 0x3c4

	.global FireRingBgfx_0861A478
FireRingBgfx_0861A478:  @ LZ77
	.incbin "baserom.gba", 0x61a478, 0x1cc

	.global FireRingBgfx_0861A644
FireRingBgfx_0861A644:  @ LZ77
	.incbin "baserom.gba", 0x61a644, 0x980

	.global FireRingBgfx_0861AFC4
FireRingBgfx_0861AFC4:  @ LZ77
	.incbin "baserom.gba", 0x61afc4, 0x3c4

	.global FireRingBgfx_0861B388
FireRingBgfx_0861B388:  @ LZ77
	.incbin "baserom.gba", 0x61b388, 0x1cc

	.global FireRingBgfx_0861B554
FireRingBgfx_0861B554:  @ LZ77
	.incbin "baserom.gba", 0x61b554, 0xa10

	.global FireRingBgfx_0861BF64
FireRingBgfx_0861BF64:  @ LZ77
	.incbin "baserom.gba", 0x61bf64, 0x5c4

	.global FireRingBgfx_0861C528
FireRingBgfx_0861C528:  @ LZ77
	.incbin "baserom.gba", 0x61c528, 0x200

	.global FireRingBgfx_0861C728
FireRingBgfx_0861C728:  @ LZ77
	.incbin "baserom.gba", 0x61c728, 0xb2c

	.global FireRingBgfx_0861D254
FireRingBgfx_0861D254:  @ LZ77
	.incbin "baserom.gba", 0x61d254, 0x6c0

	.global FireRingBgfx_0861D914
FireRingBgfx_0861D914:  @ LZ77
	.incbin "baserom.gba", 0x61d914, 0x20c

	.global FireRingBgfx_0861DB20
FireRingBgfx_0861DB20:  @ LZ77
	.incbin "baserom.gba", 0x61db20, 0xbd8

	.global FireRingBgfx_0861E6F8
FireRingBgfx_0861E6F8:  @ LZ77
	.incbin "baserom.gba", 0x61e6f8, 0x674

	.global FireRingBgfx_0861ED6C
FireRingBgfx_0861ED6C:  @ LZ77
	.incbin "baserom.gba", 0x61ed6c, 0x20c

	.global FireRingBgfx_0861EF78
FireRingBgfx_0861EF78:  @ LZ77
	.incbin "baserom.gba", 0x61ef78, 0xc18

	.global FireRingBgfx_0861FB90
FireRingBgfx_0861FB90:  @ LZ77
	.incbin "baserom.gba", 0x61fb90, 0x5d0

	.global FireRingBgfx_08620160
FireRingBgfx_08620160:  @ LZ77
	.incbin "baserom.gba", 0x620160, 0x1fc

	.global FireRingBgfx_0862035C
FireRingBgfx_0862035C:  @ LZ77
	.incbin "baserom.gba", 0x62035c, 0xc3c

	.global FireRingBgfx_08620F98
FireRingBgfx_08620F98:  @ LZ77
	.incbin "baserom.gba", 0x620f98, 0x4a8

	.global FireRingBgfx_08621440
FireRingBgfx_08621440:  @ LZ77
	.incbin "baserom.gba", 0x621440, 0x1e0

	.global FireRingBgfx_08621620
FireRingBgfx_08621620:  @ LZ77
	.incbin "baserom.gba", 0x621620, 0xc78

	.global FireRingBgfx_08622298
FireRingBgfx_08622298:  @ LZ77
	.incbin "baserom.gba", 0x622298, 0x414

	.global FireRingBgfx_086226AC
FireRingBgfx_086226AC:  @ LZ77
	.incbin "baserom.gba", 0x6226ac, 0x1dc

	.global FireRingBgfx_08622888
FireRingBgfx_08622888:  @ LZ77
	.incbin "baserom.gba", 0x622888, 0xc3c

	.global FireRingBgfx_086234C4
FireRingBgfx_086234C4:  @ LZ77
	.incbin "baserom.gba", 0x6234c4, 0x328

	.global FireRingBgfx_086237EC
FireRingBgfx_086237EC:  @ LZ77
	.incbin "baserom.gba", 0x6237ec, 0x1bc

	.global FireRingBgfx_086239A8
FireRingBgfx_086239A8:  @ LZ77
	.incbin "baserom.gba", 0x6239a8, 0xc5c

	.global FireRingBgfx_08624604
FireRingBgfx_08624604:  @ LZ77
	.incbin "baserom.gba", 0x624604, 0x238

	.global FireRingBgfx_0862483C
FireRingBgfx_0862483C:  @ LZ77
	.incbin "baserom.gba", 0x62483c, 0x19c

	.global FireRingBgfx_086249D8
FireRingBgfx_086249D8:  @ LZ77
	.incbin "baserom.gba", 0x6249d8, 0xba0

	.global FireRingBgfx_08625578
FireRingBgfx_08625578:  @ LZ77
	.incbin "baserom.gba", 0x625578, 0xe0

	.global FireRingBgfx_08625658
FireRingBgfx_08625658:  @ LZ77
	.incbin "baserom.gba", 0x625658, 0x17c

	.global FireRingBgfx_086257D4
FireRingBgfx_086257D4:  @ LZ77
	.incbin "baserom.gba", 0x6257d4, 0xb04

	.global FireRingBgfx_086262D8
FireRingBgfx_086262D8:  @ LZ77
	.incbin "baserom.gba", 0x6262d8, 0x1c

	.global FireRingBgfx_086262F4
FireRingBgfx_086262F4:  @ LZ77
	.incbin "baserom.gba", 0x6262f4, 0x158

	.global FireRingBgfx_0862644C
FireRingBgfx_0862644C:  @ LZ77
	.incbin "baserom.gba", 0x62644c, 0xa48

	.global FireRingBgfx_08626E94
FireRingBgfx_08626E94:  @ LZ77
	.incbin "baserom.gba", 0x626e94, 0x918

	.global FireRingBgfx_086277AC
FireRingBgfx_086277AC:  @ LZ77
	.incbin "baserom.gba", 0x6277ac, 0x148

	.global FireRingBgfx_086278F4
FireRingBgfx_086278F4:  @ LZ77
	.incbin "baserom.gba", 0x6278f4, 0x154

	.global FireRingBgfx_08627A48
FireRingBgfx_08627A48:  @ LZ77
	.incbin "baserom.gba", 0x627a48, 0x95c

	.global FireRingBgfx_086283A4
FireRingBgfx_086283A4:  @ LZ77
	.incbin "baserom.gba", 0x6283a4, 0x64

	.global FireRingBgfx_08628408
FireRingBgfx_08628408:  @ LZ77
	.incbin "baserom.gba", 0x628408, 0x160

	.global FireRingBgfx_08628568
FireRingBgfx_08628568:  @ LZ77
	.incbin "baserom.gba", 0x628568, 0x934

	.global FireRingBgfx_08628E9C
FireRingBgfx_08628E9C:  @ LZ77
	.incbin "baserom.gba", 0x628e9c, 0x120

	.global FireRingBgfx_08628FBC
FireRingBgfx_08628FBC:  @ LZ77
	.incbin "baserom.gba", 0x628fbc, 0x174

	.global FireRingBgfx_08629130
FireRingBgfx_08629130:  @ LZ77
	.incbin "baserom.gba", 0x629130, 0x938

	.global FireRingBgfx_08629A68
FireRingBgfx_08629A68:  @ LZ77
	.incbin "baserom.gba", 0x629a68, 0x1bc

	.global FireRingBgfx_08629C24
FireRingBgfx_08629C24:  @ LZ77
	.incbin "baserom.gba", 0x629c24, 0x180

	.global FireRingBgfx_08629DA4
FireRingBgfx_08629DA4:  @ LZ77
	.incbin "baserom.gba", 0x629da4, 0x994

	.global FireRingBgfx_0862A738
FireRingBgfx_0862A738:  @ LZ77
	.incbin "baserom.gba", 0x62a738, 0x248

	.global FireRingBgfx_0862A980
FireRingBgfx_0862A980:  @ LZ77
	.incbin "baserom.gba", 0x62a980, 0x190

	.global FireRingBgfx_0862AB10
FireRingBgfx_0862AB10:  @ LZ77
	.incbin "baserom.gba", 0x62ab10, 0x9a8

	.global FireRingBgfx_0862B4B8
FireRingBgfx_0862B4B8:  @ LZ77
	.incbin "baserom.gba", 0x62b4b8, 0x468

	.global FireRingBgfx_0862B920
FireRingBgfx_0862B920:  @ LZ77
	.incbin "baserom.gba", 0x62b920, 0x1e0

	.global FireRingBgfx_0862BB00
FireRingBgfx_0862BB00:  @ LZ77
	.incbin "baserom.gba", 0x62bb00, 0xa5c

	.global FireRingBgfx_0862C55C
FireRingBgfx_0862C55C:  @ LZ77
	.incbin "baserom.gba", 0x62c55c, 0x868

	.global FireRingBgfx_0862CDC4
FireRingBgfx_0862CDC4:  @ LZ77
	.incbin "baserom.gba", 0x62cdc4, 0x260

	.global FireRingBgfx_0862D024
FireRingBgfx_0862D024:  @ LZ77
	.incbin "baserom.gba", 0x62d024, 0xaec

	.global FireRingBgfx_0862DB10
FireRingBgfx_0862DB10:  @ LZ77
	.incbin "baserom.gba", 0x62db10, 0xca0

	.global FireRingBgfx_0862E7B0
FireRingBgfx_0862E7B0:  @ LZ77
	.incbin "baserom.gba", 0x62e7b0, 0x290

	.global FireRingBgfx_0862EA40
FireRingBgfx_0862EA40:  @ LZ77
	.incbin "baserom.gba", 0x62ea40, 0xc48

	.global FireRingBgfx_0862F688
FireRingBgfx_0862F688:  @ LZ77
	.incbin "baserom.gba", 0x62f688, 0x10c4

	.global FireRingBgfx_0863074C
FireRingBgfx_0863074C:  @ LZ77
	.incbin "baserom.gba", 0x63074c, 0x2ac

	.global FireRingBgfx_086309F8
FireRingBgfx_086309F8:  @ LZ77
	.incbin "baserom.gba", 0x6309f8, 0xd70

	.global FireRingBgfx_08631768
FireRingBgfx_08631768:  @ LZ77
	.incbin "baserom.gba", 0x631768, 0x1118

	.global FireRingBgfx_08632880
FireRingBgfx_08632880:  @ LZ77
	.incbin "baserom.gba", 0x632880, 0x2ac

	.global FireRingBgfx_08632B2C
FireRingBgfx_08632B2C:  @ LZ77
	.incbin "baserom.gba", 0x632b2c, 0xda4

	.global FireRingBgfx_086338D0
FireRingBgfx_086338D0:  @ LZ77
	.incbin "baserom.gba", 0x6338d0, 0x102c

	.global FireRingBgfx_086348FC
FireRingBgfx_086348FC:  @ LZ77
	.incbin "baserom.gba", 0x6348fc, 0x2a8

	.global FireRingBgfx_08634BA4
FireRingBgfx_08634BA4:  @ LZ77
	.incbin "baserom.gba", 0x634ba4, 0xd1c

	.global FireRingBgfx_086358C0
FireRingBgfx_086358C0:  @ LZ77
	.incbin "baserom.gba", 0x6358c0, 0xed8

	.global FireRingBgfx_08636798
FireRingBgfx_08636798:  @ LZ77
	.incbin "baserom.gba", 0x636798, 0x2a8

	.global FireRingBgfx_08636A40
FireRingBgfx_08636A40:  @ LZ77
	.incbin "baserom.gba", 0x636a40, 0xcd8

	.global FireRingBgfx_08637718
FireRingBgfx_08637718:  @ LZ77
	.incbin "baserom.gba", 0x637718, 0xe54

	.global FireRingBgfx_0863856C
FireRingBgfx_0863856C:  @ LZ77
	.incbin "baserom.gba", 0x63856c, 0x2a8

	.global FireRingBgfx_08638814
FireRingBgfx_08638814:  @ LZ77
	.incbin "baserom.gba", 0x638814, 0xce8

	.global FireRingBgfx_086394FC
FireRingBgfx_086394FC:  @ LZ77
	.incbin "baserom.gba", 0x6394fc, 0xe8c

	.global FireRingBgfx_0863A388
FireRingBgfx_0863A388:  @ LZ77
	.incbin "baserom.gba", 0x63a388, 0x2a8

	.global FireRingBgfx_0863A630
FireRingBgfx_0863A630:  @ LZ77
	.incbin "baserom.gba", 0x63a630, 0xd0c

	.global FireRingBgfx_0863B33C
FireRingBgfx_0863B33C:  @ LZ77
	.incbin "baserom.gba", 0x63b33c, 0xf68

	.global FireRingBgfx_0863C2A4
FireRingBgfx_0863C2A4:  @ LZ77
	.incbin "baserom.gba", 0x63c2a4, 0x2a8

	.global FireRingBgfx_0863C54C
FireRingBgfx_0863C54C:  @ LZ77
	.incbin "baserom.gba", 0x63c54c, 0xd70

	.global FireRingBgfx_0863D2BC
FireRingBgfx_0863D2BC:  @ LZ77
	.incbin "baserom.gba", 0x63d2bc, 0x1030

	.global FireRingBgfx_0863E2EC
FireRingBgfx_0863E2EC:  @ LZ77
	.incbin "baserom.gba", 0x63e2ec, 0x2ac

	.global FireRingBgfx_0863E598
FireRingBgfx_0863E598:  @ LZ77
	.incbin "baserom.gba", 0x63e598, 0xdc4

	.global FireRingBgfx_0863F35C
FireRingBgfx_0863F35C:  @ LZ77
	.incbin "baserom.gba", 0x63f35c, 0x10cc

	.global FireRingBgfx_08640428
FireRingBgfx_08640428:  @ LZ77
	.incbin "baserom.gba", 0x640428, 0x2ac

	.global FireRingBgfx_086406D4
FireRingBgfx_086406D4:  @ LZ77
	.incbin "baserom.gba", 0x6406d4, 0xe00

	.global FireRingBgfx_086414D4
FireRingBgfx_086414D4:  @ LZ77
	.incbin "baserom.gba", 0x6414d4, 0x1170

	.global FireRingBgfx_08642644
FireRingBgfx_08642644:  @ LZ77
	.incbin "baserom.gba", 0x642644, 0x2ac

	.global FireRingBgfx_086428F0
FireRingBgfx_086428F0:  @ LZ77
	.incbin "baserom.gba", 0x6428f0, 0xde4

	.global FireRingBgfx_086436D4
FireRingBgfx_086436D4:  @ LZ77
	.incbin "baserom.gba", 0x6436d4, 0x11e4

	.global FireRingBgfx_086448B8
FireRingBgfx_086448B8:  @ LZ77
	.incbin "baserom.gba", 0x6448b8, 0x2ac

	.global FireRingBgfx_08644B64
FireRingBgfx_08644B64:  @ LZ77
	.incbin "baserom.gba", 0x644b64, 0xd7c

	.global FireRingBgfx_086458E0
FireRingBgfx_086458E0:  @ LZ77
	.incbin "baserom.gba", 0x6458e0, 0x123c

	.global FireRingBgfx_08646B1C
FireRingBgfx_08646B1C:  @ LZ77
	.incbin "baserom.gba", 0x646b1c, 0x2ac

	.global FireRingBgfx_08646DC8
FireRingBgfx_08646DC8:  @ LZ77
	.incbin "baserom.gba", 0x646dc8, 0xd9c

	.global FireRingBgfx_08647B64
FireRingBgfx_08647B64:  @ LZ77
	.incbin "baserom.gba", 0x647b64, 0x1290

	.global FireRingBgfx_08648DF4
FireRingBgfx_08648DF4:  @ LZ77
	.incbin "baserom.gba", 0x648df4, 0x2ac

	.global FireRingBgfx_086490A0
FireRingBgfx_086490A0:  @ LZ77
	.incbin "baserom.gba", 0x6490a0, 0xca8

	.global FireRingBgfx_08649D48
FireRingBgfx_08649D48:  @ LZ77
	.incbin "baserom.gba", 0x649d48, 0x10fc

	.global FireRingBgfx_0864AE44
FireRingBgfx_0864AE44:  @ LZ77
	.incbin "baserom.gba", 0x64ae44, 0x2ac

	.global FireRingBgfx_0864B0F0
FireRingBgfx_0864B0F0:  @ LZ77
	.incbin "baserom.gba", 0x64b0f0, 0xc20

	.global FireRingBgfx_0864BD10
FireRingBgfx_0864BD10:  @ LZ77
	.incbin "baserom.gba", 0x64bd10, 0xff0

	.global FireRingBgfx_0864CD00
FireRingBgfx_0864CD00:  @ LZ77
	.incbin "baserom.gba", 0x64cd00, 0x2ac

	.global FireRingBgfx_0864CFAC
FireRingBgfx_0864CFAC:  @ LZ77
	.incbin "baserom.gba", 0x64cfac, 0xaa8

	.global FireRingBgfx_0864DA54
FireRingBgfx_0864DA54:  @ LZ77
	.incbin "baserom.gba", 0x64da54, 0xd58

	.global FireRingBgfx_0864E7AC
FireRingBgfx_0864E7AC:  @ LZ77
	.incbin "baserom.gba", 0x64e7ac, 0x2ac

	.global FireRingBgfx_0864EA58
FireRingBgfx_0864EA58:  @ LZ77
	.incbin "baserom.gba", 0x64ea58, 0x914

	.global FireRingBgfx_0864F36C
FireRingBgfx_0864F36C:  @ LZ77
	.incbin "baserom.gba", 0x64f36c, 0xb90

	.global FireRingBgfx_0864FEFC
FireRingBgfx_0864FEFC:  @ LZ77
	.incbin "baserom.gba", 0x64fefc, 0x2a8
