@ ROM data 0x08ba47d8-0x08bdcdf4 (not yet in source)
@ Generated by tools/datasplit.py: labels + incbin only.  Labels may be
@ renamed here; rerun the tool after changing data/layout.txt.

	.section .rodata.08BA47D8, "a"

	.global gClassReelSpellAnimFuncLut
gClassReelSpellAnimFuncLut:
	.incbin "baserom.gba", 0xba47d8, 0x20

	.global ProcScr_efxopFire
ProcScr_efxopFire:
	.incbin "baserom.gba", 0xba47f8, 0x28

	.global ProcScr_efxopFireBG
ProcScr_efxopFireBG:
	.incbin "baserom.gba", 0xba4820, 0x18

	.global TsaArray_Fire_ClassReel
TsaArray_Fire_ClassReel:
	.incbin "baserom.gba", 0xba4838, 0x30

	.global ProcScr_efxopFireOBJ
ProcScr_efxopFireOBJ:
	.incbin "baserom.gba", 0xba4868, 0x18

	.global ProcScr_efxopThunder
ProcScr_efxopThunder:
	.incbin "baserom.gba", 0xba4880, 0x28

	.global ProcScr_efxopThunderBG
ProcScr_efxopThunderBG:
	.incbin "baserom.gba", 0xba48a8, 0x18

	.global TsaArray_Thunder_ClassReel
TsaArray_Thunder_ClassReel:
	.incbin "baserom.gba", 0xba48c0, 0x8

	.global ProcScr_efxopThunderBGCOL
ProcScr_efxopThunderBGCOL:
	.incbin "baserom.gba", 0xba48c8, 0x20

	.global ProcScr_efxopThunderOBJ
ProcScr_efxopThunderOBJ:
	.incbin "baserom.gba", 0xba48e8, 0x18

	.global ProcScr_efxopLive
ProcScr_efxopLive:
	.incbin "baserom.gba", 0xba4900, 0x28

	.global ProcScr_efxopLiveBG
ProcScr_efxopLiveBG:
	.incbin "baserom.gba", 0xba4928, 0x18

	.global TsaArray_Live_ClassReel
TsaArray_Live_ClassReel:
	.incbin "baserom.gba", 0xba4940, 0x4

	.global ProcScr_efxopLiveBGCOL
ProcScr_efxopLiveBGCOL:
	.incbin "baserom.gba", 0xba4944, 0x20

	.global ProcScr_efxopLiveALPHA
ProcScr_efxopLiveALPHA:
	.incbin "baserom.gba", 0xba4964, 0x20

	.global ProcScr_efxopLiveOBJ
ProcScr_efxopLiveOBJ:
	.incbin "baserom.gba", 0xba4984, 0x18

	.global ProcScr_efxopLightning
ProcScr_efxopLightning:
	.incbin "baserom.gba", 0xba499c, 0x28

	.global ProcScr_efxopLightningBG
ProcScr_efxopLightningBG:
	.incbin "baserom.gba", 0xba49c4, 0x18

	.global ImgArray_Light_ClassReel
ImgArray_Light_ClassReel:
	.incbin "baserom.gba", 0xba49dc, 0x84

	.global PalArray_Light_ClassReel
PalArray_Light_ClassReel:
	.incbin "baserom.gba", 0xba4a60, 0x84

	.global TsaArray_Light_ClassReel
TsaArray_Light_ClassReel:
	.incbin "baserom.gba", 0xba4ae4, 0x36c

	.global AnimScr_TeonoObjCloseRight
AnimScr_TeonoObjCloseRight:
	.incbin "baserom.gba", 0xba4e50, 0x5c

	.global AnimScr_TeonoObjFarRight
AnimScr_TeonoObjFarRight:
	.incbin "baserom.gba", 0xba4eac, 0x20

	.global AnimScr_TeonoObj2Right
AnimScr_TeonoObj2Right:
	.incbin "baserom.gba", 0xba4ecc, 0x31c

	.global AnimScr_TeonoObjCloseLeft
AnimScr_TeonoObjCloseLeft:
	.incbin "baserom.gba", 0xba51e8, 0x5c

	.global AnimScr_TeonoObjFarLeft
AnimScr_TeonoObjFarLeft:
	.incbin "baserom.gba", 0xba5244, 0x20

	.global AnimScr_TeonoObj2Left
AnimScr_TeonoObj2Left:
	.incbin "baserom.gba", 0xba5264, 0xa0

	.global AnimScr_ArrowCloseRight
AnimScr_ArrowCloseRight:
	.incbin "baserom.gba", 0xba5304, 0x10

	.global AnimScr_ArrowFarRight
AnimScr_ArrowFarRight:
	.incbin "baserom.gba", 0xba5314, 0x7c

	.global AnimScr_ArrowCloseLeft
AnimScr_ArrowCloseLeft:
	.incbin "baserom.gba", 0xba5390, 0x10

	.global AnimScr_ArrowFarLeft
AnimScr_ArrowFarLeft:
	.incbin "baserom.gba", 0xba53a0, 0x1e4

	.global AnimScr_EfxTeyariObjType0Right
AnimScr_EfxTeyariObjType0Right:
	.incbin "baserom.gba", 0xba5584, 0x254

	.global AnimScr_EfxTeyariObjType0Left
AnimScr_EfxTeyariObjType0Left:
	.incbin "baserom.gba", 0xba57d8, 0x260

	.global AnimScr_EfxTeyariObjType1Right
AnimScr_EfxTeyariObjType1Right:
	.incbin "baserom.gba", 0xba5a38, 0x260

	.global AnimScr_EfxTeyariObjType1Left
AnimScr_EfxTeyariObjType1Left:
	.incbin "baserom.gba", 0xba5c98, 0x104

	.global AnimScr_08BA5D9C
AnimScr_08BA5D9C:
	.incbin "baserom.gba", 0xba5d9c, 0x9c

	.global AnimScr_08BA5E38
AnimScr_08BA5E38:
	.incbin "baserom.gba", 0xba5e38, 0x7f8

	.global AnimScr_EfxDanceObj
AnimScr_EfxDanceObj:
	.incbin "baserom.gba", 0xba6630, 0x30

	.global AnimScr_EfxSongObj2
AnimScr_EfxSongObj2:
	.incbin "baserom.gba", 0xba6660, 0xc58

	.global AnimScr_EfxBindingBlade_Left
AnimScr_EfxBindingBlade_Left:
	.incbin "baserom.gba", 0xba72b8, 0xc60

	.global AnimScr_EfxBindingBlade_Right
AnimScr_EfxBindingBlade_Right:
	.incbin "baserom.gba", 0xba7f18, 0x318

	.global AnimScr_HurtmutEff00OBJ1_Right
AnimScr_HurtmutEff00OBJ1_Right:
	.incbin "baserom.gba", 0xba8230, 0x48

	.global AnimScr_HurtmutEff01OBJ1_Right
AnimScr_HurtmutEff01OBJ1_Right:
	.incbin "baserom.gba", 0xba8278, 0x324

	.global AnimScr_HurtmutEff00OBJ1_Left
AnimScr_HurtmutEff00OBJ1_Left:
	.incbin "baserom.gba", 0xba859c, 0x48

	.global AnimScr_HurtmutEff01OBJ1_Left
AnimScr_HurtmutEff01OBJ1_Left:
	.incbin "baserom.gba", 0xba85e4, 0x2a0

	.global AnimScr_HurtmutEff00OBJ2_Right
AnimScr_HurtmutEff00OBJ2_Right:
	.incbin "baserom.gba", 0xba8884, 0x10

	.global AnimScr_HurtmutEff01OBJ2_Right
AnimScr_HurtmutEff01OBJ2_Right:
	.incbin "baserom.gba", 0xba8894, 0x24c

	.global AnimScr_HurtmutEff00OBJ2_Left
AnimScr_HurtmutEff00OBJ2_Left:
	.incbin "baserom.gba", 0xba8ae0, 0x10

	.global AnimScr_HurtmutEff01OBJ2_Left
AnimScr_HurtmutEff01OBJ2_Left:
	.incbin "baserom.gba", 0xba8af0, 0xbb8

	.global AnimScr_FirebreathOBJ_Left
AnimScr_FirebreathOBJ_Left:
	.incbin "baserom.gba", 0xba96a8, 0xc00

	.global AnimScr_FirebreathOBJ_Right
AnimScr_FirebreathOBJ_Right:
	.incbin "baserom.gba", 0xbaa2a8, 0xc30

	.global AnimScr_IcebreathOBJ_Right
AnimScr_IcebreathOBJ_Right:
	.incbin "baserom.gba", 0xbaaed8, 0xc30

	.global AnimScr_IcebreathOBJ_Left
AnimScr_IcebreathOBJ_Left:
	.incbin "baserom.gba", 0xbabb08, 0xc3c

	.global AnimScr_DarkBreath
AnimScr_DarkBreath:
	.incbin "baserom.gba", 0xbac744, 0x11ac

	.global AnimScr_YushaSpinShieldOBJ_LeftTypeA
AnimScr_YushaSpinShieldOBJ_LeftTypeA:
	.incbin "baserom.gba", 0xbad8f0, 0x104

	.global AnimScr_YushaSpinShieldOBJ2_RightTypeA
AnimScr_YushaSpinShieldOBJ2_RightTypeA:
	.incbin "baserom.gba", 0xbad9f4, 0x28

	.global AnimScr_YushaSpinShieldOBJ3_RightTypeA
AnimScr_YushaSpinShieldOBJ3_RightTypeA:
	.incbin "baserom.gba", 0xbada1c, 0x1174

	.global AnimScr_YushaSpinShieldOBJ_RightTypeA
AnimScr_YushaSpinShieldOBJ_RightTypeA:
	.incbin "baserom.gba", 0xbaeb90, 0x104

	.global AnimScr_YushaSpinShieldOBJ2_LeftTypeA
AnimScr_YushaSpinShieldOBJ2_LeftTypeA:
	.incbin "baserom.gba", 0xbaec94, 0x28

	.global AnimScr_YushaSpinShieldOBJ3_LeftTypeA
AnimScr_YushaSpinShieldOBJ3_LeftTypeA:
	.incbin "baserom.gba", 0xbaecbc, 0x11a4

	.global AnimScr_YushaSpinShieldOBJ_LeftTypeB
AnimScr_YushaSpinShieldOBJ_LeftTypeB:
	.incbin "baserom.gba", 0xbafe60, 0x104

	.global AnimScr_YushaSpinShieldOBJ2_RightTypeB
AnimScr_YushaSpinShieldOBJ2_RightTypeB:
	.incbin "baserom.gba", 0xbaff64, 0x28

	.global AnimScr_YushaSpinShieldOBJ3_RightTypeB
AnimScr_YushaSpinShieldOBJ3_RightTypeB:
	.incbin "baserom.gba", 0xbaff8c, 0x11a4

	.global AnimScr_YushaSpinShieldOBJ_RightTypeB
AnimScr_YushaSpinShieldOBJ_RightTypeB:
	.incbin "baserom.gba", 0xbb1130, 0x104

	.global AnimScr_YushaSpinShieldOBJ2_LeftTypeB
AnimScr_YushaSpinShieldOBJ2_LeftTypeB:
	.incbin "baserom.gba", 0xbb1234, 0x28

	.global AnimScr_YushaSpinShieldOBJ3_LeftTypeB
AnimScr_YushaSpinShieldOBJ3_LeftTypeB:
	.incbin "baserom.gba", 0xbb125c, 0xc4

	.global AnimScr_EfxSunakemuriOBJ1_R
AnimScr_EfxSunakemuriOBJ1_R:
	.incbin "baserom.gba", 0xbb1320, 0xa4

	.global AnimScr_EfxSunakemuriOBJ1_L
AnimScr_EfxSunakemuriOBJ1_L:
	.incbin "baserom.gba", 0xbb13c4, 0xa4

	.global AnimScr_EfxSunakemuriOBJ2_R
AnimScr_EfxSunakemuriOBJ2_R:
	.incbin "baserom.gba", 0xbb1468, 0xa4

	.global AnimScr_EfxSunakemuriOBJ2_L
AnimScr_EfxSunakemuriOBJ2_L:
	.incbin "baserom.gba", 0xbb150c, 0xa4

	.global AnimScr_EfxSunakemuriOBJ3_R
AnimScr_EfxSunakemuriOBJ3_R:
	.incbin "baserom.gba", 0xbb15b0, 0xa4

	.global AnimScr_EfxSunakemuriOBJ3_L
AnimScr_EfxSunakemuriOBJ3_L:
	.incbin "baserom.gba", 0xbb1654, 0x194

	.global AnimScr_EfxMantBatabata1_R
AnimScr_EfxMantBatabata1_R:
	.incbin "baserom.gba", 0xbb17e8, 0x194

	.global AnimScr_EfxMantBatabata1_L
AnimScr_EfxMantBatabata1_L:
	.incbin "baserom.gba", 0xbb197c, 0x1ac

	.global AnimScr_EfxMantBatabata2_R
AnimScr_EfxMantBatabata2_R:
	.incbin "baserom.gba", 0xbb1b28, 0x1ac

	.global AnimScr_EfxMantBatabata2_L
AnimScr_EfxMantBatabata2_L:
	.incbin "baserom.gba", 0xbb1cd4, 0x1ac

	.global AnimScr_EfxMantBatabata3_R
AnimScr_EfxMantBatabata3_R:
	.incbin "baserom.gba", 0xbb1e80, 0x1a8

	.global AnimScr_EfxMantBatabata3_L
AnimScr_EfxMantBatabata3_L:
	.incbin "baserom.gba", 0xbb2028, 0x13c

	.global AnimScr_EfxMantBatabata4_R
AnimScr_EfxMantBatabata4_R:
	.incbin "baserom.gba", 0xbb2164, 0x138

	.global AnimScr_EfxMantBatabata4_L
AnimScr_EfxMantBatabata4_L:
	.incbin "baserom.gba", 0xbb229c, 0x264

	.global AnimScr_EfxMantBatabata5_R
AnimScr_EfxMantBatabata5_R:
	.incbin "baserom.gba", 0xbb2500, 0x268

	.global AnimScr_EfxMantBatabata5_L
AnimScr_EfxMantBatabata5_L:
	.incbin "baserom.gba", 0xbb2768, 0x124

	.global AnimScr_EfxMantBatabata6_R
AnimScr_EfxMantBatabata6_R:
	.incbin "baserom.gba", 0xbb288c, 0x124

	.global AnimScr_EfxMantBatabata6_L
AnimScr_EfxMantBatabata6_L:
	.incbin "baserom.gba", 0xbb29b0, 0xa54

	.global AnimScr_EfxThunderOBJ_R
AnimScr_EfxThunderOBJ_R:
	.incbin "baserom.gba", 0xbb3404, 0xb2c

	.global AnimScr_EfxThunderOBJ_L
AnimScr_EfxThunderOBJ_L:
	.incbin "baserom.gba", 0xbb3f30, 0x418

	.global AnimScr_EfxFireOBJ_L_Front
AnimScr_EfxFireOBJ_L_Front:
	.incbin "baserom.gba", 0xbb4348, 0x2c

	.global AnimScr_EfxFireOBJ_L_Back
AnimScr_EfxFireOBJ_L_Back:
	.incbin "baserom.gba", 0xbb4374, 0x35c

	.global AnimScr_EfxFireOBJ_R_Front
AnimScr_EfxFireOBJ_R_Front:
	.incbin "baserom.gba", 0xbb46d0, 0x2c

	.global AnimScr_EfxFireOBJ_R_Back
AnimScr_EfxFireOBJ_R_Back:
	.incbin "baserom.gba", 0xbb46fc, 0xdd0

	.global AnimScr_EfxElfireObjRight
AnimScr_EfxElfireObjRight:
	.incbin "baserom.gba", 0xbb54cc, 0xe20

	.global AnimScr_EfxElfireObjLeft
AnimScr_EfxElfireObjLeft:
	.incbin "baserom.gba", 0xbb62ec, 0xf94

	.global AnimScr_EfxThunderstormOBJ
	.global AnimScr_EfxClasschgOBJ
AnimScr_EfxThunderstormOBJ:
AnimScr_EfxClasschgOBJ:
	.incbin "baserom.gba", 0xbb7280, 0x1f3c

	.global AnimScr_FimbulvetrOBJ1
AnimScr_FimbulvetrOBJ1:
	.incbin "baserom.gba", 0xbb91bc, 0x6c

	.global AnimScr_FimbulvetrOBJ2
AnimScr_FimbulvetrOBJ2:
	.incbin "baserom.gba", 0xbb9228, 0x60

	.global AnimScr_FimbulvetrOBJ2Fall_TypeA
AnimScr_FimbulvetrOBJ2Fall_TypeA:
	.incbin "baserom.gba", 0xbb9288, 0x8

	.global AnimScr_FimbulvetrOBJ2Fall_TypeB
AnimScr_FimbulvetrOBJ2Fall_TypeB:
	.incbin "baserom.gba", 0xbb9290, 0x26c

	.global AnimScr_EfxMistyRainObj1
AnimScr_EfxMistyRainObj1:
	.incbin "baserom.gba", 0xbb94fc, 0x38

	.global AnimScr_EfxHazymoonOBJ3RND
AnimScr_EfxHazymoonOBJ3RND:
	.incbin "baserom.gba", 0xbb9534, 0x14c

	.global AnimScr_EfxMistyRainObj2
AnimScr_EfxMistyRainObj2:
	.incbin "baserom.gba", 0xbb9680, 0x3f8

	.global AnimScr_EfxMistyRainObj4
AnimScr_EfxMistyRainObj4:
	.incbin "baserom.gba", 0xbb9a78, 0x34

	.global AnimScr_EfxMistyRainObj5
AnimScr_EfxMistyRainObj5:
	.incbin "baserom.gba", 0xbb9aac, 0x88

	.global AnimScr_EfxMistyRainObj3
AnimScr_EfxMistyRainObj3:
	.incbin "baserom.gba", 0xbb9b34, 0x5d8

	.global AnimScr_EfxDevineOBJ
AnimScr_EfxDevineOBJ:
	.incbin "baserom.gba", 0xbba10c, 0x1c0

	.global AnimScr_EfxHazymoonOBJ2_1
AnimScr_EfxHazymoonOBJ2_1:
	.incbin "baserom.gba", 0xbba2cc, 0x308

	.global AnimScr_EfxHazymoonOBJ2_2
AnimScr_EfxHazymoonOBJ2_2:
	.incbin "baserom.gba", 0xbba5d4, 0x2fc

	.global AnimScr_EfxHazymoonOBJ2_3
AnimScr_EfxHazymoonOBJ2_3:
	.incbin "baserom.gba", 0xbba8d0, 0xc98

	.global AnimScr_EfxFenrir1
AnimScr_EfxFenrir1:
	.incbin "baserom.gba", 0xbbb568, 0x2c

	.global AnimScr_EfxFenrir2
AnimScr_EfxFenrir2:
	.incbin "baserom.gba", 0xbbb594, 0x2c

	.global AnimScr_EfxFenrir3
AnimScr_EfxFenrir3:
	.incbin "baserom.gba", 0xbbb5c0, 0x3a4

	.global AnimScr_EfxPurge
AnimScr_EfxPurge:
	.incbin "baserom.gba", 0xbbb964, 0x274

	.global gUnk_08BBBBD8
gUnk_08BBBBD8:
	.incbin "baserom.gba", 0xbbbbd8, 0x2ad8

	.global AnimScr_EfxLiveOBJ1
AnimScr_EfxLiveOBJ1:
	.incbin "baserom.gba", 0xbbe6b0, 0x90

	.global AnimScr_EfxLiveOBJ2
AnimScr_EfxLiveOBJ2:
	.incbin "baserom.gba", 0xbbe740, 0x151c

	.global AnimScr_EfxReblowOBJ_Right1
AnimScr_EfxReblowOBJ_Right1:
	.incbin "baserom.gba", 0xbbfc5c, 0x74

	.global AnimScr_EfxReblowOBJ_Right2
AnimScr_EfxReblowOBJ_Right2:
	.incbin "baserom.gba", 0xbbfcd0, 0x158c

	.global AnimScr_EfxReblowOBJ_Left1
AnimScr_EfxReblowOBJ_Left1:
	.incbin "baserom.gba", 0xbc125c, 0x74

	.global AnimScr_EfxReblowOBJ_Left2
AnimScr_EfxReblowOBJ_Left2:
	.incbin "baserom.gba", 0xbc12d0, 0x2d74

	.global AnimScr_EfxRestOBJ
AnimScr_EfxRestOBJ:
	.incbin "baserom.gba", 0xbc4044, 0x2cc

	.global AnimScr_EfxSilenceOBJ
AnimScr_EfxSilenceOBJ:
	.incbin "baserom.gba", 0xbc4310, 0x2ce4

	.global AnimScr_EfxHammarneOBJ
AnimScr_EfxHammarneOBJ:
	.incbin "baserom.gba", 0xbc6ff4, 0x506c

	.global AnimScr_EfxSleepOBJ2
AnimScr_EfxSleepOBJ2:
	.incbin "baserom.gba", 0xbcc060, 0x180

	.global AnimScr_EfxSleepOBJ1
AnimScr_EfxSleepOBJ1:
	.incbin "baserom.gba", 0xbcc1e0, 0x5b4

	.global AnimScr_EfxBerserk1
AnimScr_EfxBerserk1:
	.incbin "baserom.gba", 0xbcc794, 0x14

	.global AnimScr_EfxBerserk2
AnimScr_EfxBerserk2:
	.incbin "baserom.gba", 0xbcc7a8, 0x14

	.global AnimScr_EfxBerserk3
AnimScr_EfxBerserk3:
	.incbin "baserom.gba", 0xbcc7bc, 0x14

	.global AnimScr_EfxBerserk4
AnimScr_EfxBerserk4:
	.incbin "baserom.gba", 0xbcc7d0, 0x14

	.global AnimScr_EfxBerserk5
AnimScr_EfxBerserk5:
	.incbin "baserom.gba", 0xbcc7e4, 0x374

	.global AnimScr_EfxBerserk6
AnimScr_EfxBerserk6:
	.incbin "baserom.gba", 0xbccb58, 0xc

	.global AnimScr_EfxBerserk7
AnimScr_EfxBerserk7:
	.incbin "baserom.gba", 0xbccb64, 0xc

	.global AnimScr_EfxBerserk8
AnimScr_EfxBerserk8:
	.incbin "baserom.gba", 0xbccb70, 0xc

	.global AnimScr_EfxBerserk9
AnimScr_EfxBerserk9:
	.incbin "baserom.gba", 0xbccb7c, 0xc

	.global AnimScr_EfxBerserk10
AnimScr_EfxBerserk10:
	.incbin "baserom.gba", 0xbccb88, 0x40c0

	.global AnimScr_EfxMshield1
AnimScr_EfxMshield1:
	.incbin "baserom.gba", 0xbd0c48, 0x150

	.global AnimScr_EfxMshield2
AnimScr_EfxMshield2:
	.incbin "baserom.gba", 0xbd0d98, 0xa20

	.global AnimScr_Spell21OBJChild_A
AnimScr_Spell21OBJChild_A:
	.incbin "baserom.gba", 0xbd17b8, 0x8

	.global AnimScr_Spell21OBJChild_B
AnimScr_Spell21OBJChild_B:
	.incbin "baserom.gba", 0xbd17c0, 0x8

	.global AnimScr_Spell21OBJChild_C
AnimScr_Spell21OBJChild_C:
	.incbin "baserom.gba", 0xbd17c8, 0x8

	.global AnimScr_Spell21OBJ2_A
AnimScr_Spell21OBJ2_A:
	.incbin "baserom.gba", 0xbd17d0, 0x24

	.global AnimScr_Spell21OBJ2_B
AnimScr_Spell21OBJ2_B:
	.incbin "baserom.gba", 0xbd17f4, 0x4c

	.global AnimScr_Spell21OBJ3_A
AnimScr_Spell21OBJ3_A:
	.incbin "baserom.gba", 0xbd1840, 0x1c

	.global AnimScr_Spell21OBJ3_B
AnimScr_Spell21OBJ3_B:
	.incbin "baserom.gba", 0xbd185c, 0xbfc

	.global AnimScr_BolganoneOBJChild_5
AnimScr_BolganoneOBJChild_5:
	.incbin "baserom.gba", 0xbd2458, 0x8

	.global AnimScr_BolganoneOBJChild_3
AnimScr_BolganoneOBJChild_3:
	.incbin "baserom.gba", 0xbd2460, 0x8

	.global AnimScr_BolganoneOBJChild_2
AnimScr_BolganoneOBJChild_2:
	.incbin "baserom.gba", 0xbd2468, 0x8

	.global AnimScr_BolganoneOBJChild_1
AnimScr_BolganoneOBJChild_1:
	.incbin "baserom.gba", 0xbd2470, 0x8

	.global AnimScr_BolganoneOBJChild_0
AnimScr_BolganoneOBJChild_0:
	.incbin "baserom.gba", 0xbd2478, 0x8

	.global AnimScr_BolganoneOBJChild_4
AnimScr_BolganoneOBJChild_4:
	.incbin "baserom.gba", 0xbd2480, 0x50

	.global AnimScr_BolganoneOBJ2Child_1
AnimScr_BolganoneOBJ2Child_1:
	.incbin "baserom.gba", 0xbd24d0, 0xc

	.global AnimScr_BolganoneOBJ2Child_0
AnimScr_BolganoneOBJ2Child_0:
	.incbin "baserom.gba", 0xbd24dc, 0x2d0

	.global AnimScr_EfxShine
AnimScr_EfxShine:
	.incbin "baserom.gba", 0xbd27ac, 0x220

	.global AnimScr_EfxLuna1
AnimScr_EfxLuna1:
	.incbin "baserom.gba", 0xbd29cc, 0x38

	.global AnimScr_EfxLuna2
AnimScr_EfxLuna2:
	.incbin "baserom.gba", 0xbd2a04, 0x228

	.global AnimScr_EfxLuna4
AnimScr_EfxLuna4:
	.incbin "baserom.gba", 0xbd2c2c, 0xb2c

	.global AnimScr_EfxExcalibur
AnimScr_EfxExcalibur:
	.incbin "baserom.gba", 0xbd3758, 0x6ec

	.global AnimScr_GespenstOBJ
AnimScr_GespenstOBJ:
	.incbin "baserom.gba", 0xbd3e44, 0x45c

	.global AnimScr_GespenstOBJ2_A
AnimScr_GespenstOBJ2_A:
	.incbin "baserom.gba", 0xbd42a0, 0x54

	.global AnimScr_GespenstOBJ2_B
AnimScr_GespenstOBJ2_B:
	.incbin "baserom.gba", 0xbd42f4, 0xc

	.global AnimScr_GespenstOBJ2_C
AnimScr_GespenstOBJ2_C:
	.incbin "baserom.gba", 0xbd4300, 0x10d4

	.global AnimScr_LuceOBJ_A
AnimScr_LuceOBJ_A:
	.incbin "baserom.gba", 0xbd53d4, 0x98

	.global AnimScr_LuceOBJ_B
AnimScr_LuceOBJ_B:
	.incbin "baserom.gba", 0xbd546c, 0x1d8

	.global AnimScr_EfxChill1_R
AnimScr_EfxChill1_R:
	.incbin "baserom.gba", 0xbd5644, 0x204

	.global AnimScr_EfxChill1_L
AnimScr_EfxChill1_L:
	.incbin "baserom.gba", 0xbd5848, 0x3b4

	.global AnimScr_EfxChill2_R
AnimScr_EfxChill2_R:
	.incbin "baserom.gba", 0xbd5bfc, 0x3b4

	.global AnimScr_EfxChill2_L
AnimScr_EfxChill2_L:
	.incbin "baserom.gba", 0xbd5fb0, 0xb4c

	.global gUnk_08BD6AFC
gUnk_08BD6AFC:
	.incbin "baserom.gba", 0xbd6afc, 0xd8

	.global gUnk_08BD6BD4
gUnk_08BD6BD4:
	.incbin "baserom.gba", 0xbd6bd4, 0x98

	.global gUnk_08BD6C6C
gUnk_08BD6C6C:
	.incbin "baserom.gba", 0xbd6c6c, 0x88

	.global AnimScr_EreshkigalOBJ2_A
AnimScr_EreshkigalOBJ2_A:
	.incbin "baserom.gba", 0xbd6cf4, 0x20

	.global AnimScr_EreshkigalOBJ2_B
AnimScr_EreshkigalOBJ2_B:
	.incbin "baserom.gba", 0xbd6d14, 0x10

	.global gUnk_08BD6D24
gUnk_08BD6D24:
	.incbin "baserom.gba", 0xbd6d24, 0x70

	.global gUnk_08BD6D94
gUnk_08BD6D94:
	.incbin "baserom.gba", 0xbd6d94, 0x50

	.global gUnk_08BD6DE4
gUnk_08BD6DE4:
	.incbin "baserom.gba", 0xbd6de4, 0x294

	.global AnimScr_08BD7078
AnimScr_08BD7078:
	.incbin "baserom.gba", 0xbd7078, 0x18

	.global AnimScr_EreshkigalOBJ3
AnimScr_EreshkigalOBJ3:
	.incbin "baserom.gba", 0xbd7090, 0x1f5c

	.global AnimScr_EfxSong
AnimScr_EfxSong:
	.incbin "baserom.gba", 0xbd8fec, 0x1ec

	.global AnimScr_EfxLokmsunaObjLeft
AnimScr_EfxLokmsunaObjLeft:
	.incbin "baserom.gba", 0xbd91d8, 0x124

	.global AnimScr_EfxLokmsunaObjRight
AnimScr_EfxLokmsunaObjRight:
	.incbin "baserom.gba", 0xbd92fc, 0x1c

	.section .rodata.08BD95E0, "a"
	.incbin "baserom.gba", 0xbd95e0, 0x15c0

	.global AnimScr_EfxDragonDeadFallBody
AnimScr_EfxDragonDeadFallBody:
	.incbin "baserom.gba", 0xbdaba0, 0xb8

	.global AnimScr_EkrDragonHead
AnimScr_EkrDragonHead:
	.incbin "baserom.gba", 0xbdac58, 0x8

	.global AnimScr_EfxDragonDeadFallBody2
AnimScr_EfxDragonDeadFallBody2:
	.incbin "baserom.gba", 0xbdac60, 0x50

	.global AnimScr_EfxDragonDeadFallHeadFx
AnimScr_EfxDragonDeadFallHeadFx:
	.incbin "baserom.gba", 0xbdacb0, 0xc

	.global EkrBg3HfScrollingConf
EkrBg3HfScrollingConf:
	.incbin "baserom.gba", 0xbdacbc, 0x280

	.section .rodata.08BDB59C, "a"

	.global gEkrLvupFaceConfig
gEkrLvupFaceConfig:
	.incbin "baserom.gba", 0xbdb59c, 0x20

	.global EkrLvupMsgsStr
EkrLvupMsgsStr:
	.incbin "baserom.gba", 0xbdb5bc, 0x20

	.global EkrLvupMsgsMag
EkrLvupMsgsMag:
	.incbin "baserom.gba", 0xbdb5dc, 0x20

	.global ProcScr_EkrLevelup
ProcScr_EkrLevelup:
	.incbin "baserom.gba", 0xbdb5fc, 0xb0

	.global ProcScr_EfxPartsofScroll
ProcScr_EfxPartsofScroll:
	.incbin "baserom.gba", 0xbdb6ac, 0x20

	.global ProcScr_EfxPartsofScroll2
ProcScr_EfxPartsofScroll2:
	.incbin "baserom.gba", 0xbdb6cc, 0x20

	.global gEfxPartsofScroll2Lut
gEfxPartsofScroll2Lut:
	.incbin "baserom.gba", 0xbdb6ec, 0x40

	.global ProcScr_Efxleveluphb
ProcScr_Efxleveluphb:
	.incbin "baserom.gba", 0xbdb72c, 0x28

	.global ProcScr_Efxlvupbg
ProcScr_Efxlvupbg:
	.incbin "baserom.gba", 0xbdb754, 0x18

	.global TsaLut_EfxLvupBG
TsaLut_EfxLvupBG:
	.incbin "baserom.gba", 0xbdb76c, 0x2c

	.global ImgLut_EfxLvupBG
ImgLut_EfxLvupBG:
	.incbin "baserom.gba", 0xbdb798, 0x2c

	.global ProcScr_efxLvupBG2
ProcScr_efxLvupBG2:
	.incbin "baserom.gba", 0xbdb7c4, 0x18

	.global TsaLut_EfxLvupBG2
TsaLut_EfxLvupBG2:
	.incbin "baserom.gba", 0xbdb7dc, 0x18

	.global ProcScr_efxLvupOBJ2
ProcScr_efxLvupOBJ2:
	.incbin "baserom.gba", 0xbdb7f4, 0x20

	.global ProcScr_efxLvupBGCOL
ProcScr_efxLvupBGCOL:
	.incbin "baserom.gba", 0xbdb814, 0x20

	.global ProcScr_EkrLvupApfx
ProcScr_EkrLvupApfx:
	.incbin "baserom.gba", 0xbdb834, 0x18

	.global ProcScr_eobjLvup
ProcScr_eobjLvup:
	.incbin "baserom.gba", 0xbdb84c, 0x28

	.global ProcScr_ekrTriangle
ProcScr_ekrTriangle:
	.incbin "baserom.gba", 0xbdb874, 0x18

	.global ProcScr_ekrTriPegasusKnight
ProcScr_ekrTriPegasusKnight:
	.incbin "baserom.gba", 0xbdb88c, 0x18

	.global ProcScr_ekrTriPegasusKnightBG
ProcScr_ekrTriPegasusKnightBG:
	.incbin "baserom.gba", 0xbdb8a4, 0x18

	.global TsaLut_EkrTriPegagusBG
TsaLut_EkrTriPegagusBG:
	.incbin "baserom.gba", 0xbdb8bc, 0x18

	.global ProcScr_EkrTriPegasusKnightOBJ
ProcScr_EkrTriPegasusKnightOBJ:
	.incbin "baserom.gba", 0xbdb8d4, 0x18

	.global ProcScr_EkrTriArmorKnight
ProcScr_EkrTriArmorKnight:
	.incbin "baserom.gba", 0xbdb8ec, 0x18

	.global ProcScr_EkrTriArmorKnightOBJ
ProcScr_EkrTriArmorKnightOBJ:
	.incbin "baserom.gba", 0xbdb904, 0x18

	.global ProcScr_EkrTriArmorKnightOBJ2
ProcScr_EkrTriArmorKnightOBJ2:
	.incbin "baserom.gba", 0xbdb91c, 0x20

	.global ProcScr_EfxTriangleQUAKE
ProcScr_EfxTriangleQUAKE:
	.incbin "baserom.gba", 0xbdb93c, 0x4c8

	.global AnimScr_TriAtkLeft
AnimScr_TriAtkLeft:
	.incbin "baserom.gba", 0xbdbe04, 0x334

	.global AnimScr_TriAtkRight
AnimScr_TriAtkRight:
	.incbin "baserom.gba", 0xbdc138, 0x98

	.global AnimScr_TriKnightOBJ
AnimScr_TriKnightOBJ:
	.incbin "baserom.gba", 0xbdc1d0, 0x90

	.global AnimScr_TriGenerialLanceOBJ
AnimScr_TriGenerialLanceOBJ:
	.incbin "baserom.gba", 0xbdc260, 0x90

	.global AnimScr_TriGenerialAxeOBJ
AnimScr_TriGenerialAxeOBJ:
	.incbin "baserom.gba", 0xbdc2f0, 0x8c

	.global AnimScr_TriGenerialHandAxeOBJ
AnimScr_TriGenerialHandAxeOBJ:
	.incbin "baserom.gba", 0xbdc37c, 0xf0

	.global AnimScr_TriKnightAtkOBJ
AnimScr_TriKnightAtkOBJ:
	.incbin "baserom.gba", 0xbdc46c, 0x178

	.global AnimScr_TriGenerialLanceAtkOBJ
AnimScr_TriGenerialLanceAtkOBJ:
	.incbin "baserom.gba", 0xbdc5e4, 0x154

	.global AnimScr_TriGenerialAxeAtkOBJ
AnimScr_TriGenerialAxeAtkOBJ:
	.incbin "baserom.gba", 0xbdc738, 0x2c8

	.global AnimScr_TriGenerialHandAxeAtkOBJ
AnimScr_TriGenerialHandAxeAtkOBJ:
	.incbin "baserom.gba", 0xbdca00, 0x64

	.global gBattleBGDataTable
gBattleBGDataTable:
	.incbin "baserom.gba", 0xbdca64, 0x2e8

	.global AnimScr_EkrPopup
AnimScr_EkrPopup:
	.incbin "baserom.gba", 0xbdcd4c, 0x8

	.global ProcScr_ekrPopup
ProcScr_ekrPopup:
	.incbin "baserom.gba", 0xbdcd54, 0x68

	.global ProcScr_ekrPopup2
ProcScr_ekrPopup2:
	.incbin "baserom.gba", 0xbdcdbc, 0x38
