@ ROM data 0x08182ae0-0x08193e20 (not yet in source)
@ Generated by tools/datasplit.py: labels, incbin and .4byte pointers.
@ Labels may be renamed here; rerun the tool then (it rewrites the
@ .4byte references) and after changing data/layout.txt.

	.section .rodata.08182AE0, "a"

	.global gUnk_08182AE0
gUnk_08182AE0:  @ LZ77
	.incbin "build/graphics/bg/bg_59.lz"

	.global gUnk_08186500
gUnk_08186500:
	.incbin "baserom.gba", 0x186500, 0x4b4

	.global gUnk_081869B4
gUnk_081869B4:
	.incbin "graphics/bg/bg_59_pal.gbapal"
	.incbin "baserom.gba", 0x1869f4, 0xc0

	.global gUnk_08186AB4
gUnk_08186AB4:  @ LZ77
	.incbin "build/graphics/bg/bg_5A.lz"

	.global gUnk_0818AB1C
gUnk_0818AB1C:
	.incbin "baserom.gba", 0x18ab1c, 0x4b4

	.global gUnk_0818AFD0
gUnk_0818AFD0:
	.incbin "graphics/bg/bg_5A_pal.gbapal"
	.incbin "baserom.gba", 0x18b090, 0x40

	.global gUnk_0818B0D0
gUnk_0818B0D0:  @ LZ77
	.incbin "build/graphics/bg/bg_5B.lz"

	.global gUnk_0818BA50
gUnk_0818BA50:
	.incbin "baserom.gba", 0x18ba50, 0x4b4

	.global gUnk_0818BF04
gUnk_0818BF04:
	.incbin "graphics/bg/bg_5B_pal.gbapal"
	.incbin "baserom.gba", 0x18bf24, 0xe0

	.global Img_DragonsGate
Img_DragonsGate:  @ LZ77
	.incbin "build/graphics/Img_DragonsGate.lz"

	.global Tsa_DragonsGate
Tsa_DragonsGate:
	.incbin "baserom.gba", 0x18f2d4, 0x4dc

	.global Pal_DragonsGate
Pal_DragonsGate:
	.incbin "graphics/bg/bg_5C_pal.gbapal"
	.incbin "baserom.gba", 0x18f830, 0x80

	.global Img_NilsInDragonsGate
Img_NilsInDragonsGate:  @ LZ77
	.incbin "build/graphics/Img_NilsInDragonsGate.lz"

	.global Tsa_NilsInDragonsGate
Tsa_NilsInDragonsGate:
	.incbin "baserom.gba", 0x18fc08, 0x4dc

	.global Pal_NilsInDragonsGate
Pal_NilsInDragonsGate:
	.incbin "baserom.gba", 0x1900e4, 0x20

	.global gUnk_08190104
gUnk_08190104:  @ LZ77
	.incbin "build/graphics/bg/bg_5D.lz"

	.global gUnk_081937D8
gUnk_081937D8:
	.incbin "baserom.gba", 0x1937d8, 0x4b4

	.global gUnk_08193C8C
gUnk_08193C8C:
	.incbin "graphics/bg/bg_5D_pal.gbapal"
	.incbin "baserom.gba", 0x193d2c, 0x60

	.section .rodata.08193DA2, "a"
	.incbin "baserom.gba", 0x193da2, 0x2

	.section .rodata.08193E00, "a"

	.global gUnk_08193E00
gUnk_08193E00:
	.incbin "baserom.gba", 0x193e00, 0x8

	.global gUnk_08193E08
gUnk_08193E08:
	.incbin "baserom.gba", 0x193e08, 0x8

	.global gUnk_08193E10
gUnk_08193E10:
	.incbin "baserom.gba", 0x193e10, 0x4

	.global gUnk_08193E14
gUnk_08193E14:
	.incbin "baserom.gba", 0x193e14, 0x4

	.global gUnk_08193E18
gUnk_08193E18:
	.incbin "baserom.gba", 0x193e18, 0x4

	.global gUnk_08193E1C
gUnk_08193E1C:
	.incbin "baserom.gba", 0x193e1c, 0x4
