"""Turn the generated art (mod/claude/out) into game data: C arrays of the
LZ77-compressed sheets, OAM and palette (src/mod/claude_banim.c) and the
battle script (mod/banim/BanimScr_Flower.s).  Uses the build's own tools
(build/tools/gbagfx, build/tools/lz77), so run a build first.

    python3 mod/claude/art/emit.py
"""
import glob
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
OUT = os.path.join(ROOT, 'mod/claude/out')
GBAGFX = os.path.join(ROOT, 'build/tools/gbagfx')
LZ77 = os.path.join(ROOT, 'build/tools/lz77')


def lz(data, tmp):
    raw, comp = os.path.join(tmp, 'in.bin'), os.path.join(tmp, 'out.lz')
    open(raw, 'wb').write(data)
    subprocess.run([LZ77, '-c', raw, comp], check=True)
    return open(comp, 'rb').read()


def c_array(name, data):
    lines = [f'const u8 {name}[] CONST_DATA __attribute__((aligned(4))) = {{']
    for i in range(0, len(data), 16):
        lines.append('    ' + ', '.join(f'0x{b:02X}' for b in data[i:i + 16]) + ',')
    lines.append('};\n')
    return '\n'.join(lines)


def main():
    parts = ['// Generated by mod/claude/art/emit.py from mod/claude/art/battle.py.\n'
             '// The flower character\'s battle animation (design by thebes (Theia\n'
             '// Vogel)): LZ77-compressed sprite sheets, OAM data and palettes.\n\n'
             '#include "gbafe.h"\n\n']
    with tempfile.TemporaryDirectory() as tmp:
        sheets = sorted(glob.glob(os.path.join(OUT, 'banim_flower_sheet_*.png')),
                        key=lambda p: int(p.rsplit('_', 1)[1].split('.')[0]))
        for i, png in enumerate(sheets):
            raw = os.path.join(tmp, f's{i}.4bpp')
            subprocess.run([GBAGFX, png, raw], check=True)
            data = open(raw, 'rb').read()
            if len(data) != 0x2000:
                sys.exit(f'{png}: {len(data):#x} bytes, a sheet is 0x2000')
            parts.append(c_array(f'Img_Banim_Flower_Sheet{i}', lz(data, tmp)))
        for side in ('R', 'L'):
            data = open(os.path.join(OUT, f'banim_flower.oam_{side.lower()}.bin'), 'rb').read()
            if len(data) > 0x57F0:
                sys.exit(f'OAM {side}: {len(data):#x} bytes, the limit is 0x57F0')
            parts.append(c_array(f'BanimOam_Flower_{side}', lz(data, tmp)))
        pal = open(os.path.join(OUT, 'banim_flower_pal.bin'), 'rb').read()
        parts.append(c_array('Pal_Banim_Flower', lz(pal, tmp)))
    open(os.path.join(ROOT, 'src/mod/claude_banim.c'), 'w').write('\n'.join(parts))
    os.makedirs(os.path.join(ROOT, 'mod/banim'), exist_ok=True)
    shutil.copy(os.path.join(OUT, 'BanimScr_Flower.s'), os.path.join(ROOT, 'mod/banim/BanimScr_Flower.s'))
    print(f'{len(sheets)} sheets -> src/mod/claude_banim.c, mod/banim/BanimScr_Flower.s')


if __name__ == '__main__':
    main()
