#!/usr/bin/env python3
"""Turn the enumerators of a C constants header into #defines for assembly.

Usage: tools/enum2inc.py include/constants/characters.h OUT.inc

Assembly sources that are run through cpp (data/events/*.s) can then
#include the result and use the same names as C.  Handles `NAME = value,`
(value a number or an earlier name) and implicit `NAME,` (previous + 1).
"""
import re
import sys
from pathlib import Path

text = re.sub(r"//[^\n]*|/\*.*?\*/", "", Path(sys.argv[1]).read_text(), flags=re.S)
out = [f"/* Generated by tools/enum2inc.py from {sys.argv[1]} */"]
for body in re.findall(r"\benum\b[^{]*\{(.*?)\}", text, re.S):
    nxt = 0
    for ent in body.split(","):
        ent = ent.strip()
        if not ent:
            continue
        m = re.fullmatch(r"([A-Za-z_]\w*)\s*(?:=\s*(.+))?", ent, re.S)
        if not m:
            sys.exit(f"{sys.argv[1]}: can't parse enumerator {ent!r}")
        name, value = m.group(1), m.group(2)
        if value is None:
            value = str(nxt)
        value = " ".join(value.split())
        out.append(f"#define {name} ({value})" if not re.fullmatch(r"\w+", value) else f"#define {name} {value}")
        nxt = f"{name} + 1"
Path(sys.argv[2]).parent.mkdir(parents=True, exist_ok=True)
Path(sys.argv[2]).write_text("\n".join(out) + "\n")
