#!/usr/bin/env python3
"""Generate the data-region link layout from data/layout.txt.

Usage: tools/gen_layout.py data/layout.txt OUT_DIR

layout.txt lines: "rom|ram ADDR SIZE OBJECT(SECTION)".  ROM entries are
placed at ADDR inside .rodata with baserom.gba incbin'd around them; RAM
entries get NOLOAD sections at ADDR.  Writes OUT_DIR/data.s,
OUT_DIR/layout.ld (inside .rodata) and OUT_DIR/ram.ld (top level).
"""
import re
import sys
from pathlib import Path

DATA_START = 0x080C57DC
ROM_END = 0x09000000


def main():
    rom, ram = [], []
    for line in Path(sys.argv[1]).read_text().splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        kind, addr, size, obj = line.split()
        (rom if kind == "rom" else ram).append((int(addr, 16), int(size, 16), obj))
    rom.sort()

    out = Path(sys.argv[2])
    out.mkdir(parents=True, exist_ok=True)
    asm = ['\t@ Generated by tools/gen_layout.py from data/layout.txt\n']
    ld = ["/* Generated by tools/gen_layout.py from data/layout.txt */\n"]

    pos = DATA_START
    for addr, size, obj in rom + [(ROM_END, 0, None)]:
        if addr < pos:
            sys.exit(f"{obj} at {addr:#x} overlaps previous data (ends {pos:#x})")
        if addr > pos:
            asm.append(f'\t.section .rom_{pos:08X}, "a"\n\t.incbin "baserom.gba", {pos - 0x08000000:#x}, {addr - pos:#x}\n')
            ld.append(f"*(.rom_{pos:08X});\n")
        if obj:
            name = re.sub(r"\W", "_", obj)
            ld.append(f'ASSERT(. == {addr:#x}, "{name}: wrong address");\n{obj};\n')
            ld.append(f'ASSERT(. == {addr + size:#x}, "{name}: wrong size");\n')
        pos = addr + size

    ram_ld = ["/* Generated by tools/gen_layout.py from data/layout.txt */\n"]
    for i, (addr, size, obj) in enumerate(sorted(ram)):
        ram_ld.append(f".ram_{i} {addr:#x} (NOLOAD) : {{ {obj}; }}\n")

    (out / "data.s").write_text("".join(asm))
    (out / "layout.ld").write_text("".join(ld))
    (out / "ram.ld").write_text("".join(ram_ld))


if __name__ == "__main__":
    main()
