#!/usr/bin/env python3
"""Generate the data-region link layout from the layout files.

Usage: tools/gen_layout.py [--modern] LAYOUT.txt... OUT_DIR

Layout lines: "rom|ram ADDR SIZE OBJECT(SECTION)" (data/layout.txt, plus
data/rom/layout.txt from tools/datasplit.py).  ADDR APPEND (mod/layout.txt,
modern build only): new data or code with no place in the original ROM,
placed after all of it, 4-aligned, in the order of the lines.  ROM entries are placed at
ADDR inside .rodata with baserom.gba incbin'd around any gaps left; RAM
entries get NOLOAD sections at ADDR.  Writes OUT_DIR/data.s,
OUT_DIR/layout.ld (inside .rodata) and OUT_DIR/ram.ld (top level).

--modern (the modern build, tools/modern.py): the same sections in the same
order, but nothing pins their addresses or sizes, so data may change size
and move.  Each ROM entry is only moved up to the next address congruent
to ADDR modulo 4 (`. += (ADDR - .) & 3`; inside an output section `.` is
the offset from its start, and .rodata starts 4-aligned): data keeps the
alignment it had, and with unchanged sizes every entry lands exactly at
ADDR.  RAM entries keep their addresses.
"""
import re
import sys
from pathlib import Path

DATA_START = 0x080C57DC
ROM_END = 0x09000000


def main():
    args = sys.argv[1:]
    modern = args[0] == "--modern"
    if modern:
        args = args[1:]
    rom, ram, appended = [], [], []
    for path in args[:-1]:
        for line in Path(path).read_text().splitlines():
            if not line.strip() or line.startswith("#"):
                continue
            kind, addr, size, obj = line.split(None, 3)
            if kind == "rom" and addr == "APPEND":
                appended.append(obj)
                continue
            (rom if kind == "rom" else ram).append((int(addr, 16), int(size, 16), obj))
    if appended and not modern:
        sys.exit(f"{appended[0]}: APPEND lines (mod/layout.txt) need the modern build (make MODERN=1)")
    rom.sort()

    out = Path(args[-1])
    out.mkdir(parents=True, exist_ok=True)
    asm = ['\t@ Generated by tools/gen_layout.py\n']
    ld = ["/* Generated by tools/gen_layout.py */\n"]

    pos = DATA_START
    for addr, size, obj in rom + [(ROM_END, 0, None)]:
        if addr < pos:
            sys.exit(f"{obj} at {addr:#x} overlaps previous data (ends {pos:#x}); rerun tools/datasplit.py after editing data/layout.txt")
        if addr > pos:
            asm.append(f'\t.section .rom_{pos:08X}, "a"\n\t.incbin "baserom.gba", {pos - 0x08000000:#x}, {addr - pos:#x}\n')
            if modern:
                ld.append(f". += ({pos:#x} - .) & 3;\n")
            ld.append(f"*(.rom_{pos:08X});\n")
        if obj and modern:
            ld.append(f". += ({addr:#x} - .) & 3;\n{obj};\n")
        elif obj:
            name = re.sub(r"\W", "_", obj)
            ld.append(f'ASSERT(ABSOLUTE(.) == {addr:#x}, "{name}: wrong address");\n{obj};\n')
            ld.append(f'ASSERT(ABSOLUTE(.) == {addr + size:#x}, "{name}: wrong size");\n')
        pos = addr + size

    for obj in appended:
        ld.append(f". = ALIGN(4);\n{obj};\n")
    if modern:
        ld.append('ASSERT(ABSOLUTE(.) <= 0x0A000000, "the ROM is larger than 32 MiB");\n')

    ram_ld = ["/* Generated by tools/gen_layout.py */\n"]
    for i, (addr, size, obj) in enumerate(sorted(ram)):
        ram_ld.append(f".ram_{i} {addr:#x} (NOLOAD) : {{ {obj}; }}\n")

    (out / "data.s").write_text("".join(asm))
    (out / "layout.ld").write_text("".join(ld))
    (out / "ram.ld").write_text("".join(ram_ld))


if __name__ == "__main__":
    main()
