#!/usr/bin/env python3
"""Build the whole game as a native executable: build/host-game/fe7u.

    tools/hostgame.py [-j N] [--keep-going]                  (make host)

Steps (docs/port-notes.md, "Host link"):

1. C: every src/*.c (but agb-sram.c: platform/sram.c replaces it),
   src/data/*.c, src/events/*.c, src/host/*.c (host-only glue), the generated
   sound/*.c, build/msg_table.c, platform/armfunc.c and the battle animations
   as C (tools/banim.py host -> build/host-game/banim/banim_host.c), compiled
   with the host's clang like tools/hostcheck.py (-DNONMATCHING=1
   -std=gnu89 -funsigned-char, PLATFORM_GBA undefined, so ANIMSCR_WIDE and
   BANIM_SHEET_INDEX are on) but with the GBA build's text conversion: the
   preprocessed source goes through `iconv -f UTF-8 -t CP932` and is compiled
   as preprocessed C.  Objects: build/host-game/obj/.
2. Data assembly: data/rom/*.s, sound/sound.s (with the songs it includes)
   and build/msg_bits.s are GBA (ELF) assembly; tools/hostasm.py rewrites each
   for the host (Mach-O sections, `_` symbol prefix, `.incbin` as bytes,
   stream addresses as offsets from gHostSoundBase) into build/host-game/asm/
   and clang assembles them.
3. The platform layer: PLATFORM_RUNTIME_SRC, PLATFORM_FRONTEND_SRC and
   platform/main.c of platform/platform.mk, with PLATFORM_RUNTIME_CFLAGS.
4. RAM symbols defined only by address (symbols.ld): tools/hostram.py writes
   build/host-game/ramsyms.s, the EWRAM and IWRAM images with every name at
   the place of its GBA offset.
5. Link with PLATFORM_LIBS; symbols.ld's aliases of C symbols become
   `-alias` flags.  Undefined symbols are listed.

Needs the matching build first (fe7u.elf for the RAM layout; sound/, banim/
and build/msg_* are generated by it).  At most -j 4 by default: the machine
this runs on has 8 GB.
"""

import argparse
import concurrent.futures
import glob
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'tools'))
# HOSTGAME_OUT: another output directory, for a build with other flags
# (HOSTGAME_FLAGS='-fsanitize=address' HOSTGAME_OUT=build/host-asan).
OUT = os.environ.get('HOSTGAME_OUT', os.path.join('build', 'host-game'))
CLANG = os.environ.get('HOSTCHECK_CC', 'clang')

# As tools/hostcheck.py, plus code generation for running: debug info, no
# type-based alias analysis (the game reads memory through any pointer type)
# and wrapping signed arithmetic (agbcc's behaviour).
CFLAGS = ['-std=gnu89', '-funsigned-char', '-ffreestanding', '-fno-common',
          '-nostdinc', '-DNONMATCHING=1', '-g', '-O1',
          '-fno-strict-aliasing', '-fwrapv',
          '-fdiagnostics-show-option', '-fno-caret-diagnostics',
          '-fno-color-diagnostics', '-Wno-unknown-pragmas',
          '-Wno-invalid-source-encoding']
# HOSTGAME_FLAGS: extra flags for the game's C and the link (sanitizers).
EXTRA_FLAGS = os.environ.get('HOSTGAME_FLAGS', '').split()


def run(cmd, **kw):
    r = subprocess.run(cmd, capture_output=True, text=True, **kw)
    if r.returncode != 0:
        sys.stderr.write(' '.join(cmd) + '\n' + r.stdout + r.stderr)
        sys.exit(1)
    return r.stdout


def include_flags():
    res = run([CLANG, '-print-resource-dir']).strip()
    return ['-isystem', os.path.join(res, 'include'),
            '-isystem', 'tools/agbcc/include', '-iquote', 'include', '-iquote', '.']


# Not linked on the host: platform/sram.c replaces agb-sram.c.
HOST_EXCLUDE = {'src/agb-sram.c'}


# The battle animation scripts and mode tables with sheet indices, and
# gBanimSheets, as C (tools/banim.py host; ROM bytes, so only under build/)
BANIM_C = os.path.join(OUT, 'banim', 'banim_host.c')


def build_banim_c():
    deps = sorted(glob.glob('banim/*.s')) + ['tools/banim.py', 'data/layout.txt']
    if newer(BANIM_C, deps):
        run([sys.executable, 'tools/banim.py', 'host', os.path.dirname(BANIM_C)])


def c_sources():
    srcs = (sorted(glob.glob('src/*.c')) + sorted(glob.glob('src/data/*.c')) +
            sorted(glob.glob('src/events/*.c')) + sorted(glob.glob('sound/*.c')) +
            ['build/msg_table.c', 'platform/armfunc.c', BANIM_C] + sorted(glob.glob('src/host/*.c')))
    return [s for s in srcs if s not in HOST_EXCLUDE]


def obj_path(src, sub='obj'):
    if src.startswith('build/'):
        src = src[len('build/'):]
    return os.path.join(OUT, sub, os.path.splitext(src)[0] + '.o')


def up_to_date(obj, dep, flagfile, sig):
    try:
        t = os.path.getmtime(obj)
        with open(flagfile) as f:
            if f.read() != sig:
                return False
        with open(dep) as f:
            deps = f.read().replace('\\\n', ' ').split(':', 1)[1].split()
    except (OSError, IndexError):
        return False
    for d in deps:
        try:
            if os.path.getmtime(d) > t:
                return False
        except OSError:
            return False
    return True


def compile_c(src, flags, sig):
    """Preprocess, convert the text to CP932 as the GBA build does, compile."""
    obj = obj_path(src)
    dep, log, flagfile = obj[:-2] + '.d', obj[:-2] + '.log', obj[:-2] + '.flags'
    if up_to_date(obj, dep, flagfile, sig):
        return None
    os.makedirs(os.path.dirname(obj), exist_ok=True)
    if os.path.exists(obj):
        os.remove(obj)
    pp = subprocess.run([CLANG] + flags + ['-E', src, '-MMD', '-MF', dep, '-MT', obj],
                        capture_output=True)
    msgs = pp.stderr.decode(errors='replace')
    if pp.returncode == 0:
        conv = subprocess.run(['iconv', '-f', 'UTF-8', '-t', 'CP932'], input=pp.stdout,
                              capture_output=True)
        msgs += conv.stderr.decode(errors='replace')
        if conv.returncode == 0:
            cc = subprocess.run([CLANG] + flags + ['-x', 'cpp-output', '-c', '-', '-o', obj],
                                input=conv.stdout, capture_output=True)
            msgs += cc.stderr.decode(errors='replace')
    with open(log, 'w') as f:
        f.write(msgs)
    with open(flagfile, 'w') as f:
        f.write(sig)
    if not os.path.exists(obj):
        return (src, msgs)
    return None


def build_c(args):
    target = ['-target', run([CLANG, '-print-target-triple']).strip()]
    flags = target + CFLAGS + include_flags() + EXTRA_FLAGS
    sig = ' '.join(flags)
    srcs = c_sources()
    with concurrent.futures.ThreadPoolExecutor(args.j) as ex:
        failed = [r for r in ex.map(lambda s: compile_c(s, flags, sig), srcs) if r]
    for src, msgs in failed:
        errs = [l for l in msgs.splitlines() if ': error:' in l]
        print('%s: %d errors' % (src, len(errs)))
        for l in errs[:10]:
            print('  ' + l)
    if failed:
        print('%d of %d C files failed' % (len(failed), len(srcs)))
        if not args.keep_going:
            sys.exit(1)
    return [obj_path(s) for s in srcs if os.path.exists(obj_path(s))]


def asm_sources():
    return sorted(glob.glob('data/rom/*.s')) + ['sound/sound.s', 'build/msg_bits.s']


def asm_deps(src):
    """The file and what it includes (the songs of sound/sound.s)."""
    deps = [src, 'tools/hostasm.py']
    for line in open(src, encoding='utf-8'):
        m = re.match(r'^\s*\.include\s+"([^"]+)"', line)
        if m:
            for d in (os.path.dirname(src), 'include', 'asm', '.'):
                p = os.path.join(d, m.group(1))
                if os.path.exists(p):
                    deps.append(p)
                    break
    return deps


def build_asm_one(src):
    obj = obj_path(src, 'asm')
    out = obj[:-2] + '.s'
    deps = asm_deps(src)
    if os.path.exists(obj) and all(os.path.getmtime(d) <= os.path.getmtime(obj) for d in deps):
        return obj
    os.makedirs(os.path.dirname(obj), exist_ok=True)
    run([sys.executable, 'tools/hostasm.py', src, out])
    run([CLANG, '-c', '-x', 'assembler', out, '-o', obj])
    return obj


def build_asm(args):
    with concurrent.futures.ThreadPoolExecutor(args.j) as ex:
        return list(ex.map(build_asm_one, asm_sources()))


def platform_vars():
    """PLATFORM_RUNTIME_SRC, PLATFORM_FRONTEND_SRC, PLATFORM_RUNTIME_CFLAGS and
    PLATFORM_LIBS of platform/platform.mk."""
    mk = ('include platform/platform.mk\nprint:\n\t@echo "$(PLATFORM_RUNTIME_SRC)|'
          '$(PLATFORM_FRONTEND_SRC)|$(PLATFORM_RUNTIME_CFLAGS)|$(PLATFORM_LIBS)"\n')
    r = subprocess.run(['make', '-s', '--no-print-directory', '-f', '-', 'print'], input=mk,
                       capture_output=True, text=True, check=True)
    rt, fe, cflags, libs = r.stdout.strip().split('|')
    return rt.split() + fe.split() + ['platform/main.c'], cflags.split(), libs.split()


def compile_platform(src, flags, sig):
    obj = os.path.join(OUT, 'platform', os.path.basename(src)[:-2] + '.o')
    dep, flagfile = obj[:-2] + '.d', obj[:-2] + '.flags'
    if not up_to_date(obj, dep, flagfile, sig):
        os.makedirs(os.path.dirname(obj), exist_ok=True)
        run([CLANG] + flags + ['-c', src, '-o', obj, '-MMD', '-MF', dep, '-MT', obj])
        with open(flagfile, 'w') as f:
            f.write(sig)
    return obj


def build_platform(args):
    srcs, cflags, libs = platform_vars()
    sig = ' '.join(cflags)
    with concurrent.futures.ThreadPoolExecutor(args.j) as ex:
        return list(ex.map(lambda s: compile_platform(s, cflags, sig), srcs)), libs


def newer(target, deps):
    try:
        t = os.path.getmtime(target)
    except OSError:
        return True
    return any(os.path.getmtime(d) > t for d in deps)


def nm_sets(objs):
    """(defined, undefined) C names over the objects."""
    pre = 1 if sys.platform == 'darwin' else 0
    d, u = set(), set()
    out = run(['nm', '-g', '-P', '-A'] + objs)
    for line in out.splitlines():
        f = line.split()
        if len(f) >= 3:
            (u if f[2] == 'U' else d).add(f[1][pre:])
    return d, u


def build_ramsyms(objs):
    """tools/hostram.py: the images of the RAM objects symbols.ld names."""
    s = os.path.join(OUT, 'ramsyms.s')
    o = s[:-2] + '.o'
    if newer(o, objs + ['symbols.ld', 'fe7u.elf', 'tools/hostram.py']):
        run([sys.executable, 'tools/hostram.py', s] + objs)
        run([CLANG, '-c', '-x', 'assembler', s, '-o', o])
    return o


def ld_aliases(defined, undefined):
    """symbols.ld's `NAME = OTHER;` where OTHER is defined in C: -alias."""
    pre = '_' if sys.platform == 'darwin' else ''
    flags = []
    for line in open('symbols.ld'):
        m = re.match(r'^\s*([A-Za-z_]\w*)\s*=\s*([A-Za-z_]\w*)\s*;', line)
        if m and m.group(1) in undefined and m.group(1) not in defined and m.group(2) in defined:
            flags.append('-Wl,-alias,%s%s,%s%s' % (pre, m.group(2), pre, m.group(1)))
    return flags


def link(objs, libs, flags):
    exe = os.path.join(OUT, 'fe7u')
    cmd = [CLANG, '-o', exe] + objs + libs + flags + EXTRA_FLAGS
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode == 0:
        return True
    und = re.findall(r'^\s+"_?([^"]+)", referenced from:', r.stdout + r.stderr, re.M)
    if und:
        print('link: %d undefined symbols:' % len(und))
        for n in sorted(und):
            print('  ' + n)
    else:
        sys.stderr.write(r.stdout + r.stderr)
    return False


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('-j', type=int, default=4)
    ap.add_argument('--keep-going', action='store_true')
    args = ap.parse_args()
    os.chdir(ROOT)
    build_banim_c()
    objs = build_c(args)
    print('C: %d objects' % len(objs))
    aobjs = build_asm(args)
    print('data: %d objects' % len(aobjs))
    pobjs, libs = build_platform(args)
    print('platform: %d objects' % len(pobjs))
    ram = build_ramsyms(objs + pobjs)
    allobjs = objs + aobjs + pobjs + [ram]
    defined, undefined = nm_sets(allobjs)
    if link(allobjs, libs, ld_aliases(defined, undefined)):
        print('%s: linked' % os.path.join(OUT, 'fe7u'))
    else:
        sys.exit(1)


if __name__ == '__main__':
    main()
