#include "gbafe.h"

CONST_DATA u8 MoveScr_08CBB4BC[] = {
    MOVE_CMD_SET_SPEED, 14,
    MOVE_CMD_MOVE_LEFT,
    MOVE_CMD_MOVE_LEFT,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_LEFT,
    MOVE_CMD_MOVE_LEFT,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_HALT,
};

CONST_DATA u8 MoveScr_08CBB4C9[] = {
    MOVE_CMD_SET_SPEED, 16,
    MOVE_CMD_MOVE_DOWN,
    MOVE_CMD_MOVE_DOWN,
    MOVE_CMD_MOVE_RIGHT,
    MOVE_CMD_MOVE_DOWN,
    MOVE_CMD_MOVE_DOWN,
    MOVE_CMD_HALT,
};

CONST_DATA u8 MoveScr_08CBB4D1[] = {
    MOVE_CMD_SET_SPEED, 16,
    MOVE_CMD_MOVE_DOWN,
    MOVE_CMD_MOVE_DOWN,
    MOVE_CMD_MOVE_LEFT,
    MOVE_CMD_HALT,
};

CONST_DATA u8 MoveScr_08CBB4D7[] = {
    MOVE_CMD_SET_SPEED, 16,
    MOVE_CMD_MOVE_RIGHT,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_RIGHT,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_HALT,
};

CONST_DATA u8 MoveScr_08CBB4DF[] = {
    MOVE_CMD_SET_SPEED, 16,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_MOVE_UP,
    MOVE_CMD_HALT,
};
