#include "gbafe.h"

// Generated by tools/gen_data_tables.py

CONST_DATA struct SupportData SupportData_Eliwood = {
    .pids = { CHARACTER_HECTOR, CHARACTER_LYN, CHARACTER_NINIAN, CHARACTER_MARCUS, CHARACTER_LOWEN, CHARACTER_HARKEN, CHARACTER_FIORA },
    .exp_base = { 72, 10, 0, 25, 20, 25, 0 },
    .exp_growth = { 3, 2, 5, 2, 2, 3, 2 },
    .count = 7,
};

CONST_DATA struct SupportData SupportData_Hector = {
    .pids = { CHARACTER_ELIWOOD, CHARACTER_LYN, CHARACTER_OSWIN, CHARACTER_MATTHEW, CHARACTER_FLORINA, CHARACTER_SERRA, CHARACTER_FARINA },
    .exp_base = { 72, 0, 20, 20, 5, 15, 0 },
    .exp_growth = { 3, 3, 2, 3, 2, 1, 1 },
    .count = 7,
};

CONST_DATA struct SupportData SupportData_Lyn = {
    .pids = { CHARACTER_ELIWOOD, CHARACTER_HECTOR, CHARACTER_FLORINA, CHARACTER_RATH, CHARACTER_KENT, CHARACTER_WIL, CHARACTER_WALLACE },
    .exp_base = { 10, 0, 76, 15, 20, 17, 15 },
    .exp_growth = { 2, 3, 4, 4, 3, 3, 2 },
    .count = 7,
};

CONST_DATA struct SupportData SupportData_Raven = {
    .pids = { CHARACTER_LUCIUS, CHARACTER_PRISCILLA, CHARACTER_REBECCA, CHARACTER_WIL, CHARACTER_BARTRE, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 30, 20, 0, 0, 0, 0, 0 },
    .exp_growth = { 3, 3, 2, 1, 1, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Harken = {
    .pids = { CHARACTER_ELIWOOD, CHARACTER_ISADORA, CHARACTER_LOWEN, CHARACTER_MARCUS, CHARACTER_VAIDA, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 25, 40, 15, 20, 0, 0, 0 },
    .exp_growth = { 3, 4, 3, 2, 1, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Guy = {
    .pids = { CHARACTER_MATTHEW, CHARACTER_RATH, CHARACTER_KAREL, CHARACTER_PRISCILLA, CHARACTER_LOUISE, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 10, 0, 5, 0, 0, 0, 0 },
    .exp_growth = { 3, 4, 3, 2, 1, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Karel = {
    .pids = { CHARACTER_GUY, CHARACTER_GEITZ, CHARACTER_KARLA, CHARACTER_DART, CHARACTER_LUCIUS, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 5, 0, 25, 0, 0, 0, 0 },
    .exp_growth = { 3, 2, 2, 2, 1, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Dorcas = {
    .pids = { CHARACTER_BARTRE, CHARACTER_GEITZ, CHARACTER_OSWIN, CHARACTER_VAIDA, CHARACTER_FARINA, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 15, 0, 0, 0, 0, 0, 0 },
    .exp_growth = { 3, 3, 2, 2, 1, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Bartre = {
    .pids = { CHARACTER_DORCAS, CHARACTER_RAVEN, CHARACTER_CANAS, CHARACTER_KARLA, CHARACTER_RENAULT, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 15, 0, 0, 5, 0, 0, 0 },
    .exp_growth = { 3, 1, 2, 4, 1, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Geitz = {
    .pids = { CHARACTER_DORCAS, CHARACTER_KAREL, CHARACTER_ISADORA, CHARACTER_FIORA, CHARACTER_DART, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 0, 0, 0, 0, 0, 0, 0 },
    .exp_growth = { 3, 2, 2, 1, 2, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Oswin = {
    .pids = { CHARACTER_HECTOR, CHARACTER_MATTHEW, CHARACTER_SERRA, CHARACTER_PRISCILLA, CHARACTER_DORCAS, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 20, 5, 10, 0, 0, 0, 0 },
    .exp_growth = { 2, 2, 1, 2, 2, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Wil = {
    .pids = { CHARACTER_LYN, CHARACTER_REBECCA, CHARACTER_RATH, CHARACTER_DART, CHARACTER_WALLACE, CHARACTER_RAVEN, CHARACTER_NONE },
    .exp_base = { 17, 30, 0, 20, 0, 0, 0 },
    .exp_growth = { 3, 3, 2, 3, 2, 1, 0 },
    .count = 6,
};

CONST_DATA struct SupportData SupportData_Rebecca = {
    .pids = { CHARACTER_WIL, CHARACTER_LOWEN, CHARACTER_SAIN, CHARACTER_DART, CHARACTER_LOUISE, CHARACTER_RAVEN, CHARACTER_NINO },
    .exp_base = { 30, 5, 0, 35, 0, 0, 0 },
    .exp_growth = { 3, 2, 2, 3, 3, 2, 3 },
    .count = 7,
};

CONST_DATA struct SupportData SupportData_Louise = {
    .pids = { CHARACTER_PENT, CHARACTER_ERK, CHARACTER_HAWKEYE, CHARACTER_REBECCA, CHARACTER_GUY, CHARACTER_HEATH, CHARACTER_SAIN },
    .exp_base = { 241, 20, 20, 0, 0, 0, 0 },
    .exp_growth = { 0, 2, 3, 3, 1, 1, 1 },
    .count = 7,
};

CONST_DATA struct SupportData SupportData_Lucius = {
    .pids = { CHARACTER_RAVEN, CHARACTER_PRISCILLA, CHARACTER_SERRA, CHARACTER_RENAULT, CHARACTER_KAREL, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 30, 5, 0, 0, 0, 0, 0 },
    .exp_growth = { 3, 2, 2, 2, 1, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Serra = {
    .pids = { CHARACTER_HECTOR, CHARACTER_MATTHEW, CHARACTER_FLORINA, CHARACTER_SAIN, CHARACTER_OSWIN, CHARACTER_LUCIUS, CHARACTER_ERK },
    .exp_base = { 15, 5, 0, 0, 10, 0, 2 },
    .exp_growth = { 1, 1, 1, 2, 1, 2, 1 },
    .count = 7,
};

CONST_DATA struct SupportData SupportData_Renault = {
    .pids = { CHARACTER_BARTRE, CHARACTER_ISADORA, CHARACTER_LUCIUS, CHARACTER_WALLACE, CHARACTER_CANAS, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 0, 0, 0, 0, 0, 0, 0 },
    .exp_growth = { 1, 1, 2, 2, 2, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Erk = {
    .pids = { CHARACTER_LOUISE, CHARACTER_NINO, CHARACTER_PENT, CHARACTER_PRISCILLA, CHARACTER_SERRA, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 20, 0, 25, 15, 2, 0, 0 },
    .exp_growth = { 2, 3, 3, 3, 1, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Nino = {
    .pids = { CHARACTER_JAFFAR, CHARACTER_ERK, CHARACTER_FLORINA, CHARACTER_MERLINUS, CHARACTER_LEGAULT, CHARACTER_CANAS, CHARACTER_REBECCA },
    .exp_base = { 25, 0, 0, 0, 0, 0, 0 },
    .exp_growth = { 3, 3, 2, 2, 2, 3, 3 },
    .count = 7,
};

CONST_DATA struct SupportData SupportData_Pent = {
    .pids = { CHARACTER_LOUISE, CHARACTER_ERK, CHARACTER_CANAS, CHARACTER_HAWKEYE, CHARACTER_FIORA, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 241, 25, 0, 20, 10, 0, 0 },
    .exp_growth = { 0, 3, 3, 3, 2, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Canas = {
    .pids = { CHARACTER_PENT, CHARACTER_NINO, CHARACTER_RENAULT, CHARACTER_BARTRE, CHARACTER_VAIDA, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 0, 0, 0, 0, 0, 0, 0 },
    .exp_growth = { 3, 3, 2, 2, 2, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Kent = {
    .pids = { CHARACTER_LYN, CHARACTER_SAIN, CHARACTER_FIORA, CHARACTER_FARINA, CHARACTER_WALLACE, CHARACTER_HEATH, CHARACTER_NONE },
    .exp_base = { 20, 30, 0, 0, 15, 0, 0 },
    .exp_growth = { 3, 3, 3, 1, 2, 2, 0 },
    .count = 6,
};

CONST_DATA struct SupportData SupportData_Sain = {
    .pids = { CHARACTER_KENT, CHARACTER_FIORA, CHARACTER_SERRA, CHARACTER_REBECCA, CHARACTER_PRISCILLA, CHARACTER_LOUISE, CHARACTER_ISADORA },
    .exp_base = { 30, 0, 0, 0, 0, 0, 0 },
    .exp_growth = { 3, 2, 2, 2, 2, 1, 1 },
    .count = 7,
};

CONST_DATA struct SupportData SupportData_Lowen = {
    .pids = { CHARACTER_ELIWOOD, CHARACTER_MARCUS, CHARACTER_ISADORA, CHARACTER_HARKEN, CHARACTER_REBECCA, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 20, 20, 10, 15, 5, 0, 0 },
    .exp_growth = { 2, 3, 3, 3, 2, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Marcus = {
    .pids = { CHARACTER_ELIWOOD, CHARACTER_MERLINUS, CHARACTER_LOWEN, CHARACTER_ISADORA, CHARACTER_HARKEN, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 25, 0, 20, 15, 20, 0, 0 },
    .exp_growth = { 2, 2, 3, 3, 2, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Priscilla = {
    .pids = { CHARACTER_RAVEN, CHARACTER_LUCIUS, CHARACTER_ERK, CHARACTER_OSWIN, CHARACTER_SAIN, CHARACTER_HEATH, CHARACTER_GUY },
    .exp_base = { 20, 5, 15, 0, 0, 0, 0 },
    .exp_growth = { 3, 2, 3, 2, 2, 2, 2 },
    .count = 7,
};

CONST_DATA struct SupportData SupportData_Rath = {
    .pids = { CHARACTER_LYN, CHARACTER_WIL, CHARACTER_GUY, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 15, 0, 0, 0, 0, 0, 0 },
    .exp_growth = { 4, 2, 4, 0, 0, 0, 0 },
    .count = 3,
};

CONST_DATA struct SupportData SupportData_Florina = {
    .pids = { CHARACTER_HECTOR, CHARACTER_LYN, CHARACTER_FARINA, CHARACTER_FIORA, CHARACTER_NINIAN, CHARACTER_NINO, CHARACTER_SERRA },
    .exp_base = { 5, 76, 35, 35, 0, 0, 0 },
    .exp_growth = { 2, 4, 3, 4, 4, 2, 1 },
    .count = 7,
};

CONST_DATA struct SupportData SupportData_Fiora = {
    .pids = { CHARACTER_FARINA, CHARACTER_FLORINA, CHARACTER_ELIWOOD, CHARACTER_KENT, CHARACTER_SAIN, CHARACTER_PENT, CHARACTER_GEITZ },
    .exp_base = { 30, 35, 0, 0, 0, 10, 0 },
    .exp_growth = { 3, 4, 2, 3, 2, 2, 1 },
    .count = 7,
};

CONST_DATA struct SupportData SupportData_Farina = {
    .pids = { CHARACTER_HECTOR, CHARACTER_FLORINA, CHARACTER_FIORA, CHARACTER_KENT, CHARACTER_DART, CHARACTER_KARLA, CHARACTER_DORCAS },
    .exp_base = { 0, 35, 30, 0, 0, 0, 0 },
    .exp_growth = { 1, 3, 3, 1, 2, 2, 1 },
    .count = 7,
};

CONST_DATA struct SupportData SupportData_Heath = {
    .pids = { CHARACTER_VAIDA, CHARACTER_LEGAULT, CHARACTER_LOUISE, CHARACTER_PRISCILLA, CHARACTER_KENT, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 0, 0, 0, 0, 0, 0, 0 },
    .exp_growth = { 2, 2, 1, 2, 2, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Vaida = {
    .pids = { CHARACTER_HEATH, CHARACTER_HARKEN, CHARACTER_KARLA, CHARACTER_WALLACE, CHARACTER_CANAS, CHARACTER_DORCAS, CHARACTER_MERLINUS },
    .exp_base = { 0, 0, 0, 0, 0, 0, 0 },
    .exp_growth = { 2, 1, 2, 2, 2, 2, 1 },
    .count = 7,
};

CONST_DATA struct SupportData SupportData_Hawkeye = {
    .pids = { CHARACTER_NINIAN, CHARACTER_PENT, CHARACTER_LOUISE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 0, 20, 20, 0, 0, 0, 0 },
    .exp_growth = { 3, 3, 3, 0, 0, 0, 0 },
    .count = 3,
};

CONST_DATA struct SupportData SupportData_Matthew = {
    .pids = { CHARACTER_HECTOR, CHARACTER_JAFFAR, CHARACTER_GUY, CHARACTER_SERRA, CHARACTER_OSWIN, CHARACTER_LEGAULT, CHARACTER_NONE },
    .exp_base = { 20, 0, 10, 5, 5, 0, 0 },
    .exp_growth = { 3, 1, 3, 1, 2, 2, 0 },
    .count = 6,
};

CONST_DATA struct SupportData SupportData_Jaffar = {
    .pids = { CHARACTER_NINO, CHARACTER_MATTHEW, CHARACTER_LEGAULT, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 25, 0, 5, 0, 0, 0, 0 },
    .exp_growth = { 3, 1, 1, 0, 0, 0, 0 },
    .count = 3,
};

CONST_DATA struct SupportData SupportData_Ninian = {
    .pids = { CHARACTER_ELIWOOD, CHARACTER_FLORINA, CHARACTER_HAWKEYE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 0, 0, 0, 0, 0, 0, 0 },
    .exp_growth = { 5, 4, 3, 0, 0, 0, 0 },
    .count = 3,
};

CONST_DATA struct SupportData SupportData_Merlinus = {
    .pids = { CHARACTER_MARCUS, CHARACTER_NINO, CHARACTER_VAIDA, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 0, 0, 0, 0, 0, 0, 0 },
    .exp_growth = { 2, 2, 1, 0, 0, 0, 0 },
    .count = 3,
};

CONST_DATA struct SupportData SupportData_Wallace = {
    .pids = { CHARACTER_LYN, CHARACTER_RENAULT, CHARACTER_WIL, CHARACTER_VAIDA, CHARACTER_KENT, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 15, 0, 0, 0, 15, 0, 0 },
    .exp_growth = { 2, 2, 2, 2, 2, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Dart = {
    .pids = { CHARACTER_FARINA, CHARACTER_WIL, CHARACTER_GEITZ, CHARACTER_REBECCA, CHARACTER_KAREL, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 0, 20, 0, 35, 0, 0, 0 },
    .exp_growth = { 2, 3, 2, 3, 2, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Legault = {
    .pids = { CHARACTER_MATTHEW, CHARACTER_NINO, CHARACTER_ISADORA, CHARACTER_JAFFAR, CHARACTER_HEATH, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 0, 0, 0, 5, 0, 0, 0 },
    .exp_growth = { 2, 2, 1, 1, 2, 0, 0 },
    .count = 5,
};

CONST_DATA struct SupportData SupportData_Isadora = {
    .pids = { CHARACTER_LEGAULT, CHARACTER_LOWEN, CHARACTER_MARCUS, CHARACTER_HARKEN, CHARACTER_GEITZ, CHARACTER_RENAULT, CHARACTER_SAIN },
    .exp_base = { 0, 10, 15, 40, 0, 0, 0 },
    .exp_growth = { 1, 3, 3, 4, 2, 1, 1 },
    .count = 7,
};

CONST_DATA struct SupportData SupportData_Karla = {
    .pids = { CHARACTER_KAREL, CHARACTER_BARTRE, CHARACTER_FARINA, CHARACTER_VAIDA, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 25, 5, 0, 0, 0, 0, 0 },
    .exp_growth = { 2, 4, 2, 2, 0, 0, 0 },
    .count = 4,
};

CONST_DATA struct SupportData SupportData_Paul = {
    .pids = { CHARACTER_JASMINE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 241, 0, 0, 0, 0, 0, 0 },
    .exp_growth = { 0, 0, 0, 0, 0, 0, 0 },
    .count = 1,
};

CONST_DATA struct SupportData SupportData_Jasmine = {
    .pids = { CHARACTER_PAUL, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 241, 0, 0, 0, 0, 0, 0 },
    .exp_growth = { 0, 0, 0, 0, 0, 0, 0 },
    .count = 1,
};

CONST_DATA struct SupportData SupportData_Lloyd63 = {
    .pids = { CHARACTER_LINUS_64, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 241, 0, 0, 0, 0, 0, 0 },
    .exp_growth = { 0, 0, 0, 0, 0, 0, 0 },
    .count = 1,
};

CONST_DATA struct SupportData SupportData_Linus64 = {
    .pids = { CHARACTER_LLOYD_63, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 241, 0, 0, 0, 0, 0, 0 },
    .exp_growth = { 0, 0, 0, 0, 0, 0, 0 },
    .count = 1,
};

CONST_DATA struct SupportData SupportData_LloydF4 = {
    .pids = { CHARACTER_LINUS_F5, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 241, 0, 0, 0, 0, 0, 0 },
    .exp_growth = { 0, 0, 0, 0, 0, 0, 0 },
    .count = 1,
};

CONST_DATA struct SupportData SupportData_LinusF5 = {
    .pids = { CHARACTER_LLOYD_F4, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE, CHARACTER_NONE },
    .exp_base = { 241, 0, 0, 0, 0, 0, 0 },
    .exp_growth = { 0, 0, 0, 0, 0, 0, 0 },
    .count = 1,
};
